### ISSUE TITLE
Integrate Your SAPUI5 App into Your Launchpad Site - Issue with fetching updated content

### ISSUE THREAD

**Issue by olivier-enault-sap** [SAPDocuments/Issues#1]
Tutorial: https://developers.sap.com/tutorials/cp-launchpad-integrate-sapui5-app.html
--------------------------

Hi team,

After succeeding with previous steps & tutos, I'm stuck at Step 2: Add your deployed SAPUI5 app to your content.

After fetching updated content from the HTML5 Apps content provider, I can't see any content from the content explorer.
I should see my Suppliers app that I've created a few steps before and that is running fine in my CF environment.

Any idea?

Best regards
Olivier

**Comment by IObert** [comment]
Hi,

How did you create the supplied app? Did you follow the instructions of the overarching [tutorial group](https://developers.sap.com/group.launchpad-cf-add-custom-app.html)?

**Comment by olivier-enault-sap** [comment]
Hi,

Yes, definitely - see enclosed.
Also my app is started and running.

Regards

![Capture](https://user-images.githubusercontent.com/47564693/102597728-53c0d180-411b-11eb-9389-e2fd468f2216.PNG)

![Capture2](https://user-images.githubusercontent.com/47564693/102598021-b619d200-411b-11eb-9631-a07de920904f.PNG)

**Comment by LindsayBert** [comment]
Hi

 In this tutorial, step 1.5, did you select **Manage by SAP Cloud Platform**?  

Also check the navigation properties in this tutorial: https://developers.sap.com/tutorials/cp-launchpad-site-add-navigation.html.

Thanks
Lindsay

**Comment by olivier-enault-sap** [comment]
Hi
Great! That was due to this step 1.5.

As I first started this tutorial with this application creation, I wasn't planning to integrate it to a Launchpad.
But then going through the Launchpad tutorials I reused this standalone application instead of creating a new one.

Many thanks
Olivier

**Comment by LindsayBert** [comment]
Glad that I could help :)

Thanks Lindsay
