### ISSUE TITLE
SAP HANA, express edition (Database   XS Advanced) - Getting started with the Marketplace on Microsoft Azure

### ISSUE THREAD

**Issue by ChrGlas** [SAPDocuments/Issues#10]
Tutorial: https://developers.sap.com/tutorials/hxe-ms-azure-marketplace-xsa.html
--------------------------

In your tutorial you describe how I use the hxe in Microsoft Azure. In step 1 I need to search for the "hana express" but the resource is not available. 
![image](https://user-images.githubusercontent.com/53343761/102879780-a7e4f200-444a-11eb-8cb0-625d225ab1fd.png)

**Comment by thecodester** [comment]
@jung-thomas Can you also republish to put the current person responsible for this tutorial? Thanks.

**Comment by jung-thomas** [comment]
I can't find the resource available in the Azure Marketplace any longer either.  I've put in a request to the SAP development team responsible to see what the story is.  Please note that with the holidays most of them are out of office right now.  

Might I suggest that instead you consider using HANA Cloud. Its a managed service that is part of SAP Cloud Platform and the recommended starting solution for developers wanting to explore HANA in the cloud. https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html

**Comment by jung-thomas** [comment]
Just confirmed with development that the removal from Azure is intentional and permanent. I will remove this tutorial. Please consider using HANA Cloud instead.

**Comment by ChrGlas** [comment]
Thank you for the information.

**Comment by ln-data-bass** [comment]
> Just confirmed with development that the removal from Azure is intentional and permanent. I will remove this tutorial. Please consider using HANA Cloud instead.

nooooo! why?
