### ISSUE TITLE
Tutorials - Degraded learning experience

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Issues#100]
Tutorial: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-4-visibility.html
--------------------------

Write here what you need help with: 

'Done' buttons don't turn green after clicking on them multiple times. So, the learning progress cannot be assigned a valid status.

Thank you,
gm

**Comment by ArchanaShukla** [comment]
@thecodester - this is more on the tutorial experience on clicking DONE button. Can you please suggest here!

**Comment by thecodester** [comment]
I am checking with IT.

@ArchanaShukla Sorry about that 😀

**Comment by thecodester** [comment]
The issue seems fixed.

@greg2git: Can you confirm?

**Comment by greg2git** [comment]
yup, it's all good now.
