### ISSUE TITLE
Run the Employee Onboarding Sample Scenario

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Issues#101]
Tutorial: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-5-run.html
--------------------------

Write here what you need help with ... Step 4.5 shows the following hard error:
The HTTP request to 'https://bpmruleruntime.cfapps.us10.hana.ondemand.com/rules-service/rest/v2/rule-services' failed with status code 401 (Unauthorized) and response body '{"error":"unauthorized","error_description":"Full authentication is required to access this resource"}'.

Thank you,
gm

**Comment by ArchanaShukla** [comment]
@greg2git - Did you run the Booster in the first exercise on Setup? Booster assigns all the needed roles to the user. If not then you can run the Booster again. Then you can check that the WorkflowManagementAdmin role collection is assigned to your user. This role collection has RuleRuntimeSuperUser role which is needed to run the rule. 

![image](https://user-images.githubusercontent.com/34297037/105635155-90ed5180-5e87-11eb-91d3-cfc3e6a6c060.png)

**Comment by greg2git** [comment]
i have rerun the booster but now this error prevents me from moving to the next step in the tutorial:

_An error occurred.
Could not load form data. Resource not found._

the 6 roles in the role collection seem fine.

**Comment by ArchanaShukla** [comment]
@greg2git - In which step do you get this error.

**Comment by greg2git** [comment]
@ArchanaShukla 

same tutorial in the subsequent step to 4.5 or in step 4.6:

_Click the My Inbox to display the Confirm or Change Equipment workflow task._

_You can add or delete the equipment, by choosing the Add_

there is no **Add** button for me to click on.

**Comment by ArchanaShukla** [comment]
@greg2git - may be scroll to the right, you will find the button, also ensure that you are in the right task and form. There are different for different task. Match the text in the image to yours

**Comment by greg2git** [comment]
the whole 'portlet' is not loading and is throwing this error:

![image](https://user-images.githubusercontent.com/24355032/107950790-43837200-6f65-11eb-959b-cb85f32dde61.png)

**Comment by MichaelCzcz** [comment]
@ArchanaShukla Any updates?

**Comment by ArchanaShukla** [comment]
I haven't seen this issue. We have tested multiple times. 
@greg2git - hope you have followed the tutorial. Do you still see this issue happening.
