### ISSUE TITLE
Get Started with the Command-Line Interface for SAP Cloud Platform (sapcp CLI)

### ISSUE THREAD

**Issue by mts2605** [SAPDocuments/Issues#102]
Tutorial: https://developers.sap.com/tutorials/cp-sapcp-getstarted.html
--------------------------

In step 9, when trying to log on, i get this;

Unexpected error during login (Correlation ID: 0a299135-8df4-48a3-91d8-056ed2cd0443).

ERROR

I have no problems logging on to https://account.hanatrial.ondemand.com/

BR Michael

**Comment by annawenger20** [comment]
Hi Michael, 
thanks for the question. Did you use a valid global account subdomain to log in? You find the subdomain in the cockpit, see attached image. 
![image](https://user-images.githubusercontent.com/63057657/105874390-c9626c00-5ffc-11eb-9d95-1c758bc83fd6.png)
If it still doesn't work, please run `sapcp --verbose login` and send us the output. 
Hope this helps, 
Anna

**Comment by mts2605** [comment]
Hi Anna
thanks for replying. It turned out that my inital installation was not good.
Everything fine, with that part;-) , now.
KR Michael
