### ISSUE TITLE
Reuse a CAP Java Service

### ISSUE THREAD

**Issue by mts2605** [SAPDocuments/Issues#104]
Tutorial: https://developers.sap.com/tutorials/cp-cap-java-service-reuse.html
--------------------------

Step 6 - Get errors:

user: bookstore $ cds deploy --to sqlite

[ERROR] db/schema.cds:14:56-62: Artifact "sap.capire.bookstore.Books" has no element "author" (in entity:"sap.capire.bookstore.Authors"/element:"books")
[ERROR] db/schema.cds:4:49-71: Cannot find package module '@sap/capire-products'
[ERROR] srv/services.cds:16:33-55: Cannot find package module '@sap/capire-products'
[ERROR] srv/services.cds:5:65-73: Element or variable "category" has not been found (in entity:"BooksService.Books"/element:"genre")

What to do?

BR Michael

**Comment by iwonahahn** [comment]
@beckermarc Can you take a look at the issue please? Thanks a lot.

**Comment by beckermarc** [comment]
Hi @mts2605, 

what is/was the output when you executed:

```
npm install $(npm pack ../products-service -s)
```

Did you make sure to follow all the steps at the end of the previous tutorial part: https://developers.sap.com/tutorials/cp-cap-java-reusable-service.html -> Step 9: Set up for reuse

Best regards,
Marc

**Comment by mts2605** [comment]
Hi Marc

Thanks for fast answer.

When looking at step 9 as suggested, after doing the full tutorial one more time, I noticed that the code shown from "your"package.json looks different than the one I see:

Shown below: (Where I, as you can see, have added new name = @sap/capire-products
_

{
  "name": "@sap/capire-products",
  "version": "1.0.0",
  "description": "Generated by cds-services-archetype",
  "license": "ISC",
  "repository": "<Add your repository here>",
  "cds": {
    "requires": {
      "db": {
        "kind": "sqlite",
        "model": "*"
      }
    }
  }
}
_

As I see it, some dependencies and scripts are missing!?

But most important, now it worked anyway;-)

Br,
Michael

**Comment by beckermarc** [comment]
Yes, these were only generated by older versions of our project generation archetype. Meanwhile those are not required anymore.
