### ISSUE TITLE
Set Up SAP Cloud Platform Launchpad Service

### ISSUE THREAD

**Issue by qingli-wang** [SAPDocuments/Issues#106]
Tutorial: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html
--------------------------

Thanks for the tutorial.

I was following this tutorial to set up the launchpad service. However at step 1.6 I was not able to find the subscription 'Launchpad' to be activated. I guessed this is because my account was set up at the time the launchpad service was not included by default. Then I followed the solution in https://answers.sap.com/questions/13228748/launchpad-service-not-available-in-cloud-foundry.html to add the service plan.

It seems that I am not the only one who may have this issue. It may be helpful to add a link or include this information so that people would know to resolve the issue when it happened.

Thanks!

**Comment by LindsayBert** [comment]
Hi

The tutorial has been updated with this information.

Thanks
Lindsay
