### ISSUE TITLE
SAP HANA Native, Create Database Artifacts Using Core Data Services (CDS)

### ISSUE THREAD

**Issue by danielva** [SAPDocuments/Issues#108]
Tutorial: https://developers.sap.com/tutorials/xsa-cap-create-database-cds.html
--------------------------

Download the header file and the items file into your local file system.

The files downloaded are xlsx files, while in the screenshot they appear as csv files.
A changes was made to the database explorer to no longer support xlsx files for import.

https://help.sap.com/viewer/a2cea64fa3ac4f90a52405d07600047b/cloud/en-US/7a0c586f5a4e442d976459e0f0a70c7a.html
Import Data (Behavior Change)
You can no longer import Excel files when importing data. You can only import CSV files.

**Comment by jung-thomas** [comment]
Not sure what happened there. Maybe we just missed changing the links.  The csv files are there in the repo and all the screenshots and other text had been changed over a while ago. But now the download links point to the csv files now as well.
