### ISSUE TITLE
Create Decision Table and Text Rules

### ISSUE THREAD

**Issue by RadovanMarinkov** [SAPDocuments/Issues#109]
Tutorial: https://developers.sap.com/tutorials/cp-cf-businessrules06-dt-textrule.html
--------------------------

Write here what you need help with ...

Dear all,
I cannot Activate Decision table. 

I can see the fields "Employee.isFulltimeEmploee" in both rows with expression "= true OR Employee.isFullTimeEmployee = false" in a red frame. When I try to Activate these error messages appeare:

Validation for rule has failed.
The header condition in column number 2 contains invalid expression:
Validation for rule has failed.
The header condition in column number 3 contains invalid expression:
Validation for rule has failed.
The header condition in column number 4 contains invalid expression:

What should i change, pls. thank you in advance. Radovan

**Comment by MichaelCzcz** [comment]
@VandanaVasudevan Please respond!

**Comment by VandanaVasudevan** [comment]
Hi Radovan,

Extremely sorry for the delay in reply. Can you please check for typos in the data object name? or the expression?

Best Regards,
Vandana

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
