### ISSUE TITLE
 Call a Remote Function Module From SAP Cloud Platform, ABAP Environment

### ISSUE THREAD

**Issue by fc158** [SAPDocuments/Issues#11]
Tutorial: https://developers.sap.com/tutorials/abap-env-rfc.html
--------------------------

Write here what you need help with ...

Hi Support, 
I would need help with Step 14. 'Test yourself' that appears to be empty: there is nothing to do, question to answer or whatever else to complete;
being like that, it's not possible to progress and complete the mission.

Please have a look and, if possible, correct the issue;

With best regards,
Flavio

**Comment by thecodester** [comment]
@julieplummer20 Remember when updating images or questions, you need to republish the MD file. I have done so and question now appears. Please also check your tutorials after publishing.

@fc158 Please try again.

**Comment by fc158** [comment]
@thecodester thank you very much for helping, it works now!
