### ISSUE TITLE
Secure a Basic Node.js App with the Authorization and Trust Management Service (XSUAA)

### ISSUE THREAD

**Issue by amitavamitra** [SAPDocuments/Issues#110]
Tutorial: https://developers.sap.com/tutorials/cp-cf-security-xsuaa-create.html
--------------------------

Write here what you need help with ...

Step 9 

4. Choose SAP ID Service.

I dont know where is SAP ID Service.  However , I must say without doing this step my app actually work in the sense , I can go to the end point and see the images of the laptops etc.

Kind Regards 

Amitava
![image](https://user-images.githubusercontent.com/20745562/106387109-11540b00-63d0-11eb-80a4-e05f91adb58c.png)

**Comment by nedo-SAP** [comment]
This issue should be fixed with the PR: https://github.com/SAPDocuments/Tutorials/pull/6467/files

**Comment by MichaelCzcz** [comment]
@nedo-SAP If it is solved, you can close this issue.
