### ISSUE TITLE
Add a New Entitlement to Your Subaccount

### ISSUE THREAD

**Issue by amitavamitra** [SAPDocuments/Issues#111]
Tutorial: https://developers.sap.com/tutorials/cp-cf-entitlements-add.html
--------------------------

Write here what you need help with ...

Step 5 I dont see any Save btutton

![image](https://user-images.githubusercontent.com/20745562/106389903-c5a85e00-63dd-11eb-9a93-a30eeed48275.png)

**Comment by IObert** [comment]
Did you already change the entitlements? The disabled "save" button (next to "add service plans") should be enabled as soon as you have unsaved changes.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
