### ISSUE TITLE
Help Thomas Get Started with SAP HANA Cloud

### ISSUE THREAD

**Issue by Selvven** [SAPDocuments/Issues#113]
Tutorial: https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html
--------------------------

In step 7 when creating the my-hdi I get the following error

Could not create the Failed to open connection to the database, because of: Failed to get connection for database '71a63089-d0bf-4471-8b75-945f07af8b99' (71a63089-d0bf-4471-8b75-945f07af8b99.hana.trial-eu10.hanacloud.ondemand.com:443), because of: SAP DBTech JDBC: Cannot connect to jdbc:sap://71a63089-d0bf-4471-8b75-945f07af8b99.hana.trial-eu10.hanacloud.ondemand.com:443 [Object is closed: com.sap.db.jdbc.SecureChannelSession@79ddbb8c 71a63089-d0bf-4471-8b75-945f07af8b99.hana.trial-eu10.hanacloud.ondemand.com:443 ConnectionID:0 SessionID:0 on sun.nio.ch.UnixAsynchronousSocketChannelImpl[connected local=/10.136.39.126:60004 remote=71a63089-d0bf-4471-8b75-945f07af8b99.hana.trial-eu10.hanacloud.ondemand.com/18.157.215.35:443]]. entity, consider deleting it using the 'cf delete-service my-hdi command'

I have then deleted the my-hdi and tried creating it via terminal and error i get is

name service plan bound apps last operation broker upgrade available 
my-hdi hana hdi-shared create failed sm-hana-broker-6ee33e0e-bc5a-4a6b-8715-5a697a76b655 S4
SELVVEN hana-cloud-trial hana create succeeded sm-hana-cloud-trial-9193d17c-64fe-44cb-a46d-a8fb4383fe16

Can anyone assist with a resolution?

Thanks

Selvven

businessone@telkomsa.net

**Comment by jung-thomas** [comment]
Same basic advice that you received from Denys in the community thread you opened https://answers.sap.com/questions/13240646/hdi-creation-failed.html

This error means your HANA system isn't running or isn't reachable.  Most likely it isn't running.  Remember that the HANA Cloud trial stops every night and must manually be restarted.  This error looks exactly like what you get when you try to deploy an HDI container but your system isn't running.  Return to the SAP BTP cockpit and check the status of your HANA systems.  This is the same place you can start the system and check the Allow List.
If running, then the Allow List is the 2nd most likely candidate - although the error message is generally slightly different with that situation. The Allow List controls which foreign IP addresses are allowed to connect to your HANA Cloud instance. For trial usage we suggest you use the Allow All.

**Comment by Selvven** [comment]
Thank you for the quick response.
I did as indicated and found that the HANA system was indeed stopped.
I restarted the HANA Cloud Trial and completed the creation of the HDI Service.

Thank you.
