### ISSUE TITLE
How to configure cors in via capire 

### ISSUE THREAD

**Issue by Victor716** [SAPDocuments/Issues#114]
How to configure cors in via capire ?
I've push the cap srv, app-router, and front end to cloud foundry. Get all xusaa and destination services binded.
But still get cors error when requesting api

Can  u help?

Victor Ye

**Comment by MichaelCzcz** [comment]
@Victor716 Please name the tutorial where you are having an issue. Thank you.

**Comment by MichaelCzcz** [comment]
These GitHub issues are to resolve issues (i.e., problems/errors) with the tutorials. Your question seems more general and likely 
would get more visibility -- and a better answer -- in the SAP Community's Questions & Answers. You can ask your question at:
https://answers.sap.com/index.html
