### ISSUE TITLE
Create an Empty SAPUI5 Project

### ISSUE THREAD

**Issue by bguler11** [SAPDocuments/Issues#115]
Tutorial: https://developers.sap.com/tutorials/sapui5-101-create-project.html
--------------------------

Write here what you need help with ...

Step 4: Create a new run configuration 

I get an error "There are no runnable resources."
![image](https://user-images.githubusercontent.com/37457811/106433807-bbd83680-6481-11eb-949b-0b924e449218.png)

**Comment by IObert** [comment]
Hi,

sorry for the late response. We updated the tutorial recently and now the run configuration is generated for you out of the box. I assume this resolves the issue. Can you please confirm?

**Comment by IObert** [comment]
I'll close this issue now but feel free to open it again if something remains unclear.
