### ISSUE TITLE
Create an API Provider System

### ISSUE THREAD

**Issue by AketzaLS** [SAPDocuments/Issues#117]
![Error](https://user-images.githubusercontent.com/78430285/106619936-60857180-6571-11eb-8602-5f75a3282498.png)
![Provider](https://user-images.githubusercontent.com/78430285/106619937-611e0800-6571-11eb-9123-043208acb6e9.png)

Tutorial: https://developers.sap.com/tutorials/hcp-apim-create-provider.html
--------------------------

Hi,

When viewing the list of services of the SAP Gateway System I get the following error:

No System Alias ​​found for Service '/ IWFND / SG_MED_CATALOG_0001' and user 'S0021022989'

Is there a problem with the Gateway system?

Thank you.

Regards.

**Comment by kulkarnir** [comment]
Hello, 

Sorry for the delay in reply,  looks like there is some issue in the SAP ES5 system.

Checking with the relevant team and will update..

Sorry for the inconvenience 

Regards, 
Raghavendra Kulkarni

**Comment by MichaelCzcz** [comment]
@kulkarnir Any updates?

**Comment by kulkarnir** [comment]
Hello Michael.

Sorry for the delay, now the ES5 issue is fixed.

Can you please add a new API Provider and try.. 

Regards,
Raghavendra Kulkarni

**Comment by MichaelCzcz** [comment]
@kulkarnir Sorry, I can't, because I didn't report the issue.

**Comment by thecodester** [comment]
@AketzaLS Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. It also seems like it was a temporary problem with ES5, which is now fixed.

If you still have questions, feel free to reopen the issue.
