### ISSUE TITLE
SAP HANA XS Advanced - Database access from Node.js

### ISSUE THREAD

**Issue by abarajithv** [SAPDocuments/Issues#118]
Tutorial: https://developers.sap.com/tutorials/xsa-node-dbaccess.html
--------------------------

Hi  am adopting this blog to develop a rest API without UI. 

Getting this error "System Error {}" while adding the route example1. 

1. I created my DB module it has Procedures to update and delete data. 
2. Created my Node JS and successfully created the route /node and got Hello world Nodejs message. 
3. While adding the route to access DB, and executing /node/example1 route, I get below error 
"System Error {}"
4. It results in internal error 500 and there are no much logs to trouble shoot. 

1. I have mta.yaml defined with correct dependencies. 
2. Created index.js and myNode.js accordingly
3. I have all the dependencies added in my package.json file 
4. attached my project file here. 

[xyziot_upload.zip](https://github.com/SAPDocuments/Issues/files/5915633/xyziot_upload.zip)

**Comment by jung-thomas** [comment]
It looks like you are catching an error in the index.js. That's where there is a System Error output.  I suggest changing this line to not stringify the error but output it as text:	res.status(500).send(`System Error ${JSON.stringify(err)}`);

When I look at your server.js you aren't initializing the hana connection as middleware. In fact you aren't making a connection to HANA at all.  See lines 53-59. You've commented them out but without this logic there is no connection to HANA. Hence the generic errors as you later try to access a HANA connection that is null.

**Comment by abarajithv** [comment]
Thanks Thomas.

Culprit was the 53-59 (Technically it was me :) ) My intention was to disable authentication. After enabling 	xsHDBConn.middleware(hanaOptions.hana), It worked like a charm. 

Much appreciate your quick response.
