### ISSUE TITLE
Register SAP Cloud Platform Cloud Foundry Subaccount in Identity Authentication Service

### ISSUE THREAD

**Issue by xanderrijken** [SAPDocuments/Issues#122]
Tutorial: https://developers.sap.com/tutorials/cp-ias-azure-ad-cf.html
--------------------------

Write here what you need help with ...
I have a trail account which I wanted to connect to a 3rd party SAML 2.0 provider.
According to te tutorial I have to go to https://[TENANT_ID].accounts.ondemand.com/admin
But this doesn't seem to work... I get 404 not found errors on this location.

Is this feature available for trial accounts? Is the link still valid, pls help.

Kind regard
Xander

**Comment by xanderrijken** [comment]
Hi @maxstreifeneder,

Can you pls tell me if this url "https://[TENANT_ID].accounts.ondemand.com/admin" is still available on the SAP Trail environment?

Hoping to hear from you soon.

Kind regards
Xander

**Comment by maxstreifeneder** [comment]
Hey @xanderrijken, 

sorry for the late feedback. (Just had a parallel convo with your colleague Wim)

Unfortunately SAP Identity Authentication Service doesn't have a trial offering so far. 
In the first tutorial of the mission it's described that you need IAS (which is a paid service). 

![image](https://user-images.githubusercontent.com/36535298/109502034-bf6ad780-7a98-11eb-9e9f-dbd4129f9679.png)
![image](https://user-images.githubusercontent.com/36535298/109502047-c42f8b80-7a98-11eb-824a-b9d27dcf6ac9.png)

The TENANT_ID is provided once you have your own (paid) IAS tenant. 

Sorry and regards,
Max

**Comment by xanderrijken** [comment]
Thanks for your reply, we will look into IAS services.
Have a nice day!
