### ISSUE TITLE
Expose Integration Flow Endpoint as API and Test the Flow

### ISSUE THREAD

**Issue by mts2605** [SAPDocuments/Issues#123]
Tutorial: https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html
--------------------------

Step 3, ad 12. Would appreciate some assistance on the needed lines of code before and after. 
When going to "ad 14! I do not get the same result in Example value.
Please provide example of lines from

32  -  components:
..

Thx
Michael

**Comment by Karunaharan** [comment]
@mts2605 - thanks for the feedback. Will update the specific step.
