### ISSUE TITLE
Expose Integration Flow Endpoint as API and Test the Flow

### ISSUE THREAD

**Issue by mts2605** [SAPDocuments/Issues#125]
Tutorial: https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html
--------------------------

Hi,
At step 5, ad 4 - the result i get is;

Code 500
_
{
  "fault": {
    "faultstring": "Execution of ServiceCallout getoauthtoken failed. Reason: ResponseCode 401 is treated as error",
    "detail": {
      "errorcode": "steps.servicecallout.ExecutionFailed"
    }
  }
}
_
BR Michael

**Comment by Karunaharan** [comment]
Hello @mts2605 - the issue usually occurs when there are errors while pasting the tokenURL in step 4.17
Could you please recheck? The tokenURL is copied from the service key in step 1.10
