### ISSUE TITLE
Create a Basic Flow with a SOAP Endpoint

### ISSUE THREAD

**Issue by mts2605** [SAPDocuments/Issues#126]
Tutorial: https://developers.sap.com/tutorials/cp-integration-create-basic-flow.html
--------------------------
Step 8 - point 3, after hit Send

Get error: (Status 500)

An internal error occurred. For error details check MPL ID AGAfCQCu0-UWKaKmB2J0nlDgoOWo in message monitoring or use the URL..

Please advice.
(Changing PW gives Status 401 UnA..... - thus it not that part;-) )

**Comment by gauthamkrishna-sap** [comment]
Hello,
We are updating this whole series in the context of the new RISE offering from SAP. Please stay tuned for further updates on this and try again in a couple of weeks.
Apologies for the inconvenience. 
Best Regards,
Gautham

**Comment by mts2605** [comment]
@gauthamkrishna-sap
Thanks, look very much forward to that.
BTW - I got https://developers.sap.com/mission.cp-starter-integration-cpi.html to work "all the way" ;-)

**Comment by gauthamkrishna-sap** [comment]
Yes, that is our new tutorial for Integration Suite :) Happy to hear that you could complete it fully.

We will update this mission also in the context of Integration Suite to ensure that you can complete this on trial landscape. 

Best Regards, Gautham

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
