### ISSUE TITLE
Start Your MDK Application in the Editor

### ISSUE THREAD

**Issue by boghyon** [SAPDocuments/Issues#127]
Tutorial: https://developers.sap.com/tutorials/cp-mobile-dev-kit-offline-app.html
--------------------------

Same issue as https://github.com/SAPDocuments/Issues/issues/16 but in a different tutorial. The `Application Id` field is empty. There is nothing to select.

I was doing the mission ["Create Your First MDK Application"](https://developers.sap.com/mission.mobile-dev-kit-get-started.html) with a fresh BTP trial account. Completed the 1st group, and now I'm stuck at the 2nd step ["Start Your MDK Application in the Editor"](https://developers.sap.com/tutorials/cp-mobile-dev-kit-offline-app.html) because of the empty field despite having the correct Cloud Foundry space assigned:

![logged-in-BAS-but-still-no-application-id-selectable-MDK](https://user-images.githubusercontent.com/12143247/107154222-17b72980-6972-11eb-9097-342479341cfc.gif)

Can anyone reproduce this?

**Comment by jitendrakansal** [comment]
@boghyon 

I don't find any issue in my trial account (eu10)

Can you please share Admin API URL from your Mobile Services trial account? 

In Mobile Services cockpit > click "Important Links" on bottom left >you will find **Admin API** under **SAP Cloud Platform SDK Tools** section
e.g. https://mobile-service-cockpit-web.cfapps.eu10.hana.ondemand.com/cockpit/v1/org/**facv2333trial**/space/**dev**

**Comment by boghyon** [comment]
https://mobile-service-cockpit-web-preview.cfapps.eu10.hana.ondemand.com/cockpit/v1/org/54596aaftrial/space/dev

**Comment by boghyon** [comment]
Could it be related to the fact that I have somehow the "Preview" version of the Mobile Service?

![MDK-preview](https://user-images.githubusercontent.com/12143247/107201957-ef730d80-69f9-11eb-9f43-857a8d52e4eb.gif)

I see no stable version of it even though the subaccount is **not beta:**

![SCP-no-beta-subaccount](https://user-images.githubusercontent.com/12143247/107202081-10d3f980-69fa-11eb-9ba6-61dadc51fe15.gif)

**Comment by jitendrakansal** [comment]
@boghyon there is currently a known issue in the BAS editor to connect to other Mobile Services editions (like preview). 
We are currently looking into this. 

If possible, switch to other account which has standard Mobile Services to continue your work.

Additionally, can you check below: 

Expand **Entitlements** in your last screenshot >Entity Assignments > select subaccount >Click Go > Configure Entitements > Add Service Plans> Search Mobile 
Do you see any entitlment other than Mobile Services preview?

**Comment by boghyon** [comment]
>Do you see any entitlment other than Mobile Services preview? 

No, there is only the "Mobile Services, preview".
![No-entitlements-other-than-Mobile-Services](https://user-images.githubusercontent.com/12143247/107208570-17ff0580-6a02-11eb-8f2c-8d0ce094d24b.gif)

> If possible, switch to other account which has standard Mobile Services to continue your work.

I might have to create a whole new SAP Community account for that. Is there a way to create a 2nd trial account without changing the entire SAP user account?

And how come that I have "Mobile Services Preview" in the Service Marketplace even though the "trial" subaccount is not in beta?

**Comment by jitendrakansal** [comment]
@boghyon can you do the following in your trial account?

- delete all apps configuration in Mobile Services preview cockpit
- Expand Entitlements in your last screenshot >Entity Assignments > select subaccount >Click Go > Configure Entitements 
- scroll down and delete "Mobile Services preview" , save 
- double check if it's been deleted from the list
- Click Configure Entitements > Add Service Plans> Search Mobile > select Mobile Services (without preview)
- once added successfully, create app config again in Mobile Services cockpit. 
- You should now be able to connect from BAS to this Mobile services account 

Mobile Services, preview will provide  our customers and partners the chance to validate their current solution against
the next release of Mobile Services into production landscape. You'll hear more about it in coming days/weeks.

**Comment by boghyon** [comment]
@jitendrakansal Had to recreate my trial account since the BTP didn't let me delete the "Mobile Services preview" (despite having no apps there). With the new trial account, I'm now able to use the stable "Mobile Services" and select the app from the template in BAS.

Thank you for the guidance! This issue is resolved.
