### ISSUE TITLE
Step 2.4 Develop and Run SAP Fiori Application With SAP Business Application Studio

### ISSUE THREAD

**Issue by hitesh-parmar** [SAPDocuments/Issues#128]
Tutorial: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html
--------------------------

On Step 2.4, screenshot mentions to select "Launchpad module", but this is not available to select.
Looks like this is changed now and hence this information needs to be updated.

**Comment by mervey45** [comment]
Hi @hitesh-parmar ,

thank you for your e-mail, we'll upate this as soon as possible.

Best regards,
Merve

**Comment by mervey45** [comment]
Hi @MichaelCzcz ,

I created following pull request for this issue: #6552.
Can you merge?

Thank you.

Best regards, 
Merve
