### ISSUE TITLE
Step 4 Develop and Run SAP Fiori Application With SAP Business Application Studio

### ISSUE THREAD

**Issue by hitesh-parmar** [SAPDocuments/Issues#129]
Tutorial: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html
--------------------------

As Application generator flow is changed, screenshots and user flow needs to be updated.

Example: 
- Step 4.2  New image 

![image](https://user-images.githubusercontent.com/24454497/107214407-281ae300-6a0a-11eb-9894-617c989d0df4.png)

- ABAP Environment: **ABAP Trial** (This is the name which is used when creating new ABAP Trial instance)
- Hint should be given at the beginning of Step 6

**Comment by mervey45** [comment]
Hi @hitesh-parmar ,

thank you for your e-mail, we'll upate this as soon as possible.

Best regards,
Merve

**Comment by mervey45** [comment]
Hi @MichaelCzcz ,

I created following pull request for this issue: #6552.
Can you merge?

Thank you.

Best regards, 
Merve
