### ISSUE TITLE
Step 5 Run SAP Fiori application for data preview

### ISSUE THREAD

**Issue by hitesh-parmar** [SAPDocuments/Issues#130]
Tutorial: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html
--------------------------

Sep 5.3
Application is now started directly and hence we can directly jump to Step 7 (steps 3 to 6 are outdated)

**Comment by mervey45** [comment]
Hi @hitesh-parmar ,

thank you for your e-mail, we'll upate this as soon as possible.

Best regards,
Merve

**Comment by mervey45** [comment]
Hi @MichaelCzcz ,

I created following pull request for this issue: #6552.
Can you merge?

Thank you.

Best regards, 
Merve
