### ISSUE TITLE
Build Your Mobile Development Kit Client Using Cloud Build Service

### ISSUE THREAD

**Issue by mlvai** [SAPDocuments/Issues#131]
Tutorial: https://developers.sap.com/tutorials/cp-mobile-dev-kit-cbs-client.html
--------------------------
hello , i cant resolve this message  .

![Screenshot_20210207-225734](https://user-images.githubusercontent.com/61939539/107217503-03fcd900-69ed-11eb-9285-90b6f713535e.jpg)
source:
![bas 2021-02-08 09-08-54](https://user-images.githubusercontent.com/61939539/107217738-5fc76200-69ed-11eb-87c6-f3d909def566.png)

**Comment by jitendrakansal** [comment]
@mlvai _ODataService.Initialize action_ type was introduced as part of [MDK 5.0 release](https://blogs.sap.com/2020/10/27/whats-new-in-mobile-development-kit-client-5.0/#ODataServiceInitializeAction) , Cloud build service hasn't yet updated to that version (5.x) to work with new OData initialize action. We are looking into this. 

I suggest you to either use public store client ([iOS](https://apps.apple.com/us/app/sap-mobile-services-client/id1413653544) or [Android](https://play.google.com/store/apps/details?id=com.sap.mobileservices.client) ) or [brand your client using MDK SDK](https://developers.sap.com/tutorials/cp-mobile-dev-kit-build-client.html).

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
