### ISSUE TITLE
Mention correct capability name

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#132]
Hello,

Scenario URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html
Step 1: Click on the URL in the integration capability. Click the Design tab (pencil icon) to access your workspace. This is where you will create your integration package and integration flow.

Issue: Please mention clearly to Click on the URL of "Cloud Integration" capability for better understanding. This is looking quite confusing.

Labels to be added:
Landscape Labels: all,
Sprint Label: SCPTest-2102
Scenario Label: SCPTest-cloudin
prio: low-prio

Thanks,
Shubham Agarwal

**Comment by Karunaharan** [comment]
@i353590 - fixed the content. awaiting approval from developer relations team to send a pull request. will be available asap.
