### ISSUE TITLE
Activation of capabilities Cloud Int. & API management failing in EU

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#133]
Hello,

Scenario URL: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html
Step 4: Provision the capabilities.
Issue: The provisioning of capabilities - Cloud Integration & API Management is failing in EU region with error message: 
"Error T001: Activation of Cloud Integration capability has failed. Please try again later. If the issue persists, please send your application URL and details of the error message to cpitrialfeedback@sap.com" 
&
"Error C002: Activation of API Management capability has failed. Please try again later. If the issue persists, please send your application URL and details of the error message to cpitrialfeedback@sap.com"
Screenshot attached for reference:
![image](https://user-images.githubusercontent.com/66831161/107322938-66c4a200-6acb-11eb-87ba-01d246b99737.png)

Labels to be added:
Landscape Labels: trial1 (EU)
Sprint Label: SCPTest-2102
Scenario Label: SCPTest-cloudin
prio: HIGH-prio

Thanks,
Shubham Agarwal

**Comment by Karunaharan** [comment]
@i353590 - As discussed, unable to duplicate the issue in EU subaccounts. Tried this morning and noon too. Able to activate the capabilities.

**Comment by i353590** [comment]
Hello @Karunaharan ,
Yes, the issue is not reproducible now. now working in EU region.

Thanks,
Shuhbam

**Comment by Markus485** [comment]
This issue currently occurs again with region US East (VA)
