### ISSUE TITLE
Screenshot of the SAP Cloud platform Trial home page has to be changed

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Issues#134]
Tutorial: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html
--------------------------
**Step 1: Subscribe to the Launchpad service**

Here the Screenshot of the SAP Cloud platform Trial home page has to be changed. In the latest version, BAS is displayed instead of WebIDE.

**Expected:**
![image](https://user-images.githubusercontent.com/65999547/107329519-4a7a3280-6ad6-11eb-99bd-f9f4e6b77e82.png)

**Actual:**
![image](https://user-images.githubusercontent.com/65999547/107329552-536b0400-6ad6-11eb-99eb-510170d6e8e7.png)

Best Regards,
Priyanka

**Comment by LindsayBert** [comment]
Hi there are many more changes to the cockpit as well as rebranding so most of the screenshots will be changed in the upcoming weeks.

Thanks
Lindsay

**Comment by LindsayBert** [comment]
Hi

All screenshots have been changed and will be published this week

Thanks Lindsay
