### ISSUE TITLE
Services tab missing in the cockpit screenshots in the tutorial

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Issues#135]
Tutorial: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html
--------------------------

Where ever the trial subaccount screenshots is displayed, the services tab is missing in all of the screenshots.

**Expected:**
![image](https://user-images.githubusercontent.com/65999547/107334007-33d6da00-6adc-11eb-9daf-f023c134c194.png)

**Actual:**
![image](https://user-images.githubusercontent.com/65999547/107333567-ab583980-6adb-11eb-924a-1a3fc8bb5163.png)

**Note:** This issue is there in multiple steps of the tutorial, Please change all of them.

**Comment by LindsayBert** [comment]
Hi 

This tutorial will be updated in the upcoming weeks.  Most screenshots need to be updated.

Thanks
Lindsay

**Comment by LindsayBert** [comment]
Hi

All screenshots have been updated.

Thanks 
Lindsay
