### ISSUE TITLE
Access SAP Cloud Platform Mobile Services

### ISSUE THREAD

**Issue by fleischr** [SAPDocuments/Issues#136]
Tutorials: https://developers.sap.com/tutorials/fiori-ios-hcpms-setup.html
--------------------------

Mobile Services not available in trial account as instructed here "Access SAP Cloud Platform Mobile Services" (https://developers.sap.com/tutorials/fiori-ios-hcpms-setup.html)

**Comment by sandeep-tds** [comment]
Hi @fleischr, 

Thank you for raising the issue. We had an issue with the service that has been fixed now. Can you please re-test it? 

Warm Regards
Sandeep T D S

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
