### ISSUE TITLE
Create Instance of SAP Cloud Platform Enterprise Messaging Service

### ISSUE THREAD

**Issue by SchroederSteffen** [SAPDocuments/Issues#138]
Tutorials: https://developers.sap.com/tutorials/cp-enterprisemessaging-instance-create.html
--------------------------

Hi Team,

We went through the mission 'Develop Enterprise Messaging Apps on SAP Cloud Platform' and the tutorial 'Create Instance of SAP Cloud Platform Enterprise Messaging Service' and noticed that the system doesn't seem to store the completion of the first question 'The rules of an SAP Cloud Platform Messaging queue are defined while ...' properly.
If you answer the test, a success message comes up but when going on the same page again (e.g. refresh), the tutorial progress is incomplete again because the question is marked as unanswered.
Because of this, the whole mission can't be completed either.

Could you please have a look?

Cheers,
Steffen

**Comment by pradeeppanda-sap** [comment]
Hi Steffen,
 Please check below image. I tried and its working fine. Can you please check again and let me know, if you are still facing the issue?

regards
Pradeep
  
![image](https://user-images.githubusercontent.com/51952722/113238092-acc90580-92c5-11eb-9a45-9a4b693dd238.png)

**Comment by SchroederSteffen** [comment]
Hi Pradeep,
Unfortunately, the issue still exists.
I can complete the tutorial:
![image](https://user-images.githubusercontent.com/48728802/113252689-6fb04380-92c4-11eb-9bc8-22847e72ffc3.png)

But after a refresh the progress is reset again:
![image](https://user-images.githubusercontent.com/48728802/113252736-7dfe5f80-92c4-11eb-841c-d0607a45c875.png)

Kind regards,
Steffen

**Comment by thecodester** [comment]
We have an issue open for this so I will close this one

https://github.com/SAPDocuments/Tutorials/issues/5574
