### ISSUE TITLE
Set Up SAP Cloud Platform Launchpad Service

### ISSUE THREAD

**Issue by beapasch** [SAPDocuments/Issues#14]
Tutorial: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html
--------------------------
"Step 6: Enter Launchpad in the search box and click the Launchpad service tile."

You should rework the tutorial because it seems that "Launchpad" was replaced with "Portal" in the meantime.
Kind regards, Bea

**Comment by LindsayBert** [comment]
Hi

It's the other way around.  The Portal has been replaced by Launchpad and you need to click on the Launchpad service tile.

Thanks
Lindsay

**Comment by beapasch** [comment]
Hi Lindsay, 
did I miss a step or why I can't find the "Launchpad" tile in my SCP Trial account? 
I can only find the "Portal" tile and also can't add the "Launchpad" via an entitlement. 
Thanks and kind regards, Bea

**Comment by LindsayBert** [comment]
Hi

Are you are using the **Launchpad** trial account?

Thanks
Lindsay

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
