### ISSUE TITLE
 Create an Application for Producing Messages

### ISSUE THREAD

**Issue by SchroederSteffen** [SAPDocuments/Issues#140]
Tutorials: https://developers.sap.com/tutorials/cp-enterprisemessaging-nodejs-producing-app.html
--------------------------

Hi Team,

We noticed that the sample code for the producer.js misses apostrophes around the use strict; at the top.
It's written as `use strict;` while it should be `'use strict';`.

Please fix it.

Cheers,
Steffen

**Comment by pradeeppanda-sap** [comment]
fixed.

**Comment by SchroederSteffen** [comment]
Thanks! 👍
