### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by mounikat987** [SAPDocuments/Issues#141]
Tutorials: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html
--------------------------
Landscape label: trail1  & ap
Priority : High-prio

Step 1: Create new SAP Fiori project

**Issue** : 

Step  No : Make sure that the target folder is /home/user/projects, select the SAP Fiori Freestyle Project template, and click Start.

In  EU & AP region , it is  appeared as "SAP Fiori Freestyle Project(deprecated)"

![image](https://user-images.githubusercontent.com/33411431/107528842-4803ff80-6be0-11eb-96b1-291be3d867bd.png)

![image](https://user-images.githubusercontent.com/33411431/107528989-6ec23600-6be0-11eb-9677-29a362909228.png)

Note : This issue is not reproducible in EU region. It works fine there.

Please change screenshot & also update the template so that it doesn't show depricated version.

Thanks 
Mounika

**Comment by raz-korn** [comment]
Hi @mounikat987 ,

I'm in the process of validating that the new tooling support the flow. Until then the current (deprecated) tooling will be used.

Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
