### ISSUE TITLE
Create a Dev Space for SAP Fiori Apps

### ISSUE THREAD

**Issue by mounikat987** [SAPDocuments/Issues#142]
Tutorials: https://developers.sap.com/tutorials/appstudio-devspace-fiori-create.html
--------------------------

Landscape label: trail1  trial2 & ap
Priority : Low-prio

**Issue :**

Step 2: Create a preconfigured SAP Fiori dev space

Here, the warning message is little different from actual message.

![image](https://user-images.githubusercontent.com/33411431/107530045-7f26e080-6be1-11eb-9cd9-0a592a837828.png)

Please change the screenshot.

Thanks
Mounika

**Comment by raz-korn** [comment]
Hi @mounikat987 ,

It will be part of the next update, including additional outdated screenshots.

Regards - Raz

**Comment by MichaelCzcz** [comment]
@raz-korn Has the tutorial been updated?

**Comment by raz-korn** [comment]
@MichaelCzcz @MamathaKH : Yes, the tutorial was updated. Yesterday it was used successfully in a partners workshop with 50 participants.

Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
