### ISSUE TITLE
Set Up Account for Document Information Extraction and Go to Application

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Issues#143]
Tutorials: https://developers.sap.com/tutorials/cp-aibus-dox-booster-app.html
--------------------------

Unsubscription to  Document Information Extraction Trial UI application is failing in both EU10 and US10 trial regions.

![image](https://user-images.githubusercontent.com/50734023/107617386-d6769080-6c75-11eb-8f49-eed9523c0758.png)

BCP ticket : https://support.wdf.sap.corp/sap/support/message/2180070784

**Comment by Juliana-Morais** [comment]
@NidhiMurkute : I've just tested using EU10 and it worked fine. Can you please try again?

**Comment by Juliana-Morais** [comment]
I've just tested once again. Subscription deletion is working fine.

**Comment by NidhiMurkute** [comment]
Hi Juliana-Morais,

I have deleted and cretaed new trial account and rechecked the issue. It still persists, kindly check.
![image](https://user-images.githubusercontent.com/50734023/108679601-c763ce00-7512-11eb-9a85-2fb8d4dff9f4.png)

**Comment by Juliana-Morais** [comment]
@NidhiMurkute : have you tried using the "Instances and Subscriptions" tab and deleting the  subscription. This screenshot looks like the outdated cockpit UI from the old "Subscriptions" tab. I'm able to create and delete the subscription without any issue. Can you send me the link to the BCP ticket?

**Comment by NidhiMurkute** [comment]
@Juliana-Morais : I am trying to unsubscribe using  "Instances and Subscriptions" tab only. Created new subaccount in US10 region. 
![image](https://user-images.githubusercontent.com/50734023/108691933-09e0d700-7522-11eb-8e88-fcd52483e105.png)

BCP ticket : https://support.wdf.sap.corp/sap/support/message/2180070784

**Comment by Juliana-Morais** [comment]
@NidhiMurkute : Thank you for the BCP ticket link.  

Have you deleted the service instance and service key before deleting the subscription? You first delete the subscription, and then the service key and finally service instance.

**Comment by NidhiMurkute** [comment]
@Juliana-Morais : As shared in screenshot, have deleted the service key and instance before unsubscription.

**Comment by Juliana-Morais** [comment]
@NidhiMurkute: then that's why the deletion is failing. Please create a service instance, delete the subscription, and then delete the service instance. Can you please try that?

**Comment by NidhiMurkute** [comment]
@Juliana-Morais : Thank you. Its working now.
