### ISSUE TITLE
Define and Expose a CDS-Based Travel Data Model

### ISSUE THREAD

**Issue by alexalmeidabr** [SAPDocuments/Issues#145]
Tutorials: https://developers.sap.com/tutorials/abap-environment-data-model.html
--------------------------

Getting the following error _"unexpected work root; the key work VIEW was expected"_ at the following line:

`define root view entity ZI_TRAVEL_M_XXX`

**Comment by mervey45** [comment]
Hi @alexalmeidabr ,

did you replaced all XXX with your number or initials? Use CTRL + F to search and replace all Xs.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
