### ISSUE TITLE
Call a Remote Function Module From SAP Cloud Platform, ABAP Environment

### ISSUE THREAD

**Issue by fjcarrasco** [SAPDocuments/Issues#146]
Hello. Regarding this tutorial https://developers.sap.com/tutorials/abap-env-rfc.html 

The abap class to test the connection doesn't find the destination in cloud.

<img width="551" alt="Captura" src="https://user-images.githubusercontent.com/77397326/107849266-65141a80-6dfa-11eb-8d01-aa23e1d4ca79.PNG">

Here my destination in cloud platform and cloud connector:

<img width="288" alt="Captura2" src="https://user-images.githubusercontent.com/77397326/107849294-a3113e80-6dfa-11eb-8d8a-a273328fc244.PNG">

<img width="311" alt="Captura3" src="https://user-images.githubusercontent.com/77397326/107849335-f3889c00-6dfa-11eb-848d-eef783445668.PNG">

<img width="490" alt="Captura4" src="https://user-images.githubusercontent.com/77397326/107849373-292d8500-6dfb-11eb-90a3-886465a15b69.PNG">

When I check the destination I get this:

![image](https://user-images.githubusercontent.com/77397326/107849406-43fff980-6dfb-11eb-9c7c-34299c558e3c.png)

Thanks

**Comment by fjcarrasco** [comment]
Ups...I have just seen this tutorial can't be completed with a trial account. Is this the problem?

**Comment by julieplummer20** [comment]
Hi FJ, 
Yes, that's the problem. I'm sorry, you won't be able to complete the tutorial.
BR Julie.
