### ISSUE TITLE
Add an API Proxy to a Product

### ISSUE THREAD

**Issue by miyasuta** [SAPDocuments/Issues#148]
Tutorials: https://developers.sap.com/tutorials/hcp-apim-create-product.html
--------------------------

Step 7: Click Publish

I'm using my trial account to follow this tutorial.
I have created Product and tried to publish it. Then I got the following message.

![image](https://user-images.githubusercontent.com/39408125/107863982-8b3dc700-6e9b-11eb-98f2-209769fd8bba.png)

Is trial version not supported for publishing Products?

**Comment by kulkarnir** [comment]
Hello, 

You have not enabled API Business Hub Enterprise, please enable it and try again 

Please check Step 4, Provision Capabilities

**Comment by miyasuta** [comment]
Hello @kulkarnir
Thanks for your reply.
I have enabled API Business Hub and now able to access it.
