### ISSUE TITLE
Define and Expose a CDS-Based Travel Data Model

### ISSUE THREAD

**Issue by nvnarendran** [SAPDocuments/Issues#149]
Tutorials: https://developers.sap.com/tutorials/abap-environment-data-model.html
--------------------------

Under step #4 in the given link point #6 Logon to your ABAP system, but doesn't mention the credentials to use if the hana trial is used with SSO. Kindly help

**Comment by mervey45** [comment]
Hi @nvnarendran,

this is ABAP Trial, not HANA trial. Please use ABAP Trial and logon with your credentials from the SAP Cloud Platform cockpit.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
