### ISSUE TITLE
Welcome Mobile Card not loading in Mobile Cards app

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#153]
Hello,

Scenario URL: https://developers.sap.com/tutorials/cp-mobile-cards-welcome.html
Step 3: View card on your mobile device

Issue: After adding the subscription in the mobile app, the card is not getting loaded in the app and it says "Failed to process card from subscription Booster Welcome Card" in the activity log of the mobile app.

Labels to be added:
Landscape label: trial1
Sprint Label: SCPTest-2102A
Scenario Label:: SCPTest-mcard

Thanks,
Shubham

**Comment by i353590** [comment]
Hello,

I have tried the scenario again today as per the Update i received that the Services issue has been fixed.
the issue is still reproducible in EU region and also, the same is reproducible in US Region also.
Only in AP Region the Welcome card was loaded successfully.
In the log Mobile app it says "Failed to process card from subscription Booster Welcome Card" 

Please look into the issue once.

labels to be added: trial2
Thanks,
Shubham

**Comment by sandeep-tds** [comment]
Hi @i353590,

Thank you so much for raising the issue. We need more details to discuss the same. Thus, I will set up a meeting with you to discuss these.

Thank you for your support.

Warm Regards
Sandeep T D S

**Comment by sandeep-tds** [comment]
Hi @i353590

Thank you so much for your time. As discussed in the call, can you please confirm the behaviour in the EU region and close the ticket? 

Thank you for your support.

**Comment by i353590** [comment]
Hello Sandeep,

Thanks for discussion.
I have retested the same in EU region as well, and the issue was not reproducible, hence we can close the ticket.

Thanks,
Shubham
