### ISSUE TITLE
Develop and Run SAP Fiori Application With SAP Business Application Studio

### ISSUE THREAD

**Issue by morriswangx** [SAPDocuments/Issues#155]
Tutorials: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html
--------------------------
Hi There,

At the end of Step 6: Deploy your application, everything worked properly. However, when I copied the URL of the application and ran it on a browser, the following message was displayed:
403 Forbidden
The request has been blocked by UCON. Server time: 2021-02-15 19:53:45

Is this meant to be? I am new to SAP so pardon me if it's a dumb question.

Morris.

**Comment by mervey45** [comment]
Hi @morriswangx ,

I assume, that you aren't then logged on with your user, when you try to open it from the browser. Because only your user can open it in the trial system. 

Best regards,
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
