### ISSUE TITLE
Use an OData Service Created by MTB to Build a Mobile App

### ISSUE THREAD

**Issue by pjcools** [SAPDocuments/Issues#16]
Tutorial: https://developers.sap.com/tutorials/cp-mobile-mtb-mdk.html
--------------------------

Step 1: Trying to follow the Tutorial but the App ID selections are not showing up correctly. 

![image](https://user-images.githubusercontent.com/38389079/103276701-5aa0eb80-4a1b-11eb-8a1e-4fd45b03511f.png)

I have selected the Mobile Services option but now the Application Id does not show any options. The tutorial screens are also different to what I am experiencing - possibly updates to BAS?

I cannot continue with this tutorial until this is resolved.

Thanks & Kind Regards
Phil Cooley

**Comment by HYMXDEV** [comment]
Hi, could you please double-check that you have selected the correct Cloud Foundry space?
In the bottom left corner of BAS you can find the current target.

![image](https://user-images.githubusercontent.com/12176022/103284281-1857ba00-49db-11eb-8df4-a851789dc995.png)

Please visit the Mobile Services Admin Cockpit and select the org and space mentioned in BAS.
I suppose you are working on EU10, so please use the following link:
[https://mobile-service-cockpit-web.cfapps.eu10.hana.ondemand.com](https://mobile-service-cockpit-web.cfapps.eu10.hana.ondemand.com)

![image](https://user-images.githubusercontent.com/12176022/103284298-260d3f80-49db-11eb-9199-6ff471be28ee.png)

After selecting the correct org and space, please check that you can retrieve the Mobile Services apps in the cockpit (go to Mobile Applications > Native/Hybrid):

![image](https://user-images.githubusercontent.com/12176022/103284357-5228c080-49db-11eb-950f-1a78c9f3f5b9.png)

If you are sure, that you have targeted the right space in BAS (that is, if you can see the apps in the Mobile Services Cockpit), it would be very helpful if you send me your org and space name. In case you don't want to put them here, you can also send me a mail to [leonard.heilos@sap.com](mailto:leonard.heilos@sap.com).

If you can't see the apps, you have probably selected the wrong space inside BAS. Therefore please follow this tutorial to target the correct space:
[https://developers.sap.com/tutorials/cp-mobile-bas-setup.html#f1eea453-c93e-41ca-9c95-ab8ea9908e15
](https://developers.sap.com/tutorials/cp-mobile-bas-setup.html#f1eea453-c93e-41ca-9c95-ab8ea9908e15
)
Best regards
Leonard

**Comment by boghyon** [comment]
@HYMXDEV Same issue at https://github.com/SAPDocuments/Issues/issues/127

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
