### ISSUE TITLE
Set Up SAP Business Application Studio for Development

### ISSUE THREAD

**Issue by eldwinc** [SAPDocuments/Issues#163]
Tutorials: https://developers.sap.com/tutorials/appstudio-onboarding.html
--------------------------

After getting Access Denied screen, i log off log in and im back in the Access Denied screen instead of being prompted with an agreement.

ive also tried accessing BAS from the cockpit under subscriptions and from there, it is also access denied

**Comment by raz-korn** [comment]
Hi @eldwinc ,

Are you using trial account? Which landscape?
Can you share a screenshot (with the url)?

Thanks - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
