### ISSUE TITLE
Register SAP Cloud Platform Cloud Foundry Subaccount in Identity Authentication Service

### ISSUE THREAD

**Issue by kainiklas** [SAPDocuments/Issues#165]
Tutorials: https://developers.sap.com/tutorials/cp-ias-azure-ad-cf.html
--------------------------

The prerequisites for this tutorial states: 
- "Get a Free Trial Account on SAP Cloud Platform". 

Unfortunately, it seems, that a trial account does not provide an IAS. Is this correct? 

- If yes, maybe correct the prerequisites. 
- If no, maybe provide an instruction where to find/get the IAS tenant

**Comment by ValAta** [comment]
In the prerequisites, I added information on how to get the IAS tenant.
