### ISSUE TITLE
Debug Your SAPUI5 App Step 2 wrong controller file name 

### ISSUE THREAD

**Issue by i-ivd** [SAPDocuments/Issues#167]
Tutorials: https://developers.sap.com/tutorials/cp-cf-sapui5-local-debug.html
--------------------------

In Step 2, the controler is wrongly named  webapp/controller/MainView.controller.xml instead of  webapp/controller/MainView.controller.js

**Comment by IObert** [comment]
Hi @i-ivd,

good catch, thanks!

I changed the text and the fix should be live in the next hour or so.
