### ISSUE TITLE
Discover Sales Order API from S/4HANA Cloud System

### ISSUE THREAD

**Issue by advit-ramesh** [SAPDocuments/Issues#169]
Tutorials: https://developers.sap.com/tutorials/cp-apim-sales-tracker-api-discover.html
--------------------------

API proxy creation is not possible by discovering the OAS 3.0 APIs from SAP API Business Hub.

![image](https://user-images.githubusercontent.com/29966401/108304316-a5193a00-720c-11eb-9c83-3345c5c2860c.png)

**Comment by shilpavij** [comment]
Could you please check now. This is fixed
