### ISSUE TITLE
Deploy Your First SAPUI5 App

### ISSUE THREAD

**Issue by MisherLiu** [SAPDocuments/Issues#170]
Tutorials: https://developers.sap.com/tutorials/appstudio-sapui5-create.html
--------------------------

In the Step7 Deploy the archive to Cloud Foundry, point 3&4, I have deploy with successfull message,however, when I run point 4 to get the URL, it gives ok with empty information"OK
name   version   app-host-id   service name   destination name   last changed   url   
user: sapui5 $ "

Why and how to fix this.

BR
Misher

**Comment by IObert** [comment]
Hi Misher,

sorry for the late response. This shouldn't happen! 
Did you follow this tutorial step by step or did you deviate at some points?
Also, what is the output when you just run `cf html5-list`

**Comment by IObert** [comment]
I'll close this one due to inactivity. Please reopen if needed
