### ISSUE TITLE
Register for SAP HANA, express edition

### ISSUE THREAD

**Issue by Tarik-T** [SAPDocuments/Issues#171]
Tutorials: https://developers.sap.com/tutorials/hxe-ua-register.html
--------------------------

Write here what you need help with ...

The registration does not work: 
I always get a 
"Sorry
Your request for information is being reviewed. Once approved, you’ll receive an e-mail with additional instructions.
Close this window and go back to SAP.com"
But I do not receive any "e-mail with additional instructions"

I was logged to SAP with my S-User ID
To exclude issues with browser, I tried Firefox as well as Edge. 
However, I always end up with message above and no  "e-mail with additional instructions"
How long might it take? Hours, Days, Weeks,? 

Thanks fro response,
Tarik

**Comment by JCurrie27** [comment]
Hi Tarik: Sorry to see the registration problem above. The email should be received immediately. Could you please copy and paste your issue above to the Q&A page to take advantage of the community support model? Support resources will see a post there, but may not see your post above. 

To log your questions on the Q&A page:

1. Go to [https://answers.sap.com/questions/ask.html](https://answers.sap.com/questions/ask.html)
2. Add a **Title**. Enter your GitHub question in the Fill in the details... form.
3. In **Select Primary Tag**, search for "express". Select SAP HANA, express edition.
4. Click **Submit your Question**.

**Comment by greg2git** [comment]
@JCurrie27 

is it possible that registration is not working because we are getting ready for HXE SPS5n?

thx, gm

**Comment by JCurrie27** [comment]
There's no scheduled registration downtime that I've been made aware of. However, depending on the geography of the registering user, I've learned it can take 1-2 business days for the registration email response. If we're still within that window, many thanks for your patience. If we're past 2 business days, please post to the Q&A page as above. Hope this helps,

**Comment by Tarik-T** [comment]
Hi John,

 

All responses of my different tries arrived at once 2 and a half hour past midnight Friday morning.

 

For now, the download does not work.
 


403 ERROR

The request could not be satisfied.

Request blocked. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront

documentation.


 

This might happen, but all day long, what sums up now to 12h?  

To avoid a personal issue, I asked a colleague of mine to try. Same error to him, so I do not think it is at least not a simple user error.

 

I contacted some EMEA support, however, if issue still persits on Saturday, I will follow your proposal.

 



 

Thanks!

Tarik

 

Gesendet: Freitag, 19. Februar 2021 um 15:00 Uhr
Von: "John Currie" <notifications@github.com>
An: "SAPDocuments/Issues" <Issues@noreply.github.com>
Cc: "Tarik-T" <tarik.torgaddon@gmx.de>, "Author" <author@noreply.github.com>
Betreff: Re: [SAPDocuments/Issues] Register for SAP HANA, express edition (#171)


 

Hi Tarik: Sorry to see the registration problem above. The email should be received immediately. Could you please copy and paste your issue above to the Q&A page to take advantage of the community support model? Support resources will see a post there, but may not see your post above.

To log your questions on the Q&A page:


	Go to https://answers.sap.com/questions/ask.html
	Add a Title. Enter your GitHub question in the Fill in the details... form.
	In Select Primary Tag, search for "express". Select SAP HANA, express edition.
	Click Submit your Question.

**Comment by JCurrie27** [comment]
Hi - I'm not a support engineer, but to my eye the error codes point to something very different than a slow registration process. I recommend posting the problem -- including the above error codes -- to the Q&A site right away, so other HANA express users and support personnel can assist. 

A colleague tried registering from our location 2 hours ago and registration worked normally here, so the problem doesn't appear to be global in nature.

**Comment by thecodester** [comment]
I will close this issue, as it will be taken care of in Q&A or support.

@JCurrie27 FYI - you should be able to close issues yourself in this repo.
