### ISSUE TITLE
Deploy Your First SAPUI5 App - Deploy step failed

### ISSUE THREAD

**Issue by i-ivd** [SAPDocuments/Issues#172]
Tutorials: https://developers.sap.com/tutorials/appstudio-sapui5-create.html
--------------------------

Step 7 Deploy the archive to CF fails with error (cf. attached logs)

[ERROR] Missing mandatory service instance [sap-btp-sapui5_html_repo_host-service] required by destination [basis_service_sap_btp_sapui5_html_repo_host]

Also the manual mta.yaml fix step 5.5 is a bit unclear, as the generated mta.yaml looks somewhat different from the one in the tutorial (some underscores instead of minus )

[this is the used mta.yaml](https://github.com/SAPDocuments/Issues/files/6005139/mta.yaml.txt)

What did i do wrong ? or could it be that this tutorial is a bit outdated ?

[sap-btp-sapui5-destination-content_sap-btp-sapui5-destination-service.log](https://github.com/SAPDocuments/Issues/files/6005120/sap-btp-sapui5-destination-content_sap-btp-sapui5-destination-service.log)
[OPERATION.log](https://github.com/SAPDocuments/Issues/files/6005124/OPERATION.log)

**Comment by IObert** [comment]
Hi,

sorry again for the late response. I just ran through the tutorial and it worked out fine for me. Maybe this was a temporary issue?

**Comment by i-ivd** [comment]
Hello Marius,

thanks, i redid from scratch and still got same issue.
However in step 5.3 there is a dropdown for _Do you plan to add a UI_? and choice Yes/No

I left this dropdown with default value **Yes**, and then it gives the error.

Today i re-tried with **No** and  then everything works fine.
![image](https://user-images.githubusercontent.com/78037321/111066423-381d5b00-84bf-11eb-9dcd-ad3d644faf9d.png)

Im not sure but it seems to be missing in the tutorial that this _Do you plan to add a UI?_ option needs to be set to No ?

Thanks,
Best regard,
Denis

**Comment by IObert** [comment]
It should work when you select "Yes". I just tried it with my trial account and I was able to deploy the app.

Are you using an old SAP Business Application Studio Dev Space? Or maybe your subaccount has an invalid config, can you deploy [this sample project](https://github.com/SAP-samples/multi-cloud-html5-apps-samples/tree/master/managed-html5-runtime-fiori-mta) without problems?

**Comment by IObert** [comment]
I'll close this one due to inactivity. Please reopen if needed
