### ISSUE TITLE
Build and Deploy Your SAP Fiori App to SAP Business Technology Platform

### ISSUE THREAD

**Issue by SoumyaChanda** [SAPDocuments/Issues#173]
Tutorials: https://developers.sap.com/tutorials/appstudio-fioriapps-mta-build-deploy.html
--------------------------

At Step 4, point 3, I cannot find the required details of destination-service under mta.yaml file. Hence cannot proceed forward with cf commands.
Please Note: The tutorial starts with template - SAP Fiori Freestyle Project, which is now deprecated. So I started with SAP Fiori Application > SAPUI5 Freestyle  > SAPUI5 application.

**Comment by raz-korn** [comment]
Hi @SoumyaChanda ,

The tutorials will be updated soon to use the new SAP Fiori tools.
The flow using SAP Fiori tools is different than the flow that is currently described in the tutorials that uses the tooling that is marked "deprecated".

Regards - Raz

**Comment by SoumyaChanda** [comment]
Hi @raz-korn,

Came across this tutorial. This contains the missing piece of the template wizard.
https://developers.sap.com/tutorials/appstudio-sapui5-create.html

Thanks,
Soumya

**Comment by raz-korn** [comment]
Hi @SoumyaChanda ,

Update to the tutorial group was released earlier this week.
I hope this will answer your question as well as the tutorial you mentioned.

Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
