### ISSUE TITLE
Access SAP Mobile Services

### ISSUE THREAD

**Issue by fleischr** [SAPDocuments/Issues#175]
Tutorials: https://developers.sap.com/tutorials/fiori-ios-hcpms-setup.html
--------------------------

Mobile Development Kit not available in BTP trial

**Comment by sandeep-tds** [comment]
Hi @fleischr 

[This Mission](https://developers.sap.com/mission.mobile-dev-kit-get-started.html) is a great place to get started with Mobile Development Kit.

Please let me know if you need further information.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
