### ISSUE TITLE
Enable SAP BTP, Kyma Runtime

### ISSUE THREAD

**Issue by iwonahahn** [SAPDocuments/Issues#176]
Tutorials: https://developers.sap.com/tutorials/cp-kyma-getting-started.html
--------------------------

There is no role `KymaRuntimeNamespaceAdmin` as mentioned in step 3.4 on SAP BTP Trial:

![image](https://user-images.githubusercontent.com/22098308/108566798-484e7a00-7307-11eb-927d-ac07c8e80adc.png)

**Comment by KevinMuessig** [comment]
I have just checked on my trial account which I have reset yesterday and I have the KymaRuntimeNamespaceAdmin role.
In addition I have created a new account with a separate email address where the role is also available after I have enabled Kyma Environment as described in the tutorial.
![image](https://user-images.githubusercontent.com/9074514/109282321-ab677180-781d-11eb-922a-f1b6128b1575.png)

Please make sure you have the Kyma Runtime fully enabled first (wait for the process to be finished) and then you will see the Roles being in the list.

Thanks,

Kevin

**Comment by jcawley5** [comment]
@KevinMuessig - Maybe some confusion here. In the latest version the role collections are created for you so the steps are not fully accurate. Please see https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/b0a874cc6dd24e608727547c208c8770.html

**Comment by iwonahahn** [comment]
I had issues with the kyma enablement (reported as bug and issue was resolved now). Today I was able to enable Kyma and assigned the roles as described in this tutorial. Will close this. Thanks a lot.

**Comment by KevinMuessig** [comment]
@jcawley5 The tutorial will be changed to match the newest documentation. Sorry for my late reply.
