### ISSUE TITLE
Mobile Cards - Cards getting automatically subscribed

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#177]
Hello,

Scenario link: https://developers.sap.com/tutorials/cp-mobile-cards-booster-starter.html#b03a40b7-d2da-45ae-990a-f16bb9befba5

Issue: Step 3 & Step 4: After completing tutorial 1, the new cards are reflecting in the mobile application automatically as soon as they are created using boosters.
Solution: Maybe we can add a note that if you have completed tutorial, probably the cards will be subscribed for you already

Labels to be added:
Landscape Labels: all
Sprint Label: SCPTest-2102
Scenario Label: SCPTest-mcard
Prio: High-prio

Thanks,
Shubham Agarwal

**Comment by sandeep-tds** [comment]
Hi @i353590 

Thank you for raising the issue. We have made the necessary changes and they will be available by early next week. 

Warm Regards
Sandeep T D S

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by i353590** [comment]
Hello,

The issue still persists.
As soon as i create a card, the same is getting subscribed automatically in the app, and we don't need to subscribe the cards.
Can you please tell what are the changes made since there is no change either in tutorial or in the application behavior.?

Kind Regards,
Shubham Agarwal
