### ISSUE TITLE
Mobile cards: Mobile card nor loading properly - US region

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#178]
Hello,

Scenario URL: https://developers.sap.com/tutorials/cp-mobile-cards-booster-starter.html#b03a40b7-d2da-45ae-990a-f16bb9befba5

Issue: In US region, Supplier Contact details Mobile card doesn't load properly alike in other regions -
Please refer to the attached screenshots:

![image](https://user-images.githubusercontent.com/66831161/108684664-2f1d1780-7519-11eb-9596-39898abb5596.png)

![image](https://user-images.githubusercontent.com/66831161/108684700-3c3a0680-7519-11eb-84df-f8cccc577f37.png)

Labels to be added:
Landscape Labels: trial2 (US)
Sprint Label: SCPTest-2102
Scenario Label: SCPTest-mcard
Prio: High-prio

Thanks,
Shubham Agarwal

**Comment by sandeep-tds** [comment]
Hi @i353590, 

Thank you so much for raising the issue. We need more details to discuss the same. Thus, I will set up a meeting with you to discuss these. 

Thank you for your support. 

Warm Regards
Sandeep T D S

**Comment by sandeep-tds** [comment]
Hi @i353590

Thank you so much for your time. As discussed in the call, can you please confirm the behaviour in the EU region and close the ticket? 

Thank you for your support.
