### ISSUE TITLE
Expose Integration Flow Endpoint as API and Test the Flow

### ISSUE THREAD

**Issue by poojacs2888** [SAPDocuments/Issues#179]
Tutorials: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html

 https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html
--------------------------
Hello,

Its saying "Unauthorized : 401 : HTTP/1.1  " for  "OData API for products.

URL - https://refapp-espm-ui-cf.cfapps.eu10.hana.ondemand.com/espm-cloud-web/espm.svc.

PLease guide.

**Comment by Karunaharan** [comment]
Hi @poojacs2888 - I tried again with same instructions and it works fine for me. Could you please try again?
