### ISSUE TITLE
Help Thomas Get Started with SAP HANA

### ISSUE THREAD

**Issue by feranecp** [SAPDocuments/Issues#18]
Tutorial: https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html
--------------------------

Hello,

in step 7.1 where I need to click on Bind (green icon) it end with error no instances found. It does not give you an option to create an instance. I have a fresh Cloud account.

Can you please help?

Thank you.

Best regards,
Pavol

**Comment by jung-thomas** [comment]
Have you tried the workaround steps in 7.1 that provide a work around for when this error situation occurs? This is a known issue in the tooling for which we are waiting on a hotfix.  But the tutorial was updated with the manual workaround to first create the HDI container instance from the terminal and then binding.

**Comment by feranecp** [comment]
I do not see any workaround solution in step 7.1. Is it at the end of the course? Have I missed something?

**Comment by feranecp** [comment]
how do I open that terminal? I havent used SAP Cloud before so this is my first course with it. Thanks.
