### ISSUE TITLE
Mobile cards - Term Inconsistency - CP & BTP

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#180]
Hello,

Tutorial link: https://developers.sap.com/tutorials/cp-mobile-cards-welcome.html

I have observed that there are inconsistencies in the tutorial with respect to the terms that we use in the tutorial.
The Cockpit has not been renamed to BTP yet, and as we are asking to go to BTP, but we actually navigate to CP which might create confusion. Also, still at some places in  the tutorial we are calling SAP CP only.
in this tutorial, Step 2.1: In your web browser, open the SAP BTP trial cockpit -> but we land at SAP Cloud Platform.
Still the BTP application itself says Cloud platform till now.

For example:
Here, the link of this screenshot navigates to page which says register on SAP BTP, and we are saying Cloud Platform here
![image](https://user-images.githubusercontent.com/66831161/108715061-5a672d00-7540-11eb-8895-504087524e57.png)

Also, in tutorial 2, Step 2.1: 
![image](https://user-images.githubusercontent.com/66831161/108716057-a5ce0b00-7541-11eb-83f0-1747096708a9.png)

We have mentioned CP, so bit confusing again for the end users.

Please update the  tutorial accordingly.
We need to see how to mention it as the App is still not updated with latest rebranding.

Labels to be added:
Landscape Labels: all
Sprint Label: SCPTest-2102
Scenario Label: SCPTest-mcard
Prio: High-prio

Thanks,
Shubham Agarwal.

**Comment by sandeep-tds** [comment]
Hi @i353590, 

Thank you for raising the issue. 

@prilk Can we please update our tutorials to ensure the rebranding is consistent with the new name? Thank you.

**Comment by thecodester** [comment]
@prilk Can you confirm that this was done?

In the meantime, closing the issue.
