### ISSUE TITLE
Create A New Welcome Card

### ISSUE THREAD

**Issue by nimble-123** [SAPDocuments/Issues#182]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-cards-welcome.html
--------------------------

Step 3: View card on your mobile device is not working

I installed the app on my iOS device but do not get the "Scan QR Code" button. If i enter my e-mail from my trial BTP account i get an error.

So i am not able to test the mobile cards on my iOS device sadly.

**Comment by sandeep-tds** [comment]
Hi @nimble-123 

Thank you for raising the issue. On an iOS device, you need to launch the QR code scanner provided by the OS.

You can follow the steps mentioned in the [tutorial](https://developers.sap.com/tutorials/cp-mobile-cards-welcome.html#8ef87c0e-4357-4a75-9a28-0b9c47f61e84) under the iOS section.

<img width="1348" alt="Screen Shot 2021-03-04 at 12 03 33 PM" src="https://user-images.githubusercontent.com/43441840/109921443-e2d49300-7ce1-11eb-97e0-7a3ef36484ad.png">

I hope this resolved your query. 

Warm Regards
Sandeep T D S

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
