### ISSUE TITLE
Create an SAP Fiori Elements Application

### ISSUE THREAD

**Issue by Nuube** [SAPDocuments/Issues#183]
Tutorials: https://developers.sap.com/tutorials/fiori-tools-cap-create-application.html
--------------------------

I could start the app as described in step 2, but the report looks different:

![image](https://user-images.githubusercontent.com/25643142/109069372-6fcf8900-76f1-11eb-9ccc-9a2f1df6d7d8.png)

**Comment by Nuube** [comment]
Any update?

**Comment by thecodester** [comment]
@jo-fiess Can you respond here or forward to whoever can? Thanks

**Comment by jo-fiess** [comment]
Hi, I just went through the tutorial from scratch up to the point you reported and it worked as expected. I would recommend to delete the dev space and start again, following exactly the workflow. If it still does not work, please tell me.
Thanks and regartds
Joachim
