### ISSUE TITLE
Enhance Your First MDK App with Additional Functionalities

### ISSUE THREAD

**Issue by browntheo-dc** [SAPDocuments/Issues#184]
Mission: https://developers.sap.com/mission.mobile-dev-kit-enhance.html
--------------------------
I have built the app using the Create Your First MDK Application Mission and was able to deploy and access it easily.
Having started completed the first stage of this next Mission, the app deploys fine but when I try to run/access it, I get the error message: "404 Not Found: Requested route ('c0b8f84dtrial-dev-nsdemosampleapp-approuter.cfapps.ap21.hana.ondemand.com') does not exist."

I've gotten the same error when trying to start the app build over from scratch. 
Can you give some help/guidance on how to resolve this issue?

**Comment by jitendrakansal** [comment]
@browntheo-dc are you using BTP trial or production account?
I guess if the deployed web application is in stopped mode. Can you navigate to Space cockpit>Applications , see if application is in stopped mode, if so, start it manually. Once it is in started mode, you should be able to access it. 

![image](https://user-images.githubusercontent.com/31536700/109124801-a33f0180-774b-11eb-867a-dc8ff1150f0f.png)

**Comment by browntheo-dc** [comment]
I'm using the BTP trial. You were right, thanks.
However, now its giving me a "Failed to initialize application data service - Error: 500 (Internal Server Error); GET /nsDemoSampleApp/SampleServiceV2/?sap-language=en Internal Server Error" When I access the deployed app.

I've tried redeploying, as well as restarting the applications and dev space with no effect

![image](https://user-images.githubusercontent.com/79611816/109558123-e0d1cf00-7b3d-11eb-807b-d2c2bd342be3.png)

**Comment by jitendrakansal** [comment]
@browntheo-dc can you try after clearing browser cache/cookies? Or open it in private/incognito window/other browser to check if error still persists?

**Comment by browntheo-dc** [comment]
@jitendrakansal Tried in Firefox, Chrome, and Edge, before and after clearing cookies. I've also tried incognito/private windows on all three. Problem still persists.

**Comment by jitendrakansal** [comment]
@browntheo-dc it works fine on my side. 
Can you please cross-check once the CF destination settings? (step4 in this tutorial https://developers.sap.com/tutorials/cp-mobile-dev-kit-ms-setup.html)

**Comment by browntheo-dc** [comment]
@jitendrakansal I've tried resetting the CF destination settings per Step 4 and have tried all three browsers before/after clearing cookies too. In all instances, it still shows the "Failed to initialize application data service - Error: 500 (Internal Server Error); GET /nsPlease_Work/SampleServiceV2/?sap-language=en Internal Server Error"

I've also just tried making another fresh build of the app per the tutorial and its not working either. I'm starting to think this may be caused by a setting on my end. Can you suggest anything which may be causing this issue from my side?

**Comment by browntheo-dc** [comment]
The app deploys to mobile and I can access the customer_list page but cannot on the web portal version.
When I try to edit customer data on the mobile version however, it wipes all fields for that customer that have not had a value set in the edit.

**Comment by thecodester** [comment]
@jitendrakansal Do you have an update on this issue? If it is an product issue (as opposed to tutorial issue) we can ask to open ticket or ask the community, and then close the ticket.

**Comment by jitendrakansal** [comment]
@browntheo-dc 

I just tested it in my trial account and everything works as expected. 

are you still having the same issues in both web runtime and mobile client?

-  If so, can you share your MDK project to look into the mobile client issue?

- For web, can you once again re-confirm the cloud foundry destination (SampleServiceV2) info? Also, can you check this as well - In BAS, create a new project, select **OData Source** as **Cloud Foundry**, select **Cloud Foundry destination** as **SampleServiceV2**
![image](https://user-images.githubusercontent.com/31536700/114740833-80dc6400-9d4a-11eb-8fe7-422e5e0c6e9f.png)
check if you are getting OData collections as below:
![image](https://user-images.githubusercontent.com/31536700/114741002-a7020400-9d4a-11eb-818e-43ac6e7c204c.png)

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
