### ISSUE TITLE
Create an Account on the SAP Gateway Demo System

### ISSUE THREAD

**Issue by i015343** [SAPDocuments/Issues#185]
Tutorials: https://developers.sap.com/tutorials/gateway-demo-signup.html
--------------------------
![image](https://user-images.githubusercontent.com/45384280/109120967-989f5f00-7781-11eb-9278-978e046d84c6.png)
I can't register the account, it always loading, I am the SAP APJ employee, 
Write here what you need help with ...

**Comment by jung-thomas** [comment]
The steps in the tutorial are working fine. When I go to the page it works correctly.  I'd suggest trying again.  Beyond that for technical support for this SAP Gateway Demo System, please email rac-support@sap.com
