### ISSUE TITLE
Deploy Your First SAPUI5 App

### ISSUE THREAD

**Issue by SoumyaChanda** [SAPDocuments/Issues#187]
Tutorials: https://developers.sap.com/tutorials/appstudio-sapui5-create.html
--------------------------

Hi Obert,

As suggested, raised an SAP incident regarding the Internal Server Error, we are getting when we try to run the app from our Production account.
Reply to that from SAP is - It would possibly be best to direct the issue to the blog post. It's not official SAP documentation.

Is this correct ?? 
Kindly help guiding us to troubleshoot this error.

Thanks,
Soumya

**Comment by IObert** [comment]
Hi,

A tutorial is not an official SAP document - that's true. But I think they should still be able to help you if you describe your issue and refer to the tutorial as the "steps to reproduce the problem"
