### ISSUE TITLE
Access a Classic Schema from SAP Business Application Studio

### ISSUE THREAD

**Issue by oskinton** [SAPDocuments/Issues#188]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-access-cross-container-schema.html
--------------------------

I cannot create the classic schema "PLAIN" due to "insufficient privilege". Is there a way around this?
![Classic_Schema_Error](https://user-images.githubusercontent.com/48292178/109210725-39d6e700-777b-11eb-9bca-993dbdf68718.PNG)

Also, your screenshots had a DB called HANA_Cloud_trial.... which is not available on my HANA DB Explorer. Did I miss any steps?

**Comment by jung-thomas** [comment]
I suspect that you are not connect in the Database Explorer with the correct user.  You are likely using an HDI container connection.  For this step in the tutorial you must use a connection via the user DBADMIN. Did you open the Database Explorer via the HANA Cloud Management screen as described in step 1?

https://developers.sap.com/tutorials/hana-cloud-access-cross-container-schema.html#3acab07e-02a5-4d5d-bc32-59ddbc48e6b5

And are you sure you are open the SQL Console via the entry for the DBADMIN user as in step 2?

From the SQL Console you can issue SELECT CURRENT_USER FROM DUMMY to verify your connection and user.  If you are using DBADMIN then it certainly should have the authorization to perform the operations in this step.

**Comment by oskinton** [comment]
Thank you so much. I was able to navigate there using the steps in your video. No wonder you advised we bookmark it, a bit tricky to find.
    On Thursday, February 25, 2021, 03:17:42 PM EST, Thomas Jung <notifications@github.com> wrote:  
 
 


I suspect that you are not connect in the Database Explorer with the correct user. You are likely using an HDI container connection. For this step in the tutorial you must use a connection via the user DBADMIN. Did you open the Database Explorer via the HANA Cloud Management screen as described in step 1?

https://developers.sap.com/tutorials/hana-cloud-access-cross-container-schema.html#3acab07e-02a5-4d5d-bc32-59ddbc48e6b5

And are you sure you are open the SQL Console via the entry for the DBADMIN user as in step 2?

From the SQL Console you can issue SELECT CURRENT_USER FROM DUMMY to verify your connection and user. If you are using DBADMIN then it certainly should have the authorization to perform the operations in this step.
