### ISSUE TITLE
Deploy Your First SAPUI5 App

### ISSUE THREAD

**Issue by jheisonurzola** [SAPDocuments/Issues#191]
Tutorials: https://developers.sap.com/tutorials/appstudio-sapui5-create.html
--------------------------

Hi,

I have followed Marius Obert tutorial and I cannot pass step 4 numeral 6 when he says: "Choose Cloud Foundry as the target runtime and type in any value for the destination as it is a mandatory field. Press Finish to create the new project."

In tutorial "Destination Name" is an input field and you can write "None" as "Destination Name". However, in my trial environment "Destination Name" is an options selector. You cannot write "None". You can only select options showed by selector. However, when I unfold options, it says: "No data available" and I cannot finish with the creation of the single module project. Can you help me to finish correctly the project with a deployment configuration correctly generated?

Best regards,

Jheison Urzola
[Steps to reproduce error.docx](https://github.com/SAPDocuments/Issues/files/6055319/Steps.to.reproduce.error.docx)

**Comment by IObert** [comment]
Hi,

I already [answered here](https://answers.sap.com/questions/13302547/no-data-available-in-destination-name-when-select.html?childToView=13303689#comment-13303689) which is why I'm closing this issue.  If you have a follow-up question, please comment under the original question.
