### ISSUE TITLE
Use Machine Learning to Enrich Business Data with Swagger UI

### ISSUE THREAD

**Issue by advit-ramesh** [SAPDocuments/Issues#195]
Tutorials: https://developers.sap.com/tutorials/cp-aibus-dox-data-api-bus.html
--------------------------

Write here what you need help with ...

Hello Experts,

When I invoke  GET /document/jobs/{id} . I do not see the enriched content for some reason. 

![image](https://user-images.githubusercontent.com/29966401/109735522-c2e09900-7c27-11eb-8072-0a32f845842e.png)

I can see a list of the enrichment data entries I have created:

![image](https://user-images.githubusercontent.com/29966401/109735924-6c278f00-7c28-11eb-936e-ce06a3568269.png)

Can you please let me know why I am unable to see the enriched data when I invoke GET /document/jobs/{id} 

Thanks for your support
Regards
Advit

**Comment by Juliana-Morais** [comment]
Hi Advit,

As mentioned in the tutorial, "Enrichment data is refreshed automatically every 4 hours. It might take up to 4 hours until the enrichment data prediction is available in the response."

Have you tried again after some time? On Monday, the team has released a new API and new Data API endpoints that allow the users to trigger the refresh by themselves. I plan to update the tutorials with the new features until the end of the week.

In the meantime, you can refer to https://help.sap.com/viewer/5fa7265b9ff64d73bac7cec61ee55ae6/SHIP/en-US/fedea48cb030469ab20749de00aa120d.html. I'll let you know once the tutorials are updated.

Best regards,
Juliana

**Comment by advit-ramesh** [comment]
Thanks, Juliana. I will give this a go. 

Regards
Advit
