### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by DipeshKumar1** [SAPDocuments/Issues#197]
Tutorials: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html
--------------------------

Issue is in the step 9 - For Consume Services, select the following, and click Next.

It's asking me to enter the Backend user & password, but it's not given in this above step 9.

Please find the attached screenshot.
![Capture](https://user-images.githubusercontent.com/31985279/109804323-2084dd80-7c48-11eb-9914-3ae856950acc.JPG)

Could you please help me to resolve this issue?

Regards,
Dipesh

**Comment by raz-korn** [comment]
Hi @DipeshKumar1 ,

Please refer to the [issue 36](https://github.com/SAPDocuments/Issues/issues/36).

Regards - Raz

**Comment by DipeshKumar1** [comment]
Hi Raz,

Thank you for your help.
Please see the below destination configuration. It doesn't contains SAP-PLATFORM property becuase I didn't get it during destination configuration.
![image](https://user-images.githubusercontent.com/31985279/109843071-b3397280-7c70-11eb-8938-049b53b6c239.png)
![image](https://user-images.githubusercontent.com/31985279/109843144-c3e9e880-7c70-11eb-88bb-d0bad8c4a80f.png)

Could you please help me to resolve this issue?
Thanks in advance!

Regards, Dipesh

**Comment by raz-korn** [comment]
Hi @DipeshKumar1 ,

Can you share the output of running the following command in the BAS terminal:
curl -v -i "ES5.dest/sap/opu/odata/iwbep/GWSAMPLE_BASIC/BusinessPartnerSet?%24top=1"

To open a new terminal in BAS:


![](https://user-images.githubusercontent.com/6040433/104128849-89e81e80-5372-11eb-8007-38351f17e8f4.png)


Regards - Raz

**Comment by DipeshKumar1** [comment]
Hi Raz,

Thank you for your response.

I'm unable to execute task because may be my project FioriDemo is not yet created.

Please find the screenshot below.
![image](https://user-images.githubusercontent.com/31985279/109972531-6bbcf000-7d1d-11eb-973b-85395181c8aa.png)

The highlighted folder 'Demo' is deleted.

Could you please help me how to run command in the BAS terminal ?

Thanks in advance!

Regards, Dipesh

**Comment by raz-korn** [comment]
Hi @DipeshKumar1 ,
This command should run in the terminal regardless of app creation.
It is for testing the connectivity to the destination on SAP BTP cockpit.
To run you should open a terminal (as you did) and run the command.
Regards - Raz

**Comment by DipeshKumar1** [comment]
Hi Raz,

No option is coming for executing task as shown below.
![image](https://user-images.githubusercontent.com/31985279/110012306-67f19380-7d46-11eb-93e5-46ad910aa65e.png)
When I clicked on 'Run task', below message is comimg.
![image](https://user-images.githubusercontent.com/31985279/110012557-a71fe480-7d46-11eb-8b1b-612ddebd85b1.png)
Kindly help.

Regards, Dipesh

**Comment by raz-korn** [comment]
Hi @DipeshKumar1 ,

You're doing OK.

Other than for opening a terminal you do not need to do any other menu command.
What you need to do is:
1. Open a terminal (as you did).
2. Type in the terminal the curl command and then press [ENTER]. This will run the command in the terminal.

Please provide the output that comes up in the terminal.

Regards - Raz

**Comment by DipeshKumar1** [comment]
Hi Raz,
Thank you!
Please find output of task below -

![image](https://user-images.githubusercontent.com/31985279/110286909-acfa1c00-800b-11eb-8eb9-0003eee8b5e7.png)
![image](https://user-images.githubusercontent.com/31985279/110286954-c1d6af80-800b-11eb-9bc2-ec42e1213f65.png)
![image](https://user-images.githubusercontent.com/31985279/110287092-fa768900-800b-11eb-9ed1-85b7e7ac6128.png)
![image](https://user-images.githubusercontent.com/31985279/110287143-0b26ff00-800c-11eb-8dbb-80ee0395d774.png)
![image](https://user-images.githubusercontent.com/31985279/110287185-1712c100-800c-11eb-9bcf-33ce837cb2b9.png)
![image](https://user-images.githubusercontent.com/31985279/110287227-242fb000-800c-11eb-9ea3-e9397674609e.png)

End of screenshot -
![image](https://user-images.githubusercontent.com/31985279/110287279-3873ad00-800c-11eb-913a-4b57d51245fd.png)

Regards, Dipesh

**Comment by raz-korn** [comment]
Hi @DipeshKumar1 ,

The output of the curl command suggests that either the credentials (probably password) are incorrect or that the user is locked.

My recommendation is that you reset the password for ES5 (see [here](https://blogs.sap.com/2017/12/05/new-sap-gateway-demo-system-available/)), and update the new password in the destination configuration in SAP BTP cockpit.

You can then re-start the application wizard as explained in the tutorial.

Regards - Raz

**Comment by DipeshKumar1** [comment]
Hi Raz,
I've reset the password of ES5 system and able to login as below-
![image](https://user-images.githubusercontent.com/31985279/110334055-5c54e400-8048-11eb-809e-759535ab22da.png)
But still I'm getting authorization issue at step 9 as shown below-
![image](https://user-images.githubusercontent.com/31985279/110334203-81e1ed80-8048-11eb-88d9-bfd00b218c99.png)

Could you plz resolve this issue?
Regards,
Dipesh

**Comment by raz-korn** [comment]
Hi @DipeshKumar1 ,

After resetting the password for ES5, did you update the new password in the destination configuration in SCP BTP cockpit?
If not, I guess that by now the user is locked, and you should reset the password again, update it in the destination configuration in SCP BTP cockpit (not the BAS wizard), and then it should work.

Regards - Raz

**Comment by DipeshKumar1** [comment]
Hi Raz,

Thank you very much for your help!
This issue has been solved now by chaning password in Destination in SAP Clould Platform BTP Cockpit.
Regards,
Dipesh

**Comment by DipeshKumar1** [comment]
Hi Raz,
Thank you very much for your help!
This issue has been solved now by chaning password in Destination in SAP Clould Platform BTP Cockpit.
Regards,
Dipesh
