### ISSUE TITLE
Set Up the SAP Launchpad Service

### ISSUE THREAD

**Issue by sebastianomarchesini** [SAPDocuments/Issues#198]
Tutorials: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html
--------------------------

In the SAP Cloud Platform Trial (BTP) now is not "Launchpad" but "Portal" service

**Comment by LindsayBert** [comment]
Hi 

If you cant see the Launchpad Service tile, your may be using an older trial account. Try this:  
Add it to your account via the **Entitlements** area. Click **Configure Entitlements**. 
Then **Add Service Plans**. Then search for `launchpad`, check the standard plan, and click **Add 1 Service Plan**. Don't forget to save in the next screen.

Another option is to create a new trial account.

Thanks 
Lindsay

**Comment by sebastianomarchesini** [comment]
Hi Lindsay, 

thank you for the help, and sorry for the late answer. 
Like you said my account is old, I solved with the first solution.

Thank you again, 
Sebastiano
