### ISSUE TITLE
Configure Business Rules, Workflow and Process Visibility

### ISSUE THREAD

**Issue by Edson-7** [SAPDocuments/Issues#199]
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-configure.html
--------------------------
Hello experts,

Write here what you need help with ...

Step 3: Import business rules from API Business Hub
Click Design icon, click Import to select Import Project from API Business Hub.

![problem](https://user-images.githubusercontent.com/80011270/109906116-273f3f00-7ca0-11eb-8c39-80ca5695d6a9.JPG)

Best regards!

**Comment by ArchanaShukla** [comment]
@Edson-7 - can you please help me translate the error in english.

**Comment by Edson-7** [comment]
An error has occurred. Contact the technical support

**Comment by ArchanaShukla** [comment]
Ok, this is very generic error. It usually comes if you have not provided right username or password in the destination BUSINESSRULES_APIHUB. Can you confirm? Also if you can open Developer Console of your browser and send me the trace when you click Import button.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
