### ISSUE TITLE
Build Luigi App with React

### ISSUE THREAD

**Issue by hendrik77** [SAPDocuments/Issues#2]
Tutorial: https://developers.sap.com/tutorials/luigi-app-react.html
--------------------------

In **step two** the command `npm run eject` did not work. Stackoferflow had the answer: https://stackoverflow.com/questions/45671057/how-to-run-eject-in-my-react-app I had to commit my changes first (so quickly setup a private github repo and did that). Afterwards the command did run without an error. With the error I was only able to go until step 5..   either a different solution or the one I found should be mentioned here.

In **step five**:
> At line 27, add:
- the line number might be missleading - in my case line 27 looks like that: 

> const typescriptFormatter = require('react-dev-utils/typescriptFormatter');

Line 29 is empty - maybe that's the place where the line should be added? 

The command:
> Remove the following line from the file (use search/find and replace, it should be at line 19 and line 311).

Line 19 is correct and it's used in line 345 in the plugins part - and my guess is that I have to delete the whole entry: 
```
        new ModuleScopePlugin(paths.appSrc, [
          paths.appPackageJson,
          reactRefreshOverlayEntry,
        ]),
```
The Prettier plugin might be responsible for the different lines but the description could be clearer

**Step 13** 
- the import link manager was already part of step 10

> Add onClick event at the Tile component:
- There is no title component in List.jsx

I stopped here. Starting the react app did result in an error. 

BR Hendrik

**Comment by alexandra-simeonova** [comment]
Hello, 
thank you for the feedback! We will make changes in the tutorials ASAP. It had been tested before but because of different user setups, it seems to vary between users (with line numbers, etc.) but we weren't aware of the `npm run eject` issue and will investigate it again

**Comment by MichaelCzcz** [comment]
@alexandra-simeonova Any updates? Please close this issue when you have made the changes to your tutorial.

**Comment by alexandra-simeonova** [comment]
Hello,
The tutorial was updated some time ago with a note about the potential problem with npm. I will close this issue.
