### ISSUE TITLE
Create an ABAP Managed Database Procedure (AMDP) and Analyze Its Performance

### ISSUE THREAD

**Issue by ThanosEfraimidis** [SAPDocuments/Issues#200]
Tutorials: https://developers.sap.com/tutorials/abap-environment-amdp-profiling.html
--------------------------

At Step 10, paragraph 1, should read "Ctrl+S, Ctrl+F3" instead of "Ctrl+S, Ctrl+3"?

**Comment by julieplummer20** [comment]
Yes. Apologies, I'll fix this at once.
Thanks and best wishes,
Julie.

**Comment by thecodester** [comment]
@julieplummer20 Is the issue fixed? In the future, please close your own tickets.

**Comment by julieplummer20** [comment]
Hi Thanos,
I have closed the issue.
Please let me know if you have any other issues or questions.
BR Julie.
