### ISSUE TITLE
Define and Expose a CDS-Based Travel Data Model

### ISSUE THREAD

**Issue by Eponasol** [SAPDocuments/Issues#205]
Tutorials: https://developers.sap.com/tutorials/abap-environment-data-model.html
--------------------------

step 5 test yourself : no answer is accepted whatever I reply

**Comment by mervey45** [comment]
Hi @Eponasol , 

what did you answer so far?

Best regards, 
Merve

**Comment by Eponasol** [comment]
Hi, 

I made a lot of different answers in a try to get through... 

In my opinion it should be the Service binding details -> Entity set and
association -> Preview 

This is when using the Eclipse ADT but I've seen that there is the same
question in the training related to the Business Application Studio so I
don't figure out what is asked really. 

I followed the course and I apply all the training but I'm not able to
complete the step 5 because of the missing answer. 

Thank you,

François Henrotte 

+32 475 28 75 32 

Le 11/03/2021 14:08, Merve Temel a écrit :

> Hi @Eponasol [1] , 
> 
> what did you answer so far? 
> 
> Best regards,
> Merve 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
 

Links:
------
[1] https://github.com/Eponasol
[2]
https://github.com/SAPDocuments/Issues/issues/205#issuecomment-796722903
[3]

**Comment by mervey45** [comment]
Hi @Eponasol , 

the answer is Service binding. You can try to type it in and test it again.

Best regards, 
Merve

**Comment by Eponasol** [comment]
OK thank you very much. 

I don't understand why it didn't accept my answers, maybe I have put too
much words...

Thank you anyway ! 

François Henrotte 

+32 475 28 75 32 

Le 11/03/2021 14:20, Merve Temel a écrit :

> Hi @Eponasol [1] , 
> 
> the answer is Service binding. You can try to type it in and test it again. 
> 
> Best regards,
> Merve 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
 

Links:
------
[1] https://github.com/Eponasol
[2]
https://github.com/SAPDocuments/Issues/issues/205#issuecomment-796730226
[3]

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
