### ISSUE TITLE
Create Table Persistence and Generate Data

### ISSUE THREAD

**Issue by AkankshaKullu** [SAPDocuments/Issues#207]
Tutorials: https://developers.sap.com/tutorials/abap-environment-persistence.html
--------------------------

**Observation:** In step 1.2 the screenshot has to be updated. Change in the UI, a checkbox has been added.

**Expected:**
![2_2](https://user-images.githubusercontent.com/69286515/110498754-9ba13480-811d-11eb-9c2e-3707e09d6a88.png)

**Actual:**
<img width="440" alt="2" src="https://user-images.githubusercontent.com/69286515/110594850-4f003c80-81a3-11eb-8c3b-09899a4da81a.png">

**Labels:**
Landscape Labels: trail1 & trail2
Sprint Label: SCPTest-2103A
Scenario Label: SCPTest-fabap
Priority: Low

**Comment by mervey45** [comment]
Hi @MamathaKH ,

I will update this as soon as possible.

Best regards, 
Merve
