### ISSUE TITLE
Set Up Workflow Management in Cloud Cockpit

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Issues#208]
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-1-setup.html
--------------------------

Step 2: Set up your account using Booster 
Screenshot for Booster creation needs to be updated

Expected Result: 
![image](https://user-images.githubusercontent.com/50734023/110500535-4ebe5d80-811f-11eb-9ff9-1fdc68bee797.png)

Actual Result:
![image](https://user-images.githubusercontent.com/50734023/110500583-5f6ed380-811f-11eb-9178-bca4bb62186b.png)

**Comment by ArchanaShukla** [comment]
Tutorial is updated with the changes
