### ISSUE TITLE
Run the Employee Onboarding Sample Scenario

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Issues#212]
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-5-run.html
--------------------------

Step 7: View process visibility workspace for completed workflow
1. The sentence should be choose 'Monitor Visibility Scenarios' instead 'Monitor Scenarios' since the tile name is 'Monitor Visibility Scenarios' as shown below

![image](https://user-images.githubusercontent.com/50734023/110504544-45cf8b00-8123-11eb-81c1-d7cba2034e96.png)

**Comment by ArchanaShukla** [comment]
Tutorial has been updated
