### ISSUE TITLE
Mobile cards: Registration of cards failing in Mobile app

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#213]
Hello,

Scenario URL: https://developers.sap.com/tutorials/cp-mobile-cards-welcome.html

Step 3.6: Scan the QR code on the right to onboard your SAP Mobile Cards client.
Issue: Registration of Mobile cards is failing after creating cards with message - registration failed
Note: Scenario executed on Android Platform & the registration on Mobile app works on clicking "Launch the Mobile Services Cockpit" on the card registration page.

Thanks,
Shubham Agarwal

labels to be added:
prio: High-prio
Sprint Label: SCPTest-2102A
Scenario Label: SCPTest-mcard
Landscape Labels: trial1, trial2, trial3

**Comment by sandeep-tds** [comment]
Hi @i353590 

I am unable to reproduce the issue. Thus, I will reach out to you on MS Teams to resolve it on your landscape.

**Comment by i353590** [comment]
Hello @sandeep-tds ,

The Trial account we used doesn't have the application now.
We tried to execute the scenario again, and the issue is not reproducible.
So, we can close the ticket. Thanks for your support :)

Regrads,
Shubham

**Comment by sandeep-tds** [comment]
Thank you so much @i353590
