### ISSUE TITLE
Build and Deploy Your SAP Fiori App to SAP Business Technology Platform

### ISSUE THREAD

**Issue by shivakumar-p-sap** [SAPDocuments/Issues#215]
Document Link: https://developers.sap.com/tutorials/appstudio-fioriapps-mta-build-deploy.html

Step 3: Deploy the application.
When we try to deploy application its throwing error. It couldn't able to create or update destination service with error mentioned below. This issue only in EU region.  

![Error1](https://user-images.githubusercontent.com/65213299/110587199-5c182e00-8199-11eb-823d-23fdb8b96b33.PNG)

![error2](https://user-images.githubusercontent.com/65213299/110587374-9a155200-8199-11eb-9011-98fd865fb1c0.PNG)

Just for the information i have added screenshot of plugins version.
![image](https://user-images.githubusercontent.com/65213299/110588076-83232f80-819a-11eb-882a-a3992019910e.png)

Labels :
Landscape Labels: trail1
Sprint Label: SCPTest-2103A
SCPTest-fbizapp: Develop an SAP Fiori App Using SAP Business Application Studio
Priority label :‘High-prio’

Regards
Shivakumar P

**Comment by raz-korn** [comment]
Hi @shivakumar-p-sap ,

Trial accounts are entitled to two destination service instances. You are expected to get this error if these are exhausted.
A similar issue is handled on the environment level - see [here](https://answers.sap.com/questions/13314408/html5-repo-managed-application-router-error-creati.html).

Regards - Raz

**Comment by thecodester** [comment]
@raz-korn I will close this issue. 2 things:

- You can close your own issues.
- Should we add any note/warning about this issue?
