### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by shivakumar-p-sap** [SAPDocuments/Issues#216]
Tutorials: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Step 3. SAP Fiori Freestyle Project appearing as deprecated in all the regions.

![pic1](https://user-images.githubusercontent.com/65213299/110589265-2aed2d00-819c-11eb-86b0-82662d2c8f6d.PNG)

Step 7. Screen shot needs to be updated and step B can be removed or can be added as a NOTE.

![pic2](https://user-images.githubusercontent.com/65213299/110589574-a2bb5780-819c-11eb-8cf8-555bc6827461.PNG)

Regards
Shivakumar P

Labels :
Landscape Labels: trail1, trail2, trail3
Sprint Label: SCPTest-2103A
SCPTest-fbizapp: Develop an SAP Fiori App Using SAP Business Application Studio
Priority label :‘Low-prio’

**Comment by raz-korn** [comment]
Hi @shivakumar-p-sap ,

I pushed an update for the tutorial yesterday. It uses the new tooling.
We need to wait for it to be available on production.

Regards - Raz

**Comment by thecodester** [comment]
@raz if this is resolved, can you close this?
