### ISSUE TITLE
Set Up the SAP Launchpad Service

### ISSUE THREAD

**Issue by DipeshKumar1** [SAPDocuments/Issues#217]
Tutorials: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html
--------------------------

Hi Team,
At below step 2 of 'Step 3: Access the SAP Launchpad service' -
"Click Instances and Subscriptions from the side panel, click the Subscriptions tab, click the Actions icon (…) on the right, and select Go to Application.",
when I clicked on 'Go to Application', I'm getting access error as shown below -
![image](https://user-images.githubusercontent.com/31985279/110601140-a2c25400-81aa-11eb-8ea6-93b0d513fc0f.png)

Could you please resolve this issue ?
Thanks in advance!

Regards, Dipesh

**Comment by LindsayBert** [comment]
Hi

Did you assign yourself to the launchpad_admin role?

Thanks
Lindsay

**Comment by DipeshKumar1** [comment]
Hi Lindsay,
Thank you for your response.
Yes! I've alredy completed all earlier steps corectly.
Regards,
Dipesh

**Comment by LindsayBert** [comment]
Hi

If you've done all the earlier steps and you're using a trial account, it should work.  If you aren't using a trial account you may not have the required entitlement. 

Thanks
Lindsay

**Comment by DipeshKumar1** [comment]
Hi,
I've been using trial account only.
Regards,
Dipesh

**Comment by LindsayBert** [comment]
Hi Dipesh 

Can you try and open a ticket.  If not, I will ask Iris Sasson our product manager to try and help solve the problem.

Thanks Lindsay

**Comment by thecodester** [comment]
@IrisSasson Can you help us here?

**Comment by DipeshKumar1** [comment]
Hi Lindsay,

Sorry! I couldn't understand regarding open a ticket.
Regards, Dipesh

**Comment by LindsayBert** [comment]
Hi Dipesh 
I will ask Iris to try and help 

Thanks Lindsay

**Comment by thecodester** [comment]
@LindsayBert Any update here? If this is a product issue with BTP, then you should alert user to contact BTP and explain how? If tutorial issue, we should investigate some more.

**Comment by IrisSasson** [comment]
The other simple option i can think about is that you don't have the entitlement as you are using an old trial account. If your trial is quite empty, I suggest to delete your current trial account and try again, or just create a new trial with different details. If the issue is solved with this, we can also help you with your old trial account

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
