### ISSUE TITLE
Add a New Entitlement to Your Subaccount

### ISSUE THREAD

**Issue by DipeshKumar1** [SAPDocuments/Issues#218]
Tutorials: https://developers.sap.com/tutorials/cp-cf-entitlements-add.html
--------------------------

Hi Team

As per step - Use the filter bar the search for hana cloud to reduce the number of available entitlements. Click the checkbox to select the service plans hdi-data-connection, hana, and relational-data-lake. Finally, confirm your selection by clicking on Add 3 Service Plan., when I selected 'hana cloud', available plans are coming uneditable.

![image](https://user-images.githubusercontent.com/31985279/110604799-79a3c280-81ae-11eb-90f9-c45f15f7ea17.png)
Could you please resolve this issue ?
Thanks in advance!
Regards , Dipesh

**Comment by IObert** [comment]
Hi Dipesh,

this means you already added the plans to your subaccount. There's no need to add them again.

I'll close this issue now but feel free to open it again if something remains unclear.
