### ISSUE TITLE
Create Behavior Definition for Managed Scenario

### ISSUE THREAD

**Issue by xiebryant** [SAPDocuments/Issues#219]
Tutorials: https://developers.sap.com/tutorials/abap-environment-behavior.html
--------------------------

Hello Experts,

![image](https://user-images.githubusercontent.com/35694735/110611767-7d454280-81ca-11eb-8d42-90ddf0896eda.png)
![image](https://user-images.githubusercontent.com/35694735/110611812-89310480-81ca-11eb-8770-bd07de938a5a.png)
![image](https://user-images.githubusercontent.com/35694735/110611964-b2ea2b80-81ca-11eb-8116-80922c94ecd6.png)

After finishing all the steps for this tutorial, I could not see the 'Create' and 'Delete' button which is expected to show.
Please advice. Thanks. 

BRs,
Bryant

**Comment by mervey45** [comment]
Hi @xiebryant ,

can you unpublish and publish your service binding again. And try it out again?

Best regards, 
Merve

**Comment by willanyong** [comment]
I have the same issue and created issue #276 before i saw this link. Any solutions ?

**Comment by thecodester** [comment]
@mervey45 Let us know when tutorial is updated and then close this issue. Thanks.

**Comment by mervey45** [comment]
Hi @thecodester ,

I created following pull request for this change: #6640.

Best regards, 
Merve
