### ISSUE TITLE
Deploy a CAP Business Application to SAP Cloud Platform

### ISSUE THREAD

**Issue by HubertWeber** [SAPDocuments/Issues#22]
Tutorial: https://developers.sap.com/tutorials/cap-service-deploy.html
--------------------------

I followed the turorial in VSCode an got  at Step 3: 2. the following message:
cds build --production
[ERROR] invalid option: --production

cds -v

@sap/cds: 3.34.2
@sap/cds-compiler: 1.26.2
@sap/cds-dk: 1.8.5
@sap/cds-foss: 1.2.0
@sap/cds-reflect: 2.11.0
@sap/cds-runtime: 1.2.2
Node.js: v12.13.1
my-bookshop: 1.0.0

**Comment by iwonahahn** [comment]
Hi,

We have tested it as described in the tutorial and it worked with the latest release of `@sap/cds-dk 3.3.2`. Could you please update your `cds-dk` with `npm install` in the root level of your project and test it again?

Thank you and best regards,
Iwona

**Comment by HubertWeber** [comment]
Thank you very much Iwona. I've tried **npm install sk-cds**

but got following errors:

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/sk-cds - Not found
npm ERR! 404
npm ERR! 404  'sk-cds@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:

**Comment by iwonahahn** [comment]
Hi Hubert,

Did the first tutorial worked for you and you were able to run the application on http://localhost:4004/ for example? 

Why you try to install **sk-cds**? We recommend trying `npm install` at the root level of your project. Afterward, you should have the latest version of `cds-dk`. It was updated yesterday (see below). Please try it with a new fresh project. 

![image](https://user-images.githubusercontent.com/22098308/104440064-2e947700-5592-11eb-9c3b-e4cf0750e160.png)


Best regards,
Iwona

**Comment by HubertWeber** [comment]
Hi Iwona,
first tutorial went well. Thougt only sk-cds was outdated. [https://cap.cloud.sap/docs/resources/troubleshooting#npm-installation](url) helped me in order to   npm config delete "@sap:registry"
Many thanks for your support.
Kind Regards
Hubert

**Comment by iwonahahn** [comment]
Hi Hubert,
Nice to read and thanks for letting me know.
Best regards,
Iwona
