### ISSUE TITLE
Install the MultiApps Cloud Foundry CLI Plugin

### ISSUE THREAD

**Issue by SwamiKalagiri** [SAPDocuments/Issues#220]
Tutorials: https://developers.sap.com/tutorials/cp-cf-install-cliplugin-mta.html
--------------------------

Write here what you need help with ...

Question "What version rules are available" is not clear and i hope it is not working for any of the options

**Comment by IObert** [comment]
Good point! I will rephrase the question to make it easier to understand.

The new phrase will be:
> The output of the command will show you all available options. One of which is called "version rules".
> What values are allowed for this option?


I'll close this issue now but feel free to open it again if something remains unclear.
