### ISSUE TITLE
Develop and Run SAP Fiori Application With SAP Business Application Studio

### ISSUE THREAD

**Issue by xiebryant** [SAPDocuments/Issues#222]
Tutorials: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html
--------------------------
Hello Experts,

In step 8, I could not choose OData V2 service for IAM App. 
![image](https://user-images.githubusercontent.com/35694735/110773152-66b8ed00-8297-11eb-86d1-6fa7af8deb93.png)
Please advice. Thanks. 

BRs,
Bryant

**Comment by mervey45** [comment]
Hi @xiebryant , 

can you try it out with OData IWSG?

Best regards, 
Merve

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
