### ISSUE TITLE
 Implement the Transport for Your Factory Calendar

### ISSUE THREAD

**Issue by mts2605** [SAPDocuments/Issues#223]
Tutorials: https://developers.sap.com/tutorials/abap-environment-transport.html
--------------------------

Step 2 - ad 4 (+ activation)

I get error "Use of Class CL_A4C_BC_FACTORY is not permitted." when trying to activate the classes.

What to do?

KR Michael

**Comment by mervey45** [comment]
Hi @mts2605 ,

if it is step 2.4 then only saving is possible. If it is another step, please tell me which step it is.

Best regards, 
Merve

**Comment by mts2605** [comment]
@mervey45 Hi Merve
I mention it as step 2, ad 4, because the "error"-class is in line 52 in ZCL_BC_TRANSPORT_API_XXX
(I did notice when to activate;-) )
Thanks,
Michael
