### ISSUE TITLE
Add Views and Define Routes to Access Them

### ISSUE THREAD

**Issue by kasimirowicz** [SAPDocuments/Issues#224]
Tutorials: https://developers.sap.com/tutorials/sapui5-101-add-routing.html
--------------------------

I was just able to run the sample when I deleted the following attribute from  webapp/webapp/view/View1.view.xml

controllerName="sap.cp.webapp.controller.View1"

**Comment by IObert** [comment]
Thanks for pointing this one out!
This one must have slipped through the last update.
