### ISSUE TITLE
Design and Deploy Your First Integration Flow : Screenshot update for Adding iflows

### ISSUE THREAD

**Issue by mounikat987** [SAPDocuments/Issues#225]
Lables : SCP-Trial1 ,SCP-Trial2 , SCP-Trial3 Low-Prio

Tutorials: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html
--------------------------

_**Issue 1** :_ 

**Step 2: Create an integration package and integration flow**

In  step2  Choose Add > Integration Flow........ when we click on 'Add button' it shows additional options such as Rest API, soap API etc.,

![image](https://user-images.githubusercontent.com/33411431/110836160-bca48980-82c5-11eb-97cb-ca2255a83640.png)

Please update screenshot accordingly.

**_Issue 2 :_** 

![image](https://user-images.githubusercontent.com/33411431/110836741-697f0680-82c6-11eb-87f1-c08bebf36986.png)

In document screenshot show "Product Profile" name as "SAP Cloud Platform Integration" but it is "SAP Cloud Integration".

So, Please update the screenshot accordingly.

Thanks
Mounika

**Comment by Karunaharan** [comment]
Hi @mounikat987 fixed the issues and pushed to QA. Will send to production by end of day.

Thanks for the feedback.
