### ISSUE TITLE
Expose Integration Flow Endpoint as API and Test the Flow : In creation of service keys, Parameter Tab shows different UI in different regions

### ISSUE THREAD

**Issue by mounikat987** [SAPDocuments/Issues#226]
Lables : SCP-Trial1 ,Low-Prio

Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html
--------------------------

**Step 1: Create service instance and key**

5.In the Parameters tab, enter the following JSON code snippet:

In **EU** & **AP**  region , the parameters tab is as shown below : 

![image](https://user-images.githubusercontent.com/33411431/111106182-94918080-857a-11eb-9329-77d6cdc6fa24.png)

In **US**  region parameters tab is shown below : 

![image](https://user-images.githubusercontent.com/33411431/111106289-d6bac200-857a-11eb-85c6-15aceba3f1a5.png)

Please look into & update note & screenshots accordingly.

Thanks
Mounika

**Comment by Karunaharan** [comment]
The issue is resolved now with the implementation of boosters that automates the service instance and key creation.
