### ISSUE TITLE
Get Started with SAP Workflow Service

### ISSUE THREAD

**Issue by Girija-karetla** [SAPDocuments/Issues#227]
Group: https://developers.sap.com/group.cp-workflow-cf.html
--------------------------

In the step3. 
After Type in yo, then choose ENTER again.

 the @workflow/workflow Module, is not available. 

   `  |° ´ Y ` 

user: projects $ cd onBoard
user: onBoard $ yo,
bash: yo,: command not found
user: onBoard $ yo 
? 'Allo! What would you like to do? (Use arrow keys)
  Run a generator
❯ Basic Multitarget Application 
  Routing Config 
  @adaptation Project/adaptation Project 
  @adaptation Project/adaptation Project Deployment 
  @sap/fiori 
  @sapflp/launchpad Module 
(Move up and down to reveal more choices)

how to create a workflow module and a workflow.

**Comment by MichaelCzcz** [comment]
@AstridHerbst Please respond!

**Comment by AstridHerbst** [comment]
Hi,
Thank you for your question. Please follow the updated tutorial at: https://developers.sap.com/group.cp-workflow-cf.html 
Best regards,
Astrid

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
