### ISSUE TITLE
Deploy an SAP Conversational AI Chatbot to Microsoft Teams

### ISSUE THREAD

**Issue by AbeDong** [SAPDocuments/Issues#228]
Tutorials: https://developers.sap.com/tutorials/conversational-ai-deploy-teams.html
--------------------------

The bot I created will reply the question in the LIST form which right in customer script, and for each element, add a button to it. The button click works good in CAI test, but when deployed it to MS team. The behavior  are different, see screen blow.
![image](https://user-images.githubusercontent.com/34675321/110894295-936e1280-8332-11eb-994a-523da0de6f51.png)

And here is the script I used.
![image](https://user-images.githubusercontent.com/34675321/110894433-d8924480-8332-11eb-93cc-cc1a7c9c89ca.png)

Is this an issue from Azure or CAI.
I change the script a little bit, but the value pass to CAI still differnt.
![image](https://user-images.githubusercontent.com/34675321/110894579-11321e00-8333-11eb-949c-3f69edecc9c8.png)

![image](https://user-images.githubusercontent.com/34675321/110894541-ff507b00-8332-11eb-92cc-eb31756e39aa.png)

**Comment by thecodester** [comment]
Sorry for the delay. You are remarking that the ID is different in chat as opposed to MS Teams?

There are peculiarities for each of the platforms, and I am not such an expert on these. These issues get talked about quite a lot in https://community.sap.com

**Comment by thecodester** [comment]
Here is some documentation on what is supported in the various channels. The tutorial was meant to show how to make the connection to the various channels. 

As for differences in channels, I only have this information: https://help.sap.com/viewer/a4522a393d2b4643812b7caadfe90c18/latest/en-US/7c96e0046b9346f488a08c8b1d2bb8b5.html -- if I get more I will post it here.

In the meantime, I will close this issue.

You might also want to try in the SAP Community: 
https://www.sap.com/community.html
https://answers.sap.com/index.html
