### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by ckaberia** [SAPDocuments/Issues#229]
Tutorials: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html
--------------------------
In the step by step for the above, the (step number 4)
4. For Data Source and Service Selection, select the following, and click Next.  Its asking for username and password, unlike the way its presented in the link.

**Comment by raz-korn** [comment]
Hi @ckaberia ,

Please refer to the [issue 36](https://github.com/SAPDocuments/Issues/issues/36).

Regards - Raz

**Comment by ckaberia** [comment]
Thank you for the feedback @Raz Korn

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

@raz-korn You can close the issue yourself.
