### ISSUE TITLE
Create Sales Order App with SAP RAD by Mendix

### ISSUE THREAD

**Issue by DataSciCode** [SAPDocuments/Issues#230]
Tutorials: https://developers.sap.com/tutorials/mendix-salesorders.html
--------------------------
The Step 6 Get list screen has now Destination field and is not represented in the tutorial and appears to be mandatory.
 
![Screenshot 2021-03-13 141531](https://user-images.githubusercontent.com/759523/111043146-9c301880-8406-11eb-8c49-b4b3c65f08c4.png)

**Comment by Paolaufer** [comment]
Hi,
Thank you for the feedback. I will review the tutorial.

**Comment by MichaelCzcz** [comment]
@Paolaufer Any updates?

**Comment by Paolaufer** [comment]
I've updated the tutorial. Thank you for the feedback!
