### ISSUE TITLE
Deploy a CAP Business Application to SAP Business Technology Platform - NPM Issue

### ISSUE THREAD

**Issue by ahusemann84** [SAPDocuments/Issues#231]
Tutorials: https://developers.sap.com/tutorials/cap-service-deploy.html
--------------------------

When executing the command `npm add @sap/hana-client --save` a fatal error is reported, indicating that no suitable image was found:

dlopen(.../my-bookshop/node_modules/@sap/hana-client/prebuilt/darwinintel64-xcode7/hana-client.node, 1): no suitable image found.  Did find:
        .../my-bookshop/node_modules/@sap/hana-client/prebuilt/darwinintel64-xcode7/hana-client.node: mach-o, but wrong architecture
        .../my-bookshop/node_modules/@sap/hana-client/prebuilt/darwinintel64-xcode7/hana-client.node: mach-o, but wrong architecture
.../my-bookshop/node_modules/@sap/hana-client/lib/index.js:58
    db.__stopAllWork();
       ^

I am using a MacBook Pro with the M1 chip. Is that architecture currently not supported by the HANA Client?

**Comment by iwonahahn** [comment]
To which steps you are referring to?  Which version of `@sap/cds-dk` are you using?
Can you please provide the output of `cds -v`?

**Comment by ahusemann84** [comment]
I am referring to https://developers.sap.com/tutorials/cap-service-deploy.html, Step 1, Point 3. When adding the SAP HANA driver dependency via `npm add @sap/hana-client --save` I get the aforementioned error.

Output of `cds v`:
@sap/cds: 4.6.5
@sap/cds-compiler: 1.50.0
@sap/cds-dk: 3.5.1
@sap/cds-foss: 2.2.1
@sap/cds-runtime: 2.9.1
Node.js: v14.16.0
home: .../.nvm/versions/node/v14.16.0/lib/node_modules/@sap/cds-dk/node_modules/@sap/cds
(node:87479) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:87479) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency

In general I am using a free installation, and that is the first error I observe. The previous tutorial (https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html) could be completed without issues.

Thanks for looking into the issue.

**Comment by iwonahahn** [comment]
I have tested it today with node v14.6 and the latest version of `cds-dk` w/o any issues:

@sap/cds: 4.6.5
@sap/cds-compiler: 1.50.0
@sap/cds-dk: 3.5.1
@sap/cds-foss: 2.2.1
@sap/cds-runtime: 2.9.7

Need to discuss this with the dev colleagues, why using node v 4.16. fail and will get back here asap.

**Comment by iwonahahn** [comment]
Hi @ahusemann84,

Together with the dev colleagues, we searched for a solution. Could you please try this ["workaround"](https://stackoverflow.com/questions/64899827/nodejs-on-apple-silicon-m1/64902152#64902152) and get back to us, if this works? 

In the meanwhile, I will contact the colleagues responsible for the `@sap/hana-client` module to ask if they are aware of issues using the new MacBook Pro with M1.

Thank you and best regards,
Iwona

**Comment by ahusemann84** [comment]
Hi @iwonahahn,

thanks for your hint, it actually solved my issue. Besides running the Terminal using Rosetta I had to uninstall node and install it again afterwards.

Then I could also install the hana-client without any problems.

Thanks and best regards,
Arne

**Comment by iwonahahn** [comment]
> Hi @iwonahahn,
> 
> thanks for your hint, it actually solved my issue. Besides running the Terminal using Rosetta I had to uninstall node and install it again afterwards.
> 
> Then I could also install the hana-client without any problems.
> 
> Thanks and best regards,
> Arne

Hi Arne,

Thanks a lot for the confirmation :).

Best regards,
Iwona

**Comment by drvup** [comment]
Just want to share with you [this post](https://stackoverflow.com/questions/65342769/install-node-on-m1-mac) (and the answer of Sators) was solving my issue too. Check with "node" > process.arch on which architecture your installation is based. Due to this issue (especially with the @sap/hana-client), I had to re-install with node v14 and the specific x64 architecture. Maybe it's worth it writing it down, so the next one will also find it :)

**Comment by gauravkr75** [comment]
@drvup thanks for the link. Solved my issue as well
