### ISSUE TITLE
Expose Integration Flow Endpoint as API and Test the Flow

### ISSUE THREAD

**Issue by i018841** [SAPDocuments/Issues#233]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html
--------------------------

hi, in step 5 where we supposed to enter the following JSON text:

{
 "roles":[
   "ESBMessaging.send"
 ]
}

There's an error encountered.  Can you advise?

**Comment by Karunaharan** [comment]
Hi @i018841, In step 1, sub step 5, please refer to the second image. You can see that there is a box available (in the **Parameters** tab) for you to add the above JSON text.

Hope this helps.
