### ISSUE TITLE
Create an SAP Cloud Application Programming Model Project for SAP HANA Cloud

### ISSUE THREAD

**Issue by jmalla** [SAPDocuments/Issues#234]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-create-project.html
--------------------------

I got an error when doing the first commit.  I had to do the following to add my email and name.  Then the commit worked:

git config --global user.email "you@example.com" 
git config --global user.name "Your Name"

**Comment by jung-thomas** [comment]
Interesting. I wouldn't have thought that would have been necessary for using the local git repository and I didn't get prompted myself but that could be that my workspace had the configuration left over from other work.  I'll add this step to the tutorial. 

Thanks,
Thomas Jung
