### ISSUE TITLE
Create Database Artifacts Using Core Data Services (CDS) for SAP HANA Cloud - No SAP HANA Projects View available

### ISSUE THREAD

**Issue by juliamerscheid** [SAPDocuments/Issues#238]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-create-database-cds.html
--------------------------

Hi team,

I followed all tutorial steps of https://developers.sap.com/group.hana-cloud-cap-setup.html so far and now I am stuck.

Tutorial: https://developers.sap.com/tutorials/hana-cloud-cap-create-database-cds.html
Step: 3.2 "You will now deploy those objects into the HANA Database creating tables and views. We will use the SAP HANA Projects view to do this. Please expand this view and you will see the following:"

There is no vi
ew available called SAP HANA Projects and it is not displayed already either.

How can I find the view or what are the necessary terminal commands to achieve the same?

As you can see in the screenshot attached there is no SAP HANA Projects view available when I type in "SAP" in the search bar for views.

![Screenshot 2021-03-17 170226](https://user-images.githubusercontent.com/64284189/111498901-afaeec80-8742-11eb-87c6-e3c50d84337d.png)

**Comment by jung-thomas** [comment]
In the Tutorial before this one in the group: https://developers.sap.com/tutorials/hana-cloud-cap-create-project.html  At Step one, Item 4 -- are you sure you did this step correctly?

![image](https://user-images.githubusercontent.com/12159356/111527170-03670900-8736-11eb-93ce-94a1c5fc520f.png)
When creating your dev space you select the HANA items on the right side. This is what adds the HANA tooling (including the HANA Projects View) into your dev space. You can stop your dev space and press the edit button. You basically get this same screen back and can add any tools you missed the first time. When you next load your dev space you should have the missing HANA tooling.

**Comment by juliamerscheid** [comment]
Thank you.
I went through the tutorial again. Although some of the marked additional SAP Extensions were part of the predefined extensions already I found it. Its working now.

**Comment by jung-thomas** [comment]
Excellent. 👍
