### ISSUE TITLE
Create Calculation View and Expose via CAP (SAP HANA Cloud)

### ISSUE THREAD

**Issue by jmalla** [SAPDocuments/Issues#242]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-calc-view.html
--------------------------

I had a problem running npm start since the services were already running but the terminal windows were closed.  So I had to find the processes running on ports 4004 and 50000 and kill them.  And then run npm start from the root folder and the app folder in another terminal to get this to run.  It may be good to add these steps,

lwctl -c basic-tools ps aux
lwctl -c basic-tools kill -9 <PID>

Regards,
Jay

**Comment by jung-thomas** [comment]
I'm not exactly sure how you go to the situation where the services were running but the terminal windows were closed.  That shouldn't be possible. I just tested and as soon as you close the terminal window it kills the running process.  And if you just close the web browser, when you restart it restores the terminal window to the same session.  

I don't really want to add steps to a tutorial for a situation that really shouldn't occur.

**Comment by sbpgit** [comment]
Hi ,

I have created the calculation with the same process as mentioned in the blog.

Below are the steps created for Calculation View.
1. Calculation view products is created in db->src  - deployment successful
2. i have generated the entity for Calculation View using hana-cli inspectView -v products -o cds
3. Service has been created in SRV folder

But while exposing as a cap service it is throwing below
Error: The file requires "db://PRODUCTS" which is not provided by any file [8212001]
Could you please help what am i missing in this process

Thanks,
Thulja

**Comment by ttulja** [comment]
Hi ,

I have created the calculation with the same process as mentioned in the blog.

Below are the steps created for Calculation View.

    Calculation view products is created in db->src - deployment successful
    i have generated the entity for Calculation View using hana-cli inspectView -v products -o cds
    Service has been created in SRV folder

But while exposing as a cap service it is throwing below
Error: The file requires "db://PRODUCTS" which is not provided by any file [8212001]
Could you please help what am i missing in this process

Thanks,
Thulja

**Comment by jung-thomas** [comment]
Answering in the separate issue here https://github.com/SAPDocuments/Issues/issues/519
