### ISSUE TITLE
Create a Start Form and its Custom Tile for Your Workflow

### ISSUE THREAD

**Issue by hvolk** [SAPDocuments/Issues#243]
Tutorials: https://developers.sap.com/tutorials/cp-workflow-4-approval-ui-cf.html
--------------------------

**Question / Feedback regarding the points mentioned under prerequisites**

Point 3:
"You have created a launchpad site. See Create a Site."
I see that the site creation is done in step 7 of the tutorial, so why is it listed as prerequisite?

Point 4:
"You have created a destination for your service instance. See Destinations Pointing to Service Instances."
It is not 100% clear for **which** service instance it needs to be created. It found it after some tries, but it would be helpful to be more specific here.
I found a similar text on this help page, which would fit well here:
https://help.sap.com/viewer/e157c391253b4ecd93647bf232d18a83/Cloud/en-US/97c079f9317c42bba31cc9ca9d4cc7c3.html
"You have created a destination to the **workflow service instance** with the **authentication method OAuth2JWTBearer**."

Or maybe add this step to the tutorial directly...

Overall, the tutorials are very helpful and easy to follow because of all the details and screenshots! Thanks!

**Comment by MichaelCzcz** [comment]
@AstridHerbst Please respond!

**Comment by AstridHerbst** [comment]
Hi,
Thank you very much for your input. The tutorials have been updated.
Best regards, Astrid

**Comment by AstridHerbst** [comment]
Sorry, wrong entry
