### ISSUE TITLE
Create a Data Element

### ISSUE THREAD

**Issue by mts2605** [SAPDocuments/Issues#245]
Tutorials: https://developers.sap.com/tutorials/abap-dev-adt-create-data-element.html
--------------------------

Write here what you need help with ...Step 11

Pls help with hint to the rewrite. I am stuck;-)

BR Michael

**Comment by julieplummer20** [comment]
Hi Michael,
I am sorry to hear this.
The correct answer is:
LOOP AT Booking_List ASSIGNING FIELD-SYMBOL(<booking>).

Please let me know if this works.
BR Julie.

**Comment by mts2605** [comment]
Hi Julie
Thanks, but unfortunately, the response i get is:

Sorry, that’s incorrect. Please try again.

KR Michael

**Comment by thecodester** [comment]
@julieplummer20 You made the answer as follows (exact match of text):

LOOP AT Booking_List ASSIGNING FIELD-SYMBOL(<booking>).

Is that what you meant?

**Comment by julieplummer20** [comment]
Hi Michael,
Sorry, there appears to be a markup error, in what I wrote.
Can you please just paste exactly what you wrote in your answer **using the "Insert Code" tag** `<>` ?
I apologize for the initial misunderstanding.
BR Julie.

**Comment by julieplummer20** [comment]
Hi Michael,
I apologise for bothering you about this. But it is not entirely clear. Did you enter:
`LOOP AT Booking_List ASSIGNING FIELD-SYMBOL(<booking>)`

or 

`LOOP AT Booking_List ASSIGNING FIELD-SYMBOL()`

`LOOP AT Booking_List ASSIGNING FIELD-SYMBOL(<booking>)` is correct. If you entered this, then there is an issue with the tools, which I will need to address with the team.

Thanks for clarifying, Julie.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
