### ISSUE TITLE
Create an Empty SAPUI5 Project

### ISSUE THREAD

**Issue by morimehul** [SAPDocuments/Issues#247]
Tutorials: https://developers.sap.com/tutorials/sapui5-101-create-project.html
--------------------------

While adding deployment configuration I am getting following error:

{"message":"@sap/fiori:app generator failed - {"message":"Could not update method 'validate' in 'cfDestination' question in generator '@sap/fiori:app' - evaluateMethod() e.trim is not a function","stack":"TypeError: evaluateMethod() e.trim is not a function\n at /extbin/npm/globals/lib/node_modules/@sap/generator-fiori/generators/deployment-generator/deploy/index.js:574:192947\n at Object.t.validateDestinationQuestion (/extbin/npm/globals/lib/node_modules/@sap/generator-fiori/generators/deployment-generator/deploy/index.js:574:192955)\n at u.validate (/extbin/npm/globals/lib/node_modules/@sap/generator-fiori/generators/deployment-generator/deploy/index.js:574:191874)\n at v.<anonymous> (/tmp/vscode-unpacked/yeoman-ui-1.1.57.vsix/extension/dist/extension.js:193:116235)\n at Generator.next (<anonymous>)\n at /tmp/vscode-unpacked/yeoman-ui-1.1.57.vsix/extension/dist/extension.js:193:110451\n at new Promise (<anonymous>)\n at r (/tmp/vscode-unpacked/yeoman-ui-1.1.57.vsix/extension/dist/extension.js:193:110196)\n at v.evaluateMethod (/tmp/vscode-unpacked/yeoman-ui-1.1.57.vsix/extension/dist/extension.js:193:115982)\n at o.<anonymous> (/tmp/vscode-unpacked/yeoman-ui-1.1.57.vsix/extension/dist/extension.js:515:3404)\n at Generator.next (<anonymous>)\n at /tmp/vscode-unpacked/yeoman-ui-1.1.57.vsix/extension/dist/extension.js:515:2068\n at new Promise (<anonymous>)\n at r (/tmp/vscode-unpacked/yeoman-ui-1.1.57.vsix/extension/dist/extension.js:515:1813)\n at o.handleRequest (/tmp/vscode-unpacked/yeoman-ui-1.1.57.vsix/extension/dist/extension.js:515:3159)\n at /tmp/vscode-unpacked/yeoman-ui-1.1.57.vsix/extension/dist/extension.js:186:63780\n at /theia/node_modules/@theia/core/lib/common/event.js:176:33\n at CallbackList.invoke (/theia/node_modules/@theia/core/lib/common/event.js:191:39)\n at Emitter.fire (/theia/node_modules/@theia/core/lib/common/event.js:318:29)\n at WebviewsExtImpl.$onMessage (/theia/node_modules/@theia/plugin-ext/lib/plugin/webviews.js:71:44)\n at RPCProtocolImpl.doInvokeHandler (/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:291:23)\n at RPCProtocolImpl.invokeHandler (/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:276:41)\n at RPCProtocolImpl.receiveRequest (/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:240:31)\n at RPCProtocolImpl.receiveOneMessage (/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:209:22)\n at /theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:101:109\n at /theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:316:17\n at /theia/node_modules/@theia/core/lib/common/event.js:176:33\n at CallbackList.invoke (/theia/node_modules/@theia/core/lib/common/event.js:191:39)\n at Emitter.fire (/theia/node_modules/@theia/core/lib/common/event.js:318:29)\n at /theia/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host.js:148:25\n at step (/theia/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host.js:48:23)\n at Object.next (/theia/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host.js:29:53)\n at /theia/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host.js:23:71\n at new Promise (<anonymous>)"}"}

**Comment by cjbernal** [comment]
Hi @morimehul ,

This issue has been reproduced by the SAP Fiori tools team, as well as reported by customers. We are currently working on a fix. We will keep you updated.

Kind regards,
Conrad (SAP Fiori tools team)

**Comment by cjbernal** [comment]
Hi @morimehul 

I see that my colleagues have closed their ticket investigating the issue. Could you please try it again? 

Thanks and regards,
Conrad (SAP Fiori tools team)

**Comment by morimehul** [comment]
Thanks @cjbernal 

Working fine  now.

Cheers
Mehul
