### ISSUE TITLE
Call an External Endpoint to Retrieve Additional Information

### ISSUE THREAD

**Issue by Gyannini** [SAPDocuments/Issues#249]
Tutorials: https://developers.sap.com/tutorials/cp-integration-consume-external-api.html
--------------------------

Hi, I believe there's an issue in step 4 of this tutorial. The element 'Content Enricher', doesn't have the 'processing' properties displayed in the tutorial.. 

On my iFlow, for this element it is expected the following properties:
- Aggregation algorithm
- Path to node (original message)
- Key element (original message)
- Path to node (lookup message)
- Key element(lookup message)

But in the tutorial it is displayed (step 4.3):
Address | SOAP endpoint URL of the flow created in Step 1
Method | POST
Authentication | Basic
Credential Name | User

Thanks! Bruno

**Comment by gauthamkrishna-sap** [comment]
Hello Bruno,

Thank you for your feedback. 

We are currently overhauling the entire mission and will release a new version with updated content soon. Please stay tuned. 

Thanks and Best Regards,
Gautham

**Comment by thecodester** [comment]
@gauthamkrishna-sap Any update on this? If this will take some time to fix we may want to take the tutorial offline. It would be better, however, to fix.

**Comment by gauthamkrishna-sap** [comment]
@thecodester The updates are in progress. I would defer to your judgement on whether to keep the tutorials live or keep them offline till the updates are rolled out. Thank you.

**Comment by thecodester** [comment]
@gauthamkrishna-sap  Can you just give us an estimate of when the tutorials will be updated? Can the tutorials be done at all?

**Comment by gauthamkrishna-sap** [comment]
We are still working on it. In the meantime, I can offer you this session from TechEd 2020: https://github.com/SAP-samples/teched2020-DEV165

This also contains mail adapter configuration with REST API and a non-SAP system. Hope you can get some hands on experience with this while we update this series.

Thanks and Best Regards,
Gautham

**Comment by gauthamkrishna-sap** [comment]
Hello,
This tutorial has been deprecated. We will replace it with an updated tutorial in the coming weeks. Please watch out for "Integration Suite tutorials" in the SAP Tutorial Navigator for new updates. 
Thank you.
