### ISSUE TITLE
Create Database Artifacts Using Core Data Services (CDS) for SAP HANA Cloud - issues with tutorial

### ISSUE THREAD

**Issue by js1972** [SAPDocuments/Issues#250]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-create-database-cds.html
--------------------------

Write here what you need help with ...

Following along with this great tutorial mission but have come across two issues.

1. The initial deployment of db artefacts to HANA Cloud fails because after we do `Hana-cli createModule` we are not instructed to log into the db directory and run `npm install`
2. Something is not right with the way things work with hdi containers. Once I have successfully deployed the db module (from the rocket ship icon at db level) and I then try to directly navigate to the DB Explorer... the navigation fails saying it could not find the hdi container. I have found that in the db explorer you can tap + (add db) and find the hdi container and add it. You can then see all your deployed artefacts. but if you go back to BAS and click DB Explorer again the navigation still fails even though the hdi container does show. Also the hdi container generated has a different name for those shows in the tutorial. Mine is generated as: `MyHANAApp-hdiMyHANAApp-db-deplpoyer-ws-zhk69` where the tutorial states that they should be names something like `SharedDeveKey@MyHANAApp-hdiMyHANAApp-db-deplpoyer-ws-zhk69`.

For item 1 above we could easily add the /db npm I step to the tutorial. But for item 2 I don't know. I have gone over what I did a second time and the same thing happens where the reality is different to what is shown in the tutorial. Any ideas?

;-)

**Comment by jung-thomas** [comment]
The npm install command isn't necessary. The deploy action (rocket icon) from the SAP HANA Projects view will run npm install automatically.  See the video: https://youtu.be/hlHY7eBriRA?t=589
Notice right before I hit deploy there is no node_modules folder in /db:
![image](https://user-images.githubusercontent.com/12159356/111948396-77e2d480-8ab5-11eb-8ac6-9a3e74e9a1ca.png)

But then you can see in the video that the the deploy task is running npm install: https://youtu.be/hlHY7eBriRA?t=598
![image](https://user-images.githubusercontent.com/12159356/111948543-b8425280-8ab5-11eb-91ed-bac0510f83dc.png)

I just re-tested this just now. I deleted the node_modules folder and package-lock.json from my /db folder.
![image](https://user-images.githubusercontent.com/12159356/111949457-263b4980-8ab7-11eb-9f91-8ee14af1995b.png)

And then just pressed the rocket icon - it does exactly as it did in my earlier tutorial run through in the video. It senses that the content is missing and runs the npm install automatically:
![image](https://user-images.githubusercontent.com/12159356/111949577-597dd880-8ab7-11eb-9bf3-4df9cff8d953.png)

On the second part, you should not have to manually add the entry to the DB Explorer When you click the Open HDI container option from the SAP HANA Projects view, it creates the entry in the DB Explorer for you. 
https://youtu.be/hlHY7eBriRA?t=670

I also just now retested the Open HDI container option too. I first deleted my entries from the DB Explorer.  I then press the Open HDI container option form the SAP HANA Projects view.  It did just now exactly what is shown in the video. It adds the entry to the DB Explorer that starts with SharedDevKey and navigates to/expands it. 

I'm afraid I'm unable to recreate either scenario you describe. Upon retesting they both flow exactly as shown in the original video.

**Comment by js1972** [comment]
Thanks for the detailed reply Thomas. I run this only an hour ago and the build would keep failing and I noticed it was a missing dep. Ran the `npm i` manually and it worked. Lets just close this then but something must have glitched for me.   ;-)

**Comment by js1972** [comment]
I have just tried repeatedly and the hdi container is not automatically navigated to.... Could it be because you are testing with a trial account and I am using a production account (feature set A) ?

**Comment by jung-thomas** [comment]
I am testing in trial because that is primarily what the tutorial is designed for. I'm not sure what would be different about this scenario in production accounts. Perhaps you lack the developer rights to the target space? The trial onboarding process does ensure that your developer rights are granted automatically. However I would have expected without the correct rights you wouldn't have been able to create the service instance at all in the earlier step. Maybe you are getting logged into Database Explorer with a different user identity then what you are using to connect manually to CF during the earlier wizard. That's the only way I could explain have the rights to create the service instance but not "See" it from Database Explorer.

**Comment by js1972** [comment]
Hmm the different user thing could be a possibility - will look into that now. As it is though I can (+) to add the hdi container and then everything works as per normal and my app runs just fine.
