### ISSUE TITLE
Create a User Interface with CAP (SAP HANA Cloud) - step 9 issue

### ISSUE THREAD

**Issue by js1972** [SAPDocuments/Issues#251]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-create-ui.html
--------------------------

Write here what you need help with ...

In STEP 9: Opening the url `/interaction_items/webapp/index.html` from the service CAP web page does not open a Fiori Launchpad as shown in the tutorial. Instead it directly opens the app.

**Comment by jung-thomas** [comment]
This looks like it is as change in how the wizard works.  When I originally created the tutorial a few weeks ago it did generate the Fiori Sandbox in the index.html. It now doesn't any longer.  I'll remove this step from the tutorial as its no longer needed.

**Comment by js1972** [comment]
@jung-thomas  This is the best overall cap tutorial by the way. Thanks. ;-)
