### ISSUE TITLE
Help Thomas Get Started with SAP HANA Cloud

### ISSUE THREAD

**Issue by abzope** [SAPDocuments/Issues#252]
Tutorials: https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html
--------------------------

Write here what you need help with ...
in below snippet as per tutorial Create statement is missing. This is leading to the error. Please corret it.:
column table "DEVS"(
  "DEVNAME" nvarchar(100) PRIMARY KEY,
  "LEARNS_FROM" nvarchar(100),
  "HINT_TEXT" nvarchar(1000),
  "CITY" nvarchar(100),
  "LON_LAT" nvarchar(200)
)

**Comment by jung-thomas** [comment]
Maybe you could clarify what you feel is missing here. Because Step 9, Part 1 does have this code snippet in it:
![image](https://user-images.githubusercontent.com/12159356/111947998-d196cf00-8ab4-11eb-80e5-9ce70c99b7c1.png)

**Comment by abzope** [comment]
"create" statement is missing in the code. To create a table statement
should be "*create column table "DEVS" (*"

[image: image.png]

BR, Abhi

**Comment by jung-thomas** [comment]
No adding CREATE is not correct.  This is an HDBTABLE artifact.  You do not place the CREATE verb in such a file. 

https://help.sap.com/viewer/3823b0f33420468ba5f1cf7f59bd6bd9/2.0.05/en-US/453d48e28f6747799546236b4b432e58.html

From the help:

> The file format required for the .hdbtable and .hdbdropcreatetable artifacts uses a DDL-style syntax that is equivalent to the SQL syntax in the corresponding SQL command CREATE TABLE, without the leading “CREATE”
