### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by sikanderw** [SAPDocuments/Issues#253]
Tutorials: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html
--------------------------

Service | GWSAMPLE_BASIC (1) - OData V2 ist not available in dropdown
-- | --

**Comment by raz-korn** [comment]
Hi @sikanderw ,
Can you share screenshot of the full screen?
Please refer to [issue 36](https://github.com/SAPDocuments/Issues/issues/36) and see if it helps.
Regards - Raz

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
