### ISSUE TITLE
Help Thomas Get Started with SAP HANA Cloud

### ISSUE THREAD

**Issue by abzope** [SAPDocuments/Issues#254]
Tutorials: https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html
--------------------------

Write here what you need help with ...

In below snippet also "create" statement is missing. please correct it. statement should be "**create column table LEARNING_RELATION(**"

![image](https://user-images.githubusercontent.com/9859883/111997784-647d4b00-8b41-11eb-98aa-e0b6671008a9.png)

**Comment by jung-thomas** [comment]
It would actually be incorrect to have the CREATE statement here as this is an HDBTABLE file. The CREATE or any action VERB is not allowed and would result in a syntax error.
