### ISSUE TITLE
Deploy Your First SAPUI5 App

### ISSUE THREAD

**Issue by ivanmir** [SAPDocuments/Issues#255]
Tutorials: https://developers.sap.com/tutorials/appstudio-sapui5-create.html
--------------------------

The generators now feature the option to add a managed AppRouter - so there is no need to manually add an AppRouter after you have created the project. 

I have also noticed that after you create a project, there is no message displayed to open the workspace. Once you open the workspace manually (using the File Menu) it opens the project. However, the project doesn't build correctly.

Apparently the Fiori MTA module and its dependencies are not consistent with NodeJS version installed on Business Application Studio. I am getting the following error while trying to run #npm install @ the project's root folder:

> keytar@7.2.0 install /home/user/projects/sapui5/node_modules/keytar
> prebuild-install || npm run build
prebuild-install WARN install libsecret-1.so.0: cannot open shared object file: No such file or directory

It seems that the current dependencies require a newer version of NodeJS.
I've managed to update nodejs to version 12 and npm to version 7 and the above error goes away completely. 
However, I've also seen messages related to updating NodeJS on BAS and SAP has discouraged this procedure as it has unknown side-effects. 

Could you please review this?

Best regards,
Ivan

**Comment by raz-korn** [comment]
Hi @ivanmir ,

Why did you need to run npm install?
I followed the tutorial and it worked well.
Perhaps it's because the node.js version in BAS was recently updated to 14.

Regards - Raz

**Comment by raz-korn** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue.
If you still have questions and want to continue the conversation, feel free to reopen the issue.
