### ISSUE TITLE
Use the Application Router in Cloud Foundry to Connect to ABAP System

### ISSUE THREAD

**Issue by IObert** [SAPDocuments/Issues#256]
Tutorials: https://developers.sap.com/tutorials/cp-connectivity-consume-odata-service-approuter.html
--------------------------

Hi Colleague,

the tutorial is outdated in several aspects: The screenshots are very old, the user approuter version is deprecated, the SAP npm registry is still used, etc.
Can you please update it as [users](https://answers.sap.com/questions/13324089/approuter-redirects-to-virtual-host.html) seem to run into issues?

**Comment by je-hal** [comment]
Hi @IObert, as already explained by email I am no longer maintaining these tutorials.

I reached out to my manager to find a solution.
