### ISSUE TITLE
OData V2 not available as Service Type 

### ISSUE THREAD

**Issue by ahusemann84** [SAPDocuments/Issues#257]
Tutorials: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html
--------------------------

I have issues to complete the Tutorial "Develop and Run SAP Fiori Application With SAP Business Application Studio". In step 8 "Step 8: Create IAM App and business catalog" I am not able to select the Service Type OData V2, thus I am not able to reference the previously created service.

![image](https://user-images.githubusercontent.com/80681442/112117616-d2665880-8bbb-11eb-9931-72ad15a5241d.png)

The dialog show several options, but OData V2 is missing.

Please have a look.

**Comment by thecodester** [comment]
@ahusemann84 Did this solve the problem for now?

@mervey45 Do you know when the tutorial will be updated?

**Comment by mervey45** [comment]
Hi @thecodester ,

I created following pull request for this change: #6640.

Best regards, 
Merve

**Comment by ahusemann84** [comment]
Hi @mervey45,

I retried the updated tutorial, now everything worked fine for me. 

Many thanks for you support.

BR
Arne

**Comment by mervey45** [comment]
Hi @ahusemann84 ,

great to hear. You're welcome.

Best regards, 
Merve
