### ISSUE TITLE
Add Federated SAP S/4HANA Roles to Your Launchpad Site

### ISSUE THREAD

**Issue by Rodfior** [SAPDocuments/Issues#258]
Tutorials: https://developers.sap.com/tutorials/cp-launchpad-federation-consumption.html
--------------------------

Hi, I was following the steps and had and issue by accessing the app:

The content it is replicated to the BTP Launchpad and I can see all the tiles from the catalog but when I try to access any of the tiles the following error shows:

No suitable resource found

I could see that the error is generated with the following URL:

https://a4e3cef1trial.launchpad.cfapps.us10.hana.ondemand.com/dynamic_dest/s4hanart/sap/opu/odata/UI2/INTEROP/PersContainers(category='P',id='sap.ushell.UserDefaultParameter')/?$expand=PersContainerItems

By checking SCC logs I understand that the URL above translates to:

http://s4hana:44300/sap/bc/ui2/cdm3/entities/sap/opu/odata/UI2/INTEROP/PersContainers(category='P',id='sap.ushell.UserDefaultParameter')/?$expand=PersContainerItems

so

https://vhcals4hcs.dummy.nodomain:44301/sap/bc/ui2/cdm3/entities/sap/opu/odata/UI2/INTEROP/PersContainers(category='P',id='sap.ushell.UserDefaultParameter')/?$expand=PersContainerItems

In the Remote Desktop browser if I try the URL above I got the same error:

No suitable resource found

On the other hand if I remove the path through service sap/bc/ui2/cdm3/entities/ I can access the required service resource without further issue e.g:

https://vhcals4hcs.dummy.nodomain:44301/sap/opu/odata/UI2/INTEROP/PersContainers(category='P',id='sap.ushell.UserDefaultParameter')/?$expand=PersContainerItems

I think that there is some problem with the exposure via service cdm3

Do you guys have any hint why service cdm3 cannot find the resources?

Best regards

**Comment by SibylleB** [comment]
Hi, 
thanks for the very detailed error description. To me, that looks like the runtime destination has not been configured correctly. Please notice that the URL should only have the suffix /sap/bc/ui2/cdm3/entities in the design time destination, but not in the runtime destination. Please check the runtime destination again.
Best,
Sibylle

**Comment by Rodfior** [comment]
Nice, it did the trick! Thank you very much, very nice tutorial by the way, keep on the good work!
