### ISSUE TITLE
Error message for "com.sap.cloud.sdk.plugins" when using "Create a Sample Application on Cloud Foundry Using SAP Cloud SDK"

### ISSUE THREAD

**Issue by billgatesfan** [SAPDocuments/Issues#26]
Tutorial: https://developers.sap.com/tutorials/s4sdk-cloud-foundry-sample-application.html
--------------------------

Hi, 

I am a complete Java newbie, and I tried to create a project using your tutorial and the **scp-cf-spring** archetype, using VS Code and few extensions like "Project Manager for Java". Later, I will host the app on CF.

Unfortunately, when I try to run it locally, I get a nice error : 

`{
	"resource": "/C:/Users/olivier.nagy@sap.com/source/repos/myjavatest/myartifactid/application/pom.xml",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "0",
	"severity": 8,
	"message": "Execution default of goal com.sap.cloud.sdk.plugins:usage-analytics-maven-plugin:3.35.0:usage-analytics failed: Plugin com.sap.cloud.sdk.plugins:usage-analytics-maven-plugin:3.35.0 or one of its dependencies could not be resolved: Failed to collect dependencies at com.sap.cloud.sdk.plugins:usage-analytics-maven-plugin:jar:3.35.0 -> com.sap.cloud.sdk.plugins:usage-analytics:jar:[3.35.0,) (com.sap.cloud.sdk.plugins:usage-analytics-maven-plugin:3.35.0:usage-analytics:default:compile)\n\norg.apache.maven.plugin.PluginExecutionException: Execution default of goal com.sap.cloud.sdk.plugins:usage-analytics-maven-plugin:3.35.0:usage-analytics failed: Plugin com.sap.cloud.sdk.plugins:usage-analytics-maven-plugin:3.35.0 or one of its dependencies could not be resolved: Failed to collect dependencies at com.sap.cloud.sdk.plugins:usage-analytics-maven-plugin:jar:3.35.0 -> com.sap.cloud.sdk.plugins:usage-analytics:jar:[3.35.0,)\r\n\tat org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:109)\r\n\tat org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:332)\r\n\tat org.eclipse.m2e.core.internal.embedder.MavenImpl.lambda$8(MavenImpl.java:1380)\r\n\tat org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)\r\n\tat org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:114)\r\n\tat org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1379)\r\n\tat org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:54)\r\n\tat org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:135)\r\n\tat org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:169)\r\n\tat org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)\r\n\tat org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:114)\r\n\tat org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)\r\n\tat org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:114)\r\n\tat org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:105)\r\n\tat org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)\r\n\tat org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:153)\r\n\tat org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:101)\r\n\tat org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:88)\r\n\tat org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:197)\r\n\tat org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:845)\r\n\tat org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)\r\n\tat org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:228)\r\n\tat org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:276)\r\n\tat org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:329)\r\n\tat org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)\r\n\tat org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:332)\r\n\tat org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:384)\r\n\tat org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:405)\r\n\tat org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)\r\n\tat org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)\r\n\tat org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)\r\nCaused by: org.apache.maven.plugin.PluginResolutionException: Plugin com.sap.cloud.sdk.plugins:usage-analytics-maven-plugin:3.35.0 or one of its dependencies could not be resolved: Failed to collect dependencies at com.sap.cloud.sdk.plugins:usage-analytics-maven-plugin:jar:3.35.0 -> com.sap.cloud.sdk.plugins:usage-analytics:jar:[3.35.0,)\r\n\tat org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:217)\r\n\tat org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:152)\r\n\tat org.eclipse.m2e.core.internal.project.registry.EclipsePluginDependenciesResolver.resolve(EclipsePluginDependenciesResolver.java:61)\r\n\tat org.apache.maven.plugin.internal.DefaultMavenPluginManager.createPluginRealm(DefaultMavenPluginManager.java:404)\r\n\tat org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm(DefaultMavenPluginManager.java:374)\r\n\tat org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm(DefaultBuildPluginManager.java:234)\r\n\tat org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:105)\r\n\t... 30 more\r\nCaused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at com.sap.cloud.sdk.plugins:usage-analytics-maven-plugin:jar:3.35.0 -> com.sap.cloud.sdk.plugins:usage-analytics:jar:[3.35.0,)\r\n\tat org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:291)\r\n\tat org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:284)\r\n\tat org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:205)\r\n\t... 36 more\r\nCaused by: org.eclipse.aether.resolution.VersionRangeResolutionException: No versions available for com.sap.cloud.sdk.plugins:usage-analytics:jar:[3.35.0,) within specified range\r\n\tat org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.filterVersions(DefaultDependencyCollector.java:654)\r\n\tat org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:397)\r\n\tat org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:365)\r\n\tat org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process(DefaultDependencyCollector.java:352)\r\n\tat org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)\r\n\t... 38 more\r\n",
	"source": "Java",
	"startLineNumber": 127,
	"startColumn": 22,
	"endLineNumber": 127,
	"endColumn": 32
}`

If I comment following in the pom.xml, things do not complain anymore, and I can run the project : 
```
<plugin>
                <groupId>com.sap.cloud.sdk.plugins</groupId>
                <artifactId>usage-analytics-maven-plugin</artifactId>
...
```

My JDK is : 
```
openjdk version "11.0.9.1" 2020-11-05 LTS
OpenJDK Runtime Environment SapMachine (build 11.0.9.1+1-LTS-sapmachine)
OpenJDK 64-Bit Server VM SapMachine (build 11.0.9.1+1-LTS-sapmachine, mixed mode)
```

Is it possible to fix that somehow in a better way? I have no idea, if what I did does not have any side effects.

It also complains about "The field Charsets.UTF_8 is deprecated" in the HelloWorldControllerTest.java : is there a way to fix it in your archetype?

There is also a warning saying "Build path specifies execution environment JavaSE-1.8. There are no JREs installed in the workspace that are strictly compatible with this environment. ". From what I found, is that there is a hardcoded value of 1.8 in the pom.xml : 

`        <java.version>1.8</java.version>`

Changing the value to "11" did not helped much :-(. Would it be possible for you to update the tutorial and explain what modifications must be done in my files, to support Java 11 "out of the box" and avoid the warnings?

Thx!

**Comment by Emdee89** [comment]
Hi @billgatesfan would you mind attaching the full build output here as a log file?

**Comment by billgatesfan** [comment]
Hi @Emdee89, 

would that suit your needs? :

> [INFO] Error stacktraces are turned on.
> [INFO] Scanning for projects...
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Build Order:
> [INFO] 
> [INFO] myArtifactId - Root                                                [pom]
> [INFO] myArtifactId - Application                                         [jar]
> [INFO] myArtifactId - Integration Tests                                   [jar]
> [INFO] 
> [INFO] -----------------------< myGroupId:myArtifactId >-----------------------
> [INFO] Building myArtifactId - Root 1.0-SNAPSHOT                          [1/3]
> [INFO] --------------------------------[ pom ]---------------------------------
> [INFO] 
> [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ myArtifactId ---
> [INFO] 
> [INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (SAP Cloud SDK Project Structure Checks) @ myArtifactId ---
> [INFO] 
> [INFO] -----------------< myGroupId:myArtifactId-application >-----------------
> [INFO] Building myArtifactId - Application 1.0-SNAPSHOT                   [2/3]
> [INFO] --------------------------------[ jar ]---------------------------------
> [INFO] 
> [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ myArtifactId-application ---
> [INFO] Deleting C:\hv\myartifactid\application\target
> [INFO] 
> [INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (SAP Cloud SDK Project Structure Checks) @ myArtifactId-application ---
> [INFO] 
> [INFO] --- jacoco-maven-plugin:0.8.6:prepare-agent (prepare-agent) @ myArtifactId-application ---
> [INFO] argLine set to -javaagent:C:\\Users\\myuser\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.6\\org.jacoco.agent-0.8.6-runtime.jar=destfile=C:\\hv\\myartifactid\\application\\target\\coverage-reports\\jacoco.exec,includes=*,excludes=org.apache.* -Xmx1024m -Dorg.slf4j.simpleLogger.defaultLogLevel=info
> [INFO] 
> [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ myArtifactId-application ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] Copying 3 resources
> [INFO] 
> [INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ myArtifactId-application ---
> [INFO] Changes detected - recompiling the module!
> [INFO] Compiling 4 source files to C:\hv\myartifactid\application\target\classes
> [INFO] 
> [INFO] --- usage-analytics-maven-plugin:3.35.0:usage-analytics (default) @ myArtifactId-application ---
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary for myArtifactId - Root 1.0-SNAPSHOT:
> [INFO] 
> [INFO] myArtifactId - Root ................................ SUCCESS [  1.091 s]
> [INFO] myArtifactId - Application ......................... FAILURE [  6.427 s]
> [INFO] myArtifactId - Integration Tests ................... SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  8.152 s
> [INFO] Finished at: 2021-01-04T17:06:55+01:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal com.sap.cloud.sdk.plugins:usage-analytics-maven-plugin:3.35.0:usage-analytics (default) on project myArtifactId-application: Execution default of goal com.sap.cloud.sdk.plugins:usage-analytics-maven-plugin:3.35.0:usage-analytics failed: Plugin com.sap.cloud.sdk.plugins:usage-analytics-maven-plugin:3.35.0 or one of its dependencies could not be resolved: Failed to collect dependencies at com.sap.cloud.sdk.plugins:usage-analytics-maven-plugin:jar:3.35.0 -> com.sap.cloud.sdk.plugins:usage-analytics:jar:[3.35.0,): No versions available for com.sap.cloud.sdk.plugins:usage-analytics:jar:[3.35.0,) within specified range -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.sap.cloud.sdk.plugins:usage-analytics-maven-plugin:3.35.0:usage-analytics (default) on project myArtifactId-application: Execution default of goal com.sap.cloud.sdk.plugins:usage-analytics-maven-plugin:3.35.0:usage-analytics failed: Plugin com.sap.cloud.sdk.plugins:usage-analytics-maven-plugin:3.35.0 or one of its dependencies could not be resolved: Failed to collect dependencies at com.sap.cloud.sdk.plugins:usage-analytics-maven-plugin:jar:3.35.0 -> com.sap.cloud.sdk.plugins:usage-analytics:jar:[3.35.0,)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
>     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
>     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
>     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
>     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
>     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
>     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
>     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke (Method.java:566)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
> Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.sap.cloud.sdk.plugins:usage-analytics-maven-plugin:3.35.0:usage-analytics failed: Plugin com.sap.cloud.sdk.plugins:usage-analytics-maven-plugin:3.35.0 or one of its dependencies could not be resolved: Failed to collect dependencies at com.sap.cloud.sdk.plugins:usage-analytics-maven-plugin:jar:3.35.0 -> com.sap.cloud.sdk.plugins:usage-analytics:jar:[3.35.0,)
>     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:109)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
>     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
>     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
>     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
>     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
>     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
>     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
>     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke (Method.java:566)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
> Caused by: org.apache.maven.plugin.PluginResolutionException: Plugin com.sap.cloud.sdk.plugins:usage-analytics-maven-plugin:3.35.0 or one of its dependencies could not be resolved: Failed to collect dependencies at com.sap.cloud.sdk.plugins:usage-analytics-maven-plugin:jar:3.35.0 -> com.sap.cloud.sdk.plugins:usage-analytics:jar:[3.35.0,)
>     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal (DefaultPluginDependenciesResolver.java:217)
>     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve (DefaultPluginDependenciesResolver.java:152)
>     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.createPluginRealm (DefaultMavenPluginManager.java:404)
>     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm (DefaultMavenPluginManager.java:374)
>     at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm (DefaultBuildPluginManager.java:234)
>     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:105)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
>     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
>     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
>     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
>     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
>     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
>     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
>     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke (Method.java:566)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
> Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at com.sap.cloud.sdk.plugins:usage-analytics-maven-plugin:jar:3.35.0 -> com.sap.cloud.sdk.plugins:usage-analytics:jar:[3.35.0,)
>     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies (DefaultDependencyCollector.java:291)
>     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies (DefaultRepositorySystem.java:284)
>     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal (DefaultPluginDependenciesResolver.java:205)
>     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve (DefaultPluginDependenciesResolver.java:152)
>     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.createPluginRealm (DefaultMavenPluginManager.java:404)
>     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm (DefaultMavenPluginManager.java:374)
>     at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm (DefaultBuildPluginManager.java:234)
>     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:105)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
>     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
>     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
>     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
>     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
>     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
>     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
>     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke (Method.java:566)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
> Caused by: org.eclipse.aether.resolution.VersionRangeResolutionException: No versions available for com.sap.cloud.sdk.plugins:usage-analytics:jar:[3.35.0,) within specified range
>     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.filterVersions (DefaultDependencyCollector.java:654)
>     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency (DefaultDependencyCollector.java:397)
>     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency (DefaultDependencyCollector.java:365)
>     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process (DefaultDependencyCollector.java:352)
>     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies (DefaultDependencyCollector.java:254)
>     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies (DefaultRepositorySystem.java:284)
>     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal (DefaultPluginDependenciesResolver.java:205)
>     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve (DefaultPluginDependenciesResolver.java:152)
>     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.createPluginRealm (DefaultMavenPluginManager.java:404)
>     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm (DefaultMavenPluginManager.java:374)
>     at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm (DefaultBuildPluginManager.java:234)
>     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:105)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
>     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
>     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
>     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
>     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
>     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
>     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
>     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke (Method.java:566)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
> [ERROR] 
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
> [ERROR] 
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <args> -rf :myArtifactId-application
>

**Comment by billgatesfan** [comment]
...as for the rest, here a screenshot of what I see : https://pasteboard.co/JI6tHYT.png
I am still trying to find where this output is stored, or who generates it.

**Comment by Emdee89** [comment]
Hi @billgatesfan,

## About the build issue

I cannot reproduce the build failure on my machine. Can you tell me how exactly you invoke the build? On the terminal or with a tool? Which Maven command exactly is invoked? Have you build the whole app initially after generating the project with `mvn clean install`?

So far my assumption is that you had now downloaded all dependencies properly into your local Maven repository (which would be done by building the app fully with the given command).

## About the JDK version issue
Changing the Maven property `java.version´ from `1.8` to `11` should do the trick. This [Stackoverflow answer](https://stackoverflow.com/a/54468127/4790468) explains some background (despite not entirely related to your case).

What exactly is the problem with using `11`?

## About the deprecated Java field
For the record: The warning message in VS code reads `The field Charsets.UTF_8 is deprecated` in `HelloWorldControllerTest.java`.
This is indeed deprecated as per the [Javadoc](https://commons.apache.org/proper/commons-codec/apidocs/deprecated-list.html). We will consider replacing that with the alternative. Please note that this is not an issue and does not block you from continuing.

**Comment by billgatesfan** [comment]
Build was done in a simple Powershell window, the above output is from the command "mvn clean package".

My Maven : 
> PS C:\> mvn -V
> C:\
> Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
> Maven home: C:\Users\myuser\source\repos\maven\apache-maven-3.6.3\bin\..
> Java version: 11.0.9.1, vendor: SAP SE, runtime: C:\Program Files\SapMachine\JDK\11
> Default locale: en_US, platform encoding: Cp1252
> OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

And for Java version, I realized today, that I forgot in manifest.yml the _JBP_CONFIG_COMPONENTS: "jres: ['com.sap.xs.java.buildpack.jdk.SAPMachineJDK']"_ env variable, so all good. Previously, the container crashed after "cf push" with : 
>    2021-01-06T16:36:25.47+0100 [APP/PROC/WEB/0] ERR Exception in thread "main" java.lang.UnsupportedClassVersionError: myGroupId/Application has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by Emdee89** [comment]
@billgatesfan Your Maven version looks recent and hence OK.

Such buildings problems are typically difficult to reproduce. I am just letting it run on my own machine with an empty Maven cache, but it just succeeded. 

Summary: I cannot reproduce your original build failure and hence the only reasonable recommendation I can give you is to retry the build. Oftentimes Maven can fetch the missing dependency then during the second build, while the reason for the first failure remains unclear.

**Comment by billgatesfan** [comment]
You were correct, I manage to delete the .m2 folder or sth like this, then again an _mvn package_ and it did the job. I didn't suspect to hit such weird Maven issues when I start a project for first time... Thx anyway for great help, and sorry for this annoyance :-).
