### ISSUE TITLE
Create a Business Service with Node.js Using Visual Studio Code

### ISSUE THREAD

**Issue by ivanmir** [SAPDocuments/Issues#260]
Tutorials: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html
--------------------------

I was not able to perform a cds deploy with the installation of sqlite3 command.
I throws me an error. I downgraded this module with the following command and now it works:
npm i sqlite3@4.2.0

Please advise.

**Comment by iwonahahn** [comment]
Hi @ivanmir,
Which version of `@sap/cds-dk` are you using?
Can you please provide the output of `cds -v`?
Best regards,
Iwona

**Comment by ivanmir** [comment]
Sure,

@sap/cds: 4.6.5
@sap/cds-compiler: 1.50.0
@sap/cds-dk: 3.5.1
@sap/cds-foss: 2.2.1
@sap/cds-runtime: 2.9.1
Node.js: v12.18.4
home: C:\Users\<my-id>\AppData\Local\nvs\node\12.18.4\x64\node_modules\@sap\cds-dk\node_modules\@sap\cds

**Comment by iwonahahn** [comment]
Hi @ivanmir,

when talking about error messages, please provide the error log or error message and the content of your `package.json`.

Thanks a lot and best regards,
Iwona

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions and want to continue the conversation with Iwona, feel free to reopen the issue.
