### ISSUE TITLE
Use OData Annotations to Add CRUD Functionality to an MDK App

### ISSUE THREAD

**Issue by boghyon** [SAPDocuments/Issues#261]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-dev-kit-annotations.html
--------------------------

I followed the above tutorial which is very well done. As an experiment, I also deployed the app as a web app.

In the web app, when searching by e.g. `Mousepad`, I see three entries.
![MDK web app filter OData annotation list Products by "Mousead"](https://user-images.githubusercontent.com/12143247/112235312-ae982680-8c3e-11eb-90b2-50cb376520dd.png)

With <code><strong>m</strong>ousepad</code>, I see no results.
![MDK web app filter OData annotation list Products by "mousead"](https://user-images.githubusercontent.com/12143247/112235444-f28b2b80-8c3e-11eb-84ce-01deb188a058.png)

On the native Android app, the case sensitivity doesn't seem to matter (`Mousepad` | `mousepad`). There are always three entries.

Are there other differences and limitations compared to native apps when it comes to pages generated via OData annotations?

**Comment by jitendrakansal** [comment]
@boghyon for the mobile app, is it offline enabled? For offline, search is case insensitive.
i just tested the app in the online mode (as per tutorial)  in both mobile client and web runtime and it works as expected. Search is CASE-SENSITIVE. 

For an online app, search returns the dataset as how backend is returning . you can test it in the browser. 
Click the launch icon for the SampleServiceV2 destination in the Mobile Services app. 
e.g. /SampleServiceV2/Products?$filter=Category eq 'Mousepads' >> returns dataset but 
/SampleServiceV2/Products?$filter=Category eq 'mousepads' >>returns no dataset

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by boghyon** [comment]
@jitendrakansal
> For offline, search is case insensitive.

This seems to be in contradiction to what @billfroelich suggested at https://answers.sap.com/answers/13353960/view.html. There, sorting is apparently case sensitive and needs to be explicitly configured.

Or is is that only the _filtering_ is case **in**sensitive offline while _sorting_ is case sensitive?

___

How can we make sure that `$filter` as well as `$orderby` requests are all case insensitive in MDK? In UI5, filter instances can have the [option `caseSensitive`](https://github.com/SAP/openui5/blob/3f07ee04bbf28c8323b874f5f6f321681c381ed8/src/sap.ui.core/src/sap/ui/model/Filter.js#L118).

@MichaelCzcz  Please reopen this issue. Issue authors cannot reopen their issues by themselves if they're not collaborators of this repo.

**Comment by billfroelich** [comment]
@boghyon I also posted this on the community question.

MDK offline searching automatically applies a tolower() wrapper to search terns to force case insensitive searching. Offline sorting however is controlled by the db collation by default and overridden by the offline flag setting mentioned above.

For Online applications, not all odata sources have implemented the tolower function. To ensure the widest support MDK online does not include the tolower wrapper by default. You can customize this with a rule in your query options if your online service does support tolower() or an equivalent function to allow for case insensitive searching.

The behavior you are seeing is the expected behavior at this time.

**Comment by boghyon** [comment]
@jitendrakansal It would be nice if the tutorial could be enhanced with:
 * the information discussed here about the case sensitivity for different cases like online (e.g. web app), offline-enabled (MDK Client), filtering, and sorting.
 * Running the app as a web app (Step 7)

**Comment by jitendrakansal** [comment]
@boghyon thanks for your feedback.

I have updated the tutorial adding the web part. 
We'll see how we can cover the above discussioon in documentation.

fyi - We have a backlog to enhance the search mode for OData service for a possible future release.
