### ISSUE TITLE
Add User Authentication to Your Application (SAP HANA Cloud)

### ISSUE THREAD

**Issue by freddycollaoblas-cjg** [SAPDocuments/Issues#262]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-add-authentication.html
--------------------------

So far I have everything OK, (xsuaa works perfect) I have no problems in business application studio, but when performing a deploy, it gives me errors, what is the correct way to do it? by mta it fails me, and cf push too.

Please your support

**Comment by freddycollaoblas-cjg** [comment]
![image](https://user-images.githubusercontent.com/80067942/112308975-84b42380-8c81-11eb-899a-ef422f0147f1.png)
![image](https://user-images.githubusercontent.com/80067942/112309003-91387c00-8c81-11eb-8c8d-497e2ba2416e.png)

As you can see, the data that I get from the main path and from the app path, works correctly with the authorizations, but I want to deploy this project. But in the deployment, when staying in the cast in the cloud, it gives me an error 500 or the mta gives an error in the srv part, etc. etc. Please your support, Thank you!

**Comment by jung-thomas** [comment]
You say that when you deploy you have errors.  You mean you are building an MTAR and deploying the application to Cloud Foundry? If so what errors.  The screenshots you added show running from the Business Application Studio, but you said that works correctly, right.   So what exactly are the errors you are getting?

**Comment by freddycollaoblas-cjg** [comment]
![image](https://user-images.githubusercontent.com/80067942/112316469-e5475e80-8c89-11eb-8c24-815f4889e448.png)
![image](https://user-images.githubusercontent.com/80067942/112316717-22abec00-8c8a-11eb-8ec2-37186cc743ab.png)
![image](https://user-images.githubusercontent.com/80067942/112316811-38211600-8c8a-11eb-9848-3be72dfab1d4.png)
![image](https://user-images.githubusercontent.com/80067942/112316857-42431480-8c8a-11eb-8e9a-3df71abf92f0.png)
![image](https://user-images.githubusercontent.com/80067942/112316899-48d18c00-8c8a-11eb-9500-c749eb18b777.png)

**Comment by jung-thomas** [comment]
Please note that you are outside the scope of this tutorial.  This tutorial does not cover the deployment of the application via MTAR. Additional steps and adjustments to the mta.yaml specifically for the UI module beyond what the wizard generated would be necessary but are not part of this tutorial. 

I could consider adding the deployment task as a separate tutorial in the future. In the mean time I'd have to refer you to other materials that cover the deployment process.

**Comment by freddycollaoblas-cjg** [comment]
Perfect Thomas, it seemed to me that something additional was missing, since in BAS everything works correctly, could you support me on how to perform the deployment with additional material or some documentation? I urgently need to deploy this project base

Thanks a lot !

**Comment by jung-thomas** [comment]
There is nothing specific to this particular tutorial for deployment yet.  I'll have to consider that for a future enhancement to the tutorial. However I could point you generally to the CAP documentation on deployment:
https://cap.cloud.sap/docs/advanced/deploy-to-cloud

The only issue is that the CAP documentation doesn't really address the full stack application that contains Fiori deployment as well. There you might want to look through some of the separate Fiori deployment materials. 

I certainly see the need here for a combined docu or tutorial that shows the whole thing, but I'm afraid I just don't have that or know where it might exist to send you to it.
