### ISSUE TITLE
Write and Publish Blog Posts on SAP Community

### ISSUE THREAD

**Issue by radhikachhabra6** [SAPDocuments/Issues#263]
Tutorials: https://developers.sap.com/tutorials/community-blogging.html
--------------------------

The last question for Step 9 has no right answer.

Here's the question:-

Which of these blogging missions is available?

Blogging Maestro

Grand Master Blogger

Ripple Effect

Gold Star

Gone Blogger Gone

**Correct answer is "Grand master blogger" and "ripple effect". But this tutorial isn't accepting the correct answers.** Please correct this error.

Regards
Radhika

**Comment by lenastodal** [comment]
Thanks @radhikachhabra6 for letting us know. The issue is fixed.
