### ISSUE TITLE
Add User Authentication to Your Application (SAP HANA Cloud)

### ISSUE THREAD

**Issue by binpath** [SAPDocuments/Issues#265]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-add-authentication.html
--------------------------
I finished with the tutorial, but in need to deploy this to cloudFoundry so the user can use the app and how should i do the cf push? Or how to deploy the mta with full project.

[2021-03-24 16:41:05] ERROR could not package the "fichacliente_ui_deployer" module when archiving: write /home/user/projects/fichacliente/.fichacliente_mta_build_tmp/fichacliente_ui_deployer/data.zip: no space left on device
make: *** [Makefile_20210324163651.mta:37: fichacliente_ui_deployer] Error 1
Error: could not build the MTA project: could not execute the "make -f Makefile_20210324163651.mta p=cf mtar= strict=true mode=" command: exit status 2

kind regards, 
Cesar Felce

**Comment by jung-thomas** [comment]
The deployment is not part of the scope of this tutorial. We can consider adding it in the future.  But for now I'd refer you to other materials that cover the deployment aspect.
https://cap.cloud.sap/docs/advanced/deploy-to-cloud

The running out of disk space is a current a bug in the MBT tool. You can work around it for now by adding

build-parameters:
      ignore: [".*/"]
      
 To the   - name: MyHANAApp_ui_deployer section of the mta.yaml.  
 
 I will say that probably further adjustments to the UI portion beyond what the wizard generated is probably needed.

**Comment by binpath** [comment]
Thanks Jung
Like this in the MTA?
`- name: fichacliente-db-deployer
    type: hdb
    path: db
    requires:
      - name: fichacliente-db
        properties: 
          TARGET_CONTAINER: ~{hdi-container-service}
      
      - name: nsagro64-grantor
        group: SERVICE_REPLACEMENTS                 
        properties: 
          key: nsagro64-service
          service: ~{nsagro64-grantor-service}
    parameters:
      buildpack: nodejs_buildpack
    build-parameters:
      ignore: [".*/"]`
      
 ok, but my client is waiting for the deployment, i know that is not the scope the tutorial, but is the only information found with your structure of the project. 
 
 kind regards, 
 Cesar

**Comment by binpath** [comment]
@jung-thomas
I have added in the mta 
`- name: fichacliente_ui_deployer
    type: com.sap.application.content
    path: .
    build-parameters:
      ignore: [".*/"]`
      
 I'm still facing the issue no space.
 
![image](https://user-images.githubusercontent.com/576680/112358215-e50d8a00-8cae-11eb-8438-f56e43e59d37.png)

I don't what to disrespect, but I'm surprised that the "Mission: Combine CAP with HANA to create Full-Stack Applications" doesn't have in the scope the deployment to production. Please i don't know how to deliver.

kinds regards,

**Comment by binpath** [comment]
Hi @jung-thomas, 
You did an awesome work on this tutorials, I have learned too much with your work. 

I could deploy it! But i had to use the original structure. With a tweak using the .env file I was able to do a cds build and then deploy with [url](https://cap.cloud.sap/docs/advanced/deploy-to-cloud) that you provided. 

Thank you again!
kind regards, 
@binpath
