### ISSUE TITLE
Start Your MDK Application in the Editor

### ISSUE THREAD

**Issue by advit-ramesh** [SAPDocuments/Issues#267]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-dev-kit-offline-app.html
--------------------------

Write here what you need help with ...

I am unable to deploy the application on Mobile Services I get the error message as 

Deploy failed. Detail: Failed with response code:404 detail:Not Found.

![image](https://user-images.githubusercontent.com/29966401/112405450-29645d00-8d77-11eb-8946-65b6dc0836a0.png)

The Web application seem to deploy but it reflects the same error when I open the application. Screen grab below 

![image](https://user-images.githubusercontent.com/29966401/112405817-e3f45f80-8d77-11eb-9f58-de3684649771.png)

As per the below log 
https://blogs.sap.com/2018/03/15/troubleshooting-tips-for-mobile-development-kit/#404

I checked the destination on the BTP platform . I have configured the destination as per the steps mentioned in the below link
https://developers.sap.com/tutorials/cp-mobile-dev-kit-ms-setup.html

I get 400 status when I check connection from the destination screen. 

![image](https://user-images.githubusercontent.com/29966401/112406027-464d6000-8d78-11eb-96c6-4e7f8b814c25.png)

Can you please let me know where I could be going wrong. 

Appreciate your Support
Regards
Advit

**Comment by advit-ramesh** [comment]
Hello Team,

I was wondering if you had a chance to look into this

**Comment by thecodester** [comment]
@jitendrakansal Do you have an update?

**Comment by jitendrakansal** [comment]
@advit-ramesh can you once check the URL? I see that URL has some additional info which is not correct. 
![image](https://user-images.githubusercontent.com/31536700/114680457-823b6b80-9d0d-11eb-87b9-7062c21ead23.png)

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
