### ISSUE TITLE
 Create Instance of SAP Event Mesh

### ISSUE THREAD

**Issue by ph-wert** [SAPDocuments/Issues#269]
Tutorials: https://developers.sap.com/tutorials/cp-enterprisemessaging-instance-create.html
--------------------------
Hi Pradeep. we could not follow the tutorial because "default" plan is not working, we got the "Lite" JSON (see below) from Martin Bachmann for the "dev" plan. maybe you want to update it. thanks
Pascal

{
	"emname": "<your-emname>",
	"options": {
		"management": true,
		"messagingrest": true
	}
}

**Comment by pradeeppanda-sap** [comment]
Hi,
  As default plan works only in the productive environment, hence as shown in the attached document, to be able to perform the steps mentioned in this tutorial, one needs to have Customer or Partner license.

![image](https://user-images.githubusercontent.com/51952722/112833430-56d14380-90b4-11eb-9d56-9c89d6e3669f.png)

If you are trying to follow this tutorial in Trial environment,  it is not possible as default plan is not available in the trial environment. Hence can you please try it in the productive environment?
Of course as Martin mentioned, if you are trying with dev environment, the json example which you have shared here should work fine.
