### ISSUE TITLE
Reuse a CAP Java Service

### ISSUE THREAD

**Issue by markobojkic** [SAPDocuments/Issues#27]
Tutorial: https://developers.sap.com/tutorials/cp-cap-java-service-reuse.html
--------------------------

Hello.  :) 
At Step 2 of Tutorial 5, when I run following command:

**npm install $(npm pack ../products-service -s)**

A file named "products-service-cds-1.0.0.tgz" is being created in root folder of **bookstore** project (not "**sap-capire-products-1.0.0.tgz**" like in your Tutorial)".

Therefore, in bookstore **package.json** file, auto-created dependency looks like this and not like in your Tutorial ("**@sap/capire-products: "file:sap-capire-products-1.0.0.tgz"**"):

{
    "name": "bookstore-cds",
    "version": "1.0.0",
    "description": "Generated by cds-services-archetype",
    "license": "ISC",
    "repository": "<Add your repository here>",
    **"dependencies": {
        "products-service-cds": "file:products-service-cds-1.0.0.tgz"
    }**
}

Therefore, in **schema.cds** file of db folder I have following issue when trying to reference sap.capire.products.Products:

using { sap.capire.products.Products } from **'@sap/capire-products'**; 

Issue that occurs: _Cannot find package 'products-service-cds'CDS (compiler)(file-unknown-package)_

I have also tried renaming **@sap/capire-products** to **products-service-cds** (since it is written with that name in my package.json), but it doesn't help either.

Hope you can help me with this one. :)

**Comment by markobojkic** [comment]
Little update.
I have modified _schema.cds_ of bookstore project, but I have issue in this line of code:

_using { sap.capire.products.Products } from '../products-service-cds-1.0.0.tgz';_

And the issue is -->  **Artifact "sap.capire.products" has not been found**

I have looked into the node_modules folder, and products-service-cds folder exists over there, which I suppose means that following command was run sucessfully:

npm install $(npm pack ../products-service -s)

But I still don't know why it won't find artifact "sap.capire.products" ?

**Comment by iwonahahn** [comment]
@beckermarc Can you take a look at the issue please? Thanks a lot.

**Comment by beckermarc** [comment]
Hi @markobojkic,

please check that you have followed step nine of the previous tutorial part `Create a Reusable Service` correctly: https://developers.sap.com/tutorials/cp-cap-java-reusable-service.html. 
It seems like you did not follow this, as you did not change the name from `products-service-cds` to `@sap/capire-products` as outlined there. Also, in case the index.cds file is missing, that is created in that step, you might run into these issues.

Please make sure that you delete the `products-service-cds-1.0.0.tgz` and the node_modules folder in the `bookstore` project, before repeating the steps in the `Reuse a CAP Java Service` part of the tutorial.

The part `from '../products-service-cds-1.0.0.tgz';` is not correct, you can not import directly from a tgz file, but only from the modules installed into your node_modules folder. Please follow the steps as outlined in the tutorial and use `using { sap.capire.products.Products } from '@sap/capire-products';`, after you have ensured that you performed the steps I mentioned earlier.

Best regards,
Marc

**Comment by iwonahahn** [comment]
Hi,

Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue.
If you still have questions, feel free to reopen the issue.

Best regards,
Iwona
