### ISSUE TITLE
Configure Business Rules, Workflow and Process Visibility

### ISSUE THREAD

**Issue by MaxSychevskiy** [SAPDocuments/Issues#270]
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-configure.html
--------------------------

I'm stuck with Bad Gateway issue. The suggested resolution is not applicable for me as I don't have 2FA user. I have checked all passwords and all seems to be fine.

**Comment by ArchanaShukla** [comment]
This should not happen Max. Can you raise the ticket on LOD-BPM-RUL component with your trial details and the steps you are trying.

**Comment by ArchanaShukla** [comment]
Closing this issue, we will track it through the other ticketing channel where you have raised the issue. If needed, reopen this again.
