### ISSUE TITLE
Set Up Integration Suite Trial - Booster

### ISSUE THREAD

**Issue by yrlgithub** [SAPDocuments/Issues#271]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html
--------------------------

Write here what you need help with ...

When I click on Booster, I don't see "Enable Integration Suite" tile or anything close to this...

**Comment by Karunaharan** [comment]
Hi @yrlgithub, could you please check now. Booster is visible in the BTP trial account.
