### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by LePanchi** [SAPDocuments/Issues#272]
Tutorials: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html
--------------------------
In Step 4 (Data Source and Service Selection), I can't see a Service. Instead, the system requests a Service username and a Service Password. 

The tutorial:
![image](https://user-images.githubusercontent.com/63903948/112629620-73f3e100-8e2c-11eb-926c-2d81a4e080e8.png)

BAS:
![image](https://user-images.githubusercontent.com/63903948/112629671-7e15df80-8e2c-11eb-940c-dafbe95b90d6.png)

**Comment by raz-korn** [comment]
Hi @LePanchi ,

Please refer to [issue 36](https://github.com/SAPDocuments/Issues/issues/36).
Also make sure that you have a user for ES5 per the prerequisite in the following [tutorial](https://developers.sap.com/tutorials/cp-portal-cloud-foundry-gateway-connection.html) that is part of this tutorial group.

Regards - Raz

**Comment by raz-korn** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue.
If you still have questions and want to continue the conversation, feel free to reopen the issue.
