### ISSUE TITLE
Use the SAP Cloud SDK in the SAP Cloud Application Programming Model

### ISSUE THREAD

**Issue by LTallarita** [SAPDocuments/Issues#273]
Tutorials: https://developers.sap.com/tutorials/cloudsdk-integrate-cap.html
--------------------------

In Step 1 number 3. of the tutorial you should run:
![image](https://user-images.githubusercontent.com/79846692/112636258-1d42d300-8e3d-11eb-868b-e1baca40f5d0.png)

However, this command causes problems in later steps. 
On the one hand, the necessary property "DgroupId=SomeValue" is missing in the command. And on the other hand the given package name is not correct, because packages must not contain special characters. 

So the command should look something like this:

`mvn archetype:generate -DarchetypeArtifactId=cds-services-archetype -DarchetypeGroupId=com.sap.cds -DarchetypeVersion=RELEASE **-DartifactId=capbusinessservice -DgroupId=com.sap.cds**`

Additionally, the class provided in step 5 is missing the package of the class and all the import statements. The class is (in my opinon) presented as "complete" even though it is not. I think that it is hard for a customer or a developer who may not have much knowledge of Java development to know that he still has to add these himself. In addition, the name of the file should also be given as BusinessPartnerReadListener**.java** and instructions should be given where to create this file.

Thanks

**Comment by MatKuhr** [comment]
Hi @LTallarita, thanks for reaching out!

Regarding the group ID: That is actually not required to be in the command itself. Maven should ask you on the command line to input a value. But it is indeed required and I think we can provide a sensible default, so I'll change the command to contain a default value.

Regarding the imports: Actually we leave out the import statements intentionally to not have so much boiler plate code. Also most IDEs will create the `package` declaration automatically when creating the file, and adding the imports is also something IDEs do pretty fast. 

That's why we felt the snippet is more clear if we omit the boiler plate.

**Comment by LTallarita** [comment]
Hi @MatKuhr,

> Regarding the group ID: That is actually not required to be in the command itself. Maven should ask you on the command line to input a value. But it is indeed required and I think we can provide a sensible default, so I'll change the command to contain a default value.

Unfortunately, Maven did not ask that in my case and in the case of my colleague. But that would explain it then...

> Regarding the imports: Actually we leave out the import statements intentionally to not have so much boiler plate code. Also most IDEs will create the package declaration automatically when creating the file, and adding the imports is also something IDEs do pretty fast.

I agree with you that it's probably clearer without all the import statements. But then maybe a disclaimer wouldn't hurt, in case the IDE doesn't do it automatically ;)

Thank you anyway for your feedback and help!

**Comment by MatKuhr** [comment]
Interesting, maybe you are on a different maven version and it behaves differently? I just tested it with:
```
$ mvn -v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
```

And with that it worked just fine

**Comment by LTallarita** [comment]
I was using the Business Application Studio with: 
`Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T19:00:29Z)
Maven home: /usr/lib/maven`
I just tested again & still didn't get asked for the group ID.

I have now tested it on my local machine with Apache Maven 3.6.3 and there it works that I am asked for the group ID and the package name.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
