### ISSUE TITLE
Create a Basic Workflow in SAP Business Application Studio

### ISSUE THREAD

**Issue by mrtnstm** [SAPDocuments/Issues#274]
Tutorials: https://developers.sap.com/tutorials/cp-workflow-2-create-module-cf.html
--------------------------

Hi,

When working through the tutorial, I tried to run the "yo" command to get the workflow:

![image](https://user-images.githubusercontent.com/14940337/112716402-8599bf00-8ee6-11eb-8898-143b07223efc.png)

However, it seems the package @workflow/workflow Module is not available for me. Am I missing something, or is it no longer there?

**Comment by AstridHerbst** [comment]
Hi,
OK, so you are in your projects folder, and choose Terminal > New Terminal, and then:
yo
Select @workflow/workflow-module
Enter path to mta.yaml
Enter the module name, there is a proposed name in light grey
Enter the workflow name and description
No merge needed anymore

I have just retried this in and it still works although some steps are now a bit changed.
**************************************************
user: projects $ yo
? 'Allo! What would you like to do? @workflow/workflow Module

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo @workflow/workflow-module

? Module Name tescht
? Workflow Name test
? Workflow Description nix
   create mta.yaml
   create tescht/workflows/test.workflow
****************************************************

When creating your dev space, have you selected the additional Workflow Management extension?

Best regards,
Astrid

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
