### ISSUE TITLE
Set Up Integration Suite Trial

### ISSUE THREAD

**Issue by I044433** [SAPDocuments/Issues#277]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html
--------------------------

Hi,

The tutorial in 'Step 5: Automatically assign roles and create service instances using Booster' tells about using the Booster to assign roles and create instance.
![Booster-SAP-Int-Suite](https://user-images.githubusercontent.com/41268663/112794469-89fbde80-9084-11eb-84f4-219f40a4573a.png)

However, this tile is not available under the Booster section in the trial account. Kindly see the attached pic. Do we need to do something additional to enable this?
Thanks
Rohit

**Comment by Karunaharan** [comment]
Hi @I044433, could you please check now. Booster is visible in the BTP trial account.
