### ISSUE TITLE
Create an ABAP Core Data Services (CDS) View in SAP Cloud Platform, ABAP Environment

### ISSUE THREAD

**Issue by ThanosEfraimidis** [SAPDocuments/Issues#278]
Tutorials: https://developers.sap.com/tutorials/abap-environment-create-cds-mde.html
--------------------------

In Step 9 where code for CDS is displayed, lines 1-3 are repeated as lines 4-6. It didn't work for me until I removed the first 3 lines.

**Comment by julieplummer20** [comment]
Hi Thanos, 
Yes, sorry, copy and paste error.
I will fix this at once.
BR Julie.

**Comment by thecodester** [comment]
@julieplummer20 Please close this issue when you have updated tutorial.

**Comment by julieplummer20** [comment]
Hi Thanos,
I have closed the issue.
Please let me know if you have any other questions.
BR Julie.
