### ISSUE TITLE
Set Up the SAP Launchpad Service

### ISSUE THREAD

**Issue by Gyannini** [SAPDocuments/Issues#279]
Tutorials: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html
--------------------------

Hi!

Thanks for the great tutorial. But would like to share two very minor issues with it:
- The name of the service seems different now. Instead of **Launchpad Service** it is called **Portal**.
- The name of the role seems to be accordingly different: Instead of **Launchpad_Admin** role it seems to be called **Portal_admin** role.

Kind regards,

**Comment by LindsayBert** [comment]
Hi

I'm glad you liked the tutorials :)

The correct name is the SAP Launchpad service and the Launchpad_Admin role as is written in the tutorial.
Originally these tutorials were meant for the SAP Cloud Portal service but they were replaced by the SAP Launchpad service.

Thanks
Lindsay

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
