### ISSUE TITLE
Integrate Your SAPUI5 App into Your Launchpad Site

### ISSUE THREAD

**Issue by dazowens** [SAPDocuments/Issues#28]
Tutorial: https://developers.sap.com/tutorials/cp-launchpad-integrate-sapui5-app.html
--------------------------

Hi, I hope you can help me I have followed the tutorial and I think i have everything exactly how it should me done.

However, in step Step 2: Add your deployed SAPUI5 app to your content, point 4, I don't get anything appearing?

This is the contents of manifest.json :  ( I have added "sap.cloud" manually as it wasn't oringinally in the file, but this doesn't seem to make any difference :( )

{
    "_version": "1.12.0",
    "sap.app": {
        "id": "ns.BuinsessPartners",
        "type": "application",
        "i18n": "i18n/i18n.properties",
        "applicationVersion": {
            "version": "1.0.0"
        },
        "title": "{{appTitle}}",
        "description": "{{appDescription}}",
        "resources": "resources.json",
        "ach": "ach",
        "sourceTemplate": {
            "id": "html5moduletemplates.basicSAPUI5ApplicationProjectModule",
            "version": "1.40.12"
        },
        "crossNavigation": {
            "inbounds": {
                "intent1": {
                    "signature": {
                        "parameters": {},
                        "additionalParameters": "allowed"
                    },
                    "semanticObject": "Object",
                    "action": "display",
                    "title": "{{appTitle}}",
                    "info": "{{appTitle}}",
                    "subTitle": "{{appSubTitle}}",
                    "icon": "sap-icon://account"
                }
            }
        },
        "dataSources": {
            "mainService": {
                "uri": "sap/opu/odata/iwbep/GWSAMPLE_BASIC/",
                "type": "OData",
                "settings": {
                    "odataVersion": "2.0",
                    "localUri": "localService/metadata.xml"
                }
            }
        }
    },
    "sap.cloud": {
        "public": true,
        "service": "Demo"
    },
    "sap.ui": {
        "technology": "UI5",
        "icons": {
            "icon": "",
            "favIcon": "",
            "phone": "",
            "phone@2": "",
            "tablet": "",
            "tablet@2": ""
        },
        "deviceTypes": {
            "desktop": true,
            "tablet": true,
            "phone": true
        }
    },
    "sap.ui5": {
        "flexEnabled": false,
        "rootView": {
            "viewName": "ns.BuinsessPartners.view.Suppliers",
            "type": "XML",
            "async": true,
            "id": "Suppliers"
        },
        "dependencies": {
            "minUI5Version": "1.60.1",
            "libs": {
                "sap.ui.core": {},
                "sap.m": {},
                "sap.ui.layout": {}
            }
        },
        "contentDensities": {
            "compact": true,
            "cozy": true
        },
        "models": {
            "i18n": {
                "type": "sap.ui.model.resource.ResourceModel",
                "settings": {
                    "bundleName": "ns.BuinsessPartners.i18n.i18n"
                }
            },
            "": {
                "dataSource": "mainService",
                "preload": true,
                "settings": {
                    "defaultBindingMode": "TwoWay",
                    "defaultCountMode": "Inline",
                    "refreshAfterChange": false
                }
            }
        },
        "resources": {
            "css": [
                {
                    "uri": "css/style.css"
                }
            ]
        },
        "routing": {
            "config": {
                "routerClass": "sap.m.routing.Router",
                "viewType": "XML",
                "async": true,
                "viewPath": "ns.BuinsessPartners.view",
                "controlAggregation": "pages",
                "controlId": "app",
                "clearControlAggregation": false
            },
            "routes": [
                {
                    "name": "RouteSuppliers",
                    "pattern": "RouteSuppliers",
                    "target": [
                        "TargetSuppliers"
                    ]
                }
            ],
            "targets": {
                "TargetSuppliers": {
                    "viewType": "XML",
                    "transition": "slide",
                    "clearControlAggregation": false,
                    "viewId": "Suppliers",
                    "viewName": "Suppliers"
                }
            }
        }
    }
}

Kind Regards

Daz

**Comment by fjcarrasco** [comment]
Hello. Same problem. I have tryed everything with no results. Any progress? Thanks

**Comment by fjcarrasco** [comment]
According to the tutorial, in the manifiest you have to insert the code after "dataSources" section however according the manifiest you posted it is before "dataSources" section.

**Comment by dazowens** [comment]
> According to the tutorial, in the manifiest you have to insert the code after "dataSources" section however according the manifiest you posted it is before "dataSources" section.

Hi,  I tried it before and after it didn't make any difference.  I decided to delete my trail account and do everything again.  However, I now have an issue deploying applicactions to cf using the business application studio.  So I am in a worse state than before and haven't had chance to spend much time resolving it unfortunately to get back to the same position.  There does seem to be quite a few bugs/issues with the trail accounts :(

This issue is logged with the author of the tutorial, so hopefully they will respond at some point?

**Comment by fjcarrasco** [comment]
I also deleted my trail account and I did everything again with the same result. I haven't had problems deploying. 

Thanks

**Comment by fjcarrasco** [comment]
Hi, I have managed. Check this out 

https://blogs.sap.com/2021/01/13/business-application-studio-launchpad-services-in-cloud-foundry/comment-page-1/#comment-548549

**Comment by dazowens** [comment]
I deleted my trail account and followed the steps again and it works fine now. :)
