### ISSUE TITLE
Create Behavior Definition for Managed Scenario

### ISSUE THREAD

**Issue by cagooi88** [SAPDocuments/Issues#280]
Tutorials: https://developers.sap.com/tutorials/abap-environment-behavior.html
--------------------------

Write here what you need help with ...
Create/update/delete button are not visible due to previous tutorial 'Define and Expose a CDS-Based Travel Data Model' (https://developers.sap.com/tutorials/abap-environment-data-model.html#b96fde0e-332e-4c76-bd94-6075cd943989). On step 5 where annotation is provided for custom action 'Accept Travel' but the custom action is not mentioned in the behaviour definition file. Because of this, Fiori Element failed to render all the actions mentioned in the behaviour definition file.

**Comment by mervey45** [comment]
Hi,

there seems to be an issue with the annotation of the overall status. If you comment it out and activate your projection view. Then add it back again and activate it. It works. I will update this tutorial to have a better solution.

Best regards, 
Merve

**Comment by mervey45** [comment]
Hi @thecodester ,

I created following pull request for this change: #6640.

Best regards,
Merve
