### ISSUE TITLE
Build and Deploy Your SAP Fiori App to SAP Business Technology Platform

### ISSUE THREAD

**Issue by vikasgith** [SAPDocuments/Issues#281]
Tutorials: https://developers.sap.com/tutorials/appstudio-fioriapps-mta-build-deploy.html
--------------------------

Unable to get the HTML5 App in Content Explorer
Hi,
I am following steps in
https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Under Step 10, I had made changes as
src="https://sapui5.hana.ondemand.com/resources/sap-ui-core.js"

After executing command
user: FioriDemo $ cf html5-list -di FioriDemo-destination-service -u
Getting list of HTML5 applications available via destinations in org 1119c0a4trial / space dev as vikas.sreedharan@mindtree.com...
OK

name                 version   app-host-id                            service name   destination name              last changed                    url   
nsbusinesspartners   1.0.0     ed039a20-d016-4f8b-8c65-1d2758ac3890   BP             BP_FioriDemo_html_repo_host   Tue, 30 Mar 2021 07:39:32 GMT   https://1119c0a4trial.cpp.cfapps.eu10.hana.ondemand.com/614e8b49-606f-417c-84eb-b4f64b1eceac.BP.nsbusinesspartners-1.0.0/   

I get url as
https://1119c0a4trial.cpp.cfapps.eu10.hana.ondemand.com/614e8b49-606f-417c-84eb-b4f64b1eceac.BP.nsbusinesspartners-1.0.0/

Under Content Explorer->HTML5 Apps, I do not see the app
https://1119c0a4trial.dt.launchpad.cfapps.eu10.hana.ondemand.com/sites#Content-Manage?sap-app-origin-hint=

But in Cockpit under HTML5 Apps, I can see the app
https://cockpit.eu10.hana.ondemand.com/trial/#/globalaccount/6e4e1d89-2829-4dd8-bc28-2bae816322d0/subaccount/cf795110-0057-4985-ae6d-2ebb89017dbe/html5applications

https://1119c0a4trial.launchpad.cfapps.eu10.hana.ondemand.com/614e8b49-606f-417c-84eb-b4f64b1eceac.BP.nsbusinesspartners-1.0.0/index.html

The url generated using cf html5-list -di FioriDemo-destination-service -u and the one in Cockpit has a small difference.
cf url:https://1119c0a4trial.cpp.cfapps.eu10.hana.ondemand.com/614e8b49-606f-417c-84eb-b4f64b1eceac.BP.nsbusinesspartners-1.0.0/
Cockpit url:https://1119c0a4trial.launchpad.cfapps.eu10.hana.ondemand.com/614e8b49-606f-417c-84eb-b4f64b1eceac.BP.nsbusinesspartners-1.0.0/index.html

Is this the reason, Under Content Explorer, I am not able to get the app under HTML5 apps.
Or 
Is there any security / Roles I am missing.
I was able to add other Apps / URLs to launch pad as per 
https://developers.sap.com/mission.launchpad-cf.html
Thanks,
Vikas

**Comment by raz-korn** [comment]
@IrisSasson / @LindsayBert : Can you help us here?

**Comment by IrisSasson** [comment]
Hi
I am not sure but it seems you didn't use the managed app router or that you did not create an MTA to begin with (the second is less likely)
Can you create an empty app again and make sure you select the managed app router? 

Using the magaged app router is documented in this tutorial: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html on Step 2

Please share a screenshot of your selections in this wizard and show your managed app router configuration

Thanks

**Comment by raz-korn** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue.
If you still have questions and want to continue the conversation, feel free to reopen the issue.
