### ISSUE TITLE
Create a Chatbot that Lets Customers Track Packages

### ISSUE THREAD

**Issue by advit-ramesh** [SAPDocuments/Issues#284]
Tutorials: https://developers.sap.com/tutorials/cai-bot-shipping-1-track-bot.html
--------------------------

Hello Experts,

When I key in the tracking number in Chat Preview, the goodbye intent is picked up by the AI. I have attached the screem grab below 

![image](https://user-images.githubusercontent.com/29966401/113065181-f0176b80-9214-11eb-8f4f-1d6273555cc6.png)

Screengrab of the Requirements

![image](https://user-images.githubusercontent.com/29966401/113065231-01607800-9215-11eb-985e-dd1a71216a8a.png)

![image](https://user-images.githubusercontent.com/29966401/113065305-1d641980-9215-11eb-973f-2d6f1f6c28e4.png)

Can you please let me know if this is a bug?

**Comment by thecodester** [comment]
The first thing that comes to mind is that when this tutorial was written the training of the chatbot was automatic but now it is manual -- you have to click Train at the top or change the settings.
Can you check if that is it?
If so, I will update the tutorial

**Comment by advit-ramesh** [comment]
The below correction has fixed this issue. Thanks 

https://github.com/SAPDocuments/Issues/issues/283

**Comment by thecodester** [comment]
:-)

Sorry for the problem.
