### ISSUE TITLE
Run the Employee Onboarding Sample Scenario

### ISSUE THREAD

**Issue by maltesh0188** [SAPDocuments/Issues#286]
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-5-run.html
--------------------------
After Step 1. onboard instances are not visible in the events section. Check the JSON file.
Write here what you need help with ...

**Comment by ArchanaShukla** [comment]
@maltesh0188 - what exactly is the issue?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
