### ISSUE TITLE
Let Customers Ask Chatbot for Shipping Price

### ISSUE THREAD

**Issue by advit-ramesh** [SAPDocuments/Issues#287]
Tutorials: https://developers.sap.com/tutorials/cai-bot-shipping-3-price-parcel.html
--------------------------
I am unable to get the right response in step 8 

![image](https://user-images.githubusercontent.com/29966401/113239982-4913fc00-9308-11eb-80d6-0059287a6ca8.png)

There is a warning 
Undefined context path 'memory.parcel-size.name'
Undefined context path 'memory.parcel-size.price'

The response JSON 

{
  "type": "message",
  "value": {
    "type": "text",
    "content": "A  parcel sent to 52 Place de la Madeleine, 75008 Paris, France will cost $",
    "markdown": false,
    "delay": null,
    "value": "A {{memory.parcel-size.name}} parcel sent to {{memory.location.formatted}} will cost ${{memory.parcel-size.price}}"
  }
}

Can you please advice 

Regards
Advit

**Comment by thecodester** [comment]
It seems that "parcel-size" is not saved in memory.

Do you have a requirement for parcel-size?
![image](https://user-images.githubusercontent.com/11659786/113501410-8b6a5280-952d-11eb-9b1b-77635f13c4f3.png)

In the conversation, can you see in the memory "parcel-size"?
![image](https://user-images.githubusercontent.com/11659786/113501401-768dbf00-952d-11eb-8e66-22880acdee1f.png)

Can you send what you have?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
