### ISSUE TITLE
Subscribe to Document Information Extraction Trial UI

### ISSUE THREAD

**Issue by sapjansch** [SAPDocuments/Issues#288]
Tutorials: https://developers.sap.com/tutorials/cp-aibus-dox-ui-sub.html
--------------------------

Hi experts, 

can't get the Trial UI out ouf the Service Marketplace. What did I/ what went wrong. 

Thanks
Jan

![image](https://user-images.githubusercontent.com/12291738/113294897-bcf9d880-92f7-11eb-98e2-36dc9caabd67.png)

**Comment by Juliana-Morais** [comment]
Hi Jan,

I can see the Document Information Extraction Trial UI tile on my Trial Account, Service Marketplace tab. Have you created a service instance for Document Information Extraction Trial? Creating the service instance is a prerequisite.

![image](https://user-images.githubusercontent.com/45172115/113668898-36f0df80-96b3-11eb-9dfb-3b2b962caebf.png)

You can also run the booster "Set up account for Document Information Extraction" to create a service instance and subscribe to the application. Please use this tutorial: https://developers.sap.com/tutorials/cp-aibus-dox-booster-app.html.

Best regards,
Juliana

**Comment by sapjansch** [comment]
Hi Juliana,

same search criteria like last week, and now I found it: 
![image](https://user-images.githubusercontent.com/12291738/113670266-2d687700-96b5-11eb-815a-a625cd5a8e59.png)

Service Instance has been active last week as well.

Thanks for your help
Best regards
Jan

**Comment by Juliana-Morais** [comment]
Hi Jan,

Thank you for letting me know.  Have a good week!

Best regards,
Juliana
