### ISSUE TITLE
Tour the SAP Community

### ISSUE THREAD

**Issue by rpbouman** [SAPDocuments/Issues#289]
Tutorials: https://developers.sap.com/tutorials/community-start.html
--------------------------

I have performed all steps but 2, 4, and 11 don't get checked. It's kinda frustrating

https://developers.sap.com/tutorials/community-start.html#a6827331-daf7-4dac-ada0-0de5c1fcd640

**Comment by thecodester** [comment]
Can you try now?

**Comment by rpbouman** [comment]
Sorry for the late reply. It works!
