### ISSUE TITLE
Discover Sales Order API from S/4HANA Cloud System

### ISSUE THREAD

**Issue by js1972** [SAPDocuments/Issues#29]
Tutorial: https://developers.sap.com/tutorials/cp-apim-sales-tracker-api-discover.html
--------------------------

Is this tutorial meant for the Neo APIM as I am trying with the CF APIM and its failing?
Some of the setup steps were different but at the point where we choose an API (step 2: create proxy) it fails when I click COPY on the api with this error:
```
Unable to copy API: Creation of the API proxy from the OAS 3.0 version of the API is not supported.
```

How can I get around this? Are the sales order api's from S4Cloud not version compatible with APIM now?

Do you know if there are any recent APIM tutorials? I have found this one as well - but as there are not dates on any tutorials its hard to tell if they are out of date or not?

**Comment by shilpavij** [comment]
Dear colleague,

this tutorial is for both neo and CF
The copy issue is a known issue but kindly log a csn on OPU-API-OD-DT.

Regards
Shilpa

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
