### ISSUE TITLE
Use Redis in the Kyma Runtime to Store and Retrieve Data

### ISSUE THREAD

**Issue by akula86** [SAPDocuments/Issues#291]
Tutorials: https://developers.sap.com/tutorials/cp-kyma-redis-function.html
--------------------------

Formatting issue:

Step 10: Sub-step numbering restarts (1, 2, 1, 2, 3, 4).

**Comment by jcawley5** [comment]
Fixed in

https://github.com/SAPDocuments/Tutorials/pull/6632
