### ISSUE TITLE
Develop and Run SAP Fiori Application With SAP Business Application Studio

### ISSUE THREAD

**Issue by carrotcn** [SAPDocuments/Issues#293]
Tutorials: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html
--------------------------

Step 8.6: Service Type: OData V2. However there is no "OData V2" in the dropdown box. See below:

![image](https://user-images.githubusercontent.com/19308240/113755602-84367680-96de-11eb-8817-f3604e6d2b30.png)

**Comment by mervey45** [comment]
Hi @carrotcn,

please select OData IWSG therefore.

@thecodester I created following pull request for this change: #6640.

Best regards,
Merve
