### ISSUE TITLE
Mobile cards: Data in Mobile cards not loading in the cards in mobile app [EU]

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#297]
Hello,

Scenario URL: https://developers.sap.com/tutorials/cp-mobile-cards-booster-starter.html#b420273f-5134-4f4b-b745-fcc680f86848

Step 3.6: The data in not loaded in the cards in the mobile app after creating the cards.
After creating sales order & Contact order, the card is getting loaded in the app, but there is NO DATA in the cards.
So, on clicking on the cards, I can't see any values. tried with creating the cards again, but same issue.

Attached screenshots for both the cards, Please check.

![EU_NO_DATA](https://user-images.githubusercontent.com/66831161/114082229-1ef3a880-98cb-11eb-85c9-9f157eaf5c82.jpeg)

![EU-NO DATA](https://user-images.githubusercontent.com/66831161/114082247-22872f80-98cb-11eb-92c0-f086f9dd5c99.jpeg)

Thanks,
Shubham

Labels to be added:
prio: High-prio
Sprint Label: SCPTest-2104A
Scenario Label: SCPTest-mcard
Landscape Labels: trial1[EU]

**Comment by shahchetali** [comment]
Hi @i353590, 

I tested the Mobile Cards Starter Scenario on all the three landscapes and it is working as expected. If the cards are not loaded into the mobile application, you just need to unsubscribe and subscribe again and then they will load. It sometime takes some time as well.
@sandeep-tds will be adding this information into the tutorial.

Thanks & Regards,
Chetali Shah

**Comment by i353590** [comment]
Hello @shahchetali,

Yes, and for that I tried creating cards again, and couldn't see the values. Now this time even cards i was able to see and the values inside those cards were not loading. I have also attached the screenshot for reference.

Thanks,
Shubham

**Comment by sandeep-tds** [comment]
Hi Team, I am closing this issue since the necessary updates were provided in the tutorial. Thank you for your support.
