### ISSUE TITLE
Mobile cards: Cards not loading in Mobile App [US]

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#298]
Hello,

Scenario URL: https://developers.sap.com/tutorials/cp-mobile-cards-booster-starter.html#b420273f-5134-4f4b-b745-fcc680f86848

Step 3: View supplier contact card on your mobile device
Issue: The cards are not loading in the mobile app.
The Welcome card ( in tutorial 1 was loaded) but the sales order and contact details cards are not getting loaded in the mobile app.
Tried deleting and creating new cards, didn't help. Getting error in the app's activity log as well: "Failed to process card".

Please refer to the attachment:

![US_CARD_NOT LOADING](https://user-images.githubusercontent.com/66831161/114083407-8eb66300-98cc-11eb-9b24-23bee3b17db0.jpeg)

Thanks,
Shubham

Labels to be added:
prio: High-prio
Sprint Label: SCPTest-2104A
Scenario Label: SCPTest-mcard
Landscape Labels: trial2 [US]

**Comment by shahchetali** [comment]
Hi @i353590, 

I tested the Mobile Cards Starter Scenario on all the three landscapes and it is working as expected. If the cards are not loaded into the mobile application, you just need to unsubscribe and subscribe again and then they will load. It sometime takes some time as well. Can you check it once?
@sandeep-tds will be adding this information into the tutorial.

Thanks & Regards,
Chetali Shah

**Comment by i353590** [comment]
Hello @shahchetali ,

I had tried that couple of times and did subscription and un-subscription multiple times, but still i couldn't see the cards.
Also, the subscription was reflecting in the app, but the cards were not loading. if that was the problem, then the error shouldn't have come in the application i hope.
but the issue might have been resolved now.


Thanks,
Shubham

**Comment by sandeep-tds** [comment]
Hi @i353590 since the issue has been resolved, can we close the ticket?

**Comment by i353590** [comment]
Hello @sandeep-tds ,

The issue seems resolved in the latest execution.
Please close the ticket.

Thanks,
Shubham
