### ISSUE TITLE
Mobile Cards - SAP BTP Rebranding Screenshots change required

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#299]
Hello,

Scenario URL: https://developers.sap.com/tutorials/cp-mobile-cards-welcome.html
Step 2.2: Logon Screen, Step 2.3: Welcome Screen, Step 2.4: Boosters screen &
Tutorial 2: https://developers.sap.com/tutorials/cp-mobile-cards-booster-starter.html
Step 2.2: Welcome Screen, Step 2.3: Boosters screen

Issue: All screenshots need to be changed as per latest rebranding changes (Screenshots still shows SAP CP).
Please update all these screenshots with new screenshots of SAP BTP.

Thanks,
Shubham

Labels to be added:
prio: Low-prio
Sprint Label: SCPTest-2104A
Scenario Label: SCPTest-mcard
Landscape Labels: trial1,trial2,trial3

**Comment by sandeep-tds** [comment]
@i353590  Thank you for raising the issue. I have updated the tutorial. The new version should be available in the coming week.

**Comment by vanita57** [comment]
Hi Sandeep,

Tutorial 2: https://developers.sap.com/tutorials/cp-mobile-cards-booster-starter.html
Step 2.3: Boosters screen is to be updated 
see 
![tempsnip](https://user-images.githubusercontent.com/56148375/121470989-9a153000-c9dc-11eb-85f8-2360af221104.png)

Thanks and Regards,
Vanita

**Comment by sandeep-tds** [comment]
Thank you for pointing it out @vanita57 I will make the necessary change.

**Comment by sandeep-tds** [comment]
Hi @vanita57, 

The issue has been fixed. Thus, I am closing the ticket. 

Thank you so much for your support.
