### ISSUE TITLE
Set Up Your Java Development Environment

### ISSUE THREAD

**Issue by MichaelPShea** [SAPDocuments/Issues#3]
Tutorial: https://developers.sap.com/tutorials/cp-java-reference-app-setup.html
--------------------------

Step 5: Install SAP Development Tools
Follow the instructions how to install Install SAP Development Tools for Eclipse Oxygen.

The link is broken to the SAP Development Tools for Eclipse Oxygen. You land on a help portal page without relevant content. Has it been replaced?

**Comment by MichaelCzcz** [comment]
@simonarangelova Please respond!

**Comment by MichaelPShea** [comment]
I have this information from Stephen Cherian: This tutorials are outdated. 
For the below step the link seems to broken
In step 5 the instructions for setting up the SAP Development Tools for Eclipse Oxygen lead nowhere.
The link should point to the page https://help.sap.com/viewer/ea72206b834e4ace9cd834feed6c0e09/Cloud/en-US/76137a37711e1014839a8273b0e91070.html

**Comment by YogithaC** [comment]
Hi Michael,

Thanks for bringing this to my notice. I'll update the tutorial with the link along with few other naming changes by next week.

Regards,
Yogitha

**Comment by sasisharath** [comment]
Hi,

This issue has been fixed and the tutorial is pushed to production. 

Best regards,
Sharath
