### ISSUE TITLE
Trial account screenshot change

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Issues#300]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html
Step 2: Enter your trial account
--------------------------

Change the screenshot at the end of this step, where the trial account is displayed. Boosters is still displayed as Recipe in the current screenshot.

**Actual:**
![image](https://user-images.githubusercontent.com/65999547/114143281-92c89c00-9931-11eb-8206-53ac81d718aa.png)

**Expected:**
![image](https://user-images.githubusercontent.com/65999547/114143295-98be7d00-9931-11eb-8dd6-335599519c3d.png)

Best Regards,
Priyanka

**Comment by Karunaharan** [comment]
hi @PriyankaShivakumar - fixed the screenshot. will send a PR very soon
