### ISSUE TITLE
Instances and Subscriptions screenshot has to be changed

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Issues#301]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html
Step 3: Subscribe to the service
--------------------------
In the current screenshot of the tutorial only Instances and Subscriptions are shown. But with the latest changes, In this screen along with Instances and Subscriptions tab, there is an additional tab called as Environment added. Also BAS is subscribed to by default.

**Actual:**
![image](https://user-images.githubusercontent.com/65999547/114144166-a9232780-9932-11eb-9eee-16707c996473.png)

**Expected:**
![image](https://user-images.githubusercontent.com/65999547/114144185-afb19f00-9932-11eb-90ae-183f26faeec2.png)

Best Regards,
Priyanka

**Comment by Karunaharan** [comment]
Hi @PriyankaShivakumar fixed. will send a PR very soon
