### ISSUE TITLE
Model Operation screenshot change

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Issues#303]
Tutorials: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html
Step 8: Connect request reply to receiver
--------------------------

Screenshot has to be changed as the UI has changed a little.

**Expected:**
![image](https://user-images.githubusercontent.com/65999547/114146625-729adc00-9935-11eb-90e1-dc8e87d20938.png)

**Actual:**
![image](https://user-images.githubusercontent.com/65999547/114146733-92320480-9935-11eb-8192-375bf2931f69.png)

Best Regards,
Priyanka

**Comment by Karunaharan** [comment]
hi @PriyankaShivakumar - fixed the screenshot. will send a PR very soon.
