### ISSUE TITLE
Service key screenshot change

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Issues#304]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html
Step 1: Copy credentials from service key
--------------------------

Screenshot has to be changed as now 2 instances are created with booster.

**Expected:**
![image](https://user-images.githubusercontent.com/65999547/114147127-0076c700-9936-11eb-85ce-4774a0aca2da.png)

**Actual:**
![image](https://user-images.githubusercontent.com/65999547/114147658-8c88ee80-9936-11eb-9216-bc0b6131a19d.png)

Best Regards,
Priyanka

**Comment by Karunaharan** [comment]
hi @PriyankaShivakumar - fixed the screenshot. will send a PR very soon.
