### ISSUE TITLE
Steps has to be changed due to rebranding

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Issues#305]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html
Step 3: Define the API
--------------------------

In step 3, the steps mentioned to access the SAAS application needs to be changed. The new way includes navigating to Instances and Subscriptions screen and accessing the Integration Suite app from there.

![image](https://user-images.githubusercontent.com/65999547/114148371-4b450e80-9937-11eb-84d9-1b083dee4ab6.png)

Best Regards,
Priyanka

**Comment by Karunaharan** [comment]
hi @PriyankaShivakumar fixed the screenshot. will send a PR very soon.
