### ISSUE TITLE
Expose Integration Flow Endpoint as API and Test the Flow

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Issues#306]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html
Step 4: Assign policy template
--------------------------

Here the sentence should be rephrased to "you need the content of the service key **copied in Step 1: Copy credentials from service key.**" Since we no longer create the service key manually, Step1: Create service instance and key step is not there.

![image](https://user-images.githubusercontent.com/65999547/114148690-ab3bb500-9937-11eb-8b93-527090c3e323.png)

Best Regards,
Priyanka

**Comment by Karunaharan** [comment]
hi @PriyankaShivakumar - thanks for all your feedback. all the comments are fixed now. thank you so much for the detailed review.
