### ISSUE TITLE
Get Started with the SAP BTP Command Line Interface (btp CLI)

### ISSUE THREAD

**Issue by VlaD-T** [SAPDocuments/Issues#307]
Tutorials: https://developers.sap.com/tutorials/cp-sapcp-getstarted.html
--------------------------

Step 3, Test: 
Theoretically the right answer is "Create a Cloud Foundry environment instance (CF org), Create a Cloud Foundry space and Assign entitlements to a subaccount", but the system shows me, that the answer is incorrect. I then tried all the possible 16 combinations and still no right answer. Could you please check if the test is working?

**Comment by annawenger20** [comment]
Hi @VlaD-T - with the btp CLI (it still says sapcp CLI in the question, sorry about this, it's actually fixed but has not been pushed tp production, should be visible soon though), you can 

- see all available regions of the global account (btp list accounts/available-region)
- create a CF environment instance (btp create accounts/environment-instance)
- assign entitlements to a subaccount (btp assign accounts/entitlement) 

Once the environment instance is created, you move to the cf CLI to create a space. The btp (sapcp) CLI is for working with global accounts, directories, and subaccounts only). 

![image](https://user-images.githubusercontent.com/63057657/115036624-f9b7f900-9ecd-11eb-82a8-f0ef6a932cd5.png)
 
Please do let me know if the text in step 3 makes it too complicated.

Cheers, Anna
