### ISSUE TITLE
Deploy an SAP Conversational AI Chatbot to Microsoft Teams

### ISSUE THREAD

**Issue by Leoooob** [SAPDocuments/Issues#308]
Tutorials: https://developers.sap.com/tutorials/conversational-ai-deploy-teams.html
--------------------------

Doesn't include anything on OAuth2 which is now required in order to be accessible in Azure.

**Comment by thecodester** [comment]
Checking on this ... thanks for reporting

**Comment by thecodester** [comment]
@Leoooob Do you mean Azure has a requirement or are you referring to the new requirement within SPA Conversational AI for using OAuth token when using the SAP Conversational AI API (instead of developer token)

**Comment by thecodester** [comment]
I checked with our team and they have not heard of any changes and that the integration still works. Can you explain a little furhter, especially in relation to this tutorial -- like where you get an error?

**Comment by Leoooob** [comment]
The oAuth information generated in the CAI webapp didn't meet the requirements for Azure, I can't remember what exactly was missing but i think we had 2/3 generated fields and Azure required 4.

The actual issue occurred in Azure while trying to register the bot to 'Azure bot channel' on Azure. It registered without an oAuth token, and received the queries from the Azure test interface, however no responses from CAI were received to this interface. I then tried to add oAuth to the bot channel which I could not apply due to the missing field(s).

A colleague managed to recreate the issue by attempting to register and test the bot via Azure bot channel, my account has now expired so I cannot recreate

**Comment by thecodester** [comment]
I just did the tutorial again and I was able to get the chatbot to work -- I did not set any OAuth settings on either side, nor did I use the OAuth credentials/token from CAI. I did the tutorial as it is written (admittedly some of the screens have changed). You have to make sure you are taking the correct values from Azure into CAI, and it might take a few minutes for the setup to take hold.

**Comment by thecodester** [comment]
The screens are somewhat different in Azure but the process was the same. Make sure to create the secret in Azure and take the value right away, and use the secret not the secret ID.

I will close the issue now but feel free to reopen and ask any questions you have.
