### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio : Screenshot for FioriDemo explorer has to be changed

### ISSUE THREAD

**Issue by mounikat987** [SAPDocuments/Issues#309]
Tutorials: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html
--------------------------
Landscape : SCPTest-trial1 , SCPTest-trial2, SCPTest-trial3
Priority : Low

--------------------------

**Step 2: Configure the app to use Managed Application Router**

**Issue** : After creating the managed application,  gitignore & mta.yml file doesnt come under "FioriDemo" folder.

The UI has changed a bit, it appears as "Explorer FioriDemo" in  top header as shown below : 

![image](https://user-images.githubusercontent.com/33411431/114380696-f825c280-9ba7-11eb-94bd-19c728b4edd4.png)

Please change screenshot everywhere in this tutorial , where it displays "FioriDemo" as folder instead of "Explorer FioriDemo"  in header section.

**Note** : This issue is common for "Step 3: Generate an app based on SAPUI5 Application template" as well.

Here also "FioriDemo" folder is not appearing & it displays in header scetion.

![image](https://user-images.githubusercontent.com/33411431/114381217-7f733600-9ba8-11eb-8812-f3ffcbd824c9.png)

Please update screenshots in complete tutorial.

Thanks
Mounika

**Comment by raz-korn** [comment]
Hi @mounikat987 ,
The tutorial reflects the way it appears in the trial environment.
No need to change.
Regards - Raz
