### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio : Odata Name has to be updated

### ISSUE THREAD

**Issue by mounikat987** [SAPDocuments/Issues#310]
Tutorials: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html
--------------------------

Landscape : SCPTest-trial1 , SCPTest-trial2, SCPTest-trial3
Priority : Low

-------
Step 3: Generate an app based on SAPUI5 Application template

4.For Data Source and Service Selection, select the following, and click Next.
Step | Parameter | Value

A | Data source | Connect to an SAP system
B | System | ES5
C | Service | GWSAMPLE_BASIC (1) - OData V2

**Issue :** 

Here, the service name has changed to "ZGWSAMPLE_BASIC (1) - OData V2".

![image](https://user-images.githubusercontent.com/33411431/114389658-e7c71500-9bb2-11eb-8f90-88a8a4335d78.png)

Please update in this step & screenshot accordingly.

Thanks
Mounika

**Comment by raz-korn** [comment]
Hi @mounikat987 ,
I updated the screenshot.
Regards - Raz
