### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio : screenshot for fiori app tile has to be updated

### ISSUE THREAD

**Issue by mounikat987** [SAPDocuments/Issues#311]
Tutorials: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html
--------------------------
Landscape : SCPTest-trial1 , SCPTest-trial2, SCPTest-trial3
Priority : Low
-----------------
Step 3: Generate an app based on SAPUI5 Application template

2.Select the SAP Fiori Application tile, and click Start.

**Issue**  : SAP Fiori Application tile has image/logo in it as below :- 

![image](https://user-images.githubusercontent.com/33411431/114391612-54431380-9bb5-11eb-90a9-20114900c46f.png)

please update screenshot accordingly.

Thanks
Mounika

**Comment by raz-korn** [comment]
Hi @mounikat987 ,
I updated the screenshot.
Please note that the only difference is that it's a bit scrolled down.
Regards - Raz
