### ISSUE TITLE
Configure Business Rules, Workflow and Process Visibility

### ISSUE THREAD

**Issue by FarozanFarman** [SAPDocuments/Issues#312]
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-configure.html
--------------------------
Step 4: Deploy business rules
4: Select the Cloud Runtime option.

Issue: The screenshot needs to be updated.

It has been asked to Select the **Cloud Runtime** option but in the screenshot, it is **SAP Cloud Platform**.

Expected Result:
![image](https://user-images.githubusercontent.com/71028764/114388065-d5e47280-9bb0-11eb-913c-6bd1aa7aeda7.png)

Actual Result:
![image](https://user-images.githubusercontent.com/71028764/114388117-e85eac00-9bb0-11eb-98c8-4ba599221fc8.png)

Labels:
Landscape Labels: trail1, trail2, trail3
SCPTest-fabap : Automate and Extend Employee Onboarding
Label: SCPTest-2104
Priority label : 'Low'

Regards,
Farozan

**Comment by ArchanaShukla** [comment]
Please use the current tutorials. Updated tutorial have been published now.
