### ISSUE TITLE
Deploy a CAP Business Application to SAP Business Technology Platform

### ISSUE THREAD

**Issue by raprins** [SAPDocuments/Issues#313]
Tutorials: https://developers.sap.com/tutorials/cap-service-deploy.html
--------------------------

The databse deployer is always down.

**Comment by iwonahahn** [comment]
@raprins To which step are you referring in the tutorial? What do you mean with "The database deployer is always down"? Please share more details, error messages, version numbers you are using. Thanks a lot!

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
