### ISSUE TITLE
Use Redis in the Kyma Runtime to Store and Retrieve Data

### ISSUE THREAD

**Issue by cagooi88** [SAPDocuments/Issues#314]
Tutorials: https://developers.sap.com/tutorials/cp-kyma-redis-function.html
--------------------------

I am following the tutorial https://developers.sap.com/tutorials/cp-kyma-redis-function.html#8ff2b8bc-7c1b-4439-83ae-89b3d0bac8e3.
At step 11, review function output log, I am only getting Processing event and Getting ordering details log. I am not getting Received Order and Caching data log. If I remove the orderCode filter, I am getting below error.

2021-04-13T19:03:58.542343736Z | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
-- | --
2021-04-13T19:03:58.542327736Z | Function failed to execute: Error: connect ECONNREFUSED 127.0.0.1:80

Of course, I am not able to complete step 12 since the orderCode is not cached in Redis.

Please advise what could be the step that I have missed?

**Comment by jcawley5** [comment]
Hello,

Please check that you have the have the correct value for the const COMM_GATEWAY_URL defined on line three as detailed in step 9.  Otherwise please add some screenshots of the configuration if you are still experiencing issues.

Regards,
Jamie

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
