### ISSUE TITLE
Add Rich Enterprise Controls to the User Interface

### ISSUE THREAD

**Issue by Sandervanlaarhoven** [SAPDocuments/Issues#315]
Tutorials: https://developers.sap.com/tutorials/sapui5-fiori-cf-fiorify.html
--------------------------

Step 2: Use the smart filter bar

The ProductID filter value is entered wrong in the tutorial, must be >3 and <18 and in the screenshot it's the other way round.

**Comment by IObert** [comment]
Good catch @Sandervanlaarhoven!

I updates the screenshot and the change should be live within the next few minutes.
