### ISSUE TITLE
Take a Tour of SAP BTP Trial

### ISSUE THREAD

**Issue by klickerlebnis** [SAPDocuments/Issues#316]
Tutorials: https://developers.sap.com/tutorials/cp-trial-quick-onboarding.html
--------------------------

In this tutorial 

- https://developers.sap.com/tutorials/cp-trial-quick-onboarding.html

I get **403 following the urls in step 2 environments**

- https://help.sap.com/viewer/DRAFT/60f1b283f0fd4d0aa7b3f8cea4d73d1d/Internal/en-US/e50ab7b423f04a8db301d7678946626e.html
- https://help.sap.com/viewer/DRAFT/60f1b283f0fd4d0aa7b3f8cea4d73d1d/Internal/en-US/720c423ef1a8498ab690cf0e5512ba50.html
- https://help.sap.com/viewer/DRAFT/60f1b283f0fd4d0aa7b3f8cea4d73d1d/Internal/en-US/ccb83c700e8d4bb8aa545d7307b8b08a.html

Thanks, 
Dominik

**Comment by Jessica-Katz** [comment]
https://github.com/SAPDocuments/Tutorials/pull/6658
