### ISSUE TITLE
Get Started with the SAP BTP Command Line Interface (btp CLI)

### ISSUE THREAD

**Issue by klickerlebnis** [SAPDocuments/Issues#317]
Tutorials: https://developers.sap.com/tutorials/cp-sapcp-getstarted.html
--------------------------

In step 3 change the name in the question from **sapcp CLI** to **btp CLI** ...
For which of the following tasks do you use the **sapcp CLI**?

Thanks, 
Dominik

**Comment by annawenger20** [comment]
Thanks for noticing! I updated the tutorial accordingly. Have a good day!
