### ISSUE TITLE
Get Started with the SAP BTP Command Line Interface (btp CLI)

### ISSUE THREAD

**Issue by klickerlebnis** [SAPDocuments/Issues#318]
Tutorials: https://developers.sap.com/tutorials/cp-sapcp-getstarted.html
--------------------------

In step 7 the command in the quiz is still using sapcp

`sapcp list accounts/subaccount --help` instead `btp list accounts/subaccount --help`

Thanks, 
Dominik

**Comment by annawenger20** [comment]
same here - all occurecnes of sapcp have been removed. Enjoy and thanks a lot for the feedback!
