### ISSUE TITLE
Create a Dev Space for Business Applications

### ISSUE THREAD

**Issue by klickerlebnis** [SAPDocuments/Issues#320]
Tutorials: https://developers.sap.com/tutorials/appstudio-devspace-create.html
--------------------------

In Step 1 Section 4 the name has changed from **"SAP Cloud Business Application"** to **"Full Stack Cloud Application"**

Thanks, 
Dominik

**Comment by Paolaufer** [comment]
@MichaelCzcz updated the text and the images, but the changes are not visible in the QA output.
Could you please take a look and see if you can find out why?

**Comment by MichaelCzcz** [comment]
@Paolaufer QA is currently getting migrated. Please use the preview feature in Atom to view your changes.

**Comment by Paolaufer** [comment]
The tutorial has been updated.
