### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by skt1483** [SAPDocuments/Issues#322]
Tutorials: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html
--------------------------

Write here what you need help with ...

One step to choose the 'Add application to managed application router?' is missing ' - I hope it should be YES ( see screen shot )
https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

![Screenshot 2021-04-15 000957](https://user-images.githubusercontent.com/70734066/114812942-0e39ab80-9d7f-11eb-8d95-1debd8d5e32b.jpg)

![image](https://user-images.githubusercontent.com/70734066/114812852-dc284980-9d7e-11eb-9477-92ad841a81fb.png)

**Comment by raz-korn** [comment]
Hi @skt1483 ,

The wizard used in this tutorial does not have a "Target Name" step. Instead it has a "Deployment Configuration" step, as appears in the tutorial. Please go through the tutorial steps and check.

Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
