### ISSUE TITLE
Connect Using the SAP HANA Node.js Interface

### ISSUE THREAD

**Issue by krishraheja** [SAPDocuments/Issues#323]
Tutorials: https://developers.sap.com/tutorials/hana-clients-node.html
--------------------------

1. Step2.3 npm install "C:\SAP\hdbclient\node" is not getting executed. I executed cmd with Admin role
2. If I skip Step2.3 mentioned above and execute module, I get the error as Invalid value for KEY, directory search path: 

C:\Users\I076029\HANAClientsTutorial\node\nodeQuery.js:35
connection.connect(connOptions);
           ^

Error: Invalid value for KEY, directory search path: C:\ProgramData\.hdb\AGRN34702481A\S-1-5-21-74642-3284969411-2123768488-225413
    at Object.<anonymous> (C:\Users\I076029\HANAClientsTutorial\node\nodeQuery.js:35:12)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: -10104,
  sqlState: ''
}

**Comment by danielva** [comment]
Note that 
npm install "C:\SAP\hdbclient\node"
is an optional step.  It performs the same action as npm install @sap/hana-client

node nodeQuery.js would fail with an error of Error: Cannot find module '@sap/hana-client' if the HANA client driver was not installed.


The error 
Invalid value for KEY
Indicates that the user store key cannot be found. This key was created in the previous tutorial 
https://developers.sap.com/tutorials/hana-clients-hdbsql.html#c537166e-883e-417f-b1ae-7ce10dbbd688

Alternatively, comment out the serverNode line in Option 1 and in Option 2 in nodeQuery.js specify the serverNode, UID, and PWD value.

Hope that helps

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
