### ISSUE TITLE
Deploy a CAP Business Application to SAP Business Technology Platform

### ISSUE THREAD

**Issue by mizmauz** [SAPDocuments/Issues#324]
Tutorials: https://developers.sap.com/tutorials/cap-service-deploy.html
--------------------------

I have followed the tutorial. Until this point everything works fine.

cds build --production -> creates a gen/srv folder, but no gen/db folder

cf push -f gen/db
Error: **cf push -f gen/db
Incorrect Usage: The specified path 'gen/db' does not exist.**

cf push -f gen/srv --random-route
Error:
Applying manifest file gen\srv\manifest.yml...
For application 'my-bookshop-srv': Services must be a list of service instances
FAILED

Manifest.yaml
---
applications:
  - name: my-bookshop-srv
    path: .
    memory: 256M
    buildpacks:
      - nodejs_buildpack
    services:

Package.json
There is no automatic reference to the my-bookshop-db service. Do i have to enter it manually

  "cds": {
    "features": {
      "fiori_preview": true
    },
    "requires": {
      "db": {
        "kind": "sqlite",
        "model": "*",
        "credentials": {
          "database": "db/my-bookshop.db"
        }
      }
    }
  }
}

**Comment by iwonahahn** [comment]
Hi @mizmauz,

In your `package.json` you need to update "kind". Use "sql" instead of "sqlite". This should work.  

Best regards,
Iwona

**Comment by mizmauz** [comment]
Hi Iwona, thanks it worked
