### ISSUE TITLE
Create a Basic Flow with a SOAP Endpoint

### ISSUE THREAD

**Issue by jmalla** [SAPDocuments/Issues#325]
Tutorials: https://developers.sap.com/tutorials/cp-integration-create-basic-flow.html
--------------------------

Step 5: Add a mail receiver, 3. Configure the Mail receiver - there is no option for Proxy Type None.  I can only see Proxy Type as Internet or On-Premise

Step 6: Save, deploy and execute the flow - unable to deploy without adding a To in the email.  MAIL ATTTRIBUTES To is mandatory.  But in the tutorial it is left empty.

- Jay

**Comment by gauthamkrishna-sap** [comment]
Hello,
Thank you for the feedback. We are in the process of updating this entire mission and you will see a new version released shortly. Apologies for the short term inconvenience. Please stay tuned for an update from our end regarding this in the next few days.
Thanks and Best Regards,
Gautham

**Comment by zhmq0124v** [comment]
Hi Gautham,

Any updates? Today I spent hours to walk through this mission with the help of this blog https://blogs.sap.com/2020/01/15/cpi-gmail-smtp-integration/comment-page-1
The tutorial itself does not work. https://developers.sap.com/tutorials/cp-integration-create-basic-flow.html

**Comment by gauthamkrishna-sap** [comment]
Hi @zhmq0124v 

We are still working on it. In the meantime, I can offer you this session from TechEd 2020: https://github.com/SAP-samples/teched2020-DEV165

This also contains mail adapter configuration with REST API and a non-SAP system. Hope you can get some hands on experience with this while we update this series. 

Thanks and Best Regards,
Gautham

**Comment by gauthamkrishna-sap** [comment]
Hello,
We are still working on updates for this series. In the meantime, this tutorial from TechEd is a great alternative to continue your integration learning journey: https://github.com/SAP-samples/teched2020-DEV165
Best Regards,
Gautham

**Comment by gauthamkrishna-sap** [comment]
Hello,
This tutorial has been deprecated. We will replace it with an updated tutorial in the coming weeks. Please watch out for "Integration Suite tutorials" in the SAP Tutorial Navigator for new updates. 
Thank you.
