### ISSUE TITLE
Step 8: Trigger the integration flow - Error calling SOAP URL

### ISSUE THREAD

**Issue by jmalla** [SAPDocuments/Issues#326]
Tutorials: https://developers.sap.com/tutorials/cp-integration-create-basic-flow.html
--------------------------

I am trying to send XML to the SOAP end point:
https://e*****fftrial.it-cpitrial-rt.cfapps.us10.hana.ondemand.com/cxf/submitFreightInfo

I am using my BTP credentials and posting the XML from the tutorial:

I get the response:

<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
    <soap:Body>
        <soap:Fault>
            <soap:Code>
                <soap:Value>soap:Receiver</soap:Value>
            </soap:Code>
            <soap:Reason>
                <soap:Text xml:lang="en">An internal error occurred during message processing. For error details check the System Logs Monitor in https://e*****fftrial.it-cpitrial.cfapps.us10.hana.ondemand.com:443/itspaces/shell/monitoring/SystemLogs</soap:Text>
            </soap:Reason>
        </soap:Fault>
    </soap:Body>
</soap:Envelope>

But with my trial account, I am unable to see the error in the system log:
https://e*****fftrial.it-cpitrial.cfapps.us10.hana.ondemand.com:443/itspaces/shell/monitoring/SystemLogs

If I go to message monitoring, the flow is not even executing.  So I am not sure why the authentication is not working.

- Jay

**Comment by jmalla** [comment]
There is another post with the same type of issue - Create a Basic Flow with a SOAP Endpoint #137
https://github.com/SAPDocuments/Issues/issues/137

**Comment by jmalla** [comment]
For the Neo environment, we just had to add the role ESBmessaging.send:
https://help.sap.com/viewer/368c481cd6954bdfa5d0435479fd4eaf/Cloud/en-US/24585cc503334e6c917ef383efb5558a.html

But not sure about Cloud Foundry.

**Comment by jmalla** [comment]
I saw another person who encountered the same issue:

Assign ESBMessaging.send role #5519
https://github.com/SAPDocuments/Tutorials/issues/5519

I created a role collection and added the role "MessagingSend" and added this to my userid that I use to log into the tenant but I still get the same error. Not sure what I am missing.

**Comment by gauthamkrishna-sap** [comment]
Hello,
Thank you for the feedback. We are in the process of updating this entire mission and you will see a new version released shortly. Apologies for the short term inconvenience. Please stay tuned for an update from our end regarding this in the next few days. 
Thanks and Best Regards,
Gautham

**Comment by gauthamkrishna-sap** [comment]
Dear All,
Just to clarify, this is the old Neo based tutorial which we are in the process of updating to reflect the new screenshots from Integration Suite trial. Please stay tuned for this update. 
Thanks and best regards,
Gautham

**Comment by jmalla** [comment]
Thanks Gautham - yes it would be good to update the tutorials for the Cloud Foundry system and pointing to ES5.  For some of the questions on the tutorials, they should be in radio button format instead of having the user enter in free form text where the answers are not simple.

**Comment by gauthamkrishna-sap** [comment]
Thanks for that specific point too. We will definitely take this into consideration while designing the tutorials.

**Comment by gauthamkrishna-sap** [comment]
Hello,
We are still working on updates for this series. In the meantime, this tutorial from TechEd is a great alternative to continue your integration learning journey: https://github.com/SAP-samples/teched2020-DEV165
Best Regards,
Gautham

**Comment by gauthamkrishna-sap** [comment]
Hello,
This tutorial has been deprecated. We will replace it with an updated tutorial in the coming weeks. Please watch out for "Integration Suite tutorials" in the SAP Tutorial Navigator for new updates. 
Thank you.
