### ISSUE TITLE
Create a Project to Author Rules

### ISSUE THREAD

**Issue by cocquerel** [SAPDocuments/Issues#327]
Tutorials: https://developers.sap.com/tutorials/cp-cf-businessrules04-create-project.html
--------------------------

Write here what you need help with ...
Step 2 is failing with the following error message : "com.sap.brms.repositoryservice.odata.api.messaging.MessagingException: Failed to post to Messaging service"

**Comment by VandanaVasudevan** [comment]
Hi,

Can you try the step once again? Also, which data center are you using?

Best Regards,
Vandana

**Comment by cocquerel** [comment]
Hi
I confirm I still have the issue. Data canter is Europe (Frankfurt) - AWS cf-eu10
Here are screenshots of the error and subaccount details
Regards,
Michael
![image](https://user-images.githubusercontent.com/7956591/115250109-8e6a6300-a129-11eb-9b3c-954132e4c7d2.png)
![image](https://user-images.githubusercontent.com/7956591/115250320-bbb71100-a129-11eb-9765-10bebb62a3d8.png)

**Comment by VandanaVasudevan** [comment]
@ArchanaShukla Can you please help here?

**Comment by ArchanaShukla** [comment]
Hello, sorry for asking it again but can you (a) can you try creating the project again and check, (b) if you open Developer Console of your browser and send the Network trace for the error. Thanks!

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
