### ISSUE TITLE
Create a Reusable Service

### ISSUE THREAD

**Issue by RajaramKankipati** [SAPDocuments/Issues#328]
Tutorials: https://developers.sap.com/tutorials/cp-cap-java-reusable-service.html
--------------------------

Write here what you need help with ...

Step5:  after 'npm install --save-dev sqlite3' another command needs to be executed before deploying to SQLite. 

unset NODE_PATH

**Comment by beckermarc** [comment]
Hi @RajaramKankipati,

thanks for this hint. 

Can you please provide the information what the error was in your case when you didn't run `unset NODE_PATH`? 
Did you run the tutorial in Business Application Studio or locally?

Best regards,
Marc

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
