### ISSUE TITLE
Send and Receive Test SAP Event Mesh

### ISSUE THREAD

**Issue by dutchin** [SAPDocuments/Issues#329]
Tutorials: https://developers.sap.com/tutorials/cp-enterprisemessaging-test-queue-sendreceive.html
--------------------------

Write here what you need help with ... 

The "Receive Message" portion of this tutorial seems wrong.  Shouldn't you be using GET instead of POST.  And the cut and paste for the body - that seems wrong to.  If you are going to receive/consume, there shouldn't be anything in the body.  Am I missing something

**Comment by pradeeppanda-sap** [comment]
hi,
 A GET is used where state of the object is not changed. Though we in our back of our mind, think if SEND is POST, RECEIVE should be a GET. But in this case, even RECEIVE does change the state. The message which was there in the queue, after receiving gets deleted. And hence it is a POST.

regards
