### ISSUE TITLE
Call an External Endpoint to Retrieve Additional Information

### ISSUE THREAD

**Issue by jmalla** [SAPDocuments/Issues#330]
Tutorials: https://developers.sap.com/tutorials/cp-integration-consume-external-api.html
--------------------------

The tutorial has some inconsistencies.  

- In step 2, item 1 instructions specify - "Set Name to user."  However, the screenshot shows creating the user "clientIDuser" and not "user".  Later on Step 3 item 5, the  instructions are to use - Credential Name | user.  Either the screenshot needs to be changed to have "user" or the instructions need to be changed to "clientIDuser"

- Also - a lot of the iFlow screenshots are not correct - there should be more steps in the flows.

- In Groovy script, need to have the import statement at the top:
import com.sap.gateway.ip.core.customdev.util.Message;

- Step 4: Replace the Request Reply step with a Content Enricher.  The  item 3 within this step has a table of values does not make sense as this cannot be set for the Content Enricher - the table is for a later item 5 for the communication channel.

Field | Value
-- | --
Address | SOAP endpoint URL of the flow created in Step 1
Method | POST
Authentication | Basic
Credential Name | User

Step 4 item 5 - there is no Method Post on the SOAP channel.

For the final result, i am getting back the following - the Content Enricher is putting this in a multimap:
`<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Header/>
    <soap:Body>
        <multimap:Messages xmlns:multimap="http://sap.com/xi/XI/SplitAndMerge">
            <multimap:Message1>
                <orders xmlns:dis="http://camel.apache.org/cxf/jaxws/dispatch" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
                    <order>
                        <orderID>BS00010023</orderID>
                        <OrderDate>11.04.2019</OrderDate>
                        <CustomerName>Kiara</CustomerName>
                        <CustomerLastName>Jain</CustomerLastName>
                        <Address>23,Prime View,Redfield,Bangalore,Karnataka,560037,India</Address>
                        <ContactNumber>0091-8437329849</ContactNumber>
                        <items>
                            <item>
                                <ProductID>RPD4044543</ProductID>
                                <ProductDescription>Wireless Mouse</ProductDescription>
                                <Quantity>1</Quantity>
                            </item>
                        </items>
                        <OrderValue>1257</OrderValue>
                        <ShippingType>Priority 2-day</ShippingType>
                        <SpecialPackaging>None</SpecialPackaging>
                        <PaymentType>CoD</PaymentType>
                    </order>
                </orders>
            </multimap:Message1>
            <multimap:Message2>
                <order xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
                    <code>KWA2PRBK5I</code>
                    <orderID>BS00010023</orderID>
                </order>
            </multimap:Message2>
        </multimap:Messages>
    </soap:Body>
</soap:Envelope>`

Suggestion -  It would be really helpful to show the completed iFlow after the exercise and maybe even have the finished package on GitHub.

Regards,
Jay

**Comment by jmalla** [comment]
For the response, in the tutorial, the results are no in a multimap with two messages - so the Aggregation Algorithm maybe set to Enrich instead of Combine.  I left it as the default Combine - and this resulted in the multimap.  I am assuming the Aggregation Algorithm of Enrich (which is not shown) may be needed to set up to get the results shown. 

Here is what I am getting.  I need this to be like what the tutorial shows in order to continue.
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Header/>
    <soap:Body>
        <multimap:Messages xmlns:multimap="http://sap.com/xi/XI/SplitAndMerge">
            <multimap:Message1>
                <orders xmlns:dis="http://camel.apache.org/cxf/jaxws/dispatch" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
                    <order>
                        <orderID>BS00010023</orderID>
                        <OrderDate>11.04.2019</OrderDate>
                        <CustomerName>Kiara</CustomerName>
                        <CustomerLastName>Jain</CustomerLastName>
                        <Address>23,Prime View,Redfield,Bangalore,Karnataka,560037,India</Address>
                        <ContactNumber>0091-8437329849</ContactNumber>
                        <items>
                            <item>
                                <ProductID>RPD4044543</ProductID>
                                <ProductDescription>Wireless Mouse</ProductDescription>
                                <Quantity>1</Quantity>
                            </item>
                        </items>
                        <OrderValue>1257</OrderValue>
                        <ShippingType>Priority 2-day</ShippingType>
                        <SpecialPackaging>None</SpecialPackaging>
                        <PaymentType>CoD</PaymentType>
                    </order>
                </orders>
            </multimap:Message1>
            <multimap:Message2>
                <order xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
                    <code>KWA2PRBK5I</code>
                    <orderID>BS00010023</orderID>
                </order>
            </multimap:Message2>
        </multimap:Messages>
    </soap:Body>
</soap:Envelope>

**Comment by jmalla** [comment]
I set the Content Enricher to Enrich and got this to work.  These steps are missing in the tutorial

Aggregation Algorithm: Enrich

Original Message:
Path to Node: /orders/order 
Key Element: orderID

Lookup Message:
Path to Node: /order
Key Element: orderID

Please update the tutorial so other users can create the correct output which is needed for the next tutorial in the series.

Regards,
Jay

**Comment by gauthamkrishna-sap** [comment]
Hello,
We are still working on updates for this series. In the meantime, this tutorial from TechEd is a great alternative to continue your integration learning journey: https://github.com/SAP-samples/teched2020-DEV165
Best Regards,
Gautham

**Comment by Ciutipie** [comment]
Hey Gautham,
Till you get this going I noticed the email sent after following the tutorial is enriching the original message.

What would you recommend to use in the flow in order to strip the additional orderID tag and just get the code node?

From
<orderID>BS00010023</orderID><order xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <code>KWA2MNW2U</code>
    <orderID>BS00010023</orderID>
</order>
                

To
<orderID>BS00010023</orderID>
 <code>KWA2MNW2U</code>

**Comment by gauthamkrishna-sap** [comment]
Hello,
This tutorial has been deprecated. We will replace it with an updated tutorial in the coming weeks. Please watch out for "Integration Suite tutorials" in the SAP Tutorial Navigator for new updates. 
Thank you.
