### ISSUE TITLE
Add Conditional Routing to Your Integration Flow

### ISSUE THREAD

**Issue by jmalla** [SAPDocuments/Issues#331]
Tutorials: https://developers.sap.com/tutorials/cp-integration-add-conditional-routing.html
--------------------------

Step 5: Execute the flow

The email shown is not correct.  The second message is embedded in the first as shown in the results for the previous tutorial.  With the content enricher, the order element and child code and orderID are inside the request order from the previous tutorial.  But in the screenshot, code is shown under order which is not accurate.

        <orders xmlns:dis="http://camel.apache.org/cxf/jaxws/dispatch" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
            <order>
                <orderID>BS00010023</orderID>
                <order xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
                    <code>KWA2PRBK5I</code>
                    <orderID>BS00010023</orderID>
                </order>
                <OrderDate>11.04.2019</OrderDate>

**Comment by gauthamkrishna-sap** [comment]
Hello,

Apologies for the inconvenience.

We are still working on updating it. In the meantime, I can offer you this session from TechEd 2020: https://github.com/SAP-samples/teched2020-DEV165

This also contains mail adapter configuration with REST API and a non-SAP system. Hope you can get some hands on experience with this while we update this series.

Thanks and Best Regards,
Gautham

**Comment by gauthamkrishna-sap** [comment]
Hello,
We are still working on updates for this series. In the meantime, this tutorial from TechEd is a great alternative to continue your integration learning journey: https://github.com/SAP-samples/teched2020-DEV165
Best Regards,
Gautham

**Comment by gauthamkrishna-sap** [comment]
Hello,
This tutorial has been deprecated. We will replace it with an updated tutorial in the coming weeks. Please watch out for "Integration Suite tutorials" in the SAP Tutorial Navigator for new updates. 
Thank you.
