### ISSUE TITLE
Add Multiple Receivers and Convert Message Format

### ISSUE THREAD

**Issue by jmalla** [SAPDocuments/Issues#332]
Tutorials: https://developers.sap.com/tutorials/cp-integration-add-multiple-receiver-formats.html
--------------------------

Step 1: Add additional routes to the router step - 
item  - Save, deploy and execute the flow with the existing input message with the changed address field again.
This address will not work with the logic:
2025 M Street,Northwest,Washington DC,20036:

The address needs to be like this in order for the route to work:
2025,M Street,Northwest,Washington DC,20036,USA

The route logic is looking for KWA2MNW2U - note that there is a U at the end - so the address should have USA.  Also, you need to add a comma after the 2025 because the Groovy script is splitting the address string with the comma delimiter.

Please correct the tutorial.

Regards,
Jay

**Comment by gauthamkrishna-sap** [comment]
Hello,

Apologies for the inconvenience.

We are still working on updating it. In the meantime, I can offer you this session from TechEd 2020: https://github.com/SAP-samples/teched2020-DEV165

This also contains mail adapter configuration with REST API and a non-SAP system. Hope you can get some hands on experience with this while we update this series.

Thanks and Best Regards,
Gautham

**Comment by gauthamkrishna-sap** [comment]
Hello,
We are still working on updates for this series. In the meantime, this tutorial from TechEd is a great alternative to continue your integration learning journey: https://github.com/SAP-samples/teched2020-DEV165
Best Regards,
Gautham

**Comment by gauthamkrishna-sap** [comment]
Hello,
This tutorial has been deprecated. We will replace it with an updated tutorial in the coming weeks. Please watch out for "Integration Suite tutorials" in the SAP Tutorial Navigator for new updates. 
Thank you.
