### ISSUE TITLE
Set Up Integration Suite Trial

### ISSUE THREAD

**Issue by iamdipan** [SAPDocuments/Issues#334]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html
--------------------------

I am trying to use openconnector using my trial account, it is showing authorization issue. can you please help me on this issue?\

![image](https://user-images.githubusercontent.com/83091793/115920900-70d62a00-a498-11eb-8b89-992c338af371.png)

**Comment by Karunaharan** [comment]
Hi @iamdipan, When do you face this issue? Is it while adding the Open Connector capability in your Integration Suite trial account? Please let us know.

**Comment by iamdipan** [comment]
@Karunaharan I am facing this when I am trying to open the openconnector url after adding it in integration suite capability.

**Comment by Karunaharan** [comment]
@iamdipan - By following the instructions of this tutorial, you won't be adding the necessary roles for Open Connectors capability.
In steps 4.1 and 5.5, select "Extend Non-SAP Connectivity". That should help you.

**Comment by iamdipan** [comment]
@Karunaharan tried with above mentioned steps, still facing the same issue. Cleared browser cache and tried again, still getting same error.

**Comment by Karunaharan** [comment]
@iamdipan - Please try following these instructions https://help.sap.com/viewer/51ab953548be4459bfe8539ecaeee98d/sap.cp.integration.suite/en-US/2c6214a3228e4b4cba207f49fda92ed4.html
