### ISSUE TITLE
Create an API Provider System

### ISSUE THREAD

**Issue by jmalla** [SAPDocuments/Issues#335]
Tutorials: https://developers.sap.com/tutorials/hcp-apim-create-provider.html
--------------------------

Please update the screenshots.  The documentation states about connecting to ES5.  But the screenshots show ES4.

Thanks,
Jay

**Comment by kulkarnir** [comment]
Hello Jay, 

Thanks for your feedback, we are updating the tutorial.

Regards, 
Raghu

**Comment by kulkarnir** [comment]
We will publish with updated screenshots soon 

Regards, 
Raghavendra
