### ISSUE TITLE
Add an API Proxy to a Product

### ISSUE THREAD

**Issue by jmalla** [SAPDocuments/Issues#336]
Tutorials: https://developers.sap.com/tutorials/hcp-apim-create-product.html
--------------------------

When I try to publish the product, I get the error - Unable to publish Product - without any details.  I am not sure why this issue is happening.

Thanks,
Jay

**Comment by kulkarnir** [comment]
Hello Jay,

Could you please check if you have enabled API BUsiness Hub Enterprise (Developer Portal).

Regards, 
Raghavendra
