### ISSUE TITLE
Protect Your API Proxy by Adding Application Key Verification

### ISSUE THREAD

**Issue by jmalla** [SAPDocuments/Issues#337]
Tutorials: https://developers.sap.com/tutorials/hcp-apim-verify-api.html
--------------------------

This tutorial seems to be incomplete.  After completing tutorial 5 of 5, it should have steps to call the API from Postman to verify all of the tutorial steps and the resulting end product is working.

Thanks,
Jay

**Comment by kulkarnir** [comment]
Hello Jay,

Thanks for your feedback, we will enhance the tutorial

Regards, 
Raghavendra
