### ISSUE TITLE
Protect Your API Proxy by Adding Application Key Verification

### ISSUE THREAD

**Issue by jmalla** [SAPDocuments/Issues#338]
Tutorials: https://developers.sap.com/tutorials/hcp-apim-verify-api.html
--------------------------

I am unable to find the answer for the question in - Step 4: Learn about assigning multiple policies
Which property do you set when creating a policy to determine if you should check the response or request?

I read through the article referenced at https://blogs.sap.com/2016/06/24/part-10-assigning-multiple-policies-to-an-api-proxy/

It would be better to have this question be in the form or a radio button instead of free form text.

Thanks,
Jay

**Comment by kulkarnir** [comment]
Hello Jay, 

Thanks for the feedback,  we will take care 

Regards, 
Raghavendra

**Comment by Ciutipie** [comment]
Just wondering what is the correct answer to this ?:) Could you let us know @kulkarnir
