### ISSUE TITLE
"Adapt UI" option missing after completing UI5 App mission

### ISSUE THREAD

**Issue by ahusemann84** [SAPDocuments/Issues#339]
Mission: https://developers.sap.com/mission.sapui5-cf-launchpad.html
--------------------------

Hi, 

I completed the aforementioned mission and I am able to open the App via the Lauchpad Service.
However the UI Adaptation offered by the Flexibility Services are not available, despite it being mentioned in the tutorial summary.

I checked the manifest.json, there the property flexEnabled is set to true. 

I also had a look at the official documentation, but this was of no help to me: https://help.sap.com/viewer/0f8b49c4dfc94bc0bda25a19aa93d5b2/Cloud/en-US/85285044a12e4cbcb85b21d8e7f7c402.html

Is there anything I missed?

Thanks and BR
Arne

**Comment by IObert** [comment]
Hi Arne,

you were able to make keyuser changes to the UI in an earlier version of this tutorial (that used another approach that is now deprecated). So the only feature of the flex service that are currently supported is the "Variant Management" of [step 5](https://developers.sap.com/tutorials/sapui5-fiori-cf-deploy.html). 
We're working on making more flex services available in the near future - so stay tuned.

I hope this answers your question.

Regards,
Marius

**Comment by ahusemann84** [comment]
Thanks, Marius this answers my question for now an I am looking forward to see more flexibility services in action soon.

BR
Arne
