### ISSUE TITLE
Consume the API Proxy in SAP Web IDE

### ISSUE THREAD

**Issue by js1972** [SAPDocuments/Issues#34]
Tutorial: https://developers.sap.com/tutorials/hcp-apim-webide-int.html
--------------------------

Write here what you need help with ...

This tutorial is not working in the CF runtime nor with BAS.

In the step where we create a destination to the dev portal (APIM) it says we need to use AppToAppSSO - however this option does not existing Cloud foundry - how do we proceed?

In the step where you run a template/generator in WebIDE I an trying with Business Application Studio. In BAS we cannot see the destinations as available systems to choose from. The only way I can see the destination in BAS is to add "WebIDEUsage: odata_abap" - but then I get Authentication issues.

Is it not possible to use APIM from BAS as of yet? If it is can you please point me to the documentation on how it is done?

**Comment by shilpavij** [comment]
This tutorial will be decommissioned and the team is working on provisioning the new ones.

I hope this helps!

**Comment by js1972** [comment]
Thankyou for the update. I would say it's best to pull this tutorial immediately if it doesn't work. Same goes for all other tutorials that don't work as described.

**Comment by shilpavij** [comment]
Dear Raghu,

Can you please take care.

Regards
Shilpa

Sent from my iPhone

On 12-Jan-2021, at 7:48 PM, Jason Scott <notifications@github.com> wrote:

﻿

Closed #34<https://github.com/SAPDocuments/Issues/issues/34>.
