### ISSUE TITLE
Test the Business Rules API from SAP API Business Hub

### ISSUE THREAD

**Issue by krishraheja** [SAPDocuments/Issues#340]
Hi Colleague,

I am following your tutorial “Test the Business Rules API from SAP API Business Hub" in series “MISSION: Get Started with SAP Business Rules Service ".

I have achieved all the steps but while testing, I am getting the error as mentioned in the attachment. I can’t understand the reason of the issue. It would be very thankful if you can help me in understanding the issue.

Thanks a lot in advance !

Best Regards,
Krishan
[SAP BTP Business Rule Service.docx](https://github.com/SAPDocuments/Issues/files/6392008/SAP.BTP.Business.Rule.Service.docx)

**Comment by VandanaVasudevan** [comment]
This issue is resolved.
