### ISSUE TITLE
Use Redis in the Kyma Runtime to Store and Retrieve Data

### ISSUE THREAD

**Issue by D041453** [SAPDocuments/Issues#342]
Tutorials: https://developers.sap.com/tutorials/cp-kyma-redis-function.html
--------------------------

Hi Colleagues, 

this is just a minor thing to mention. When working through the tutorial I noticed that terminology has changed in some places and the screenshot and terms in the tutorial are outdated. Maybe you find time to update, for example in:

Step 7.4 - Event Triggers seems to be called Event Subscriptions in the meantime.

Best regards,
 Alex

**Comment by jcawley5** [comment]
Hi Alex,

Thank you for the comment. The tutorials have been updated to reflect the name changes.

Regards,
Jamie
