### ISSUE TITLE
Install the Kubernetes Command Line Tool

### ISSUE THREAD

**Issue by bcschaich** [SAPDocuments/Issues#343]
Tutorials: https://developers.sap.com/tutorials/cp-kyma-download-cli.html
--------------------------
The command names in this section:
KUBECONFIG="<KUBECONFIG_FILE_PATH>"
is not sufficient. You also need to add the file name there. Found out myself, but could be easier if mentioned.

**Comment by jcawley5** [comment]
Thank you for your feedback. I'll add some additional detail which will be available in the next push to production.
