### ISSUE TITLE
Create an SAP BTP ABAP Environment Trial User

### ISSUE THREAD

**Issue by petehalm** [SAPDocuments/Issues#344]
Tutorials: https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html
--------------------------
Hi,
I'm on step 3.2 and my popup isn't quite the same as shown in the document. So I went back and selected Service Key and imported my json key from the previous step. Now when I go to login to the connection it takes my credentials, but the Organization has only 1 option: 03dce686trail. However, it should be : 47d53e63trial (Step 1.3). Also, I guessed at my credentials for the connection and not sure where that is maintained. Currently using Eclipse Version: 2021-03 (4.19.0)
Build id: 20210312-0638.
Thanks,
Pete

**Comment by mervey45** [comment]
Hi @petehalm, 

the screenshots depends on your adt version. You have 2 Options to select. You can select service key and then paste your service key from SAP BTP Cockpit trial. Option 2 is to navigate through the wizards. This means, you can then select Use Cloud Foundry Environment.
![image](https://user-images.githubusercontent.com/27953324/116656553-2ae3ff00-a98d-11eb-9449-a357eac81ed5.png)


Are you sure, that you have downloaded the latest service key from SAP BTP Cockpit? 

I would suggest you to use option 2. Navigate through the wizards. So you need to select Use SAP BTP Cloud Foundry Environment.
And then you move on with step 3.3 https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html#acb2798f-3555-46d1-8d59-6c824bf59509.

If you still face issues, please contact me again. I hope I could help you.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
