### ISSUE TITLE
[Deploy CAP with SAP HANA Cloud project as MTA] Updating service "MyHANAApp-xsuaa-service"

### ISSUE THREAD

**Issue by LarsVlyminckx** [SAPDocuments/Issues#345]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-deploy-mta.html
--------------------------
Hi

I'm currently following this tutorial but I'm stuck at Step 3: Deploy your application to SAP BTP, Cloud Foundry runtime

When I want to deploy my app I get this error: 
Updating service "MyHANAApp-xsuaa-service"...
Service operation failed: Controller operation failed: 502 Updating service "MyHANAApp-xsuaa-service" failed: Bad Gateway: CF-ServiceBrokerBadResponse(10001): Service broker error: Service broker xsuaa failed with: org.springframework.cloud.servicebroker.exception.ServiceBrokerException: Error updating application myhanaappfinal!t85382 (Cannot change AppId with update.) 

Any idea how to fix this?

If you need more information, I'll gladly give it.

Thanks in advance.

Lars

**Comment by jung-thomas** [comment]
Interesting that it wouldn't update the service.  That worked a few weeks ago.  In fact if you didn't change the application ID you received this error:
Therefore if you package the complete application and deploy it; when trying to deploy the UAA service instance again you will receive an error that the Application with the given name already exists.
![image](https://user-images.githubusercontent.com/12159356/116696690-3be23f80-a990-11eb-9394-4927791af74f.png)

You can try removing the final from the id in the xs-security.json but I think that will just go back to this previous error.  If the service broker will no longer allow updating either then the only option left is to delete the myHANAApp-xsuaa-service before you deploy.  You can do that from the command line with a cf delete-service <service-name> before you deploy.

**Comment by LarsVlyminckx** [comment]
It is working! 
I removed the "final" and I could deploy it.
But now the local isn't working anymore.
I get this error page
![image](https://user-images.githubusercontent.com/33087668/116705969-67cfe600-a9cd-11eb-9230-a46fad78d576.png)
How can I fix this? Or do I to create a new uaa or?

**Comment by jung-thomas** [comment]
Well that's the thing, once you deploy the final MTA into the same space the local test with the XSUAA won't work any longer.  Normally you would have separate spaces for this. You could leave the redirect_url in the xs-security.json if you don't mind it being there in the deployed version.  It's technically less secure and not something you'd want to deploy into production for real; but if you just want both to run within a trial space this is an acceptable risk.

**Comment by LarsVlyminckx** [comment]
So I added the redirect_url back in the xs-security.json but now I have this error "again"
![image](https://user-images.githubusercontent.com/33087668/116711099-cfd4fb00-a9d2-11eb-8103-bf44edece719.png)

**Comment by jung-thomas** [comment]
I guess if you really want to deploy into the same space and test locally in that space you are going to have to wildcard the redirect URI completely.  This is why this tutorial isn't part of the overall series because to deploy you should really do so into a separate space. But for separate deployment into two spaces with real security you are beyond the scope of the trial.
