### ISSUE TITLE
Deploy Your Node.js App with the Cloud Foundry CLI

### ISSUE THREAD

**Issue by strawherotk** [SAPDocuments/Issues#346]
Tutorials: https://developers.sap.com/tutorials/cp-node-deploy-cf-cli.html
--------------------------

In Step 2, I think the **tutorial is not correct**.
Instead of using "cf push", it should be "cf push APP_NAME"

If I use only "cf push", there will be an error.

Could you please check & update?

Thanks.

**Comment by jung-thomas** [comment]
So you are saying it needs an extra space on the end after cf push?  I don't believe that would be necessary.

**Comment by strawherotk** [comment]
Hi @jung-thomas ,
What I proposed to change is:
![image](https://user-images.githubusercontent.com/19721878/117031549-e0ff6e00-ad2a-11eb-8338-08e0ca9cb889.png)

Unfortunately, the <APP_NAME> is disappeared after publishing, because of the Markdown format (I think).
I'm sorry that I didn't check my question after upload.

I've updated the question. Could you please check again?

Thanks.

**Comment by jung-thomas** [comment]
I just tested and the tutorial is correct.  The usage of an appname after the cf push is not needed.  The cf push command will pickup and use the manifest.yaml and gather all settings from that. This is as the tutorial is intended.
![image](https://user-images.githubusercontent.com/12159356/117035948-e9c45580-acd2-11eb-86ca-07a49ea96d65.png)

If that didn't work for you maybe you were in the /myapp subdirectory when you issued the cf push command or perhaps you put the manifest.yaml in the wrong folder.  It should be in the nodetutorial root folder.
