### ISSUE TITLE
Deploy Your First SAPUI5 App

### ISSUE THREAD

**Issue by solus1002** [SAPDocuments/Issues#348]
Tutorials: https://developers.sap.com/tutorials/appstudio-sapui5-create.html
--------------------------
After the deployment, I tried to open the site with Url, but I got error messages as the attachment. 
I tried a new DevSpace or even with a new subaccount. But always the same error occurs. 
Could you please help me? 
Thank you.

![2021-05-05 20_12_55-Welcome](https://user-images.githubusercontent.com/73489035/117189286-4f513880-adde-11eb-9435-899493e4d24f.png)

**Comment by longieirl** [comment]
Hi,

It looks like you are using the portal service rather than the launchpad service. On the last part of the tutorial, referened above, you need to execute;

```
cf html5-list -di sap-btp-sapui5-destination-service -u --runtime cpp
```

Can you please run this command and try to load the app?

John

**Comment by masahiroo** [comment]
Hi,

I haven't specified the service either portal or launchpad. And the same URL is returned for both cpp and launchpad as following.

Regards, Masahiro

====
user: sapui5 $ cf html5-list -di sap-btp-sapui5-dest-srv -u --runtime cpp
Getting list of HTML5 applications available via destinations in org 4f372421trial / space dev as masahiro.obata@sap.com...
OK

name           version   app-host-id                            service name     destination name           last changed                    url   
sapbtpsapui5   1.0.0     9a3a629e-ffce-4767-bcd6-2e7c33c4be29   sap-btp-sapui5   sap-btp-sapui5_repo_host   Mon, 10 May 2021 12:50:42 GMT   https://4f372421trial.cpp.cfapps.us10.hana.ondemand.com/d4042a4b-076a-4ac5-823f-19a9585e4d85.sap-btp-sapui5.sapbtpsapui5-1.0.0/   
user: sapui5 $ 
user: sapui5 $ cf html5-list -di sap-btp-sapui5-dest-srv -u --runtime launchpad
Getting list of HTML5 applications available via destinations in org 4f372421trial / space dev as masahiro.obata@sap.com...
OK

name           version   app-host-id                            service name     destination name           last changed                    url   
sapbtpsapui5   1.0.0     9a3a629e-ffce-4767-bcd6-2e7c33c4be29   sap-btp-sapui5   sap-btp-sapui5_repo_host   Mon, 10 May 2021 12:50:42 GMT   https://4f372421trial.cpp.cfapps.us10.hana.ondemand.com/d4042a4b-076a-4ac5-823f-19a9585e4d85.sap-btp-sapui5.sapbtpsapui5-1.0.0/   
user: sapui5 $

**Comment by longieirl** [comment]
Linking to this issue - https://github.com/SAP/cf-html5-apps-repo-cli-plugin/issues/42

@raz-korn is correct, if you update the url as follows;

https://4f372421trial.launchpad.cfapps.us10.hana.ondemand.com/d4042a4b-076a-4ac5-823f-19a9585e4d85.sap-btp-sapui5.sapbtpsapui5-1.0.0/

It should work for you.

John
