### ISSUE TITLE
Create an ABAP Database Table and Relevant ABAP Dictionary Objects

### ISSUE THREAD

**Issue by RenukaRaj** [SAPDocuments/Issues#35]
Tutorial: https://developers.sap.com/tutorials/abap-dev-create-table.html
--------------------------

Write here what you need help with ...

Am new to ABAP, I CAN FIND below lines,

 GET TIME STAMP FIELD DATA(zv_tsl).

What is ZV_TSL. How to create timestamp related  datas?

**Comment by julieplummer20** [comment]
Hi, 
I am not sure I understand your question.
You simply enter the code in the tutorial. The system then calls the current date and time and stores it in the table ZACCOUNTS_XXX in the column "lastchangedat". 
ZV_TSL has the type timestamp.
If you select ZV_TSL, then choose F2 (ABAP Element Info), then you can see this.
![image](https://user-images.githubusercontent.com/22739917/104457387-4aa41280-55aa-11eb-9d78-e5eb9e5ded5f.png)

Are you getting an error when you do this?
Please just let me know.
BR Julie.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
