### ISSUE TITLE
Create a Chatbot that Lets Customers Track Packages

### ISSUE THREAD

**Issue by klickerlebnis** [SAPDocuments/Issues#350]
Tutorials: https://developers.sap.com/tutorials/cai-bot-shipping-1-track-bot.html
--------------------------

Would be great to add a further screenshot in **step 7 section 3** to better follow up on following instructions:

- Click Add Quick Reply twice, and:
- For the first, add Yes for both the title and value.
- For the second, add No for both the title and value.

Thanks,
Dominik

**Comment by thecodester** [comment]
I have added an image to that section. Is that what you meant?

https://github.com/SAPDocuments/Tutorials/commit/880ec6034b3e6131824b8443b3d4ab05d15786a7

**Comment by thecodester** [comment]
I will close the issue as I've added the contents, but feel free to provide additional comments.
