### ISSUE TITLE
Create a Chatbot that Lets Customers Track Packages

### ISSUE THREAD

**Issue by klickerlebnis** [SAPDocuments/Issues#351]
Tutorials: https://developers.sap.com/tutorials/cai-bot-shipping-1-track-bot.html
--------------------------

In step 6 section 4 the tutorial can be improved by adding yes and no as "unset memory field" to add exception handling to the question "Could you give me your tracking number?". Otherwise an error occurs.

![image](https://user-images.githubusercontent.com/37261568/117331762-5ab46a80-ae97-11eb-8a55-191606294c24.png)

![image](https://user-images.githubusercontent.com/37261568/117331321-f1345c00-ae96-11eb-82cb-b128078f479d.png)

- For the message, enter _Could you give me your tracking number?_
- **Add two unset memory fields with values yes and no**
- Click Save, then click Back.

**Comment by thecodester** [comment]
I have added this unset instructions: https://github.com/SAPDocuments/Tutorials/commit/24f57313f4633dd799731ceb3d592de172b3dbf3

Please check.

**Comment by thecodester** [comment]
I will close the issue since the tutorial is updated but feel free to reopen or provide additional comments.
