### ISSUE TITLE
Perform Actions On Cards To Support Your Business Case

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Issues#353]
**Tutorials: https://developers.sap.com/tutorials/cp-mobile-cards-booster-starter.html**

Steps:
**Step 3: View supplier contact card on your mobile device
Step 4: View sales order approval card on your mobile device**
--------------------------
**Issue:**
Contact Card and Sales Order Approval Card are auto subscribed, So please remove the steps to subscribe to these cards in Step 3 and Step 4.
Instead add a note that if the cards are not visible, then we have to unsubscribe and subscribe to these cards again and then do a pull refresh for the cards to be visible.

Best Regards,
Priyanka

**Comment by VanitaDhanagar** [comment]
issue is still exist .

**Comment by sandeep-tds** [comment]
@PriyankaShivakumar  @VanitaDhanagar Thank you for raising the issue. I have updated the tutorial. The new version should be available in the coming week.

**Comment by sandeep-tds** [comment]
The tutorial has been updated, thus I am closing the ticket.
