### ISSUE TITLE
View the SAP BTP from 10,000 Meters

### ISSUE THREAD

**Issue by Amster2017** [SAPDocuments/Issues#354]
Tutorials: https://developers.sap.com/tutorials/cp-explore-cloud-platform.html
--------------------------

The buttons on the tutorial do not work correctly. Neither in Safari, nor in Firefox.

When you submit an answer, you get a "Technical error" after a while.

Kind regards,

Steffen

**Comment by thecodester** [comment]
The buttons work again (actually a week ago). @Amster2017  Is everything OK for you? Please don't be discouraged and please go ahead and complete the tutorial.
