### ISSUE TITLE
Add Automated System Tests with the SAPUI5 Test Recorder to Your CI/CD Pipeline

### ISSUE THREAD

**Issue by riteshdube2020** [SAPDocuments/Issues#355]
Tutorials: https://developers.sap.com/tutorials/cp-cicd-systemtest-recorder.html
--------------------------

Write here what you need help with ...
none of the done buttons working , when click on it it do nothing.  I even tried incognito mode but its same. 
<img width="549" alt="open sap error" src="https://user-images.githubusercontent.com/60839056/117623357-4e7b2680-b191-11eb-82a4-c21f98b592a7.png">

**Comment by Jessica-Katz** [comment]
Hi @riteshdube2020,
the Done buttons only work when you're logged in.
The user should be the same as your SAP Community user. For more information on registering a profile on SAP Community, see [Registration and Profile Maintenance](https://community.sap.com/resources/registration-and-profile).

**Comment by Jessica-Katz** [comment]
Hi @riteshdube2020,
the Done buttons only work when you're logged in.
The user should be the same as your SAP Community user. For more information on registering a profile on SAP Community, see [Registration and Profile Maintenance](https://community.sap.com/resources/registration-and-profile).
