### ISSUE TITLE
Create Database Artifacts Using Core Data Services (CDS) for SAP HANA Cloud

### ISSUE THREAD

**Issue by krishraheja** [SAPDocuments/Issues#356]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-create-database-cds.html
--------------------------

Hi Support,

In step 3.3, it is mention to use SAP HANA Project view, but I can't see this in my dev space.

Please suggest how to get it.
[BAS Dev space issue.docx](https://github.com/SAPDocuments/Issues/files/6451935/BAS.Dev.space.issue.docx)

**Comment by jung-thomas** [comment]
It looks like you missed doing Step 1 - Part 4 of the previous tutorial in this Mission. 
https://developers.sap.com/tutorials/hana-cloud-cap-create-project.html

You need to configure you Dev Space to include the SAP HANA tools. They are not included automatically. This is what this step does. You can stop your dev space, press the pencil icon and perform this step again on your existing dev space.
