### ISSUE TITLE
Set Up Account for Document Information Extraction and Go to Application

### ISSUE THREAD

**Issue by FarozanFarman** [SAPDocuments/Issues#357]
Tutorials: https://developers.sap.com/tutorials/cp-aibus-dox-booster-app.html
--------------------------
Issue: https://github.com/SAPDocuments/Issues/issues/143

Usually, for deleting a subaccount with Saas applications, we first delete the service instances and then the subscriptions of those Saas applications.
But as per the above-mentioned ticket, here, for "Document Information Extraction Trial UI", we need to delete the subscription first and then the service key and service instance.
As an end-user, I might not be aware of this and can get stuck.
Just to avoid any confusion, I wanted to know why do we follow a unique approach for this particular Saas Application?

Labels :
Landscape Labels: trail1, trail2
SCPTest-docinfo : Get Started with Document Information Extraction
Label: SCPTest-2105
Priority label : 'Low'

Thanks and Regards,
Farozan

**Comment by Juliana-Morais** [comment]
Hi Farozan,

The Saas Application relies on the service instance. You cannot get access to the Saas Application without first creating a service instance, and you all cannot delete the Saas Application, if you have already deleted the service instance.

Best regards,
Juliana
