### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by kalmanl** [SAPDocuments/Issues#36]
Tutorial: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html
--------------------------

step 8, Consume Services, documentation not updated

The interface shows different fields from the guide. 
I'm using a trial account followed by previous guidelines 

there is an authentication section shown which dos not appear in the documentation, tried to put my auth info from "Subaccount: trial - Destinations" but with no success 
Screenshot 
![image](https://user-images.githubusercontent.com/9283404/103767569-89c1e900-5029-11eb-946b-67da727b5315.png)

**Comment by raz-korn** [comment]
Hi @kalmanl ,

Please refer to issues: [5493](https://github.com/SAPDocuments/Tutorials/issues/5493), [6290](https://github.com/SAPDocuments/Tutorials/issues/6290).

Regards - Raz

**Comment by kalmanl** [comment]
Hi
Raz, Thanks for the answer, I looked and the issues you referred to. I checked my destination connection and it looks good. And I have access to ES5 service in the [link](https://sapes5.sapdevcenter.com/sap/opu/odata/iwbep/GWSAMPLE_BASIC/$metadata) but I still get the user and password fields and it says authentication error.
Can you please assist me with how to proceed 

I think in general its good to add a note if there is an error to check your destination service or your connection to ES5 or to explain the relation

**Comment by kalmanl** [comment]
Hi @raz-korn 

here is my destination confirmation 

![image](https://user-images.githubusercontent.com/9283404/104117352-5c2ab780-5329-11eb-93cf-0679d1998da8.png)

Thanks - Kalman

**Comment by raz-korn** [comment]
Hi @kalmanl ,

can you share the output of running the following command in the **BAS** terminal:
curl -v -i "ES5.dest/sap/opu/odata/iwbep/GWSAMPLE_BASIC/BusinessPartnerSet?%24top=1"

to open a new terminal in BAS:
![image](https://user-images.githubusercontent.com/6040433/104128849-89e81e80-5372-11eb-8007-38351f17e8f4.png)

Regards - Raz

**Comment by kalmanl** [comment]
Hi @raz-korn 
I attached the output of the command 
![image](https://user-images.githubusercontent.com/9283404/104449086-bab09980-55a6-11eb-8f83-c11c16f38c69.png)

* Uses proxy env variable no_proxy == 'localhost,127.0.0.1,github.com,.github.com,.npmjs.org,.yarnpkg.com,npm.sap.com,.maven.apache.org'
* Uses proxy env variable http_proxy == 'http://127.0.0.1:8887'
*   Trying 127.0.0.1:8887...
* Connected to 127.0.0.1 (127.0.0.1) port 8887 (#0)
> GET http://ES5.dest/sap/opu/odata/iwbep/GWSAMPLE_BASIC/BusinessPartnerSet?%24top=1 HTTP/1.1
> Host: ES5.dest
> User-Agent: curl/7.74.0
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
HTTP/1.1 401 Unauthorized
< Content-Type: text/html; charset=utf-8
Content-Type: text/html; charset=utf-8
< Date: Wed, 13 Jan 2021 11:52:29 GMT
Date: Wed, 13 Jan 2021 11:52:29 GMT
< Sap-System: ES5
Sap-System: ES5
< Set-Cookie: ARBE=24e67db96cb1d86766077f9542d49a8aac7b4d0c8f725da1e1289cf06493ce90a31cf8cbb327a9b114ba2bcf51267e97; Path=/; HttpOnly;
Set-Cookie: ARBE=24e67db96cb1d86766077f9542d49a8aac7b4d0c8f725da1e1289cf06493ce90a31cf8cbb327a9b114ba2bcf51267e97; Path=/; HttpOnly;
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload;
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload;
< Vary: Accept-Encoding
Vary: Accept-Encoding
< Www-Authenticate: Basic realm="SAP NetWeaver Application Server [ES5/002]"
Www-Authenticate: Basic realm="SAP NetWeaver Application Server [ES5/002]"
< X-Frame-Options: SAMEORIGIN
X-Frame-Options: SAMEORIGIN
< X-Request-Id: 885fad02-a189-4eaa-7c9d-5afe0973b91b
X-Request-Id: 885fad02-a189-4eaa-7c9d-5afe0973b91b
< X-Vcap-Request-Id: 885fad02-a189-4eaa-7c9d-5afe0973b91b
X-Vcap-Request-Id: 885fad02-a189-4eaa-7c9d-5afe0973b91b
< Content-Length: 1236
Content-Length: 1236

< 
<html><head><title>Logon Error Message</title><META http-equiv="Content-Type" content="text/html;charset=UTF-8"><style type="text/css">body { font-family:tahoma,helvetica,sans-serif;color:#333333;background-color:#FFFFFF; }td { font-family:tahoma,helvetica,sans-serif;font-size:70%;color:#333333; }h1 { font-family:tahoma,helvetica,sans-serif;font-size:160%;font-weight:bold;margin-top:15px;margin-bottom:3px;color:#003366; }h2 { font-family:verdana,helvetica,sans-serif;font-size:120%;font-style:italic;font-weight:bold;margin-top:6px;margin-bottom:6px;color:#999900; }p { font-family:tahoma,helvetica,sans-serif;color:#333333;margin-top:4px;margin-bottom:4px; }ul { font-family:tahoma,helvetica,sans-serif;color:#333333;list-style-type:square;margin-top:8px;margin-bottom:8px; }li { font-family:tahoma,helvetica,sans-serif;color:#33333;margin-top:4px; }.emphasize { color:#333333;background-color:#C8E3FF;padding:5px;}.note { color:#CC6600; }a { font-family:tahoma,helvetica,sans-serif;text-decoration:underline;color:#336* Connection #0 to host 127.0.0.1 left intact
699; }a:visited { color:#001166; }a:hover { text-decoration:none; }</style></head><body><table cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td><h1>Logon failed</h1></td></tr></table></body></html>user: user $

**Comment by raz-korn** [comment]
Hi @kalmanl ,

I can think of the following, which will eventually come down to one solution: Changing the password for ES5:
- Most probably, your user is locked (too many login attempts). 
- The password for the destination configuration on SCP Cockpit is incorrect.

Please note that after you change the password for ES5 (using WEBGUI), you'll need to update the SCP destination configuration with the new password.

BTW - I assisted yesterday a colleague with a similar issue. You might be able to access ES5 using WEBGUI. However, if you logout and then try to login again, you'll get the "too many..." notification.

Regards - Raz

**Comment by kalmanl** [comment]
Hi @raz-korn 
I tried, It works now! not sure exactly why, I didn’t change my password, but I reviewed  my destination configuration 

I think in general its good to add a note if there is an error to check your destination service or your connection to ES5 or to explain the relation, or explain the relation between the app were creating and the destination service 

Thanks for your assistance 
Kalman
