### ISSUE TITLE
Extend your Simple Data Model with a Second Entity

### ISSUE THREAD

**Issue by ksadashivnayak** [SAPDocuments/Issues#363]
Tutorials: https://developers.sap.com/tutorials/odata-06-extend-odata-service.html
--------------------------

Write here what you need help with ...Staying with Northwind, let’s look at the details for the seventh category next, including a list of products in that category /Categories(7)$?expand=Products (only a couple of the products are shown in this sample output, for brevity):

Here the Query is incorrect it should be  ($ and ? interchanged)
category /Categories(7)?$expand=Products

**Comment by qmacro** [comment]
Nice spot, @ksadashivnayak ! You get my "eagle eye" award today :-) Thank you, [fixed](https://github.com/SAPDocuments/Tutorials/commit/c59a552b5e80558457b4e0951e2ffa62e23450a2)!
