### ISSUE TITLE
Define and Expose a CDS-Based Travel Data Model

### ISSUE THREAD

**Issue by shivakumar-p-sap** [SAPDocuments/Issues#365]
Tutorials: https://developers.sap.com/tutorials/abap-environment-data-model.html
--------------------------
A last step can be added saying "Click on Travel processor to view the application" and 2 screenshots can be added.
![Step_Last-1](https://user-images.githubusercontent.com/65213299/117929957-0720a180-b31b-11eb-80fc-77d0ddf5c3ef.PNG)

![Step_Last](https://user-images.githubusercontent.com/65213299/117929986-10117300-b31b-11eb-8a08-521d5e414a38.PNG)

Labels:
Landscape Labels: trail1 & trail2
Scenario Label: SCPTest-fabap 
Sprint Label: SCPTest-2105A
Priority: Low

Regards
Shivakumar P

**Comment by maulik-parekh** [comment]
Dear Team,

Unable to view Create & Update button in Preview.


Regards,

**Comment by mervey45** [comment]
Hi @maulik-parekh ,

can you please add a space anywhere in your coding in your data defintion ZI_TRAVEL_M_XXX and your behavior definition  ZI_TRAVEL_M_XXX and activate both. Then start the preview of your main entity TravelProcessor in your service binding again?

Thank you.

Best regards, 
Merve

**Comment by maulik-parekh** [comment]
Hi @mervey45 ,

Thank you for your suggestion. I have followed the same and reactivated both. However Create & Update button not visible.
![image](https://user-images.githubusercontent.com/84318760/118480684-34f95200-b730-11eb-98dd-b01ffbc7005f.png)


Regards,

**Comment by mervey45** [comment]
Hi @maulik-parekh ,

did you create also the behavior definition for the projection view? If no, please do so. If yes, please also add a space here, activate and start your preview again.


Best regards, 
Merve

**Comment by maulik-parekh** [comment]
Hi @mervey45 ,

Yes, I did created in line to the tutorial (https://developers.sap.com/group.abap-env-restful-managed.html).

![image](https://user-images.githubusercontent.com/84318760/118484176-8e638000-b734-11eb-85f5-4020a4cd745b.png)



Regards,

**Comment by mervey45** [comment]
Hi @maulik-parekh ,

can you show me the code of both of your behavior definitions?

Best regards, 
Merve

**Comment by maulik-parekh** [comment]
Yes,

1. Code behavior for ZI_TRAVEL_M_M as below:
managed implementation in class ZCL_BP_I_TRAVEL_M_M unique; //zbp_i_travel_m_m unique;

define behavior for ZI_TRAVEL_M_M alias Travel
persistent table ztravel_m
etag master last_changed_at
lock master
{

// key that will be automatically generated by the framework
  field ( readonly, numbering : managed ) mykey;

  // semantic key calculated in a determination
  field ( readonly ) travel_id;

  // administrative fields (read only)
  field ( readonly ) last_changed_at, last_changed_by, created_at, created_by;

  // mandatory fields that are required to create a travel
  field ( mandatory ) agency_id, overall_status, booking_fee, currency_code;

  // mandatory fields that are required to create a travel
  field ( mandatory ) Begin_Date, End_Date, Customer_ID;

  // standard operations for travel entity
  create;
  update;
  delete;

  // instance action and dynamic action control
  action ( features : instance ) acceptTravel result [1] $self;

  // validations
  validation validateCustomer on save { field customer_id; }
  validation validateDates on save { field begin_date, end_date; }
  validation validateAgency on save
  { field agency_id; }

  // determination
  determination CalculateTravelKey on modify
  { create; }
}


2. Code behavior for zc_travel_M_M  as below:

projection;

define behavior for zc_travel_M_M alias TravelProcessor
use etag
{
  use create;
  use update;
  use delete;

  use action acceptTravel;
}



Regards,

**Comment by mervey45** [comment]
Hi @maulik-parekh ,

the coding seems to be ok. Can you please add the space coding in your data defintion ZI_TRAVEL_M_XXX and your behavior definition ZI_TRAVEL_M_XXX and activate both aain?. Then start the preview of your main entity TravelProcessor in your service binding again?

Maybe 

Best regards,
Merve

**Comment by maulik-parekh** [comment]
HI @mervey45,

I have reactivated as suggested. However, Create button not visible.

Is it because I have used Binding Type: OData V4 - UI ?


Also, It is said in one line that '
The behavior implementation is created for travel booking. By using the managed approach, the implementation of create, update and delete is done automatically.'


Regards,

**Comment by mervey45** [comment]
Hi @maulik-parekh ,

yes, you need OData V2 - UI, otherwise you can get issues with the ui.

If you try it out with OData V2 - UI, then it should work.

Best regards, 
Merve

**Comment by maulik-parekh** [comment]
Hi @mervey45 

Yes, I have created new Service Binding with OData V2 UI and Create Button is visible !

I appreciate your help and thank you  :)

![image](https://user-images.githubusercontent.com/84318760/118508283-ad6e0c00-b74c-11eb-896f-816fa41c53a5.png)

Result:
![image](https://user-images.githubusercontent.com/84318760/118508727-105fa300-b74d-11eb-8d18-c2605e5e81d7.png)

![image](https://user-images.githubusercontent.com/84318760/118508768-1b1a3800-b74d-11eb-8952-16653f8c8a01.png)


Regards,
