### ISSUE TITLE
Configure Business Rules, Workflow and Process Visibility

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Issues#366]
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-configure.html

Step 7: Create visibility scenario
--------------------------

Here in point 2, while creating the visibility scenario, the screenshot to add the workflow is not relevant to the step. So please remove it.
![image](https://user-images.githubusercontent.com/65999547/117970859-cc346300-b346-11eb-8380-9d6a6144ab06.png)

Best Regards,
Priyanka

**Comment by ArchanaShukla** [comment]
this is fixed and updates tutorial is now available.
