### ISSUE TITLE
Deploy Your First SAPUI5 App

### ISSUE THREAD

**Issue by mukeshdhakar28** [SAPDocuments/Issues#367]
Tutorials: https://developers.sap.com/tutorials/appstudio-sapui5-create.html
--------------------------

In step 5 getting error while running the URL in a new terminal. Like below:
user: sapui5 $ cf html5-list -di sap-btp-sapui5-destination-service -u --runtime launchpad
Getting list of HTML5 applications available via destinations in org a4213b7atrial / space dev as mukesh.dhakar@lntinfotech.com...
FAILED

**Comment by raz-korn** [comment]
Hi @mukeshdhakar28 ,

Can you please share a screenshot?
My estimation is that you are not logged in to CF.
Use the Command Pallet (View | Find Command), filter for CF commands, and select the CF Login command. Follow the instructions, and then try again.

Regards - Raz

**Comment by mukeshdhakar28** [comment]
Hello Raz,
Thanks for reply.

I followed the step and I am able to login.
![image](https://user-images.githubusercontent.com/84131886/118124602-7083db80-b413-11eb-9e07-88d30ab4fe39.png)

I am getting the below error while following the tutorial step 4:
![image](https://user-images.githubusercontent.com/84131886/118124689-9315f480-b413-11eb-8558-4857aad453f7.png)

**Comment by mukeshdhakar28** [comment]
I also revised the quota plan and deployed the mta archive again... but still the same problem when I run the command to get the URL of the deployed app.

**Comment by raz-korn** [comment]
In the URL, replace "cpp" with "launchpad".
More details available [here](https://developers.sap.com/tutorials/appstudio-fioriapps-mta-build-deploy.html#356f2a86-9d16-4be5-9dfd-a87fc70e6574).

**Comment by mukeshdhakar28** [comment]
Hello Raz,
Issue got resolved, I did not realize the generated URL is pointing to the cpp by default.  👍 

Thanks a lot for your prompt response!!!

Best Regards
