### ISSUE TITLE
Set Up the SAP Launchpad Service

### ISSUE THREAD

**Issue by KylerXu** [SAPDocuments/Issues#369]
Tutorials: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html
--------------------------

After selecting "Go to Application", I got below error.(Translated into English: There is a problem, please try again later )
![image](https://user-images.githubusercontent.com/41565565/118231762-1ee65a00-b4c2-11eb-862d-7b17dc39b38f.png)

And the error log file is empty.....

**Comment by LindsayBert** [comment]
Hi
I'm not sure what the problem is.  Have you done all the prerequisites: Subscribed to the Launchpad service, assigned yourself to the Launchpad_Admin role?  If you've done this already, and you still can't access the launchpad, you may need to open a support ticket.

Thanks
Lindsay

**Comment by KylerXu** [comment]
> Hi
> I'm not sure what the problem is. Have you done all the prerequisites: Subscribed to the Launchpad service, assigned yourself to the Launchpad_Admin role? If you've done this already, and you still can't access the launchpad, you may need to open a support ticket.
> 
> Thanks
> Lindsay
 
Hello,
Yes. I already subscribed to the Launchpad  service and assigned Launchpad_Admin role. But when I select "Go to Application",the error box appeared. 
![image](https://user-images.githubusercontent.com/41565565/118952795-d2ea5800-b98e-11eb-9b00-8a17b2a592f5.png)
![image](https://user-images.githubusercontent.com/41565565/118953009-04fbba00-b98f-11eb-807d-370b3faafcaa.png)

Best Regards,
Kyler

**Comment by KylerXu** [comment]
> Hi Kyler - I spoke to our product manager, Iris Sasson and she suggested that you try these options:
> 
> 1. Try using a different browser. If you are using Edge, try Chrome.
> 2. If this doesn't work, try a different data center (amazon us/eur and see if the same thing happens. Note if you use a different data center, you'll have to delete your trial account and create a new one in the the new data center.
>    Let's see if this works.
>    Thanks Lindsay

Hi Lindsay, 

  1.  I tried several browsers, but the error box still appeared.
  2.  It works! Thanks. And thank you for Iris's good suggestions Have a nice weekend!
 
![image](https://user-images.githubusercontent.com/41565565/119115281-96cff980-ba59-11eb-9e31-97349f23ba2f.png)

  
Best Regards,
Kyler
