### ISSUE TITLE
Create an Empty SAPUI5 Project, problem to create SAPUI5 freestyle from template with Northwind OData Service

### ISSUE THREAD

**Issue by DenisGalandSAP** [SAPDocuments/Issues#37]
Tutorial: https://developers.sap.com/tutorials/sapui5-101-create-project.html
--------------------------

Hello,

I have followed the guide until the step 3, section 8, and at the end of the generator, BAS returns an error ans the application is not generated

here's the error:

{"message":"fiori-project:app generator failed - env.on(error) Failed to consume services due to: undefined\nAbort ui5-simple creation.","stack":"Error: env.on(error) Failed to consume services due to: undefined\nAbort ui5-simple creation.\n at Ui5SimpleGenerator._abortGenerator (/extbin/generators/ui5-generators/generator-ui5-simple/generators/app/index.js:205:24)\n at /extbin/generators/ui5-generators/generator-ui5-simple/generators/app/index.js:126:26\n at processTicksAndRejections (internal/process/task_queues.js:97:5)"}

If I create an application without the OData, there are no issues, so I guess the Destination I created from the previous tutorial has a problem.

https://developers.sap.com/tutorials/cp-cf-create-destination.html#765bac60-947f-4be7-910c-7116197946cf

I have the right response when testing the destination alone, see the result screenshot.
So I don't know what is wrong with it, there's just one thing that is not clear, the guide mentions that 
the parameter HTML5.DynamicDestination needs to be set manually, how can that be done?

![Destination](https://user-images.githubusercontent.com/77061287/103777906-da3d4480-5031-11eb-8a2a-24763b6fbd66.png)

Regards

Denis

**Comment by raz-korn** [comment]
Hi @DenisGalandSAP ,

For the additional parameter: Click the New Property button, and instead of selecting the property from the drop-down, type it manually.

Regards - Raz

**Comment by thearngrim** [comment]
oh yes, i didn't paid attention to the cursor, it was a combobox and not a select, i added the parameter and now the template can be generated.

Thank you for the hint, the ticket can be closed 👍

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
