### ISSUE TITLE
Develop and Run SAP Fiori Application With SAP Business Application Studio

### ISSUE THREAD

**Issue by maulik-parekh** [SAPDocuments/Issues#372]
Tutorials: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html
--------------------------

Dear Team,

In Step 3 point 2 , Project selection time or after need to select .vscode file/folder extension. This is not mentioned in tutorial.

Regards

**Comment by mervey45** [comment]
Hi @maulik-parekh ,

this has been updated. I close this ticket.

Best regards, 
Merve
