### ISSUE TITLE
Add Routing to a UI5 Web Components for React Project

### ISSUE THREAD

**Issue by saphendricksjoerg** [SAPDocuments/Issues#374]
Tutorials: https://developers.sap.com/tutorials/ui5-webcomponents-react-routing.html
--------------------------

Hi,
when applying the code changes for step 5 I always run into the following error:
Error: Invalid hook call. Hooks can only be called inside of the body of a function component.

It comes from const history = use.History();

I am running React 17.0.2

I had the same issue with a different non SAP tutorial. Maybe you can check whether your code works with the latest React version.

Cheers,
Joerg Hendricks

PS I love the tutorial. Really taught me a lot.

**Comment by Lukas742** [comment]
Hi @saphendricksjoerg 

I'm glad to hear that you liked the tutorial :) 

Are you using the exact same code as you posted above? If so, then this should be the problem, as the React Router Dom hook is `useHistory` and not `use.History`. --> `const history = useHistory()`

If this was just a typo in the description, please check if you declared the hook on the top level of the component without any conditional clauses. See [here](https://reactjs.org/docs/hooks-rules.html) for more details. Something like this will throw the error you mentioned above:
```jsx
export function Home() {
  ...
  const handleProgressHeaderClick = () => {
    const history = useHistory();
    history.push("/detail");
  };
  ...
```

```js
  if(something){
    const history = useHistory();
  }
```

I also created a [codesandbox](https://codesandbox.io/s/red-wind-l6z4z?file=/src/Home.jsx) containing this section of the tutorial, you can double check your implementation with it.

**Comment by saphendricksjoerg** [comment]
Hi Lukas,

thanks for the quick response.

sorry, this was a typo in the message above.
Here is my App component:
import React from "react";
import { Avatar, ShellBar, ShellBarItem } from "@ui5/webcomponents-react";
import "@ui5/webcomponents-icons/dist/add.js";
import { Switch, Route, Redirect } from "react-router-dom";
import { useHistory } from "react-router-dom";
import { Home } from "./Home";
import { Detail } from "./Detail";

export function MyApp() {
  const history = useHistory();
  const handleLogoClick = () => {
    history.push("./");
  };
  return (
    <>
      <ShellBar
        logo={<img src="reactLogo.png" />}
        profile={<Avatar image="profilePictureExample.png" />}
        primaryTitle="My App"
        onLogoClick={handleLogoClick}
      >
        <ShellBarItem src="sap-icon://add" text="Add" />
      </ShellBar>
      <Switch>
        <Route path="/home" component={Home} />
        <Route path="/detail" component={Detail} />
        <Redirect from="/" to="/home" />
      </Switch>
    </>
  );
}

and here the home component:
import "@ui5/webcomponents-icons/dist/table-view.js";

export function Home() {
  const [toggleCharts, setToggleCharts] = useState("lineChart");
  const [loading, setLoading] = useState(false);
  const history = useHistory();
  const handleProgressHeaderClick = () => {
    history.push("/detail");
  };

Best regards,
Joerg

**Comment by Lukas742** [comment]
> Here is my App component:
> ```jsx
> import React from "react";
> import { Avatar, ShellBar, ShellBarItem } from "@ui5/webcomponents-react";
> import "@ui5/webcomponents-icons/dist/add.js";
> import { Switch, Route, Redirect } from "react-router-dom";
> import { useHistory } from "react-router-dom";
> import { Home } from "./Home";
> import { Detail } from "./Detail";
> 
> export function MyApp() {
>   const history = useHistory();
>   const handleLogoClick = () => {
>     history.push("./");
>   };
>   return (
>     <>
>       <ShellBar
>         logo={<img src="reactLogo.png" />}
>         profile={<Avatar image="profilePictureExample.png" />}
>         primaryTitle="My App"
>         onLogoClick={handleLogoClick}
>       >
>         <ShellBarItem src="sap-icon://add" text="Add" />
>       </ShellBar>
>       <Switch>
>         <Route path="/home" component={Home} />
>         <Route path="/detail" component={Detail} />
>         <Redirect from="/" to="/home" />
>       </Switch>
>     </>
>   );
> }
> ```

This looks good to me.

> and here the home component:
> ```jsx
> import "@ui5/webcomponents-icons/dist/table-view.js";
> 
> export function Home() {
>   const [toggleCharts, setToggleCharts] = useState("lineChart");
>   const [loading, setLoading] = useState(false);
>   const history = useHistory();
>   const handleProgressHeaderClick = () => {
>     history.push("/detail");
>   };
> ```

I guess you only posted a part of the component here, right? If so this part looks also fine and shouldn't throw an error. 
Else there are many imports missing and also there is no return value provided for the component to render.

Did you compare your implementation with the codesandbox example I provided above and did you find any discrepancies there?

**Comment by saphendricksjoerg** [comment]
This is my full HOME component:
import React, { useState } from "react";
import {
  Card,
  Text,
  List,
  StandardListItem,
  ValueState,
  ProgressIndicator,
  Title,
  TitleLevel,
  FlexBox,
  FlexBoxJustifyContent,
  FlexBoxWrap,
  FlexBoxDirection,
  AnalyticalTable,
  Icon
} from "@ui5/webcomponents-react";
import { spacing } from "@ui5/webcomponents-react-base";
import { useHistory } from "react-router-dom";
import { BarChart, LineChart } from "@ui5/webcomponents-react-charts";
import "@ui5/webcomponents-icons/dist/horizontal-bar-chart.js";
import "@ui5/webcomponents-icons/dist/line-chart.js";
import "@ui5/webcomponents-icons/dist/list.js";
import "@ui5/webcomponents-icons/dist/table-view.js";

export function Home() {
  const [toggleCharts, setToggleCharts] = useState("lineChart");
  const [loading, setLoading] = useState(false);
  const history = useHistory();
  const handleProgressHeaderClick = () => {
    history.push("/detail");
  };

  const handleHeaderClick = () => {
    if (toggleCharts === "lineChart") {
      setLoading(true);
      setTimeout(() => {
        setLoading(false);
        setToggleCharts("barChart");
      }, 2000);
    } else {
      setLoading(true);
      setTimeout(() => {
        setLoading(false);
        setToggleCharts("lineChart");
      }, 2000);
    }
  };
  const dataset = [
    {
      month: "January",
      data: 65
    },
    {
      month: "February",
      data: 59
    },
    {
      month: "March",
      data: 80
    },
    {
      month: "April",
      data: 81
    },
    {
      month: "May",
      data: 56
    },
    {
      month: "June",
      data: 55
    },
    {
      month: "July",
      data: 40
    }
  ];
  const tableData = new Array(500).fill(null).map((_, index) => {
    return {
      name: `name${index}`,
      age: Math.floor(Math.random() * 100),
      friend: {
        name: `friend.Name${index}`,
        age: Math.floor(Math.random() * 100)
      }
    };
  });

  const tableColumns = [
    {
      Header: "Name",
      accessor: "name" // String-based value accessors!
    },
    {
      Header: "Age",
      accessor: "age"
    },
    {
      Header: "Friend Name",
      accessor: "friend.name"
    },
    {
      Header: "Friend Age",
      accessor: "friend.age"
    }
  ];
  const contentTitle =
    toggleCharts === "lineChart" ? "Line Chart" : "Bar Chart";
  const switchToChart =
    toggleCharts === "lineChart" ? "Bar Chart" : "Line Chart";
  return (
    <FlexBox
      justifyContent={FlexBoxJustifyContent.Center}
      wrap={FlexBoxWrap.Wrap}
      style={spacing.sapUiContentPadding}
    >
      <Card
        avatar={
          <Icon
            name={
              toggleCharts === "lineChart"
                ? "line-chart"
                : "horizontal-bar-chart"
            }
          />
        }
        heading="Stock Price"
        style={{ width: "300px" }}
        headerInteractive
        onHeaderClick={handleHeaderClick}
        subheading={`Click here to switch to ${switchToChart}`}
      >
        <Text style={spacing.sapUiContentPadding}>{contentTitle}</Text>
        {toggleCharts === "lineChart" ? (
          <LineChart
            dimensions={[{ accessor: "month" }]}
            measures={[{ accessor: "data", label: "Stock Price" }]}
            dataset={dataset}
            loading={loading}
          />
        ) : (
          <BarChart
            dimensions={[{ accessor: "month" }]}
            measures={[{ accessor: "data", label: "Stock Price" }]}
            dataset={dataset}
            loading={loading}
          />
        )}
      </Card>
      <Card
        heading="Progress"
        subheading="List"
        style={{ width: "300px", ...spacing.sapUiContentPadding }}
        avatar={<Icon name="list" />}
        headerInteractive
        onHeaderClick={handleProgressHeaderClick}
      >
        <List>
          <StandardListItem info="finished" infoState={ValueState.Success}>
            Activity 1
          </StandardListItem>
          <StandardListItem info="failed" infoState={ValueState.Error}>
            Activity 2
          </StandardListItem>
          <StandardListItem
            info="in progress"
            infoState={ValueState.Warning}
            style={{ height: "80px" }}
          >
            <FlexBox direction={FlexBoxDirection.Column}>
              <Title level={TitleLevel.H5}>Activity 3</Title>
              <ProgressIndicator value={89} valueState={ValueState.Success} />
            </FlexBox>
          </StandardListItem>
          <StandardListItem
            info="in progress"
            infoState={ValueState.Warning}
            style={{ height: "80px" }}
          >
            <FlexBox direction={FlexBoxDirection.Column}>
              <Title level={TitleLevel.H5}>Activity 4</Title>
              <ProgressIndicator value={5} valueState={ValueState.Error} />
            </FlexBox>
          </StandardListItem>
        </List>
      </Card>
      <Card
        heading="AnalyticalTable"
        style={{ maxWidth: "900px", ...spacing.sapUiContentPadding }}
        avatar={<Icon name="table-view" />}
      >
        <AnalyticalTable
          data={tableData}
          columns={tableColumns}
          visibleRows={5}
        />
      </Card>
    </FlexBox>
  );
}

**Comment by saphendricksjoerg** [comment]
I couldn't find any differences to the code sample

**Comment by Lukas742** [comment]
I just copied both of your components and tried it out myself and with the latest React dependencies it's working fine for me.

My last guess would be that the dependencies are somehow broken. Could you try deleting the `node_modules` folder and `package-lock.json` file (if you used `yarn` the `yarn.lock` file) inside of your project folder.

If that does not help, could you push the project to git and make the repository public or make me a collaborator so I can take a look at it?

**Comment by saphendricksjoerg** [comment]
Do I need to delete package-lock.json as well?

**Comment by Lukas742** [comment]
Yup :)

**Comment by saphendricksjoerg** [comment]
npm install react? npm install w/o further parameters doesn't do anything. wouldn't I need to download the UI5 components as well?
Sorry for the stupid questions but I am new to this.

**Comment by Lukas742** [comment]
`npm install` installs all modules listed in your `package.json` file. With `npm install <module-name>` you can install a specific module, but as you deleted all modules now, you need to reinstall them. 

More about this [here](https://docs.npmjs.com/cli/v7/commands/npm-install)

**Comment by saphendricksjoerg** [comment]
This is what I understood but you told me to delete the package.json file.  with this gone how would npm know what to install unless I explicitly specify it?

**Comment by Lukas742** [comment]
> Do I need to delete package-lock.json as well?

You asked about the `package-lock.json` file, not the `package.json` file. And yes you still need that one

**Comment by saphendricksjoerg** [comment]
oops, I misread your first reply and deleted the package.json file first. That's why I was confused and asked afterwards whether I have to delete the package-lock.json too. Now it all makes sense ;-)
Could you post the package.json please?

**Comment by saphendricksjoerg** [comment]
or should I just run
npx create-react-app my-app --template @ui5/cra-template-webcomponents-react
again.
I can backup the relevant files before and delete the my-app folder

**Comment by Lukas742** [comment]
This would be cleanest way, but to save you the time I added the `package.json` here.
If your project has a different name than "my-app", please adjust accordingly in the json below.

```json
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@ui5/webcomponents": "1.0.0-rc.14",
    "@ui5/webcomponents-fiori": "1.0.0-rc.14",
    "@ui5/webcomponents-icons": "1.0.0-rc.14",
    "@ui5/webcomponents-react": "^0.15.2",
    "@ui5/webcomponents-react-base": "^0.15.4",
    "@ui5/webcomponents-react-charts": "^0.16.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.3"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "jest": {
    "transformIgnorePatterns": [
      "node_modules/(?!(@ui5|lit-html)).*\\.js$"
    ]
  }
}

```

**Comment by saphendricksjoerg** [comment]
Now it works :-)
Reinstalling with this package.json did the trick.
Thanks a lot for all the effort!

**Comment by Lukas742** [comment]
Glad to hear that. In many cases, when there is no explanation for an error, reinstalling node_modules does the trick :)

Closed.
