### ISSUE TITLE
Using the SAP HANA Python Interface for Sentiment Analysis/ Entity Detection

### ISSUE THREAD

**Issue by NazaninSA** [SAPDocuments/Issues#375]
Tutorials: https://developers.sap.com/tutorials/hana-clients-python.html
--------------------------
Is it possible to do sentiment analysis or entity detection or any other capabilities of Hana Text Analytics through the python interface? I didn't find any sample code for that!

**Comment by danielva** [comment]
If you are using using SAP HANA SPS 05, I believe there are instructions at 
https://help.sap.com/viewer/62e301bb1872437cbb2a8c4209f74a65/2.0.05/en-US/a3adb442cbc44a84a626d99014d3dbc9.html

If you are using SAP HANA Cloud, the following link lists some high level feature differences.
https://help.sap.com/viewer/3c53bc7b58934a9795b6dd8c7e28cf05/hanacloud/en-US/e131e792973348d1ac072590fe3d137c.html


Hope that helps.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
