### ISSUE TITLE
Create a Basic Flow with a SOAP Endpoint

### ISSUE THREAD

**Issue by concur-perryb** [SAPDocuments/Issues#376]
Tutorials: https://developers.sap.com/tutorials/cp-integration-create-basic-flow.html
--------------------------

SOAP Adapter configuration is no longer current.  After selecting SOAP Adapter, user must specify the Message Protocol - SAP RM or SOAP 1.x.  For the tutorial, the latter appears to be the appropriate selection.

**Comment by gauthamkrishna-sap** [comment]
We are still working on updating it. In the meantime, I can offer you this session from TechEd 2020: https://github.com/SAP-samples/teched2020-DEV165

This also contains mail adapter configuration with REST API and a non-SAP system. Hope you can get some hands on experience with this while we update this series.

Thanks and Best Regards,
Gautham

**Comment by gauthamkrishna-sap** [comment]
Hello,
We are still working on updates for this series. In the meantime, this tutorial from TechEd is a great alternative to continue your integration learning journey: https://github.com/SAP-samples/teched2020-DEV165
Best Regards,
Gautham

**Comment by gauthamkrishna-sap** [comment]
Hello,
This tutorial has been deprecated. We will replace it with an updated tutorial in the coming weeks. Please watch out for "Integration Suite tutorials" in the SAP Tutorial Navigator for new updates. 
Thank you.
