### ISSUE TITLE
Use the Application Router in Cloud Foundry to Connect to ABAP System

### ISSUE THREAD

**Issue by IObert** [SAPDocuments/Issues#377]
Tutorials: https://developers.sap.com/tutorials/cp-connectivity-consume-odata-service-approuter.html
--------------------------

Step 5.
The SAP npm registry is deprecated, please remove this part of step 5.

Also, please note that the cockpit UI has changed several times since the screenshots were recorded. It would be great if you could update them as well. 

Thanks

**Comment by je-hal** [comment]
Hi @IObert, as already explained by email I am no longer maintaining these tutorials.

I reached out to my manager to find a solution.
