### ISSUE TITLE
Deploy an SAP Conversational AI Chatbot to Microsoft Teams

### ISSUE THREAD

**Issue by matbeerkens** [SAPDocuments/Issues#378]
Tutorials: https://developers.sap.com/tutorials/conversational-ai-deploy-teams.html
--------------------------

Hi, in above tutorial, step 3.3 has changed in Azure Portal.
This is now located in "Configuration".

On top, the setup does not lead to an operational connection.

**Comment by thecodester** [comment]
Yes, I just did the tutorial again and the screens were much different (in the end the configuration was basically the same) and I did not know if this was because the status of my subscription changed or the screens changed for everybody. I will try to update the tutorial soon.

**Comment by matbeerkens** [comment]
Perfect, here is also an example: https://blogs.sap.com/2021/02/22/sap-conversational-artificial-intelligence-building-chatbot-with-ai-step-by-step-process-of-deploying-an-sap-ai-chatbot-on-microsoft-teams-and-telegram/
BTW it DOES work, my other bot is aparantly mallfunctioning.
This issue can be closed.
