### ISSUE TITLE
Get to Know SAP Tutorials

### ISSUE THREAD

**Issue by chauhanankit** [SAPDocuments/Issues#379]
Tutorials: https://developers.sap.com/tutorials/tutorial-getting-started.html
--------------------------

Write here what you need help with ...

I just finished the tutorial "Build Your First Chatbot with SAP Conversational AI".

During this time, I had few questions and confusion. Do we have an option for the instant support to clear our doubts?

**Comment by thecodester** [comment]
I'm happy to help. What exactly do you need help with?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
