### ISSUE TITLE
Set Up a Workflow With Extended Employee Onboarding

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Issues#38]
@ArchanaShukla 

Tutorial: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-3-workflow.html
--------------------------

Write here what you need help with: Step 2 is mac-specific.

Unless the tutorial is not supposed to be followed by a Windows user the steps are missing like uploading a zip file, extracting it in the dev space, etc.

Thank you,
greg

**Comment by ArchanaShukla** [comment]
Hello @greg2git ,
I did not understand your suggestion. The tutorials are not OS specific. Step 1 already asks you to download the content from the GitHub in the zip form, and extract the zip. In Step 2, you have to setup the Dev space and then in Step 3, all you need is open the dialog in Business Application Studio and drag and drop the extracted folder. 

Can you please explain what exactly you feel is missing. 

Thanks,

**Comment by greg2git** [comment]
sure, my version of Windows will not allow an unzipped folder to be uploaded (or dragged) into BAS. 
i'm assuming your Mac version is not having a problem with the folder 'drag&drop' mouse operation.

does this make sense?

**Comment by ArchanaShukla** [comment]
@greg2git - I also checked with another Windows machine and was able to successfully drag-and-drop the folder. It will help if you can attach any error that you get, or screenshots on where you dragging and dropping. Please note that it takes sometime to upload, you will see a progress bar on the BAS and once the files are uploaded.

**Comment by greg2git** [comment]
BAS interface seems to have changed since my last login and i can now drag both zipped an unzipped folders into the the dev space from my Windows. in case of zipped folders there's an extra step to be followed: open terminal and run unzip filename.zip command. 
it's up to you if you want to include this clarification in any future tutorial updates but i don't see is as a technical problem, so closing the issue now. 
thank you for responding.
