### ISSUE TITLE
Get to Know SAP Tutorials

### ISSUE THREAD

**Issue by mmcisme25** [SAPDocuments/Issues#380]
Tutorials: https://developers.sap.com/tutorials/tutorial-getting-started.html
--------------------------
No help needed - just a comment.  In the first question.  "step 3" is incorrect.  However typing 3 is correct.   Interesting - but strange.  I wonder if I had typed "three" if that would have been correct.

**Comment by thecodester** [comment]
I have changed the question and happy you completed the mission.
