### ISSUE TITLE
 Create Queues and Queue Subscriptions for SAP Event Mesh

### ISSUE THREAD

**Issue by rmaripeddi** [SAPDocuments/Issues#382]
Tutorials: https://developers.sap.com/tutorials/cp-enterprisemessaging-queue-queuesubscription.html
-------------------------

While I am clicking on go to application, getting authorization error as below.
![image](https://user-images.githubusercontent.com/64585357/118997076-008ecb80-b9a6-11eb-9b2d-26f4a1027e30.png)

**"You are not authorized to access the SAP Event Mesh Cockpit. Get your user assigned to a role to gain access, see Create User Groups, Role Collection and Assign Role Collection"**

Could you please help me what authorizations or roles I have to add and where to do this activity.

**Comment by pradeeppanda-sap** [comment]
if you are trying in trial landscape, it has to be a dev event mesh.  and the tutorial here is for event mesh of default type.
Hence, you have to use a productive landscape and use the default instance.

**Comment by rmaripeddi** [comment]
Is that possible to test the whole thing with trial landscape or do I need to purchase plan for default. If it is possible in trial version , could you please help me with the document which I can follow.

**Comment by pradeeppanda-sap** [comment]
hi.,
 Sorry for little late in replying.
 To be able to work on Default type of Event Mesh, you need to use the productive one. Details as you know is available in sap store. It is charged on the traffic.

regards
Pradeep
