### ISSUE TITLE
Set Up Your Local Infrastructure to Develop with SAP Cloud SDK

### ISSUE THREAD

**Issue by dheffernan-sap** [SAPDocuments/Issues#384]
Tutorials: https://developers.sap.com/tutorials/s4sdk-setup.html
--------------------------

Write here what you need help with ...

I am getting an error when executing mvn clean package. The error is when maven runs the integration tests:
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.938 s <<< FAILURE! - in com.sap.cloud.sdk.tutorial.HelloWorldServletTest
[ERROR] com.sap.cloud.sdk.tutorial.HelloWorldServletTest  Time elapsed: 1.937 s  <<< ERROR!
org.jboss.arquillian.container.spi.client.container.LifecycleException: Something went wrong
Caused by: org.apache.openejb.OpenEJBException: org.apache.xbean.recipe.ConstructionException: Error invoking constructor: public org.apache.tomee.catalina.TomcatSecurityService(): Error invoking constructor: public org.apache.tomee.catalina.TomcatSecurityService()
Caused by: org.apache.xbean.recipe.ConstructionException: Error invoking constructor: public org.apache.tomee.catalina.TomcatSecurityService()
Caused by: java.lang.NoClassDefFoundError: java/security/acl/Group
Caused by: java.lang.ClassNotFoundException: java.security.acl.Group

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   HelloWorldServletTest » Lifecycle Something went wrong
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for firstapp - Root ls:
[INFO] 
[INFO] firstapp - Root .................................... SUCCESS [  0.287 s]
[INFO] firstapp - Application ............................. SUCCESS [  4.591 s]
[INFO] firstapp - Integration Tests ....................... FAILURE [  4.804 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.790 s
[INFO] Finished at: 2021-05-21T14:39:41+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project firstapp-integration-tests: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/i055722/DEV/firstapp/integration-tests/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]

Any help would be appreciated.
regards
David

**Comment by MatKuhr** [comment]
Hi & sorry for the late response. A `NoClassDefFoundError` often indicates a dependency version mismatch or conflict.

Specifically `java.security.acl.Group` was deprecated with Java 9 and removed I think with 14. Which Java version are you using?

**Comment by newtork** [comment]
What does the following command return for you?
```
javac -version
mvn -version
```

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
