### ISSUE TITLE
Display Database Content and Run SQL Queries

### ISSUE THREAD

**Issue by maulik-parekh** [SAPDocuments/Issues#385]
Tutorials: https://developers.sap.com/tutorials/abap-display-data-queries.html
--------------------------

Hi,

I am unable to view data in Eclipse with ABAP Could Project - SAP BTP trial account. Error 'No authorization to view data'.

(Step 2: Select a database table.)

Please suggest how to add authorization.

Regards,

![image](https://user-images.githubusercontent.com/84318760/119265428-52cd2800-bc04-11eb-9632-6f1af3f4250d.png)

**Comment by maulik-parekh** [comment]
Requesting for suggestion.

**Comment by julieplummer20** [comment]
Hi,
You need to fulfil the prerequisite: "You have a valid instance of an on-premise AS ABAP server, version 7.51 or higher "
You may not be able to do this tutorial on SAP BTP ABAP Environment.
BR Julie.

**Comment by julieplummer20** [comment]
Hi Maulik, Try a different table: Search for /DMO/*CUSTOMER*.
BR Julie.
