### ISSUE TITLE
 Configure SAP HANA service smart data integration for SAP BTP with the SAP HANA service for SAP BTP

### ISSUE THREAD

**Issue by guyperets** [SAPDocuments/Issues#387]
Hi,

I can't connect to the BTP trial account (connect to SAP Cloud Platform CF, SAP HANA Service via JDBC )- I'm getting the following error:

**Connecting to SAP HANA server via JDBC...
Failed to connect to SAP HANA server via JDBC.
Context: Failed to connect to server SAP DBTech JDBC: Cannot connect to jdbc:sap://hana.trial-eu10.hanacloud.ondemand.com:443 [Unknown host hana.trial-eu10.hanacloud.ondemand.com:443 [hana.trial-eu10.hanacloud.ondemand.com], -709].**

Any helpful tips? 
Guy
Tutorials: https://developers.sap.com/tutorials/haas-dm-connect-sdi.html
--------------------------

Write here what you need help with ...

**Comment by jung-thomas** [comment]
The main issue I see right away is that this tutorial is marked as not for Trial Accounts:
**This tutorial cannot be completed with a trial account.**

Yes I can see from the URL you provided in the error message that you are trying to use this on trial. This tutorial can only be perform on a production account with access to an instance of SAP HANA service for SAP BTP.

I would also suggest that even trial aside that URL isn't correct.  That doesn't appear to be a HANA URL. It looks to me like that is the URL of the Cloud Controller of BTP itself.
