### ISSUE TITLE
Deploy Commerce Mock Application in the Kyma Runtime

### ISSUE THREAD

**Issue by bcschaich** [SAPDocuments/Issues#388]
Tutorials: https://developers.sap.com/tutorials/cp-kyma-mocks.html
--------------------------

Step 2 in this tutorial (upload of a YAML) does not work with Firefox. Maybe mark to use another browser (Chrome worked, of course)

**Comment by jcawley5** [comment]
Hello, I can not replicate the issue using firefox 88.0.1. Please make sure you are using the latest version and have no browsers add-ons that may block the process. If you continue to experience issues please create an issue in the Kyma repo at https://github.com/kyma-project/kyma/issues including the output found in the browser developer console.
