### ISSUE TITLE
Set Up Process Visibility to Track Employee Onboarding Workflow

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Issues#39]
@ArchanaShukla 

Tutorial: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-4-visibility.html
--------------------------

Write here what you need help with ... Step 1.2

The input screen is different in the tutorial and 'Create' button is not available.

![CreateMissing](https://user-images.githubusercontent.com/24355032/103912337-28575400-50d5-11eb-81c8-9526cb2ec9ed.JPG)

**Comment by ArchanaShukla** [comment]
Thanks for bringing this up. This is due to the recent product screen changes. Tutorial would be updated in next cycle. This screen change should not block your tutorial. 

@MichaelCzcz - please close this ticket as this screen change is tracked by another issue as well.

**Comment by ArchanaShukla** [comment]
@greg2git - check the description. you should not use quotes etc.

**Comment by greg2git** [comment]
@ArchanaShukla and @MichaelCzcz 

what are the plans for the next update cycle? quotes were irrelevant here as this is a description and not a mandatory field. 

also, what is the open issue for this greyed out 'Create' button?

thank you,
gm
