### ISSUE TITLE
Help Thomas Get Started with SAP HANA Cloud

### ISSUE THREAD

**Issue by russellw999** [SAPDocuments/Issues#391]
Tutorials: https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html
--------------------------

Write here what you need help with ...

I found this tutorial very useful for getting to grips with the new look  SAP Cloud Interface , particularly the Business Application Studio.  I think it would make a good Pre Requisite Tutorial to the Mission
 "Use Clients to Query an SAP HANA Database "

**Comment by jung-thomas** [comment]
Thanks for the kind words regarding this tutorial and I'm glad you found it helpful. I don't own the Use Clients... tutorial, but I can reach out to the author and ask if they want to add a link to this tutorial in their prerequisites section.
