### ISSUE TITLE
Install the MultiApps Cloud Foundry CLI Plugin

### ISSUE THREAD

**Issue by eguo** [SAPDocuments/Issues#392]
Tutorials: https://developers.sap.com/tutorials/cp-cf-install-cliplugin-mta.html
--------------------------

After I completed exact steps of this tutorials, when I run following command on my mac. 

`$ cf deploy my.mtar -e my.mtaext  `

I got following output:

`'deploy my.mtar' is not a registered command. See 'cf help -a'`

**Comment by IObert** [comment]
Hi,

can you confirm that you see the multiapps plugin when you run the command from step 3:
```
cf plugins | grep multiapps
```

**Comment by IObert** [comment]
I'll close this issue now but feel free to reopen if needed.
