### ISSUE TITLE
Enable the SAP Cloud Platform, API Management Service

### ISSUE THREAD

**Issue by mendesthi** [SAPDocuments/Issues#393]
Tutorials: https://developers.sap.com/tutorials/hcp-apim-enable-service.html
--------------------------

Hi guys,
I think this is outdated, would you mind to check.
Thanks.

**Comment by shilpavij** [comment]
Dear Colleague,

Yes, you are right. It should be deleted as we already have Integration Suite starter tutorial https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html

Regards
Shilpa

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by mendesthi** [comment]
Hi Michael, good morning. 

I have just browsed for the outdated tutorial and it is still available, leading many customer and partners to wrong instructions, loosing expensive consulting time. 

So issue is not closed.

Thanks,
Thiago.
