### ISSUE TITLE
Create Destination for SAP API Management Service

### ISSUE THREAD

**Issue by superwangnan** [SAPDocuments/Issues#395]
Tutorials: https://developers.sap.com/tutorials/cp-apim-sales-tracker-create-destination.html
--------------------------

Hi team,

Do we have a tutorial for how to create destination and work with Business application studio? By this tutorial, we can list the apis of api management by WebIDE. So, I want to implement the same result as BAS.

Thanks.

**Comment by shilpavij** [comment]
Dear Colleague,

As of today,APIM does not support BAS.

Regards
shilpa
