### ISSUE TITLE
Deploy Your First SAPUI5 App

### ISSUE THREAD

**Issue by DIBYAJYOTINANDA** [SAPDocuments/Issues#396]
Tutorials: https://developers.sap.com/tutorials/appstudio-sapui5-create.html
--------------------------

Write here what you need help with ...

unable to deploy the app with the steps followed
cf html5-list -di sap-btp-sapui5-destination-service -u --runtime launchpad

cf html5-list -di sap-btp-sapui5-destination-service -u --runtime cpp

![image](https://user-images.githubusercontent.com/6195570/120106334-3c7e1980-c17a-11eb-90cd-fc00d0396c8f.png)

Regards,
Dibyajyoti Nanda

**Comment by nathangov** [comment]
The service name is incorrect. Run this command instead:
`cf html5-list -di sap-btp-sapui5-dest-srv -u --runtime launchpad`

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
