### ISSUE TITLE
SAP MTA Project myapphana deployment error 

### ISSUE THREAD

**Issue by DIBYAJYOTINANDA** [SAPDocuments/Issues#397]
Hi Team,

I am trying to deploy the MTA application myapphana from the Github via Business application studio.
but as per the steps the app is not deploying due to some issue.
 
https://www.youtube.com/watch?v=-b78yas5RQ4&list=PLkzo92owKnVw3l4fqcLoQalyFi9K4-UdY&index=16

![image](https://user-images.githubusercontent.com/6195570/120106846-4d2f8f00-c17c-11eb-8875-eb7618fd15ed.png)

![image](https://user-images.githubusercontent.com/6195570/120107022-e5c60f00-c17c-11eb-8412-9f15e8522f18.png)

Regards,
Dibyajyoti Nanda

**Comment by MichaelCzcz** [comment]
These GitHub issues are to resolve issues (i.e., problems/errors) with the tutorials. Your question seems more general and likely 
would get more visibility -- and a better answer -- in the SAP Community's Questions & Answers. You can ask your question at:
https://answers.sap.com/index.html
