### ISSUE TITLE
Create an Empty SAPUI5 Project

### ISSUE THREAD

**Issue by russellw999** [SAPDocuments/Issues#398]
Tutorials: https://developers.sap.com/tutorials/sapui5-101-create-project.html
--------------------------

Write here what you need help with ...

I get to step 8 and press Finish to complete my project and the following messages appear
" Dependencies are being loaded "
" Project Generated and saved for future use"

The only problem is there is no Project ?

I have cycled though this twice

The project does not appear in the Explorer or as a Recent Project

Refresh of the browser has no effect 

I then find the Project by using the menu  File --> Open Workspace

I would have expected that when i create a Project , it would be  visible in the Explorer and not have to go digging for it in a File  menu
Regards

**Comment by ianquigley-sap** [comment]
Hi @russellw999,

Thanks for your feedback.  After successfully creating a project with the generator, the following will happen:

1. If you already have the project workspace open in your workspace, you will see the project files already available.
2. If you do not have a workspace open (as in this case), you will not see the project displayed, and will have to open the workspace as detailed in step 8 of the tutorial.

You are quite correct about option 2 above, it would be more intuitive to automatically open the workspace with the project already displayed.   Technically, it was not possible for us to update this until recently.  I agree with your feedback, and thanks again for providing it.

Watch this space, and hopefully we can make the changes suggested.

Regards,
Ian

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
