### ISSUE TITLE
Add an SAPUI5 App to Your Launchpad Site

### ISSUE THREAD

**Issue by mlvai** [SAPDocuments/Issues#4]
Tutorial: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-new-sapui5.html
--------------------------
Ubuntu 18.04.5 LTS
left chorme   / right  firefox 84 
In firefox its no possible create/edit  or  delete   content .(content-manager) 

https://user-images.githubusercontent.com/61939539/102702020-80203f00-423c-11eb-8ddc-6aca4cccf427.mp4

**Comment by LindsayBert** [comment]
Hi - I don't know what the problem is.  
Can you open a ticket for this issue. Perhaps someone in the community can help.

Thanks
Lindsay

**Comment by thecodester** [comment]
These GitHub issues are to resolve issues (i.e., problems/errors) with the tutorials. Your question is more general and likely would get more visibility -- and a better answer -- in the SAP Community's Questions & Answers.

https://www.sap.com/community.html
https://answers.sap.com/index.html

@LindsayBert  Use this test and these direct links if you need to refer someone to the community.
