### ISSUE TITLE
Set Up SAP Business Application Studio for CAP Java

### ISSUE THREAD

**Issue by redjump** [SAPDocuments/Issues#40]
Tutorial: https://developers.sap.com/tutorials/cp-cap-java-app-studio.html
--------------------------
Step 2:Create application skeleton
4. run mvn -B archetype:generate -DarchetypeArtifactId=cds-services-archetype -DarchetypeGroupId=com.sap.cds \
-DarchetypeVersion=RELEASE \
-DgroupId=com.sap.cap -DartifactId=products-service -Dpackage=com.sap.cap.productsservice

error report: bash: maven: command not found

**Comment by beckermarc** [comment]
Hi @redjump,

can you please provide a screenshot of the bash showing the executed command and the output?

Its a little unclear to me how the bash is reporting that the command `maven` can not be found, while this is not even mentioned in the command that should be run. Can you execute the command `mvn -version` successfully?

Best regards,
Marc Becker

**Comment by iwonahahn** [comment]
Hi @redjump,

We haven't heard from you in a while, so we are closing the issue.
If you still have questions, feel free to reopen the issue.

Best regards,
Iwona
