### ISSUE TITLE
How to send msg to Event Mesh use MQTT.js or other MQTT client？

### ISSUE THREAD

**Issue by wivwiv** [SAPDocuments/Issues#400]
I want to send a message to event mesh.

I create an instance in *Cloud Foundry* Space and created a  *Service Key*.

 *Service Key*:
```
...
{
      "oa2": {
        "clientid": "xxxxxxxx",
        "clientsecret": "**********",
        "tokenendpoint": "https://*******.authentication.eu10.hana.ondemand.com/oauth/token",
        "granttype": "client_credentials"
      },
      "protocol": [
        "mqtt311ws"
      ],
      "broker": {
        "type": "sapmgw"
      },
      "uri": "wss://enterprise-messaging-messaging-gateway.cfapps.eu10.hana.ondemand.com/protocols/mqtt311ws"
    }
...
```

 *How to get mqtt.js client info and topic?*
```
const mqtt = require('mqtt')

const client = mqtt.connect('<URL>', {
  clientid: '<How to get it>',
  password: '<How to get it>'
})

client.publish(`<MQTT topic,How to get it>`, '<Payload how to get it>')

```

**Comment by MichaelCzcz** [comment]
These GitHub issues are to resolve issues (i.e., problems/errors) with the tutorials. Your question seems more general and likely 
would get more visibility -- and a better answer -- in the SAP Community's Questions & Answers. You can ask your question at:
https://answers.sap.com/index.html
