### ISSUE TITLE
Deploy a CAP Business Application to SAP Business Technology Platform

### ISSUE THREAD

**Issue by hunkaf** [SAPDocuments/Issues#401]
Tutorials: https://developers.sap.com/tutorials/cap-service-deploy.html
--------------------------

This command throws an error:
cf create-service hanatrial hdi-shared my-bookshop-db

The plan hdi-shared could not be found for service hanatrial.
FAILED

**Comment by iwonahahn** [comment]
Hi @hunkaf,

the service SAP HANA Schemas & HDI Containers Trial (hanatrial) was removed for newly created trial accounts. You now need to use the trial service on SAP HANA Cloud (hana-cloud-trial) to deploy your application. To avoid confusion we will update the tutorial asap.

Best regards,
Iwona

**Comment by iwonahahn** [comment]
Hi @hunkaf,

The issue is resolved and I have updated the tutorial, see my comment in this [issue](https://github.com/SAPDocuments/Issues/issues/347#issuecomment-854209352).

Best regards,
Iwona
