### ISSUE TITLE
Use SAP HANA as the Database for a CAP Java Application

### ISSUE THREAD

**Issue by daniel-torok** [SAPDocuments/Issues#402]
Tutorials: https://developers.sap.com/tutorials/cp-cap-java-hana-db.html
--------------------------

After executing step 3 / 3 : "Add the following configuration in the file .cdsrc.json in the root folder of your bookstore project:"
The mentioned effect does not happen. What commands should we execute to get the '.hdbtable and .hdbview' files?

**Comment by beckermarc** [comment]
Hi, yes this hint is a little bit misplaced. The files are only generated after executing the `cds deploy --to hana:bookstore-hana` command mentioned after that. Can you try this?

**Comment by daniel-torok** [comment]
Hi! Yes, after executing the 'cds deploy' command these files are generated as well. Thank you for your response!
