### ISSUE TITLE
Develop a Fiori App Using the ABAP RESTful Application Programming Model (Managed Scenario)

### ISSUE THREAD

**Issue by MrEntwickler** [SAPDocuments/Issues#404]
Group: https://developers.sap.com/group.abap-env-restful-managed.html
--------------------------

Hello Team,

Thank you very much for your tutorials on https://developers.sap.com/ .

But one thing I feel missing here in your tutorial( Develop a Fiori App Using the ABAP RESTful Application Programming Model (Managed Scenario) ) is mentioning of prerequisites like stack details viz component and the respective versions that are required to practice the examples mentioned in the tutorial.

Kindly, correct me if I am wrong or missing something here. It would be of so helpful if you can attach those details to these tutorials.

To be honest, your tutorial section is really great except the above missing point. Really appreciate your work to encourage the learners.

Thank you very much.

Regards,
Entwickler

**Comment by mervey45** [comment]
Hi @MrEntwickler ,

do you mean the instruction to install Eclipse/ADT? If yes, then is is part of the second tutorial of this group: https://developers.sap.com/tutorials/abap-environment-persistence.html.

Best regards, 
Merve
