### ISSUE TITLE
Enable SAP BTP, Kyma Runtime

### ISSUE THREAD

**Issue by bvarwig** [SAPDocuments/Issues#406]
Tutorials: https://developers.sap.com/tutorials/cp-kyma-getting-started.html
--------------------------

in step  "Step 4: Open Kyma runtime console UI" the cockpit has changed and the dashbord is no longer found where tutorial expects it.
![image](https://user-images.githubusercontent.com/8438658/121011753-436ae480-c797-11eb-9577-76021b5cebc4.png)

new location for dashboard: 
![image](https://user-images.githubusercontent.com/8438658/121012031-93e24200-c797-11eb-829f-53f6542789c8.png)

Regards Britta

**Comment by KevinMuessig** [comment]
Hi @bvarwig ,

thank you for your feedback. I am currently working on fixing this step in the tutorial.

Best,

KM
