### ISSUE TITLE
SAP Fiori tools - Open guided development: oData V4 

### ISSUE THREAD

**Issue by AshithaDechamma** [SAPDocuments/Issues#407]
Tutorials: https://developers.sap.com/tutorials/fiori-tools-configure-lrop.html
--------------------------

In BAS, I am trying to extend Fiori List Report application using SAP Fiori tools - Open guided development. I noticed that adding custom action to page using extensions is not available for oData V4 along with other extension options. But, all the options are available for V2. Is it yet to be released for oData V4?

**Comment by cjbernal** [comment]
Hi Ashitha,

Unfortunately, an OData V4 version of the guide has not yet been released. We are actively working to create parity between our guides, prioritizing based on customer requests and needs but have not planned this one yet. As you are not the first person to have asked, we will need to investigate. At this time however, I cannot make any promises for a particular release date. 

We have received your formal request (via the Request a Guide feature), so do know that your request was seen by the development team. From here it will be prioritized amongst other new guide requests.

Kind regards,
Conrad (Co-product owner, Guided Development)

**Comment by AshithaDechamma** [comment]
Hello Conrad,

Thanks for the information.

Regards,
Ashitha
