### ISSUE TITLE
 Create Instance of SAP Event Mesh

### ISSUE THREAD

**Issue by jmalla** [SAPDocuments/Issues#408]
Tutorials: https://developers.sap.com/tutorials/cp-enterprisemessaging-instance-create.html
--------------------------

I get the following error when trying to create the instance:
Service broker error: Service broker enterprise-messaging-service-broker failed with: Service broker parameters are invalid: [{"message":"Unrecognized field","propertyPath":"namespace"}]

Not sure why this is happening:

I am passing in the following:

{
"emname": "LtcMessageClient",
"namespace": "Ltc/LtcMessageClient/1",
"version": "1.1.0",
"options": {
    "management": true,
    "messagingrest": true,
    "messaging": true
},
"rules": {
    "queueRules": {
        "publishFilter": [
            "${namespace}/*"
        ],
        "subscribeFilter": [
            "${namespace}/*"
        ]
    },
    "topicRules": {
        "publishFilter": [
            "${namespace}/*"
        ],
        "subscribeFilter": [
            "${namespace}/*"
        ]
    }
}
}

I also tried with:
{
"emname": "LtcMessagingClient",
"namespace": "Ltc/LtcMessagingClient/Messaging",
"version": "1.1.0",
"options": {
    "management": true,
    "messagingrest": true,
    "messaging": true
},
"rules": {
    "queueRules": {
        "publishFilter": [
            "${namespace}/*"
        ],
        "subscribeFilter": [
            "${namespace}/*"
        ]
    },
    "topicRules": {
        "publishFilter": [
            "${namespace}/*"
        ],
        "subscribeFilter": [
            "${namespace}/*"
        ]
    }
}
}

**Comment by jmalla** [comment]
I am using the trial account

**Comment by pradeeppanda-sap** [comment]
Hi @jmalla
You are trying to create an instance of default plan in the trial environment (the descriptor which you are using is of default plan). And as we have mentioned, trial environment does not have default plan, and hence if you are trying to create an instance with default plan in trial environment, it will not work. You need to be working in productive environment, to be able to work with the default plan. And hence, if you notice, this tutorial has that information .

![Capture](https://user-images.githubusercontent.com/51952722/121133875-7ae99780-c850-11eb-9645-0caa1ff9d924.PNG)

Hope it is clear.

thanks 
Pradeep
