### ISSUE TITLE
 Create Queues and Queue Subscriptions for SAP Event Mesh

### ISSUE THREAD

**Issue by jmalla** [SAPDocuments/Issues#409]
Tutorials: https://developers.sap.com/tutorials/cp-enterprisemessaging-queue-queuesubscription.html
--------------------------

From the Trial account, I do not see this screen. I only see the following.
![SAP Event Mesh](https://user-images.githubusercontent.com/7725180/121067270-b4060700-c77f-11eb-87f3-f18cf86837a5.jpg)

**Comment by pradeeppanda-sap** [comment]
Hi @jmalla,
  There seems to be some confusion.
  Sorry, if we have provided some information which is creating some kind of confusion in the tutorial.
  Please note that, the tutorial to work with the default plan holds good only if you are using a productive environment.
  Default version is not available in the trial environment.

 And the management screen you have provided here is for dev plan.  How did you get that screen? Can you please let me know the steps you followed to get that screen?

regards
pradeep

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
