### ISSUE TITLE
SAP HANA, express edition, in Google Cloud Platform Launcher (Database   XS Advanced)

### ISSUE THREAD

**Issue by captainabap** [SAPDocuments/Issues#41]
Tutorial: https://developers.sap.com/tutorials/hxe-gcp-getting-started-launcher-xsa.html
--------------------------

I can't find HANA Express in the GCP Launcher. Was it removed?

**Comment by jung-thomas** [comment]
Yes the HANA express edition offerings in the hyperscalers have been removed. Tutorials are pending removal as well. HANA express is still offered as a binary installer, docker image, and VM. But if you want a cloud hosted version of HANA , we suggest the HANA Cloud which does have a free trial.
