### ISSUE TITLE
Design and Deploy Your First Integration Flow

### ISSUE THREAD

**Issue by VincentNgVS** [SAPDocuments/Issues#410]
Tutorials: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html
--------------------------

Hi, 
I do not get any data of HT-2000 from https://refapp-espm-ui-cf.cfapps.eu10.hana.ondemand.com/espm-cloud-web/espm.svc. Is there another product or any other site I can use to test? 
Thanks.

![NoProductReturned](https://user-images.githubusercontent.com/42636616/121126507-d4ef5a80-c85a-11eb-8ab4-1cc0e6c59f38.JPG)

**Comment by Karunaharan** [comment]
Hi @VincentNgVS - other product IDs like HT-2001, HT-6120, HT-6121 also works. I checked this morning, and HT-2000 worked for me. Could you please check again?
