### ISSUE TITLE
Perform Actions On Cards To Support Your Business Case

### ISSUE THREAD

**Issue by VanitaDhanagar** [SAPDocuments/Issues#411]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-cards-booster-starter.html
--------------------------

The value for LifeCycleStatus did not change to Accepted ,It remains as NEW 
The value for LifeCycleStatus did not change to Rejected: Invalid Amount, it remains as NEW 

Thanks and Regards,
Vanita

**Comment by sandeep-tds** [comment]
Hi Vanita, 

I am unable to reproduce the issue. Thus, I will reach out to you on MS Teams to resolve it on your landscape. 

Thank you for your support.

**Comment by VanitaDhanagar** [comment]
it is fixed .Thank you sandeep
