### ISSUE TITLE
Configure Business Rules, Workflow and Process Visibility

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Issues#413]
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-configure.html
**Step 6: Build and deploy workflow**
--------------------------

**Issue:** 
The below screenshot and the information about the organisation-name/space-name in the bottom-blue bar can be removed as this feature is no longer available in BAS.

**Existing screenshot:**
![image](https://user-images.githubusercontent.com/65999547/121344945-e7908f00-c941-11eb-9ae1-ffa35acbdf4c.png)

**Actual screenshot:**
![image](https://user-images.githubusercontent.com/65999547/121344961-ec554300-c941-11eb-94b5-31c44c2d24e8.png)

Best Regards,
Priyanka

**Comment by NidhiMurkute** [comment]
Hi,

SCPTest-2107A: The screenshot is still not updated.
