### ISSUE TITLE
The name of the file should be changed

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Issues#414]
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-5-run.html
Step 1: Set up sample events for workflow
--------------------------
**Issue:**
The name of the file, when we download from [Link](https://github.com/SAP-samples/cloud-process-visibility/releases/download/1.0.0/Employee_OnboardingEvents.json) is **Employee_OnboardingEvents.json** but in the tutorial its given as **EmployeeOnboardingEvents.json**.
![image](https://user-images.githubusercontent.com/65999547/121345542-9af98380-c942-11eb-821c-a8aa82c3db23.png)

Best Regards,
Priyanka

**Comment by NidhiMurkute** [comment]
Hi,

SCPTest-2107A: The above issue still persists.

**Comment by ArchanaShukla** [comment]
Done, this is fixed now
