### ISSUE TITLE
Create A New Welcome Card

### ISSUE THREAD

**Issue by vanita57** [SAPDocuments/Issues#415]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-cards-welcome.html
--------------------------
Hi ,

The Welcome Card Template - Single Instance is not downloading automatically it shows downloading but never downloads.
Until we do unsubscribe and subscribe the card from application.

Kindly check on this .

Labels to be added:
prio: Medium
Sprint Label: SCPTest-2106A
Scenario Label: SCPTest-mcard
Landscape Labels: trial1,trial2,trial3
Thanks and Regards,
Vanita

**Comment by sandeep-tds** [comment]
Hi Vanita, 

I was not able to reproduce the issue. Thus, can we please sync internally to see what's happening on your landscape?

**Comment by sandeep-tds** [comment]
Hi Vanita, 

Since the issue is the same as the one you raised today, I am closing this ticket. 
https://github.com/SAPDocuments/Issues/issues/493

Warm Regards
Sandeep T D S
