### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio : Update screenshots with vscode folder included

### ISSUE THREAD

**Issue by mounikat987** [SAPDocuments/Issues#416]
Tutorials: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html
--------------------------

**Step 1: Create new Multitarget Application project**

7.SAP Business Application Studio reloads with the FioriDemo project open in its workspace. In the Explorer view you can see the FioriDemo project, its folder structure, and files.

**Issue1 :** 

The screenshot doesn't have vscode folder. Please update screenshot with vscode folder.

**Expected Result :** 

![image](https://user-images.githubusercontent.com/33411431/121500207-b96f8580-c9fb-11eb-9ec4-fc5665ab35b8.png)

========================

**Step 2: Configure the app to use Managed Application Router**

4.Select the Approuter Configuration wizard, and click Start.
7.Verify that the correct path appears (/home/user/projects/FioriDemo), and click Next.
8.For Approuter configuration, select the following, and click Next.

**Issue2 :** 

In above 3 steps,the screenshot doesn't have vscode folder. Please update screenshot in 3 places with vscode folder.

**Expected Result :** 

![image](https://user-images.githubusercontent.com/33411431/121501183-9ee9dc00-c9fc-11eb-8f75-8de1a3e05669.png)

Thanks
Mounika

**Comment by raz-korn** [comment]
Hi @mounikat987 ,

Thanks for letting me know.
Since it's a minor issue, unless something more significant appears, it will wait for the next update.
therefore, I'm closing this issue.

Regards - Raz
