### ISSUE TITLE
Run the Employee Onboarding Sample Scenario

### ISSUE THREAD

**Issue by IsabellaMasselli** [SAPDocuments/Issues#42]
Tutorial: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-5-run.html
--------------------------

Write here what you need help with ...  This is the second time I have logged this issue.  It was previously closed (Closed #6104.) as I did not have the time to check whether it had been fixed.. 

1.  I get all the way passed the successful Importing of the EmployeeOnboardingEvents JSON file but when I try to filter it there is no file to be found so I cannot continue with the tutorial.

**Comment by ArchanaShukla** [comment]
Hello @IsabellaMasselli ,
Can you please raise a ticket on LOD-BPM-PVS component. This could be a product issue or an issue with your trial account. The dev teams might need your cloud account details to look into it and update your account if needed. Thanks!

**Comment by ArchanaShukla** [comment]
@MichaelCzcz - there is another issue on this from Isabella. You may close this one. 
https://github.com/SAPDocuments/Issues/issues/69

**Comment by MichaelCzcz** [comment]
@ArchanaShukla In this repository you have permission to close issues that are assigned to you.
