### ISSUE TITLE
Req. Product details - API Management failing

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#421]
Hello,

Tutorial Link: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html
Step 4: Provision the capabilities
------------

Issue: The provisioning of API Management is failing in US region.
![image](https://user-images.githubusercontent.com/66831161/121568152-ff990900-ca3c-11eb-9315-db8b71320328.png)
The Scenario works fine in the EU and AP region.

Labels to be added:
Sprint Label: SCPTest-2106A
Landscape Labels: trial2 (US)
prio: High
Scenario Label: SCPTest-cloudin

Kind regards,
Shubham Agarwal

**Comment by Karunaharan** [comment]
Hi @i353590
Thanks for the feedback.

Checked a couple of times with different users. The issue is resolved now.

![image](https://user-images.githubusercontent.com/29120597/123375553-8f46c780-d5a6-11eb-8ef9-72c87c7fe61c.png)
