### ISSUE TITLE
Req. product details Integration -- Boosters failing for assigning role collection

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#422]
Hello,

Tutorial Link: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html
Step 5: Automatically assign roles and create service instances using Booster
-----------------

Issue: Step 5.6: In the Review tab, check your selections and choose Finish. You can see that the booster is being processed
The boosters are failing in EU & AP region for Assigning role collection.

Error says: "Could not assign users to role collections as some of the capabilities are not activated." even when the mentioned capabilities were activated.
Continued by manually assigning the roles.
Also, I couldn't find the role "AuthGroup.SelfService.Admin" while manually adding roles to my user. the scenario was successful though.

![image](https://user-images.githubusercontent.com/66831161/121569289-420f1580-ca3e-11eb-8df4-844692ff079b.png)

Labels to be added:
Sprint Label: SCPTest-2106A
Landscape Labels: trial1, trial3
prio: High
Scenario Label: SCPTest-cloudin

Kind regards,
Shubham Agarwal

**Comment by Karunaharan** [comment]
Hi @i353590 
Booster is getting successfully executed in EU & AP regions.

**Comment by Karunaharan** [comment]
I tested in EU and AP regions again this morning. Booster is working fine.
