### ISSUE TITLE
Req. product details Integration -- Screenshot Update || Add Integration Flow 

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#423]
Hello,

Tutorial Link: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html#a83503f8-f95b-4e97-b3bc-254ad2e537a7
Step 2: Create an integration package and integration flow
--------------------------

Issue: Step 2.2: Choose Add > Integration Flow.
On Clicking "add", now we get additional option Script Collection, so latest screenshot needs to be attached.
Please update the screenshot:
![image](https://user-images.githubusercontent.com/66831161/121570685-b9917480-ca3f-11eb-90c7-696410494141.png)

Labels to be added:
Sprint Label: SCPTest-2106A
Landscape Labels: trial1, trial2, trial3
prio: low
Scenario Label: SCPTest-cloudin

Kind regards,
Shubham Agarwal

**Comment by Karunaharan** [comment]
Hi @i353590 - the issue is fixed. will publish asap.
