### ISSUE TITLE
Fiori App Using launchpad -- Need to refresh browser to click on "Go to Site"

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#424]
Hello,

Tutorial Link: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-new-sapui5.html#4278ff9d-57b8-4e33-a2c8-1a5a5030076b
Step 6: Review the site
-----------------------
Issue: 
After creating the app, group and assigning the app to the group, on navigating back to the "Site Directory", We are unable to click on "Go to Site", without refreshing the browser.
Please refer the image:

![image](https://user-images.githubusercontent.com/66831161/121651370-2b0d0980-cab8-11eb-957e-1d48fae2ed8b.png)

Labels to be added:
Sprint Label: SCPTest-2106A
Landscape Labels: trial1, trial2, trial3
prio: High
Scenario Label: SCPTest-psite

Kind regards,
Shubham Agarwal

**Comment by LindsayBert** [comment]
Hi

I'm sorry for the late reply but I must have missed the notification of this issue.  I've never come across this issue before so I'm not able to help.  To have your issue inspected, please open a BCP for the EP-CPP-CF-DEV component.

Thanks
Lindsay

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
