### ISSUE TITLE
Create an SAP BTP ABAP Environment Trial User

### ISSUE THREAD

**Issue by FarozanFarman** [SAPDocuments/Issues#426]
**Tutorials:** https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html
--------------------------
**Issue:** We can provide both the options to connect to system to SAP BTP ABAP Environment.

**Steps to reproduce:**
At Step 1: Start boosters:
6. The booster is now executed successfully. Download the service key for later use. The service key is needed to setup the connection in ABAP Development Tools (ADT).

**Description:**
Since we are using **Select SAP BTP Cloud Foundry Environment and click Next >** in Step 3: 2nd point to connect the system to SAP BTP ABAP Environment, downloading the service key is not required.
Or else, before downloading there must be mentioned that "If you are connecting the system to SAP BTAP ABAP Environment in Step 3: 2nd point using Service Key option, then Download the service key. The service key is needed to setup the connection in ABAP Development Tools (ADT).

So we can provide both the options 1) To upload the service key which was downloaded earlier and connect the system using service key in Step 3. 
2)Select SAP BTP Cloud Foundry Environment, here we use the user id and password and continue without any upload of service key. Hence, a download is not required for this option.

Labels:
Landscape Labels: trail1, trail2
Scenario Label: SCPTest-fabap
Priority: Low
Sprint Label: SCPTest-2106A

Thanks and Regards,
Farozan

**Comment by FarozanFarman** [comment]
Hi Team,

Any update on this as the issue still persists.


Thanks and Regards,
Farozan

**Comment by mervey45** [comment]
Hi @FarozanFarman ,

I created following pull request: #6834. @MichaelCzcz  can you merge my pull request? 
Thank you in advance.

Best regards, 
Merve
