### ISSUE TITLE
Install the Kubernetes Command Line Tool

### ISSUE THREAD

**Issue by phil9909** [SAPDocuments/Issues#427]
Tutorials: https://developers.sap.com/tutorials/cp-kyma-download-cli.html
--------------------------

On Step 2:

If I run `kubectl version --client` I get the following output:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-13T02:40:46Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
```

If I click on "Submit Answer" this is rejected.

**Comment by jcawley5** [comment]
Hello,

The question is asking for the code or command that will provide the version information, not the result. 

Regards,
Jamie
