### ISSUE TITLE
Unable to import/select Equipment Determination Rules

### ISSUE THREAD

**Issue by LarsVlyminckx** [SAPDocuments/Issues#428]
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-configure.html
--------------------------

I'm currently following this tutorial but I'm stuck at **"Step 3: Import business rules from API Business Hub"** .
I get the error **"Bad Gateway Error"** :
![image](https://user-images.githubusercontent.com/33087668/122023591-fe166a80-cdc7-11eb-989a-3e53b8901b0b.png)

But if I go to the destinations and check the connection of "BUSINESSRULES_APIHUB" I get a correct working connection: **"Connection to "BUSINESSRULES_APIHUB" established. Response returned: "200: OK"**:
![image](https://user-images.githubusercontent.com/33087668/122023673-0ec6e080-cdc8-11eb-8dcd-375da984ac24.png)

When I go to [api.sap.com](https://api.sap.com/package/EquipmentDeterminationRules?section=Artifacts) I see the business rule but I can't select it as you can see in the picture: 
![image](https://user-images.githubusercontent.com/33087668/122023363-c1e30a00-cdc7-11eb-80b7-066c24307f5a.png)

Can somebody help me? What should I do?

Thanks in advance.

Lars

**Comment by ArchanaShukla** [comment]
Do you have user in API Business Hub? If not then login to api.sap.com and then wait for couple of hours 1-2 hours and try again - it should work.

**Comment by LarsVlyminckx** [comment]
As you can see on the last picture (top right) I was already logged in. I also imported the rule form Business Rules service as you can see on the first picture.

**Comment by ArchanaShukla** [comment]
Yes you are logged in, but was this the first time that you logged in? If yes then it takes some time to reflect. If you have logged in couple of hours before and still it is failing, then is your user two-factor authentication enabled? If yes, then you have to use password as password+passcode.

**Comment by LarsVlyminckx** [comment]
No it wasn't the first time that I was logged in. I already used this for Cloud Platform Integration and IoT API. I don't have two-factor authentication enabled. 
When I go to api.sap.com and select the business rule. I see in the console that I also have an error:
![image](https://user-images.githubusercontent.com/33087668/122063881-f0290f80-cdf0-11eb-8d15-a4f6be7ecf4a.png)
I don't know that this is the issue or not, but this isn't correct. Some colleagues of my also have this error.
In the network section I see that the UI is doing some API Calls
![image](https://user-images.githubusercontent.com/33087668/122064870-c58b8680-cdf1-11eb-88a1-0284fdcf1354.png)

**Comment by LarsVlyminckx** [comment]
I checked the API calls in incognito and there it was working after I logged in. So I updated the destinations and now it's working. So it was probably a password/login issue.

Thanks for the help
