### ISSUE TITLE
Add a List Report Interface to the CAP App (SAP HANA Cloud)

### ISSUE THREAD

**Issue by venkytc** [SAPDocuments/Issues#429]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-add-list-report.html
--------------------------

when I try to create run configuration, it says "there are no runnable resources". 
how to fix this?

**Comment by IObert** [comment]
Did you open your CAP project in the current workspace?

And can you please add a screenshot of the error message?

**Comment by venkytc** [comment]
Thanks for your response. I have this target
![image](https://user-images.githubusercontent.com/68116682/122043193-b22fe980-cdf8-11eb-89f1-83efa4960746.png)
 
and I this is the error I get

![image](https://user-images.githubusercontent.com/68116682/122043360-e3a8b500-cdf8-11eb-9b94-bc74d20e4020.png)

**Comment by IObert** [comment]
I wasn't referring to the target. I meant which workspace you use in the SAP Business Application Studio. You can navigate there when you click on the "files" icon on the top-left corner.

**Comment by venkytc** [comment]
pls see the workspace image
![image](https://user-images.githubusercontent.com/68116682/122064603-e6160980-ce0e-11eb-8ee2-2e1e28c91b69.png)

**Comment by IObert** [comment]
It is strange. I noticed that you used a different name for your project (this shouldn't cause the problem) but maybe you also diverged somewhere else from that path that has been described in [the tutorial](https://developers.sap.com/group.dsag-cloud-dev-day-cf.html).

Can you confirm that you used the Dev Space kind "Full Stack Cloud Application" and also followed all other steps exactly as described?

**Comment by venkytc** [comment]
I am able to fix this. as you mentioned, I had workspace at 'Projects'. when I opened 'MYCLOUDAPP', it started working. Thanks for pointing out.

**Comment by IObert** [comment]
Awesome!
