### ISSUE TITLE
Help Thomas Get Started with SAP HANA

### ISSUE THREAD

**Issue by DanGielman** [SAPDocuments/Issues#43]
Tutorial: https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html
--------------------------

Not able to find the COMMUNITY table. I follow the process correctly.

**Comment by jung-thomas** [comment]
Can you please share some details.  What does your project look like (a screenshot would help).  Your last deployment log.  Anything that might help us "See" what you are doing at this step.

**Comment by jung-thomas** [comment]
We can't help you if you don't return and supply a few more details about your problem.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
