### ISSUE TITLE
Add a List Report Interface to the CAP App (SAP HANA Cloud)

### ISSUE THREAD

**Issue by venkytc** [SAPDocuments/Issues#430]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-add-list-report.html
--------------------------

at step 3, in MTA Module from Template wizard, when I select application folder as /home/user/projects/MyCloudApp, it says 'The folder you have selected does not seem to contain a valid CAP project.  Please check and try again.'

**Comment by venkytc** [comment]
Please see the error screen:
![image](https://user-images.githubusercontent.com/68116682/122043767-59148580-cdf9-11eb-955a-4f052a804c6e.png)

**Comment by IObert** [comment]
Similar to the question from the other issue: How did you create the CAP project? Did you follow this tutorial? 
<https://developers.sap.com/group.dsag-cloud-dev-day-cf.html>

**Comment by IObert** [comment]
I'll close this now. Feel free to reopen if needed.
