### ISSUE TITLE
Call an External Endpoint to Retrieve Additional Information

### ISSUE THREAD

**Issue by vvnsmc** [SAPDocuments/Issues#433]
Tutorials: https://developers.sap.com/tutorials/cp-integration-consume-external-api.html
--------------------------

The tutorial says to try HTTP Adapter for a Content Enricher which is not supported.

When i tried SOAP adapter with same parameter the output is different from what mentioned in the Tutorial, this output failing in Routes. Please check and suggest changes

**Comment by gauthamkrishna-sap** [comment]
We are working on updating the tutorial series. In the meantime, I can offer you this session from TechEd 2020: https://github.com/SAP-samples/teched2020-DEV165

This also contains mail adapter configuration with REST API and a non-SAP system. Hope you can get some hands on experience with this while we update this series.

Thanks and Best Regards,
Gautham

**Comment by vvnsmc** [comment]
Thanks Gautam, i will go through the link.
Was able to figure out an alternative with additional components(Groovy + message mapping) & completed tutorial.
so closing this issue.
