### ISSUE TITLE
 Create Instance of SAP Event Mesh

### ISSUE THREAD

**Issue by cosmo83** [SAPDocuments/Issues#434]
Tutorials: https://developers.sap.com/tutorials/cp-enterprisemessaging-instance-create.html
--------------------------
Can someone help me with what iam missing. I have created the event-mesh instance with the default plan. There is no application link that is visible to me. I have no way to go to the event dashboard as described in the tutorials.

![image](https://user-images.githubusercontent.com/973160/122314767-6d11d180-cf36-11eb-9afe-61329cff79b1.png)

**Comment by pradeeppanda-sap** [comment]
Hi... 
 Sorry for the issue you are getting.
 While description has been provided in the [in this tutorial](https://developers.sap.com/tutorials/cp-enterprisemessaging-queue-queuesubscription.html), but let me admit that,  it does not have the recent changes.
While we are in the process of updating the content (will take a day or two), you can go ahead and create a management dashboard screen, by creating another event mesh instance by selecting of type "standard". This will create a management dashboard instance and you can manage the messsaging artifacts there.
Should you still require some more clarification, please re-open the issue and provide the details. We will be more than happy to help you.

regards
Pradeep
