### ISSUE TITLE
Call SAP API Business Hub API from a SAPUI5 Application

### ISSUE THREAD

**Issue by krisho007** [SAPDocuments/Issues#435]
Tutorials: https://developers.sap.com/tutorials/hcp-abh-api-ui5-app.html
--------------------------

In Step 1 of the tutorial, it is not clear why we need to create two destinations and when are we using each destination.
One of the destination connects to sandbox.api.sap.com. Not sure what is the role of sandbox here.

**Comment by Prathibha-Mouli** [comment]
Hi @krisho007, 
The tutorial is updated to provide clarity in the Step 1. 
Updated Tutorial : https://developers.sap.com/tutorials/hcp-abh-api-ui5-app.html

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
