### ISSUE TITLE
Call SAP API Business Hub API from a SAPUI5 Application

### ISSUE THREAD

**Issue by krisho007** [SAPDocuments/Issues#436]
Tutorials: https://developers.sap.com/tutorials/hcp-abh-api-ui5-app.html
--------------------------

The UI for BAS seems to have changed drastically for this scenario. The tutorial seems to need a rebuid.

**Comment by Prathibha-Mouli** [comment]
@krisho007 we are aware, and will pick it up when we have the bandwidth.
Thank you.
