### ISSUE TITLE
Define and Expose a CDS-Based Travel Data Model

### ISSUE THREAD

**Issue by klickerlebnis** [SAPDocuments/Issues#438]
Tutorials: https://developers.sap.com/tutorials/abap-environment-data-model.html
--------------------------

In Step 5 the answers should accept both values: Service Binding OR Service binding (OR service binding).

Many thanks! Great tutorial!

**Comment by mervey45** [comment]
Hi @Klickerlebnis,

thank you for your feedback. We'll update this as soon as possible.

Best regards, 
Merve

**Comment by mervey45** [comment]
Hi @MichaelCzcz  ,

I created following pull request: #6834. Can you merge my pull request?
Thank you in advance.

Best regards,
Merve
