### ISSUE TITLE
Add Transactional Behavior to Your Core Data Services

### ISSUE THREAD

**Issue by mts2605** [SAPDocuments/Issues#44]
Tutorial: https://developers.sap.com/tutorials/abap-environment-transactional-enablement.html
--------------------------

Hi,
In step 4, i can't select "New Behavior Implementation" Only what is seen in screendump.
![noimp](https://user-images.githubusercontent.com/43760831/104245556-c300bb80-5464-11eb-9d7d-4a2369997df2.png)
Please advice.
Michael

**Comment by mervey45** [comment]
Hi @mts2605 ,

thank you for your feedback, we'll update this as soon as possible.

Best regards, 
Merve

**Comment by mts2605** [comment]
Hi @mervey45

I found a way to get the New Behavior Implementation. In the error inside the behavior definition, it suggested to create a class;-) 
But maybe that could be added to the tutorial.
No matter what, great set of tutorials!
Thanks.
Michael
