### ISSUE TITLE
Set Up Local Development Using VS Code

### ISSUE THREAD

**Issue by Kaderde** [SAPDocuments/Issues#440]
Tutorials: https://developers.sap.com/tutorials/btp-app-set-up-local-development.html
--------------------------
In Step 9: Install VS Code Extensions 
Later, you can open the page through the **_command_** CDS: Show CAP Release Notes.
we would like to be more specific about the command to use : 
Later, you can open the page through the **_Command palette in VS Code_** : CDS: Show CAP Release Notes.
to distinguish from windows command line.

Thanks

Abdelkader

**Comment by iwonahahn** [comment]
This will be fixed with https://github.com/SAPDocuments/Tutorials/pull/6780
