### ISSUE TITLE
Develop and Run SAP Fiori Application With SAP Business Application Studio

### ISSUE THREAD

**Issue by klickerlebnis** [SAPDocuments/Issues#441]
Tutorials: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html
--------------------------

In step 8 there is no 
Service Type: OData IWSG
available. 

What can I choose instead?

It seems to be the **OData V2 (deprecated)** service.

Many thanks

**Comment by mervey45** [comment]
Hi @klickerlebnis ,

thank you for your feedback.
The screenshot has changed. OData V2 (deprecated) should be the one.

We will update this as soon as possible.

Best regards, 
Merve

**Comment by mervey45** [comment]
Hi @MichaelCzcz  ,

I created following pull request: #6834. Can you merge my pull request?
Thank you in advance.

Best regards,
Merve
