### ISSUE TITLE
Deploy an App to SAP BTP, Cloud Foundry runtime

### ISSUE THREAD

**Issue by yyaqqann** [SAPDocuments/Issues#443]
Tutorials: https://developers.sap.com/tutorials/cp-cf-dev-02-deploy-app.html
--------------------------

when i am clicking Deploy Application and check the file's location all right.then I clikc Deploy,an error occurs like :
'Unable to create route. We are sorry, but we have encountered an internal error. If the problem persists, please create a support ticket. Please specify a different route.'
may I ask how to solve this problem.

**Comment by qmacro** [comment]
Hi @yyaqqann - issues here are for providing feedback for the tutorial content itself. Please head on over to the SAP Community Q&A for your question - there's a specific tag for [SAP BTP, Cloud Foundry environment](https://community.sap.com/search/?ct=qa&mt=73555000100800000287&q=cloud%20foundry&qt=all). Thanks.
