### ISSUE TITLE
Create Decision Table and Text Rules

### ISSUE THREAD

**Issue by AbeDong** [SAPDocuments/Issues#444]
Tutorials: https://developers.sap.com/tutorials/cp-cf-businessrules06-dt-textrule.html
--------------------------

When I created the decision table, and test the service in the API HUB, something wired from what I can see.
1. Here is the decision table.
![image](https://user-images.githubusercontent.com/34675321/122886330-72c24980-d372-11eb-9ef0-bd6332728009.png)
2. When I try with below payload 'CHN' '3000', I can get the result. 
![image](https://user-images.githubusercontent.com/34675321/122886563-a8673280-d372-11eb-8972-0f2c56f0984b.png)
![image](https://user-images.githubusercontent.com/34675321/122886702-c46ad400-d372-11eb-8b31-b56e5443d24b.png)
3. When I try with below payload 'USA' '3000', I can get an empty result
![image](https://user-images.githubusercontent.com/34675321/122887034-114eaa80-d373-11eb-8fbf-b6aa233aa0a9.png)
![image](https://user-images.githubusercontent.com/34675321/122887070-1b70a900-d373-11eb-8209-c3d58c6452ee.png)
4. When I try with payload 'USA' '2000', get an request error
![image](https://user-images.githubusercontent.com/34675321/122887203-40651c00-d373-11eb-9444-e0dbea18ee90.png)
![image](https://user-images.githubusercontent.com/34675321/122888035-0a746780-d374-11eb-9b31-66fead15bbba.png)
5. If I changed the decision table like below, then the service can return a result.
![image](https://user-images.githubusercontent.com/34675321/122888518-85d61900-d374-11eb-9cc1-044161b6d8f6.png)
![image](https://user-images.githubusercontent.com/34675321/122888603-971f2580-d374-11eb-9e9b-ecb5baf9381e.png)

Any idea why the functionality looks like this?
Thank you

**Comment by VandanaVasudevan** [comment]
Hi @AbeDong,

The logic should ideally work even when the value of JobTitle is MATCHES '.*'. Is this issue repeating?
If yes, can you share the zip file of your project with me? (From the Manage Projects screen, choose the export icon and save the project to your workspace.)

Best Regards,
Vandana

**Comment by AbeDong** [comment]
Hi Vandana,
Please find the project which has issue.
Thank you very much.

Vandana Vasudevan ***@***.***> 于2021年6月24日周四 下午9:06写道：

**Comment by VandanaVasudevan** [comment]
Hi @AbeDong,

I'm unable to find the project. Can you please send it once again?

Best Regards,
Vandana

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
