### ISSUE TITLE
Create an SAP Cloud Application Programming Model Project for SAP HANA Cloud

### ISSUE THREAD

**Issue by dungvti** [SAPDocuments/Issues#445]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-create-project.html
--------------------------

Issue - Create a new service instance

In step 3.3 not able to create hana instance because plan **hdi-shared** has been deleted in BTP trial account so this creation is not possible.
 
Error when binding:
![1](https://user-images.githubusercontent.com/78527812/122898007-bd44c580-d374-11eb-9a4f-480ac7f18f8d.png)

And service Hana in my trial account:
![2](https://user-images.githubusercontent.com/78527812/122898183-e1a0a200-d374-11eb-82fc-1dabf49176b4.png)

Can somebody help me? What should I do?

**Comment by jung-thomas** [comment]
I don't believe this is anything specific with this tutorial but a general issue with the entitlement setup in BTP trial.  Did you just recently create your trial account?  I've seen a few similar reports from people newly created that their entitlements aren't correct.   But you are looking at the wrong entitlement in the above screenshot.  It's not the HDI containers trial.  That's for the older HaaS trial.  Instead look at the middle entry. Do you see an hdi-shared available there?  It should be.  If it's not assigned to your user then add the service plan from this same screen. If it is already assigned then unassign it, save, back out, and then come back in and add it back.
