### ISSUE TITLE
Develop a Business App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by VanitaDhanagar** [SAPDocuments/Issues#446]
Tutorials: https://developers.sap.com/tutorials/appstudio-cap-app.html
--------------------------
Step 3 : in cat-service.cds file 

action submitOrder (book : **Books.ID,** amount: Integer);

A line of code need to updated (comma to colon)

action submitOrder (book : **Books:ID**, amount: Integer);

Thanks and Regards,
Vanita

**Comment by Paolaufer** [comment]
Thank you for the feedback!
I've made the change and will republish the tutorial.
