### ISSUE TITLE
Create a UI Using Freestyle SAPUI5

### ISSUE THREAD

**Issue by ivanmir** [SAPDocuments/Issues#447]
Tutorials: https://developers.sap.com/tutorials/btp-app-create-ui-freestyle-sapui5.html
--------------------------

The text refers to changes in the manifest.yaml whereas it is in fact related to manifest.json

**Comment by iwonahahn** [comment]
Hi @ivanmir,

Thank you for reporting it. We have updated the tutorial, see [here](https://github.com/SAPDocuments/Tutorials/pull/6790).

Best regards,
Iwona
