### ISSUE TITLE
Implement Roles and Authorization Checks In CAP

### ISSUE THREAD

**Issue by ivanmir** [SAPDocuments/Issues#448]
Tutorials: https://developers.sap.com/tutorials/btp-app-cap-roles.html
--------------------------

On Step 3: the first thing to do is to copy file .cdsrc.json from the template directory. But this file is not part of the cloned repository. On the other hand, there is a file with the same name already on the root project folder with an empty content.

**Comment by iwonahahn** [comment]
Hi @ivanmir,

Thank you for reporting this. We have fixed this and you find now the file [here](https://github.com/SAP-samples/cloud-cap-risk-management/tree/master/templates/cap).

Best regards,
Iwona
