### ISSUE TITLE
Prepare for SAP BTP Development

### ISSUE THREAD

**Issue by ivanmir** [SAPDocuments/Issues#449]
Tutorials: https://developers.sap.com/tutorials/btp-app-prepare-btp.html
--------------------------

From Step 4 onwards it gets confusing - the tutorial should clearly state that either you create a trial account or use an existing global account. Usually developers will already have their own global account created and ready to use - BTP Control Center is for administrator, not developers - isn't it?

**Comment by iwonahahn** [comment]
Hi @ivanmir,

Thank you for your feedback. We will have a look at the tutorial and will improve it.

Best regards,
Iwona

**Comment by uwe-klinger** [comment]
Hi @ivanmir,

Thanks for your feedback.

You're right, the the text lacks some guidance. We'll add it.

But will keep the documentation for live landscapes, as developers might need to setup their development account. Anyhow, and also in the spirit of DevOps, it doesn't hurt to understand the full process. :-)

Best regards,
Uwe
