### ISSUE TITLE
Create an ABAP Core Data Services (CDS) View in SAP Cloud Platform, ABAP Environment

### ISSUE THREAD

**Issue by mts2605** [SAPDocuments/Issues#45]
Tutorial: https://developers.sap.com/tutorials/abap-environment-create-cds-mde.html
--------------------------

Step 9 - I am not sure which CDS view to enter/Add the suggested annotation in. Please explain a bit more detailled.

Thanks, Michael

**Comment by julieplummer20** [comment]
Done!
BR Julie.

**Comment by mts2605** [comment]
Sorry, but what was changed?

**Comment by julieplummer20** [comment]
After Michael's feedback, I added the name of the CDS view to step 9.

**Comment by mts2605** [comment]
Thanks Julie, but no matter which browser I use, I still can not see any changes.
BTW - in step 9 also - I would expect a screendump after this sentence:

"The start of your CDS view will then look like this...."

Thanks for a great tutorial.
KR Michael

**Comment by julieplummer20** [comment]
Hi Michael,
Could you please email me, preferably with a contact no. ?
I think we are perhaps talking at cross-purposes here, so it might be easier to resolve this via Teams / Skype.
I will be out of the office this afternoon, and not working tomorrow, but can contact you on Monday.
Thanks and best wishes,
Julie.

**Comment by julieplummer20** [comment]
Hi, I apologize. I will make sure this is visible both internally and externally, and let you know. 
Thank you for the positive feedback. 
BR Julie.

**Comment by julieplummer20** [comment]
Hi Michael,
I am sorry about the delay. Can you now see the change?
Re: Your second question: Normally, you are right, I would expect a screen shot. However, in this case, I mean that your code should look like the code immediately below.
![Snag_56ebbd5](https://user-images.githubusercontent.com/22739917/105012053-00a1ad80-5a3e-11eb-85da-b05c603c624c.png)

HTH Julie.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
