### ISSUE TITLE
Deploy Your Multi-Target Application (MTA)

### ISSUE THREAD

**Issue by ivanmir** [SAPDocuments/Issues#450]
Tutorials: https://developers.sap.com/tutorials/btp-app-cap-mta-deployment.html
--------------------------

Step 1: correct answer is mbt whereas the text says mtb. Other answers are correct (mta is the old tool name, mta-build doesn't exist - but mta build is the command that builds the mtar archive.

**Comment by iwonahahn** [comment]
Hi @ivanmir,

Thank you for reporting it. We have updated the tutorial, see [here](https://github.com/SAPDocuments/Tutorials/pull/6790).

Best regards,
Iwona
