### ISSUE TITLE
Deploy a Go MSSQL API Endpoint in the Kyma Runtime

### ISSUE THREAD

**Issue by imran-asif-sse** [SAPDocuments/Issues#452]
Tutorials: https://developers.sap.com/tutorials/cp-kyma-api-mssql-golang.html
--------------------------

On Step the Env varaible should be enclosed in '' for Windows Powershel to work.
It should be as below:

$ENV:MYAPP_username='sa'
$ENV:MYAPP_password='Yukon900'
$ENV:MYAPP_database='DemoDB'
$ENV:MYAPP_host='localhost'
$ENV:MYAPP_port=1433

**Comment by jcawley5** [comment]
Thank you for the comment - fixed in 

https://github.com/SAPDocuments/Tutorials/pull/6795
