### ISSUE TITLE
Tutorial : Integrate a Custom-Developed SAPUI5 App Into Your Launchpad Site

### ISSUE THREAD

**Issue by I321500** [SAPDocuments/Issues#453]
I followed the tutorial and completed the following chapters successfully.
 - Set Up SAP Business Application Studio for Development
 - Create a Dev Space for SAP Fiori Apps
 - Create an SAP Fiori App Using SAP Business Application Studio

In "Build and Deploy Your SAP Fiori App to SAP Business Technology Platform", I followed all the steps.
In step 4, sub-step 5 it says we will be able to see the application. But for me it shows "Application could not be started due to technical issues."

Git : https://github.wdf.sap.corp/sli-innersource/SocialAtSAP-Admin.git
Git Branch : adminUI.

Url after deloyment : https://social-sap-dev.launchpad.cfapps.sap.hana.ondemand.com/e41c7fde-8c61-4d7b-9321-c281370be8f4.admin.comsocialadmineventevent-1.0.0/index.html

Please help me out at the earliest.

<img width="740" alt="FLP issue" src="https://user-images.githubusercontent.com/86424499/123292559-c7132800-d530-11eb-9086-5c6d23b65251.PNG">

**Comment by LindsayBert** [comment]
Hi

If you did all the tutorials then it can only be one of the following reasons:

You used a standalone app router when you created the MTA
You didn't add an intent to the app

If it's the first problem, you should delete the app from the space on in your subaccount and develop it again using this tutorial https://developers.sap.com/tutorials/appstudio-fioriapps-create.html. 
Make sure you select '**Managed by SAP Cloud Platform**' App Router' (as explained in step 2)

If it's not one of these issues, then there is really a technical problem and you should open up a support ticket.

Hope this helps.
Thanks
Lindsay

**Comment by I321500** [comment]
Hi Lindsay,

We have used the Managed App router option as mentioned in the tutorial.
The one major difference is, we have CAP service which has UI annotations as well. So, instead of SAP Freestyle application, we chose 'List Object Page'.
While loading the app, there are issues with metadata.
Could you please help here?

Thanks,
Viji

**Comment by LindsayBert** [comment]
Hi

Thank you for your reply. It seems that your issues require investigating your code which is beyond the scope of supporting the tutorials. To have your issue inspected, please open a BCP for the EP-CPP-CF-DEV component.

Thanks
Lindsay

**Comment by I321500** [comment]
Thanks Lindsay, I will do it.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
