### ISSUE TITLE
Consume a Basic OData Service

### ISSUE THREAD

**Issue by matton2** [SAPDocuments/Issues#455]
Tutorials: https://developers.sap.com/tutorials/xsa-sapui5-odata.html
--------------------------

Hello.  Since sap.iu.unified.Shell has been depreciated, would it be possible to share an example using sap.f.ShellBar in the setup.js file?

**Comment by jung-thomas** [comment]
The newer version of this sample for SAP HANA Cloud does use sap.f.ShellBar: https://github.com/SAP-samples/hana-opensap-cloud-2020/tree/main/app/resources/odataBasic

But there are no plans to update the older XSA/HANA Express tutorials at this time.

**Comment by matton2** [comment]
Thanks for the example @jung-thomas !
