### ISSUE TITLE
Deploy Your Multi-Target Application (MTA)

### ISSUE THREAD

**Issue by yker14** [SAPDocuments/Issues#457]
Tutorials: https://developers.sap.com/tutorials/btp-app-cap-mta-deployment.html
--------------------------

Hello. 

I'm getting an error at the end of the tutorial Deploy Your Multi-Target Application (MTA) when executing the command:
cf deploy cpapp_1.0.0.mtar

The error shown is:
Could not get access token: not a compact JWS

I am a little clueless about how package-lock.json creates this JWS and how to fix it.

Thanks!

**Comment by slavipande** [comment]
Hi there,

This error does not look like it's related to the .mtar file. Could you please doublecheck if you're logged in successfully to your BTP account and try deployment again?

Please let us know in case you encounter further difficulties.

Best regards,
Svetoslav

**Comment by yker14** [comment]
Hi, indeed. I was not properly logge in. The message is misleading though.

Sorry for the inconveniences an thanks!

**Comment by iwonahahn** [comment]
Hi @yker14,

Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

Best regards,
Iwona
