### ISSUE TITLE
SAP HANA XS Advanced, Creating an HDI Module

### ISSUE THREAD

**Issue by pablolaurin** [SAPDocuments/Issues#458]
Tutorials: https://developers.sap.com/tutorials/xsa-hdi-module.html
--------------------------

I think the table/view snippets are missing the prefix _hana_app.db.data::_
Without the prefix, I get this error when building the db module:

> Error: com.sap.hana.di.table.validation: "PurchaseOrder.Item" has to be prefixed with the namespace "hana_app.db.data" and the name must not contain additional ':' characters after the namespace prefix [8200530]        at "src/data/PurchaseOrderItem.hdbtable$PurchaseOrder.Item.validate" (1:14-34)

**Comment by jung-thomas** [comment]
No the prefix isn't missing in the code snippet.  In the earlier step you should have cleared the namespace:

**Clear the namespace field** (namespaces are only really there for backwards compatibility with the old HANA repository), enter a name for the schema and check the Build Module after creation tick box. Press Finish.
![image](https://user-images.githubusercontent.com/12159356/123654229-dda0d400-d7fb-11eb-8934-7e2d63c32ff2.png)

We aren't using a namespace in this tutorial.

**Comment by pablolaurin** [comment]
Thanks Thomas!
