### ISSUE TITLE
Create an ABAP Database Table and Relevant ABAP Dictionary Objects

### ISSUE THREAD

**Issue by german-mesa** [SAPDocuments/Issues#459]
Tutorials: https://developers.sap.com/tutorials/abap-dev-create-table.html
--------------------------

Hi developers.sap.com team,

Just a minor thing. While creating the table, account_number starts being a key field at the beginning to become a non-key field at the end. The other way around happens to the bank_customer_id. Starts being a non-key field at the beginning to become a key field at the end.

I believe there's a small typo there.

BR
German

**Comment by julieplummer20** [comment]
Hi German,
You are quite right.
I apologise. I will fix this at once. For reference, here is the correct code:

`@EndUserText.label : 'Bank Accounts Table JP'
@AbapCatalog.enhancement.category : #NOT_EXTENSIBLE
@AbapCatalog.tableCategory : #TRANSPARENT
@AbapCatalog.deliveryClass : #A
@AbapCatalog.dataMaintenance : #RESTRICTED
define table zaccounts_jp3 {
  key client         : mandt not null;
  key account_number : abap.numc(8) not null;




  @AbapCatalog.foreignKey.screenCheck : false
  bank_customer_id   : /dmo/customer_id not null
    with foreign key [0..*,1] /dmo/customer
      where customer_id = zaccounts_jp3.bank_customer_id;
  bank_name          : z_bank_name_jp3;
  city               : /dmo/city;
  @Semantics.amount.currencyCode : 'zaccounts_jp3.currency'
  balance            : abap.curr(16,2);
  currency           : /dmo/currency_code;
  account_category   : abap.numc(2);
  lastchangedat      : timestampl;

}`

Thanks and best wishes,
Julie.
