### ISSUE TITLE
Create a Calculation View with Differential Privacy in SAP HANA Cloud

### ISSUE THREAD

**Issue by jagadeesh247** [SAPDocuments/Issues#460]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-calculation-view-differential-privacy.html
--------------------------

Write here how you think we can improve the tutorial ...

Hi Team,

The provided material is very good and helpful, But in the tool when I follwed the same process while creating the calculation view nothing is coming up it is like a blank screen which keeps on running as shown below.
Please help to update anything if we missed to add installation command for Creating Hana views ? Even I have seen the same thread which other user is also facing. Please find the attached link.

https://answers.sap.com/questions/13421902/calculation-view-editor-in-sap-business-applicatio.html?childToView=13422669

Expecting your valuble solution for the same to proceed further .

![hana_xsa_cloud_jag - SAP Business Application Studio](https://user-images.githubusercontent.com/32096987/123795870-1925c600-d902-11eb-8398-36a448671a68.png)

Thanks.

Regards,
jagadeesh.

**Comment by jung-thomas** [comment]
This does not appear to be any issue with the steps in the tutorial itself. It would appear to be a problem in the Calculation View editor itself. For that we would suggest that you post your question in the SAP Community Q&A or open a support ticket for the Business Application Studio Calculation View editor itself.

**Comment by jagadeesh247** [comment]
Hi Thomas,

Thanks for your quick response. I was using the HANA Cloud BTP Trail platform. Could you please help me on the procedure how to raise a support ticket for the same . It wolud be very helpful if there is any specific document with steps to be followed for the trail edition.

Thanks.

Regards,
jagadeesh.
