### ISSUE TITLE
Consume SOAP Based Web Services with SAP BTP, ABAP Environment

### ISSUE THREAD

**Issue by Tukutupap** [SAPDocuments/Issues#461]
Tutorials: https://developers.sap.com/tutorials/abap-environment-soap-web-services.html
--------------------------

Product used in the example ('HT-1000') does not exist in product table SNWD_PD in ES5. Here is a list of alternative products that can be used.

AR-FB-1000PR
AR-FB-1001PR
AR-FB-1002PR
AR-FB-1003PR
AR-FB-1004PR
AR-FB-1005PR
AR-FB-1006PR
AR-FB-1007PR
AR-T-1000 PR
AR-T-1001 PR
AR-T-1002 PR

**Comment by mervey45** [comment]
Hi @Tukutupap ,

thank you for your feedback.

Best regards. 
Merve
