### ISSUE TITLE
Deploy Your Multi-Target Application (MTA)

### ISSUE THREAD

**Issue by TheMasonAbides** [SAPDocuments/Issues#462]
Tutorials: https://developers.sap.com/tutorials/btp-app-cap-mta-deployment.html
--------------------------

In the questions, you have the mbt package spelled incorrectly in the answers.
![Screen Shot 2021-06-29 at 11 07 05 AM](https://user-images.githubusercontent.com/32575169/123839406-51a9ad80-d8ca-11eb-82ab-6a9d4026ebc9.png)

**Comment by iwonahahn** [comment]
Hi @TheMasonAbides,

Thank you for reporting this. We have fixed it as you can see [here](https://developers.sap.com/tutorials/btp-app-cap-mta-deployment.html#ec941da1-ae80-48ba-9600-1c9cca1f3ef5).

Best regards,
Iwona

**Comment by TheMasonAbides** [comment]
Thanks Iwona!
