### ISSUE TITLE
Build an Application End-to-End using CAP, Node.js and VS Code

### ISSUE THREAD

**Issue by AndyGla** [SAPDocuments/Issues#463]
Mission: https://developers.sap.com/mission.btp-application-cap-e2e.html
--------------------------

This tutorial is great.

By downloading all materials from github you can either get the requiered code snippets from the website or by copying it from the "tutorials"-folder. That reduces the errors :-D

Thanks a lot - really enjoying this mission

Cheers 

Andy

**Comment by uwe-klinger** [comment]
Hi Andy,

It's great to hear that you enjoyed doing our tutorial. Thanks for your feedback.

Best regards,
Uwe (on behalf of the tutorial team)
