### ISSUE TITLE
Create a UI Using Freestyle SAPUI5

### ISSUE THREAD

**Issue by laszloKajan** [SAPDocuments/Issues#465]
Tutorials: https://developers.sap.com/tutorials/btp-app-create-ui-freestyle-sapui5.html
--------------------------

Step 5 "If these are of interest to you, you can go on using cds watch and skip the rest of the section." should probably read:

- "If these are of /no/ interest to you ...".

**Comment by iwonahahn** [comment]
Hi @laszloKajan,

Thank you for your feedback. We have updated the tutorial in [step 5](https://developers.sap.com/tutorials/btp-app-create-ui-freestyle-sapui5.html#8e986496-9203-4868-925d-b60467623331).

Best regards,
Iwona
