### ISSUE TITLE
Set Up the SAP HANA Cloud Service

### ISSUE THREAD

**Issue by yker14** [SAPDocuments/Issues#466]
Tutorials: https://developers.sap.com/tutorials/btp-app-hana-cloud-setup.html
--------------------------
I am getting this message in the BTP screen at step 4.13 where it says i must have "undefined vCPUs" for this capabilities.

I'm also having troubles deploying the app at the end of this tutorial, not sure if it might be related to this.

![image](https://user-images.githubusercontent.com/7229713/124208314-e5d36a80-daac-11eb-80e3-36e21629bbae.png)

Thank you for the help in advance.

**Comment by iwonahahn** [comment]
Hi @yker14,

The message is related to the SAP Cloud Connector enabling, This is not relevant for you. Could you please share which issue you face for deployment? Maybe you can share your GitHub repo and we can have a look,

Best regards,
Iwona

**Comment by yker14** [comment]
Hello @iwonahahn thank you for assisting me with the issue.

So this happens in the step 8.2 of the Deploy Your Multi-Target Application (MTA) tutorial. 

The steps fails to do the deploy task of cpapp-db-deployer. The logs return the following messages:

######org.cloudfoundry.multiapps.controller.persistence.services.ProcessLogger########flowable-async-job-executor-thread-1644###
[PollExecuteTaskStatusExecution] [cpapp-db-deployer] [HIDDEN] [Thu Jul 01 04:00:50 UTC 2021] Could not check if session variable APPLICATION is set correctly: Connection failed (RTE:[89008] Socket closed by peer ([HIDDEN].hana.trial-us10.hanacloud.ondemand.com:443)) (STDOUT, APP/TASK/deploy)#

DEBUG#com.sap.cloud.lm.sl.xs2.[HIDDEN].cpapp-db-deployer.executeTaskTask#
######org.cloudfoundry.multiapps.controller.persistence.services.ProcessLogger########flowable-async-job-executor-thread-1644###
[PollExecuteTaskStatusExecution] [cpapp-db-deployer] [HIDDEN] [Thu Jul 01 04:00:50 UTC 2021] Could not determine status of last build: Connection failed (RTE:[89008] Socket closed by peer ([HIDDEN].hana.trial-us10.hanacloud.ondemand.com:443)) (STDOUT, APP/TASK/deploy)#

DEBUG#com.sap.cloud.lm.sl.xs2.[HIDDEN].cpapp-db-deployer.executeTaskTask#
######org.cloudfoundry.multiapps.controller.persistence.services.ProcessLogger########flowable-async-job-executor-thread-1644###
[PollExecuteTaskStatusExecution] [cpapp-db-deployer] [HIDDEN] [Thu Jul 01 04:00:50 UTC 2021] Error: Connection failed (RTE:[89008] Socket closed by peer ([HIDDEN].hana.trial-us10.hanacloud.ondemand.com:443)) (STDERR, APP/TASK/deploy)#

DEBUG#com.sap.cloud.lm.sl.xs2.[HIDDEN].cpapp-db-deployer.executeTaskTask#
######org.cloudfoundry.multiapps.controller.persistence.services.ProcessLogger########flowable-async-job-executor-thread-1644###
[PollExecuteTaskStatusExecution] [cpapp-db-deployer] [HIDDEN] [Thu Jul 01 04:00:50 UTC 2021] Error: Connection failed (RTE:[89008] Socket closed by peer ([HIDDEN].hana.trial-us10.hanacloud.ondemand.com:443)) (STDERR, APP/TASK/deploy)#

DEBUG#com.sap.cloud.lm.sl.xs2.[HIDDEN].cpapp-db-deployer.executeTaskTask#
######org.cloudfoundry.multiapps.controller.persistence.services.ProcessLogger########flowable-async-job-executor-thread-1644###
[PollExecuteTaskStatusExecution] [cpapp-db-deployer] [HIDDEN] [Thu Jul 01 04:00:50 UTC 2021] Deployment to container [HIDDEN] failed - error: Connection failed (RTE:[89008] Socket closed by peer ([HIDDEN].hana.trial-us10.hanacloud.ondemand.com:443)) [Deployment ID: none]. (STDERR, APP/TASK/deploy)#


After that a set of supposed npm error messages and then a clean up and exit: 

npm ERR! errno 1 (STDERR, APP/TASK/deploy)#
npm ERR! code ELIFECYCLE (STDERR, APP/TASK/deploy)#
npm ERR! deploy@ start: `node node_modules/@sap/hdi-deploy/deploy.js` (STDERR, APP/TASK/deploy)#
npm ERR! This is probably not a problem with npm. There is likely additional logging output above. (STDERR, APP/TASK/deploy)#
npm ERR! Failed at the deploy@ start script. (STDERR, APP/TASK/deploy)#
npm ERR!  (STDERR, APP/TASK/deploy)#
npm ERR! Exit status 1 (STDERR, APP/TASK/deploy)#npm ERR!     /home/vcap/app/.npm/_logs/2021-07-01T04_00_50_586Z-debug.log (STDERR, APP/TASK/deploy)#
npm ERR! A complete log of this run can be found in: (STDERR, APP/TASK/deploy)#
Exit status 1 (STDOUT, APP/TASK/deploy)#

Note that cpapp-srv does deploy successfully and the instances of cpapp, cpapp-db and cpapp-uaa. 

Here is the [link](https://github.com/yker14/btptutorial.git) to a repo with my tutorial files.

**Comment by uwe-klinger** [comment]
Hi @yker14 ,

We had a few issues with apps running on trial not being whitelisted as "SAP IP". I opened a ticket for that issue.

For the time being, please try the following:

1. Log into your trial account
2. Choose subaccount **trial**
3. Choose **Spaces**
4. Choose space **dev**
5. Choose **SAP HANA Cloud**
6. Choose **Actions → SAP HANA Cloud Central** for your SAP HANA Cloud instance 
7. Choose **... → Edit ** in the row of your SAP HANA Cloud instance
8. Change **Allowed conntections** to **Allow all IP addresses**
9. Choose **Save**
10. Wait for your SAP HANA Cloud instance to complete the restart. You may need to click the refresh circle button to check the state.

Best regards,
Uwe
