### ISSUE TITLE
Create Business Configuration for Factory Calendar

### ISSUE THREAD

**Issue by klickerlebnis** [SAPDocuments/Issues#467]
Tutorials: https://developers.sap.com/tutorials/abap-environment-service-binding.html
--------------------------

Under step 2.8 the right-click has to be performed with "Dictionary" instead Right-click on Data Elements...

**Comment by mervey45** [comment]
Hi @klickerlebnis ,

thank you for your feedback. You are able to create a new data element by right-clicking the dictinary and then selecting data element. Or you can directly right-click the data elements folder to create a new data element. You have both options.

Best regards, 
Merve
