### ISSUE TITLE
Installing SAP HANA, express edition with Docker

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Issues#468]
Tutorials: https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html
--------------------------

A new Hana express has been released: `2.00.054.00.20210603.1.` 

Please update accordingly, especially for sizing requirements.

Thanks,
greg

**Comment by JCurrie27** [comment]
Updated string to 2.00.054.00.20210603.1
