### ISSUE TITLE
Use Machine Learning to Extract Information from Documents with Document Information Extraction Trial UI

### ISSUE THREAD

**Issue by AkankshaKullu** [SAPDocuments/Issues#47]
Tutorial: https://developers.sap.com/tutorials/cp-aibus-dox-ui.html
--------------------------

Write here what you need help with ...

In step 2.4 the screenshot needs to be changed as the UI has changed. We no longer get the option to "Add Line Item and Delete Last Line Item" instead we get the + icon to do so.

Expected:
![1](https://user-images.githubusercontent.com/69286515/104323275-fd716380-550b-11eb-9970-3e20abcc22d9.png)

Actual:
<img width="960" alt="1_2" src="https://user-images.githubusercontent.com/69286515/104323288-019d8100-550c-11eb-88ac-b909957d3cc9.png">

Labels:
Landscape Labels:  trial1,  trial2
Sprint Label: SCPTest-2012B
Scenario Label: SCPTest-docinfo
Priority: High

**Comment by Juliana-Morais** [comment]
Hi, the issue has been fixed and the changes have been pushed to PROD with https://github.com/SAPDocuments/Tutorials/pull/6411

**Comment by MichaelCzcz** [comment]
@Juliana-Morais You can close your issues in this repository.

**Comment by Juliana-Morais** [comment]
https://developers.sap.com/tutorials/cp-aibus-dox-ui.html#eac0bd2d-299c-42cd-b408-5648337b3981 has been updated.
