### ISSUE TITLE
Develop and Run SAP Fiori Application With SAP Business Application Studio

### ISSUE THREAD

**Issue by pjcools** [SAPDocuments/Issues#470]
Tutorials: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html
--------------------------
Having an issue with Step 8: Create IAM App and business catalog

When creating the IAM app I cannot see the Service Type of 'OData IWSG' - this does not show in my list. I can only see the following. 

![image](https://user-images.githubusercontent.com/38389079/124378832-ef501300-dcf6-11eb-90c5-a75214dc2d2a.png)

Is there a setting I need to make to allow this option to appear?

thanks
Phil Cooley

**Comment by mervey45** [comment]
Hi @pjcools , 

please try out OData V2, there was a name change. I'll update this.

Thank you.

Best regards, 
Merve

**Comment by pjcools** [comment]
This did not work

![image](https://user-images.githubusercontent.com/38389079/125184969-3e50f780-e265-11eb-8e2b-83b1ef7d8647.png)

But I chose the deprecated item and then it worked. If you can please update this tutorial to show the right steps that would be great. 

This screenshot shows it has worked when I selected the deprecated entry. 

![image](https://user-images.githubusercontent.com/38389079/125184991-5a549900-e265-11eb-99ae-fb3b95530cc9.png)


Kind Regards
Phil Cooley

**Comment by mervey45** [comment]
Hi @pjcools , 

in my last message I mentioned deprecated in brackets. I also ment the deprecated version of odata v2. I'll update this as soon as possible.

Best regards, 
Merve
