### ISSUE TITLE
Create Database Artifacts Using Core Data Services (CDS) for SAP HANA Cloud

### ISSUE THREAD

**Issue by russellw999** [SAPDocuments/Issues#471]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-create-database-cds.html
--------------------------

Write here how you think we can improve the tutorial ...

Step 3 Deploy Objects into the Databaee -  Use the  SAP HANA Projects view ??

I would if it existed but it does not appear on the left side options

I have
1.   MyHANNAAPP
2.  NPM SCRIPTS
3.  CAP DATA MODELS AND SERVICES
4. TIMELINE

How can i active this view

**Comment by jung-thomas** [comment]
Go back to the previous tutorial when you created your Dev Space: https://developers.sap.com/tutorials/hana-cloud-cap-create-project.html
In the first step when creating the space you need to select the additional SAP HANA Tools and Calculation View editor.  
![image](https://user-images.githubusercontent.com/12159356/124400698-76e75300-dcf2-11eb-8ebb-50e35fe9fa4f.png)

If you are missing the SAP HANA Projects view, then you didn't select the SAP HANA Tools at this step. If you stop your dev space and then press the Edit Icon, it will return you to this same screen as when you were creating your Dev Space.  Add the two tools as specified in the tutorial, save and restart the Dev Space.  When you reload the Business Application Studio you should then have the SAP HANA Projects View.
