### ISSUE TITLE
Create a Reusable Service

### ISSUE THREAD

**Issue by MerlinBrandner** [SAPDocuments/Issues#472]
Tutorials: https://developers.sap.com/tutorials/cp-cap-java-reusable-service.html
--------------------------

index.cds has wrong admin-services path. Missing letter 's'  in " using from './srv/admin-service'; "
Instead it should be: " using from './srv/admin-services'; "

`using from './srv/admin-service';`

should be changed to

`using from './srv/admin-services';`

**Comment by beckermarc** [comment]
Hi @MerlinBrandner,

thanks for opening an issue, but that might be a typo on your side. In the original step where the tutorial instructs to create this file we suggest to name it `admin-service.cds`. See Step 3 in this tutorial part: https://developers.sap.com/tutorials/cp-cap-java-app-studio.html. If you follow that suggestion the using statement is correct.

I couldn't find any place where we suggest to name the file `admin-services.cds`. If you happen to find one, please link it here and I will reopen this issue.

Best regards,
Marc
