### ISSUE TITLE
Create an SAP Cloud Application Programming Model Project for SAP HANA Cloud

### ISSUE THREAD

**Issue by russellw999** [SAPDocuments/Issues#473]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-create-project.html
--------------------------

Write here how you think we can improve the tutorial ...
Hi Thomas,

I think a link to your YouTube SAPDev  video's on Building hana-opensap-cloud would be useful for giving a deeper background on whats going on when you create the project.  By chance i had come across these video's before doing this tutorial.  As i don't have a background with command line npm that showed me a useful list of commands ( which i have saved in a file.  It also let me understand the issues like changing the location of the gen directory, replacing the start command npx , checking the installed versions etc
That gave me a greater understanding of whats  going on when you use the wizard for example.  i can see that will be useful as the BTP environment makes extensive use of terminal commands

Regards
Russell

**Comment by jung-thomas** [comment]
I appreciate the feedback and I'm glad you found the larger video series helpful.  However I hesitate to link it directly inside the body of the tutorial. Many people will see that as a prerequisite to performing the tutorial and that's more content than many people will want to review before attempting a few hours at a tutorial.  The idea is that the tutorials are targeted or small samples of learning content. But one thing we want to build out on https://learning.sap.com/ is a complete learning journeys that combine many different sources and mediums to help people navigate to exactly the right level of content they are looking for. That's where we can hopefully layout larger options like the hands-on dev videos alongside smaller scale tutorials and make it clear which parts to take in what order.
