### ISSUE TITLE
SAP HANA Database Explorer Overview

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Issues#474]
Tutorials: https://developers.sap.com/tutorials/hana-dbx-overview.html
--------------------------

Hi Dan,

can provide more details for this statement? 
`A machine that can run SAP HANA, express edition if the SAP HANA Cloud trial is not used`

Prior versions of explorer, i.e. pre-existing connections can no longer be opened or even displayed, have stopped working for me but it is not quite clear why.

**Comment by danielva** [comment]
Further requirements on running SAP HANA, express edition are provided in step 4 of the tutorial.

There is an option in the settings menu (gear icon top left) of the database explorer, under Database Explorer called Remove all user data.  Pressing that would delete the connections.

If the pre-existing connections stopped being displayed in a production version of the software, I would recommend reporting the issue to support.

Regards,
Dan van Leeuwen
