### ISSUE TITLE
Discover and Import the Live Process Package -- Screenshot needs to be updated

### ISSUE THREAD

**Issue by Vikramkulkarni01** [SAPDocuments/Issues#476]
Tutorials: https://developers.sap.com/tutorials/cp-cf-workflowmanagement-discover.html
--------------------------
Hi, 

Update the screenshot of the tutorial in the following step
Step 1: Configure destination

It still shows SAP Cloud Platform Cockpit. Should be changed to SAP BTP Cockpit.

![image](https://user-images.githubusercontent.com/59861880/124553508-74037400-de52-11eb-9053-3e9c12501953.png)

Regards, 
Vikram Kulkarni

**Comment by Deeksha-R** [comment]
@Vikramkulkarni01 thank you! i have now updated the screenshot. You will be able to view the changes with today's publish.
