### ISSUE TITLE
Add a New Entitlement to Your Subaccount

### ISSUE THREAD

**Issue by slavik-chapelskyi** [SAPDocuments/Issues#484]
Tutorials: https://developers.sap.com/tutorials/cp-cf-entitlements-add.html
--------------------------
Seems like a typo in _**Select** the `tile`_ -> `title`
![image](https://user-images.githubusercontent.com/33541009/124726837-cad28180-df16-11eb-81fd-9e2700907f71.png)

**Comment by IObert** [comment]
Hi,

thanks for providing feedback. Actually, this is not a typo. I meant the tile that *has the title* "Trial"
<https://www.pinterest.com/lbroumand/tile-based-ux-design/>
