### ISSUE TITLE
Alerts in SAP HANA Database and Data Lake

### ISSUE THREAD

**Issue by iwonahahn** [SAPDocuments/Issues#485]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-alerts.html
--------------------------

Write here how you think we can improve the tutorial ...

Hi Dan,

SAP Alert Notification service is only available for Free Tier and not on Trial (for Feature Set B), as you can see [here](https://discovery-center.cloud.sap/servicessearch/alert/?) and below in the screenshot. This should be mentioned in the prereqs of the tutorial.

![2021-07-07_17-55-08](https://user-images.githubusercontent.com/22098308/124792230-1d2e9500-df4d-11eb-8f07-eb867db18532.png)

Thank you and best regards,
Iwona

**Comment by danielva** [comment]
Reached out via email and included a colleague I hope can help further.  I do see the alert service in my trial account and am also using Feature Set B.  
For trial, perhaps the following link might help.
https://discovery-center.cloud.sap/serviceCatalog/sap-alert-notification-service?region=all&tab=service_plan&licenseModel=free
It mentions that regions that it is available for trial.  I hope that explains the problem.  
Please email me if that does not help.

**Comment by iwonahahn** [comment]
Hi Daniel,
Thank you for your reply. As mentioned in my reply to the email I manually need to entitle the service. Maybe a note would be helpful in step 5?
Best regards,
Iwona
