### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by DOCQUIERV5** [SAPDocuments/Issues#487]
Tutorials: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html
--------------------------

Write here how you think we can improve the tutorial ...

The tutorial asks to complete form like this

![image](https://user-images.githubusercontent.com/87133385/124929642-f5990480-e000-11eb-9b03-e28db35d6ea7.png)

And here, in this case, he asks like this (Username and password??? I tried with user S0023309132 and his password but that doesn't work)

![image](https://user-images.githubusercontent.com/87133385/124930564-bb7c3280-e001-11eb-9466-57d83fa57d10.png)

What i have to do? Thanks in advance

Vivian Docquier

**Comment by raz-korn** [comment]
Hi @DOCQUIERV5 ,

Do you have an account on ES5?
The credentials for ES5 should be used in the ES5 destination configuration in SAP BTP.
Please refer to this [issue ](https://github.com/SAPDocuments/Issues/issues/36) for steps to troubleshoot.
Let me know if it worked or additional assistance is needed.

Regards - Raz

**Comment by DOCQUIERV5** [comment]
Hi Raz,

I think well I have an account. Check!


***@***.***D77411.D16DF7B0]
***@***.***D77411.D16DF7B0]




Vivian DOCQUIER

***@***.***D77411.D16DF7B0]
Mechelen | Gent | Lummen | Namen | Windhof(L)
www.ordina.be<https://www.ordina.be/> / E-mail disclaimer<http://www.ordina.be/mailfooter/disclaimer.htm>

**Comment by DOCQUIERV5** [comment]
I think it's all right

Thanks a lot Raz
