### ISSUE TITLE
Help Thomas Get Started with SAP HANA Cloud

### ISSUE THREAD

**Issue by amysy** [SAPDocuments/Issues#488]
Tutorials: https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html
--------------------------

The Image in step 7 shows the db name and other artifacts. My screen is different DB name is not shown directly goes to shared key hdi. 
![HelpTPJ-issue](https://user-images.githubusercontent.com/13893456/125036992-40df0180-e059-11eb-8fba-f9de04c146c6.PNG)

**Comment by amysy** [comment]
Step 9- in sub-step 2: create file DEVS.hdtable deployment doesn't work.  It errs out with the message as shared in the image attached below. I'd like to complete this step before moving to the rest of the tutorial.
![HelpTPJ-issue2](https://user-images.githubusercontent.com/13893456/125042710-c6fe4680-e05f-11eb-8cc9-885bc8c638da.png)

**Comment by amysy** [comment]
This issue is not closed, Kindly help me resolve to work on this tutorial.

**Comment by jung-thomas** [comment]
That step is telling you to create a file named DEVS.hdbtable. 
![image](https://user-images.githubusercontent.com/12159356/125073254-acd95e00-e089-11eb-9976-5287fc56dd98.png)

You created a file named DEVS.hdtable. hdtable is not a valid file extension and therefore the deploy step doens't know what to compile it into.  

To your earlier question
>The Image in step 7 

It's perfectly normal that you might see multiple connections or containers in the Database Explorer. Those could be from other tutorials or other work you've done.  But the image matches the selected container which should be opened automatically when navigating via the open container button in the SAP HANA Projects view in the Business Application Studio.
