### ISSUE TITLE
Customize the Overview View Controller to Display Customers and Products

### ISSUE THREAD

**Issue by Schokolado** [SAPDocuments/Issues#489]
Tutorials: https://developers.sap.com/tutorials/fiori-ios-scpms-teched19-03.html
--------------------------

Write here how you think we can improve the tutorial ...

Update The Turorial according to the newest Version, where no Proxy classes and Model will be created. 
All i see iss ESPMContainer.

**Comment by KevinMuessig** [comment]
Hi @Schokolado ,

I will work on updating the tutorials to the newest version!

Thanks for letting me know.

Best Kevin
