### ISSUE TITLE
Name of the entitlements in prerequisite should be changed

### ISSUE THREAD

**Issue by PriyankaRShivakumar** [SAPDocuments/Issues#490]
**Tutorials:** https://developers.sap.com/tutorials/appstudio-fioriapps-mta-build-deploy.html
--------------------------
**Step: Prerequisite**

**Issue:**
Application Runtime is now called Cloud Foundry Runtime. This should be changed.

Best Regards,
Priyanka

**Comment by raz-korn** [comment]
Thanks, @PriyankaRShivakumar .
Updated and pushed to production.

Regards - Raz
