### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by PriyankaRShivakumar** [SAPDocuments/Issues#491]
Tutorials: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html
--------------------------
**Step 3: Generate an app based on SAPUI5 Application template**

**Issue:**
The data source and Screenshot should be changed. The data source **Connect to an SAP system** is now **Connect to a system** as below.
![image](https://user-images.githubusercontent.com/17827092/125060984-81c32e80-e0ca-11eb-8033-87a1f94583a1.png)

Best Regards,
Priyanka

**Comment by raz-korn** [comment]
Thanks, @PriyankaRShivakumar .
Updated and pushed to production.

Regards - Raz
