### ISSUE TITLE
Perform Actions On Cards To Support Your Business Case

### ISSUE THREAD

**Issue by VanitaDhanagar** [SAPDocuments/Issues#492]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-cards-booster-starter.html
--------------------------

in step 3.8 : Tap on Call, SMS, **Open Maps** and Email action to perform the corresponding action.

Open map option is not available 
![Screenshot_2021-07-08-15-38-32-073_com sap content2go](https://user-images.githubusercontent.com/80330660/125149219-4883d080-e155-11eb-9562-0b1a66843307.jpg)

Lable to add : 
prio: High-prio
Sprint Label: SCPTest-2107A
Scenario Label: SCPTest-mcard
Landscape Labels: trial2 [US]

Thanks and Regards,
Vanita

**Comment by sandeep-tds** [comment]
Hi Vanita, 

I tested the behaviour on my device and can confirm that the Open Maps option appears on both iOS & Android. 
I will reach out to you internally to see the issue on your device. 

![Droid](https://user-images.githubusercontent.com/43441840/125679230-2ed6cdb3-c2fd-4c96-b586-926dc9bc4425.jpeg)

![iOS](https://user-images.githubusercontent.com/43441840/125679320-02ac7c2f-f98c-40a2-9b28-91a997780320.jpeg)

**Comment by VanitaDhanagar** [comment]
Hi Sandeep ,

This issue is exist in US region ,Please check in that region as mentioned in label .

Thanks and Regards,
Vanita

**Comment by sandeep-tds** [comment]
Hi @VanitaDhanagar, I've completed the test and can confirm that the options are available even in the US region.

**Comment by VanitaDhanagar** [comment]
Hi @sandeep-tds   ,In our current validation(CW32) issue is not persist .

Thanks and Regards,
Vanita

**Comment by sandeep-tds** [comment]
Thank you for confirming the same Vanita. I am closing the issue.
