### ISSUE TITLE
Create an SAP Fiori Elements-Based UI

### ISSUE THREAD

**Issue by sqjlin** [SAPDocuments/Issues#494]
Tutorials: https://developers.sap.com/tutorials/btp-app-create-ui-fiori-elements.html
--------------------------

Step 2, isn't these Fiori Elements (e.g. List Report Object Page) available in @sap/generator-fiori instead of @sapui5/sapui5-templates

**Comment by iwonahahn** [comment]
Hi @sqjlin,

Thank you for reporting it. We need to reproduce this issue with the latest release and will get back to you asap.

Best regards,
Iwona

**Comment by iwonahahn** [comment]
Hi @sqjlin,

The_List Report Object Page_ is one of four floorplans as shown in the screenshot [here](https://developers.sap.com/tutorials/btp-app-create-ui-fiori-elements.html#1ac967fe-87cd-4a6b-9483-0dac7b344787) when using the template wizzard provided by the package `@sap/generator-fiori`.  

`@sapui5/sapui5-templates` will be used later in the tutorial [Create a UI Using Freestyle SAPUI5](https://developers.sap.com/tutorials/btp-app-create-ui-freestyle-sapui5.html).

What is your concrete question or issue here?

Best regards,
Iwona

**Comment by iwonahahn** [comment]
Hi @sqjlin,

We haven't heard from you in a while, so we are closing the issue. If you still have questions, feel free to open a new issue.

Best regards,
Iwona
