### ISSUE TITLE
Set Up Workflow Management in Cloud Cockpit

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Issues#495]
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-1-setup.html
--------------------------

Step1 : If user has two subaccounts in trial landscape then after selecting the workflow Booster, the below popup comes, where one has to select the subaccount in which the required entitlements for the Booster have been added.
![image](https://user-images.githubusercontent.com/50734023/125245465-39944e00-e30e-11eb-9364-13a2edcac7f5.png)

A note can be added for the above case. With one subaccount the flow works as mentioned.

**Comment by ArchanaShukla** [comment]
this is fixed now
