### ISSUE TITLE
Develop and Run SAP Fiori Application With SAP Business Application Studio

### ISSUE THREAD

**Issue by sebasgoldberg** [SAPDocuments/Issues#499]
Tutorials: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html
--------------------------

Hi, after successfully deploying the UI App to the ABAP Cloud Environment I am trying to access to the App using the URL displayed in the console's deploy log, but I am getting the following:

![image](https://user-images.githubusercontent.com/1379852/125628326-1528ff7b-e8e2-403d-be5d-bade3e68e95e.png)

What is the problem?

Thanks in advance.

**Comment by mervey45** [comment]
Hi @sebasgoldberg ,

have you created the IAM app and business catalog (step 7 + 8)? If not, please do so. If yes, please contact me again.

Best regards, 
Merve

**Comment by sebasgoldberg** [comment]
Hi @mervey45,

Yes, I have created.

Now it is working, but initially the response was the mentioned 403 Forbidden.

Additionally I have tried to add the App to the BTP Lauchpad service, but I am getting the same error when trying to access to the App from Launchpad:

![image](https://user-images.githubusercontent.com/1379852/125814581-20ce979c-4af8-4ac4-a27f-77dbfb687eec.png)

![image](https://user-images.githubusercontent.com/1379852/125814781-5a539689-6009-4cd5-b2e2-739492688da3.png)

![image](https://user-images.githubusercontent.com/1379852/125814958-0698d777-3233-422a-9ce4-e6d022150d6a.png)

The URL that is failing is the following:

https://5422bbff-4781-4b19-8ca9-5f7ac9d4a30b.abap.eu10.hana.ondemand.com/cp.portal/ui5appruntime.html?sap-ui-app-id=zrapfiori12345.Component&sap-startup-params=&sap-shell=FLP&sap-touch=0&sap-ui-versionedLibCss=true&sap-plugins=RTAPluginAgent&sap-theme=sap_fiori_3&sap-locale=en&sap-iframe-hint=UI5

Thanks in advance.

**Comment by sebasgoldberg** [comment]
Hi @mervey45,

Do you have any update regarding running SAP Fiori Application in SAP BTP ABAP Environment and publishing it in a BTP Fiori Launchpad Service? 

Thanks in advance.

**Comment by mervey45** [comment]
Hi @sebasgoldberg ,

did you try to do following [tutorial](https://developers.sap.com/tutorials/abap-environment-abap-flp.html) in the trial system? If yes, then this won't work. Because this is currently only available for licensed systems.

If you still have any issues, feel free to contact me again. 

Best regards, 
Merve

**Comment by sebasgoldberg** [comment]
Hi @mervey45,

The problem is that the trial system does not have the apps needed to do the suggested tutorial.

![image](https://user-images.githubusercontent.com/1379852/126165258-3559b0bb-ab64-44a6-9b46-2f27e26ee571.png)

1) How can I complete the suggested tutorial in the trial system?

2) Additionally, Should not be possible to consume from BTP Fiori Launchpad Service a SAP Fiori Application in SAP BTP ABAP Environment?

Thanks in advance.

**Comment by mervey45** [comment]
Hi @sebasgoldberg ,

the tutorial I suggested (https://developers.sap.com/tutorials/abap-environment-abap-flp.html) is only doable in a licensed system. This functionality is not provided in the trial system. The ABAP trial systems are limited in their functionality. In the trial systems, you can only open your Fiori Launchpad app via the deployment link, like in tutorial: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html#737e8114-d7a0-4988-aa32-00118df5bf73 mentioned (step: 9.3- 9.6).


Best regards, 
Merve

**Comment by sebasgoldberg** [comment]
OK, no problem @mervey45.

And what about consuming it from BTP Fiori Launchpad Service?

Is it possible?

Thanks in advance.

**Comment by mervey45** [comment]
Hi @sebasgoldberg ,

it is not possible.

Best regards, 
Merve
