### ISSUE TITLE
Installing SAP HANA, express edition with Docker

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Issues#500]
Tutorials: https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html
--------------------------

Your prerequisites page lists Debian 9 Community option as tested, but when trying to obtain Docker image for that linux distribution 9 is not available any longer but only 10 and 11 are. 

Can you please either update this dependency or remove it from the this list in your tutorial?

Thank you,
greg

**Comment by JCurrie27** [comment]
Thanks greg2git - I'm confirming latest Debian support with our team and will update this tutorial accordingly.
