### ISSUE TITLE
Start Your MDK Application in the Editor: Error "Cannot find module encoding" while executing "3. Select MDK Project and click Start."

### ISSUE THREAD

**Issue by pekiti** [SAPDocuments/Issues#502]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-dev-kit-offline-app.html
--------------------------

Error "Cannot find module encoding' while executing "3. Select MDK Project and click Start."

`{"message":"@ext-mdkvsc-npm-rel/mdk:app generator failed - runGenerator() Cannot find module 'encoding'\nRequire stack:\n- /extbin/npm/globals/lib/node_modules/node-fetch/lib/body.js\n- /extbin/npm/globals/lib/node_modules/node-fetch/index.js\n- /extbin/npm/globals/lib/node_modules/@ext-mdkvsc-npm-rel/generator-mdk/generators/app/odata.js\n- /extbin/npm/globals/lib/node_modules/@ext-mdkvsc-npm-rel/generator-mdk/generators/app/Prompts.js\n- /extbin/npm/globals/lib/node_modules/@ext-mdkvsc-npm-rel/generator-mdk/generators/app/index.js\n- /tmp/vscode-unpacked/yeoman-ui-1.4.5.vsix/extension/dist/extension.js\n- /theia/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host-rpc.js\n- /theia/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host.js","stack":"Error: runGenerator() Cannot find module 'encoding'\nRequire stack:\n- /extbin/npm/globals/lib/node_modules/node-fetch/lib/body.js\n- /extbin/npm/globals/lib/node_modules/node-fetch/index.js\n- /extbin/npm/globals/lib/node_modules/@ext-mdkvsc-npm-rel/generator-mdk/generators/app/odata.js\n- /extbin/npm/globals/lib/node_modules/@ext-mdkvsc-npm-rel/generator-mdk/generators/app/Prompts.js\n- /extbin/npm/globals/lib/node_modules/@ext-mdkvsc-npm-rel/generator-mdk/generators/app/index.js\n- /tmp/vscode-unpacked/yeoman-ui-1.4.5.vsix/extension/dist/extension.js\n- /theia/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host-rpc.js\n- /theia/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host.js\n at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)\n at Function.Module._load (internal/modules/cjs/loader.js:667:27)\n at Function.module._load (/theia/packages/theia-wing-plugin-ext/lib/plugin/node/wing-api-node-provider.js:27:33)\n at Function.module._load (/theia/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js:67:33)\n at Module.require (internal/modules/cjs/loader.js:887:19)\n at require (internal/modules/cjs/helpers.js:74:18)\n at Object.<anonymous> (/extbin/npm/globals/lib/node_modules/node-fetch/lib/body.js:8:15)\n at Module._compile (internal/modules/cjs/loader.js:999:30)\n at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n at Module.load (internal/modules/cjs/loader.js:863:32)"}`

**Comment by jitendrakansal** [comment]
@pekiti  are you experiencing this issue in your trial or productive account?

**Comment by pekiti** [comment]
@jitendrakansal It's happening in my trail environment

**Comment by jitendrakansal** [comment]
@pekiti okay, thanks for the info.
I am currently checking it with our dev experts, will get back to you.

**Comment by jitendrakansal** [comment]
@pekiti we couldn't reproduce this issue in trial account.
Could you try creating a new dev space (SAP Mobile Applications) and then see if you are able a MDK project successfully?

**Comment by pekiti** [comment]
HI, you can close the ticket.
During my 2nd attempt I run into a new issue as the generator didn't offer me "Mobile Services" as ODataSource.
So, either the generator (BAT) has some "hick-ups" or the problem is sitting in front of the screen ;-)

**Comment by jitendrakansal** [comment]
@pekiti regarding that you don't see "mobile services" option in the OData Source could be your CF token is no longer active Or has been expired.
please try this 

navigating to View menu > Find Command> CF: Login to Cloud foundry to initiate a valid session and click Start Over.
