### ISSUE TITLE
Create a CAP-Based Application

### ISSUE THREAD

**Issue by vishalkr31** [SAPDocuments/Issues#504]
Tutorials: https://developers.sap.com/tutorials/btp-app-create-cap-application.html
--------------------------

Write here how you think we can improve the tutorial ...

while copying the excel to our project ( cpapp) we first need to create folder data in the db folder

**Comment by iwonahahn** [comment]
Hi @vishalkr31,

There is no need to create a `data` folder, cause as mentioned in step 2.7. you should copy this folder from the templates:

![2021-07-16_15-23-16](https://user-images.githubusercontent.com/22098308/125955133-98ae2af7-a03c-43e5-9434-a2eb1fb730d9.png)

Best regards,
Iwona
