### ISSUE TITLE
Configure Business Rules, Workflow and Process Visibility

### ISSUE THREAD

**Issue by 18251926152** [SAPDocuments/Issues#505]
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-configure.html
--------------------------

Write here how you think we can improve the tutorial ...

I am a beginner, when I try to finish the 2nd tutorial in Mission Beginer 'Automate and Extend Employee Onboarding',  the STEP 6 did no t work whether i tried many times with different PC. 
I have to say it is so frustrating.  I do every details precisely according to the tutorial.
But in the first picture following, the note above the picture help me nothing.
All l got when i tried to deploy the .mtar is the 2nd picture following.
I just want to finish the tutorial, but i am stuck here.
Looking forward to your reply and help me to finish it.
Pls contect me 'shengjun.dong@mt.com'
<img width="662" alt="捕获" src="https://user-images.githubusercontent.com/52917863/126061051-c5fdcd56-6639-4e51-8af7-ce968edbe83c.PNG">

![捕获2](https://user-images.githubusercontent.com/52917863/126061275-e6f76356-9fa4-4b1a-bd61-bca8d9928ce4.PNG)

**Comment by ArchanaShukla** [comment]
You have to login to CF in the Business Application Studio to be ale to deploy successfully as mentioned in the note. There are many ways to connect to CF. You can use CF command line in studio or click function F1 and in wizard that opens, type login and follow the wizard

![image](https://user-images.githubusercontent.com/34297037/126345419-651e8e5e-cfa3-488c-b68c-9ef85428a091.png)
