### ISSUE TITLE
 Create a Simple IoT Device Model

### ISSUE THREAD

**Issue by german-mesa** [SAPDocuments/Issues#506]
Tutorials: https://developers.sap.com/tutorials/iot-express-2-create-device-model.html
--------------------------

Write here how you think we can improve the tutorial ...

Hi there,

This link in prerequisites points nowhere:
"3. To be able to see the data created in this tutorial in SAP IoT, it is necessary to follow this guide for configuring the message processing of SAP Internet of Things."

Best,
German

**Comment by marcuscbehrens** [comment]
We will soon retire this tutorial. if you have a new subscription to SAP IoT with the "oneproduct" service plan then this does not apply to you anyway anymore.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
