### ISSUE TITLE
Set Up the SAP Launchpad Service

### ISSUE THREAD

**Issue by AisonBird** [SAPDocuments/Issues#507]
Tutorials: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html
--------------------------

Got nothing when search launchpad in the marketplace.
should add launchpad service to entitlements first.

**Comment by LindsayBert** [comment]
Hi - if you are not using a trial account, you need to set up your subaccount including entitlements. There is a link in the tutorial to a tutorial that will help you with this: https://help.sap.com/viewer/8c8e1958338140699bd4811b37b82ece/Cloud/en-US/fd79b232967545569d1ae4d8f691016b.html 

Thanks
Lindsay

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
