### ISSUE TITLE
Continue Your OData Exploration with EPM

### ISSUE THREAD

**Issue by FinkRiedelE** [SAPDocuments/Issues#509]
Tutorials: https://developers.sap.com/de/tutorials/odata-02-exploration-epm.html
--------------------------

Write here how you think we can improve the tutorial ...
Step4 needs to be updated

**Comment by qmacro** [comment]
Hi @FinkRiedelE - can you please expand on how you think the step should be updated? Thanks.

**Comment by becrazy76** [comment]
Explanation can be found here: https://github.com/SAPDocuments/Issues/issues/527

**Comment by qmacro** [comment]
Ah, so this is likely the same issue - thank you @becrazy76 :-) @FinkRiedelE I'll assume you were referring to the rogue data that suddenly appeared in the OData service. It's back to normal now. Cheers!
