### ISSUE TITLE
 Create Instance of SAP Event Mesh

### ISSUE THREAD

**Issue by condamoor-sap** [SAPDocuments/Issues#511]
Tutorials: https://developers.sap.com/tutorials/cp-enterprisemessaging-instance-create.html
--------------------------

I think the way you create an Instance has changed.  Your tutorial shows creating the EM instance under a Space, but it now is available as a Subscription under the Subaccount.. and you go directly to the Instance after you subscribe. see attached screenshot.
Can you confirm and update the Tutorial appropriately.

[EM.docx](https://github.com/SAPDocuments/Issues/files/6871570/EM.docx)

**Comment by condamoor-sap** [comment]
Ignore the above issue. My bad!
I got it all working.

Thanks
-ravi

**Comment by pradeeppanda-sap** [comment]
Hi Ravi,
 You got it working is a good thing.
 However we need to accommodate those changes which you have mentioned.
 
Let this issue be open. I will change and close it.

regards
Pradeep

**Comment by pradeeppanda-sap** [comment]
Hi Ravi,
 The management dashboard application related information on how to use it (yes, at sub account level) has been provided in [Create Queues and Queue Subscriptions for SAP Event Mesh](https://developers.sap.com/tutorials/cp-enterprisemessaging-queue-queuesubscription.html).
And the instance creation process of event mesh instance, as mentioned today, needs to be changed to accommodate new steps. I have updated it. It should be reflected in a day or two.

Thanks again for bringing up the points.

regards
Pradeep

**Comment by condamoor-sap** [comment]
Hi Pradeep,
I figured that out after I opened the issue…That’s why I closed it as ‘my bad’.
Referring to both the Service and the Management dashboard app as just Event Mesh is definitely confusing. Fixing the naming will help.

Do you have any documentation or tutorial or blog on how to connect S4 On Prem (not S4 Cloud) to Event mesh? Most of what I see are around S4 Cloud.

Thanks
-ravi

**Comment by pradeeppanda-sap** [comment]
https://community.sap.com/topics/event-mesh

This is one shop stop for Event Mesh related information.
You will get information on onPremise also.

Should you intend to have some more information, please send me a mail in pradeep.panda@sap.com
