### ISSUE TITLE
Extend the Bookstore with Custom Code

### ISSUE THREAD

**Issue by krishmabhatia** [SAPDocuments/Issues#512]
Tutorials: https://developers.sap.com/tutorials/cp-cap-java-custom-logic.html
--------------------------
I am currently on step number 3, Test handler where when I executed sub-step no 7 "Create a new order item:" using post, stocks didn't get deducted by 2.Can you pls help me? Let me know in case anything else is needed.Attaching screenshots of post command and output for reference.
<img width="1791" alt="BAS Java Post command" src="https://user-images.githubusercontent.com/49376048/126919213-514b876f-e11c-4bf1-9f83-209e69b6ded0.png">
<img width="1796" alt="output" src="https://user-images.githubusercontent.com/49376048/126919224-0fb09f3d-176e-4c3f-8f52-47c2352270f4.png">

Regards,
Krishma

**Comment by krishmabhatia** [comment]
Adding orderItems created screenshot also.
<img width="1791" alt="order items created" src="https://user-images.githubusercontent.com/49376048/126920457-5562fcbf-3b9f-4941-9cae-7fabbf328862.png">


Regards,
Krishma

**Comment by krishmabhatia** [comment]
Adding Order and OrderItems screenshot as well.
<img width="1791" alt="order final" src="https://user-images.githubusercontent.com/49376048/126922185-f3093e60-2b06-494b-a112-220c885e3928.png">
<img width="1787" alt="order items screenshot final" src="https://user-images.githubusercontent.com/49376048/126922205-0d63c100-e9ff-4ded-9fe9-0830fe692ae5.png">

**Comment by iwonahahn** [comment]
@beckermarc can you please have a look here?

**Comment by beckermarc** [comment]
Hi @krishmabhatia 

did you make sure to restart the application after adding the code?
Can you please provide the startup output of the application after starting it through the run configuration?

Best regards,
Marc Becker

**Comment by krishmabhatia** [comment]
Hi @beckermarc ,

Yes, I did that and even today again I tested by creating new order ending with 08 but still stock is not getting reduced by 2.
PFA startup output of the application after starting it through the run configuration.

Let me know in case you need anything else. Also, I am not sure but I am not getting any notification or mail of the replies sent by you and your team even though my notification for this thread is subscribed, pls let me know in case I need to enable anything else also to get a notification for replies sent by you for this thread.

Thanks in advance!!

Regards,
Krishma

<img width="1682" alt="debug output" src="https://user-images.githubusercontent.com/49376048/127843830-3757d946-67f3-4a77-8031-e080f60ae099.png">
<img width="1784" alt="task output" src="https://user-images.githubusercontent.com/49376048/127843887-cdd81d23-1b39-46a3-9544-f76e85ff4c16.png">

**Comment by beckermarc** [comment]
Sorry for the late reply. Can you please attach the full startup output as a text file, not as a screenshot. The relevant parts that I wanted to check are unfortunately not visible in the screenshot you attached here.

Regarding notifications: This depends on your GitHub notification settings I guess, which you can customize in the account settings of GitHub.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
