### ISSUE TITLE
 Send and Receive Test SAP Event Mesh

### ISSUE THREAD

**Issue by condamoor-sap** [SAPDocuments/Issues#514]
Tutorials: https://developers.sap.com/tutorials/cp-enterprisemessaging-test-queue-sendreceive.html
--------------------------

In constructing the URL to get the access token, you had suggested to use
https://<***space name***>.authentication.sap.hana.ondemand.com/oauth/token
?grant_type=client_credentials&response_type=token

This is incorrect. The <**space name***> should be the Global account name not Space name and the rest of the URL is determined by the Hypercaler used.

A better way is to look at the value for "tokenendpoint" in the service key file as in...
  "tokenendpoint": "https://gcoe.authentication.us10.hana.ondemand.com/oauth/token"

and use it as the URL for getting the Access token.

**Comment by pradeeppanda-sap** [comment]
1. <space name> indeed is a mistake. 
2.  getting the token endpoint from the service key is definitely a better approach.

Thanks a lot for helping me correcting the mistake. 
Have updated. Should be merged and released today.


regards
Pradeep
