### ISSUE TITLE
Get Started with the SAP BTP Command Line Interface (btp CLI)

### ISSUE THREAD

**Issue by renejeglinsky** [SAPDocuments/Issues#517]
Tutorials: https://developers.sap.com/tutorials/cp-sapcp-getstarted.html
--------------------------

I think in Step 4 it would be helpful to mention how to extract the tarball that is provided on the tools page. At least for windows users, this is probably not the most common archive to interact with. Windows natively supports to extract tarball as follows (in my case):

```
tar -xvzf btp-cli-windows-amd64-2.6.2.tar.gz
```
This command extracted the archive in a _windows-amd64_ folder that then contained the _btp.exe_ file.

Regards,
René

**Comment by annawenger20** [comment]
Hi @renejeglinsky - thanks for the feedback. Please have a look at https://developers-qa.sap.com/tutorials/cp-sapcp-getstarted.html (update should be available in a few minutes) and let me know if my addition helps. 
Best regards, Anna

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
