### ISSUE TITLE
Set Up Trust Between Identity Authentication and SAP Cloud Platform

### ISSUE THREAD

**Issue by MichaelPShea** [SAPDocuments/Issues#518]
Tutorials: https://developers.sap.com/tutorials/abap-custom-ui-trust-settings.html
--------------------------

The tutorial uses the old product name for SAP Cloud Platform (now SAP BTP) and SAP Cloud Platform Identity Authentication (now SAP Cloud Identity Services -- Identity Authentication).

**Comment by Liebherr** [comment]
Sorry for not caring so far, will do so asap.
Regards
Ulrike

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
