### ISSUE TITLE
Create Calculation View and Expose via CAP (SAP HANA Cloud)

### ISSUE THREAD

**Issue by ttulja** [SAPDocuments/Issues#519]
Hi ,

I have created the calculation with the same process as mentioned in the blog.

Below are the steps created for Calculation View.

    Calculation view products is created in db->src - deployment successful
    i have generated the entity for Calculation View using hana-cli inspectView -v products -o cds
    Service has been created in SRV folder

But while exposing as a cap service it is throwing below
Error: The file requires "db://PRODUCTS" which is not provided by any file [8212001]
Could you please help what am i missing in this process

Thanks,
Thulja

**Comment by jung-thomas** [comment]
Could you perhaps share some screenshots of your project and content.  Most likely culprit is some misspelling, but we can't help you diagnose that if we can't see the content in your project.  Also do you get this error when you do the deploy to HANA or when you do the cds run?

**Comment by ttulja** [comment]
Thanks for the response.
Below are few screenshot of project content
•	Products.hbdcalculationview is the view created and in container I can see products in “Columns Views” with data
 
![image](https://user-images.githubusercontent.com/49712221/127655941-9a2bc48b-ef83-4e6d-9d3b-1aadd3e0d4bd.png)

•	In db folder->schema.cds
 
![image](https://user-images.githubusercontent.com/49712221/127655812-79fa1b22-7a38-49ae-bf33-3a0f0171629e.png)

•	in srv->schema_srv.cds
![image](https://user-images.githubusercontent.com/49712221/127655763-5d0bd4bf-a160-4f29-b3bd-34eea88ae65b.png)

 
•	While deploying facing the below error
 
![image](https://user-images.githubusercontent.com/49712221/127655708-37ae09af-b3c8-4f37-8301-57903d0c0e84.png)


Regards,
Thulja

**Comment by jung-thomas** [comment]
So what tutorial is this?  I don't see entity names I recognize.  But it appears your problem is case sensitivity.  CAP Is case insensitive, but HANA artifacts are not.  You created you calculation view in lower case. Therefore the CAP Proxy entity can't see it. Either change the name of the calculation view to be all upper case or you will need to put a synonym on top of it.  You will have the same issue with the columns in the Calculation view. Either make them all upper case or you will need to define a SQL View in CAP with alias names (all upper case) for each column.

**Comment by ttulja** [comment]
Thanks for the inputs , it worked.

Regards,
Thulja

**Comment by ttulja** [comment]
Hi Thomas,

Thanks for the help on Calculation views and I am facing one more issue in deployment need your help on this.
1. While deploying "Deploy MTA Archive" it shows Some instances have crashed.
![image](https://user-images.githubusercontent.com/49712221/128071566-45b54895-8ecd-4276-8351-d41a69bff1df.png)

2. I checked in logs in DEV space.
![image](https://user-images.githubusercontent.com/49712221/128071741-1b973dcc-3d2f-4db1-971e-6786bdce8c84.png)

3. To resolve this , i have executed "npm init"  to regenerate package.json and "npm install socket.io --save"
4. But even after this i am facing the same.

Could you please help in finding this issue or assign to some one, who can help me in this.
Sorry to ping you again

Thanks,
Thulja

**Comment by jung-thomas** [comment]
This is not the correct forum to request general support or ask questions which aren't directly related to content in a tutorial. Consider using the SAP Community Q&A to ask questions of your fellow community members.
