### ISSUE TITLE
Develop a Business App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by mion-snl** [SAPDocuments/Issues#520]
Tutorials: https://developers.sap.com/tutorials/appstudio-cap-app.html
--------------------------

**Step 3: Define bookshop service**

There seems to be a typographical error in the CDS code that the developer is supposed to copy which causes the following error during runtime:

> Artifact “CatalogService.Books.ID” has not been found (in action:“CatalogService.submitOrder”/param:“book”)

Basically this line:
`    action submitOrder (book : Books.ID, amount: Integer);`

The reference to the Book ID should be Books:**I**D not Books**.**ID.

Or... just leave it in for debugging practice.

**Comment by Paolaufer** [comment]
HI!

Thank you for bringing this to our attention!! I've fixed it and will republish soon.
