### ISSUE TITLE
Build Your First FAQ Chatbot

### ISSUE THREAD

**Issue by klickerlebnis** [SAPDocuments/Issues#522]
Tutorials: https://developers.sap.com/tutorials/conversational-ai-faq-chatbot-beginner.html
--------------------------

The question in step 7 is not up to date anymore. 

What is the question that has 51% confidence? instead of What is the question that has 37% confidence?
Answer: What is a trigger?

You could also update this sentense:
For the first question, the bot was 99% sure, so it showed this as the question the user was asking. The second question had 82% confidence, the next 74% and the next 73%.

Best regards, Dominik

**Comment by thecodester** [comment]
I have updated the question for this tutorial. Sorry for the problems, and thanks for pointing out.
