### ISSUE TITLE
Create an ABAP Core Data Services (CDS) View in SAP Cloud Platform, ABAP Environment

### ISSUE THREAD

**Issue by tbh0502** [SAPDocuments/Issues#523]
Tutorials: https://developers.sap.com/tutorials/abap-environment-create-cds-mde.html
--------------------------

Write here how you think we can improve the tutorial ...
In Step 6: Create service binding, the Binding Type = ODATA V2 (UI…) is suggested.
But the UI annotation didn't work when the bingding type is OData V2 UI in preview.
However, the UI annotation can work when he bingding type is OData V4 UI in preview.
Is there any mistake/typo about the binding type?

**Comment by julieplummer20** [comment]
Hi,
I've just tested this. Which annotation are you referring to?
For me, they are all working - using OData V2 UI.
I apologize for the delay. If you could just clarify this, I will investigate further.
Thanks and best wishes,
Julie.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
