### ISSUE TITLE
Explore Visualization Options for Spatial Data in SAP HANA Cloud

### ISSUE THREAD

**Issue by russellw999** [SAPDocuments/Issues#524]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-smart-multi-model-1.html
--------------------------

Write here how you think we can improve the tutorial ...

Step 2 :
      Point 4:   Create a user and Assign the privileges ...... if you have forgotten how to create a
                       user you can read more here ?????
                       < There is no link to show where you create the user >
                       
                       Having looked at the sample Github teched202-DAT260 data repository i came across the 
                       Getting started instructions and there it is clear where you create the user.
                       
                       It would be a good idea to make thins clear in the tutorial by including the like to the instruction
                       
     Regards
     Russell

**Comment by VijayKrishnanSR** [comment]
Hi Russell,
Thank you for pointing it out for us. We had initially planned to use another link for these instructions, but that content is in the process of being migrated into a tutorial. For the time being, we will update using the link to GitHub sample data- getting started instructions (as you have mentioned). We will get back to you once we have added the links.
Let us know if you have any other questions.

Regards,
Vijay

**Comment by VijayKrishnanSR** [comment]
The updates have been published. Thank you once again.
