### ISSUE TITLE
Connect Using the SAP HANA Go Interface

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Issues#525]
Tutorials: https://developers.sap.com/tutorials/hana-clients-golang.html
--------------------------

Hi Dan,

any plans to provide instructions on how to install Hana client for Go? (cp -r ~/sap/hdbclient/golang/src/SAP $HOME/go/src/) your code assumes the client is already installed in linux but the https://tools.hana.ondemand.com/#hanatools don't have Go-specific installation instructions. 
otherwise, someone may hesitate to continue with the tutorial as they had not yet installed  https://tools.hana.ondemand.com/additional/hanaclient-2.9.23-linux-x64.tar.gz since they didn't know what the expected results would be in the Go environment on linux and not on Windows.

Thank you,
greg

**Comment by danielva** [comment]
The assumption is that the user has installed the HANA Client and there is a pre-requisite to have completed the first three tutorials in the mission (the second tutorial covers the installation).  I did try it today and the steps are pretty much the same.  I did notice that for GO 1.16 you need to set an additional environment variable.
export GO111MODULE=auto.
I will update the tutorial to mention this.

Thanks for the feedback,
Dan
