### ISSUE TITLE
Continue Your OData Exploration with EPM

### ISSUE THREAD

**Issue by becrazy76** [SAPDocuments/Issues#527]
Tutorials: https://developers.sap.com/tutorials/odata-02-exploration-epm.html
--------------------------
**Which of these are sub categories for the Computer Systems main category?**
Computer systems seems not to be present any longer. Not able to answer this question. Will try out which one it was. ;)

**Comment by qmacro** [comment]
There have been some low-level db issues with the EPM OData service used in this tutorial, which have been fixed today. But the data is rather different, isn't it? I wasn't expecting that :-) I'll contact support to look into where these data changes are coming from. Thanks for bringing this to my attention!

**Comment by becrazy76** [comment]
Checked this morning and it is back :)
![image](https://user-images.githubusercontent.com/8298499/128133543-8a99c380-fe72-4677-b876-5f9281259f15.png)

**Comment by qmacro** [comment]
Nice one @becrazy76 - thanks for following up. We're still investigating what happened here, but I'm glad the data is back to what it should be for now. Happy learning!
