### ISSUE TITLE
 Call a Remote Function Module From SAP Business Technology Platform (BTP), ABAP Environment

### ISSUE THREAD

**Issue by Vrum89** [SAPDocuments/Issues#528]
Tutorials: https://developers.sap.com/tutorials/abap-env-rfc.html
--------------------------

You should change the initial password. It's 'manage' not 'Manage'
I found the solution on [https://help.sap.com/viewer/cca91383641e40ffbe03bdc78f00f681/Cloud/en-US/db9170a7d97610148537d5a84bf79ba2.html](url)

Thanks for your guide.
It is essentials for upgrading my career to do not a "Simply" Abapers :)

**Comment by julieplummer20** [comment]
Hi Vrum89,
You are right. I apologize. I will fix this at once.
Thank you for your general feedback!
BR Julie.

**Comment by julieplummer20** [comment]
Hi Vrum, 
The change is now visible in the tutorial.
Thanks for the heads-up.
I will close this now. If you have any more feedback, please let me know.
BR Julie.
