### ISSUE TITLE
Configure Business Rules, Workflow and Process Visibility

### ISSUE THREAD

**Issue by Fomka** [SAPDocuments/Issues#529]
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-configure.html
--------------------------

There is a mismatch between the tutorial and actual data. The tutorial says "Click Connectivity | Destinations from the left-hand navigation and search for the destination with name BUSINESSRULES_APIHUB" and shows a screenshot where BUSINESSRULES_APIHUB destination has authentication property set to "BasicAuthentication". In fact that BUSINESSRULES_APIHUB has authentication property set by default to "NoAuthentication", see the attached image.

![BUSINESSRULES_APIHUB error 1](https://user-images.githubusercontent.com/278683/128173778-ab0019ed-fdf3-497b-bb99-80849d032701.PNG)

**Comment by ArchanaShukla** [comment]
Hello Fomka, 
I tried in multiple accounts in trial and for all accounts in AWS and Azure, its showing correctly. Can you delete this destination run the Booster again, and let me know if you still see this issue. Also let me know which trial data center you are logged in?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
