### ISSUE TITLE
Get Started with the SAP BTP Command Line Interface (btp CLI)

### ISSUE THREAD

**Issue by zjhua2002** [SAPDocuments/Issues#531]
Tutorials: https://developers.sap.com/tutorials/cp-sapcp-getstarted.html
--------------------------

About step: "Step 11: Enable command autocompletion", there is a typo about this command line.

From BTP Help (CLI: btp --help), the correct one would be:
btp enable autocomplete SHELL

**Comment by annawenger20** [comment]
done. sorry for the delay, my process of forwarding issues to a substitute during my long absence did not work. 
Sincere apologies for that!
