### ISSUE TITLE
Add the SAP Launchpad Service - Issue with Server Module Destination

### ISSUE THREAD

**Issue by dzmitryburiak** [SAPDocuments/Issues#533]
Tutorials: https://developers.sap.com/tutorials/btp-app-launchpad-service.html
--------------------------

Hi Colleagues,

I'm trying to follow the steps of the tutorial to implement the same scenario in my application. I can see application tile in my Launchpad after performing all the steps, but it seems application router managed by Launchpad service doesn't see the destination of the server module as I get 404 for metadata call.

Destination itself is configured upon deploying and can be reached with 401, which is expected.

[mta.txt](https://github.com/SAPDocuments/Issues/files/6939628/mta.txt)

I have attached my mta.yaml file for the reference. 

This is CDS -v output:

@sap/cds: 5.4.1
@sap/cds-compiler: 2.5.0
@sap/cds-dk: 4.1.5
@sap/cds-foss: 3.0.0
@sap/eslint-plugin-cds: 1.1.4
Node.js: v14.16.0
home: /extbin/npm/globals/lib/node_modules/@sap/cds
renegotiation-sbo-cds: 1.0.0

Please let me know if you can take a look at the issue and I can share the credentials to access the app in a private message.

Thanks in advance,
Dmitri

**Comment by uwe-klinger** [comment]
Hi Michael,

I couldn't find any issue in your MTA. I think, that the 404 indicates either a problem in the xs-app.json of the UI application (route doesn't point to service) or your path is wrong or wrongly mapped in the xs-app.json.  If the destination doesn't work you'll get a 503 if I remember correctly. The easiest way to find it out is to look at the logs of the CAP service. With that you can find out if it reaches the service at all and if with which path.

```
cf logs <your app name>
```

And then fire your request.

You can also compare your application to our solution: https://github.com/SAP-samples/cloud-cap-risk-management/tree/launchpad-service. I know your's is different, so you need to do some translation in your brain ;-)

You can also try to get some help from our community: https://community.sap.com/topics/cloud-application-programming

I hope that helps!

Best regards,
Uwe

**Comment by dzmitryburiak** [comment]
Hi Uwe,

Thanks a lot for your reply!

I have already checked logs and my server module is not called at all, that's why I cannot see any logs with cf logs.However it works fine with my pwn application router and I can see logs in that case.

I have attached xs-app.json located in my HTML5 module. 

Can you please take a look?
[xs-app.txt](https://github.com/SAPDocuments/Issues/files/6945479/xs-app.txt)

Thanks in advance,
Dmitri

**Comment by uwe-klinger** [comment]
Hi Michael,

I don't see an issue here. Maybe it requests the wrong path. It should be /<namespace-without-dots>.<id-without-dots>/odata/...

For that the leading "/" needs to be removed from the service in the UI5 apps `manifest.json` file which is done by the `fiori add deploy-config cf` command.

Best regards,
Uwe

**Comment by dzmitryburiak** [comment]
Hi Uwe,

Thanks! I've tried to remove "/" in manifest.json to make path to the service like this:

`    "mainService": {
                "uri": "/odata/v2/NegotiationService/",
                "type": "OData",
                "settings": {
                    "annotations": [
                        "annotation"
                    ],
                    "localUri": "localService/metadata.xml"
                }
            },`

In that case incorrect "route" from xs-app.json is used (as "/" doesn't exist in "source" it goes to the 2 route)

`"routes": [        
        {
            "source": "^/odata/(.*)$",
            "target": "/odata/$1",
            "destination": "renegotiation-backend",
            "authenticationType": "xsuaa",
            "csrfProtection": false
        },
        {
            "source": "^(.*)",
            "target": "$1",
            "authenticationType": "xsuaa",
            "service": "html5-apps-repo-rt"
        }
    ]`

I have also checked [example ](: https://github.com/SAP-samples/cloud-cap-risk-management/tree/launchpad-service) and see the same config there...

Regards,
Dmitri

**Comment by dzmitryburiak** [comment]
Hi Colleagues,

Any more ideas what might be wrong?

**Comment by uwe-klinger** [comment]
Hi Dmitri,

It's hard to tell when you only have partial access. To really track down the problem I would need to have access to the source code and the subaccount. But this is a level of support that I can't offer. 

Sorry, I think my last hint was misleading. I remember that the "/" gets truncated by the `ui5 build` anyway. I think you need to check things one after the other. You could for example create a second destination manually in the cockpit and try it out with your app.

I recognized one thing that might be a mistake. In your route above you use `renegotiation-backend` destination and in the attached `mta.yaml` file the name of the destination is `renegotiation-api`. Maybe this is the reason.

Best regards,
Uwe

**Comment by iwonahahn** [comment]
Hi @dzmitryburiak,

We haven't heard from you in a while, so we are closing the issue.

Best regards,
Iwona
