### ISSUE TITLE
Deploy Your Application with Access Control (SAP HANA Cloud)

### ISSUE THREAD

**Issue by AndyGla** [SAPDocuments/Issues#534]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-add-auth-deploy.html
--------------------------

Dear Marius,

first of all, thank you for you great work doing tutorials on CAP :-D

There is a problem with steps 4 an 5 in this tut - or at least I have a problem:

Step 4: Make the Fiori app deployment-ready

There is no xs-app.json file in my project.
Can you maybe send me the github-repository / branch, where to find that?

Edit: Found that the xs-app.json file needs to be in the frontend/webapp folder, in which it is not yet.

Step 5: Adjust mta.yaml

In this step you only provide screenshots - no code snippets.
Maybe you can integrate these there?

Thank you very much in advance.

And best wishes from Stuttgart

Andy

Edit: Added Screenshot
![image](https://user-images.githubusercontent.com/81348932/128535569-8b0103af-7700-4152-9de6-32fe6c61c811.png)

**Comment by IObert** [comment]
Hi @AndyGla,

Thanks, I'm glad you enjoy this content. And thanks for your feedback.

In case you don't see the `xs-app.json`, this might mean you missed a substep when the project has been generated. This doesn't have to be a big problem but it could mean other files are missing too. Please make sure you have all the needed files.

Regarding the snippet: Yes, I was thinking about adding snippets in the tutorial but decided against it. Let me explain why.

If I add the entire file in here, it would have between 150 and 200 LOC which would make the tutorial very hard to read. On top, people would just copy and paste the entire file and don't pay attention to the diff/highlighted lines. So this is something I wanted to avoid.
I could have added only the "delta lines" in a snippet but then it would be very hard to describe where these lines need to be pasted exactly, so the screenshots are required anyway. 

I hope this made it clear why there are not many snippets in this particular tutorial. Do you have any other questions regarding this tutorial?

Regards,
Marius

**Comment by AndyGla** [comment]
Hi @IObert 

thank you for your detailed answer.

Just doing it fresh from scratch and there is the xs-app.json :-D

Regards

Andy
