### ISSUE TITLE
Create a Graphical View in SAP Data Warehouse Cloud

### ISSUE THREAD

**Issue by gurudevendranath** [SAPDocuments/Issues#535]
Tutorials: https://developers.sap.com/tutorials/data-warehouse-cloud-7-graphicalview.html
--------------------------

Step 4 doesn't accepts any answer as correct.There should be one answer as correct.But none answer is accepted as correct.

Thanks.

**Comment by rashidabdulrahiman** [comment]
The issue has been fixed. Thanks!
