### ISSUE TITLE
Deploy Your First SAPUI5 App

### ISSUE THREAD

**Issue by klickerlebnis** [SAPDocuments/Issues#536]
Tutorials: https://developers.sap.com/tutorials/appstudio-sapui5-create.html
--------------------------

In step 5.4 this command shows for me the list of urls:

cf html5-list -di sap-btp-sapui5-dest-srv -u --runtime launchpad

instead of 
cf html5-list -di sap-btp-sapui5-destination-service -u --runtime launchpad

Best regards
Dominik

**Comment by klickerlebnis** [comment]
A little hint or description in the tutorial might be sufficient and helpful till new version/ enhancement of the tool.

**Comment by cjbernal** [comment]
Hi Dominik,

Thank you for pointing this out. I am currently working with the product team to figure out the best way to get the required change into the tutorials. 

Kind regards,
Conrad

**Comment by cjbernal** [comment]
The change has been made to the tutorial and will be live once the SAP Devs tutorial team approves. Closing this. @klickerlebnis Thank you again for the feedback.
