### ISSUE TITLE
Deploy Your First SAPUI5 App

### ISSUE THREAD

**Issue by klickerlebnis** [SAPDocuments/Issues#537]
Tutorials: https://developers.sap.com/tutorials/appstudio-sapui5-create.html
--------------------------

Hi Conrad, 

In Step 6 you might add the helpful info, to replace cpp with launchpad in the url.
https://xxxxxxtrial.cpp.cfapps.eu10.hana.ondemand.com/
https://xxxxxxtrial.launchpad.cfapps.eu10.hana.ondemand.com/

It would be helpful. The runtime flag had no effect for me.

**Comment by raz-korn** [comment]
Hi @klickerlebnis ,

Supporting the runtime flag is planned for an upcoming release of BAS.
Meanwhile, there's a need to update the URL, as you mentioned.

Regards - Raz

**Comment by cjbernal** [comment]
As mentioned in #536 this tutorial has been updated to feature the above information as well. Closing this. @klickerlebnis Thank you for your feedback here, as well!
