### ISSUE TITLE
Set Up the SAP Launchpad Service - Subscription or Service Instance?

### ISSUE THREAD

**Issue by AbdullahChougle** [SAPDocuments/Issues#538]
Tutorials: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html
--------------------------

Write here how you think we can improve the tutorial ...

In my sub account, I have added the Launchpad Service (scp-launchpad). However, when I try to follow the step 1. of the launch pad service exercise in my account, I am asked to create a service instance and not a subscription for the launch pad service. It is listed then under the instances section and not the subscription section. I am then unsure how to follow the rest of the steps. 

**_This activity was not done on the trial account_**

**Comment by LindsayBert** [comment]
Hi

Did you check that you have the correct quotas and entitlements assigned?
Have you followed all the steps in this topic that is a prerequisite when using a global account: [Initial Setup](https://help.sap.com/viewer/8c8e1958338140699bd4811b37b82ece/Cloud/en-US/fd79b232967545569d1ae4d8f691016b.html)

Thanks Lindsay
