### ISSUE TITLE
Create an SAP BTP ABAP Environment Trial User

### ISSUE THREAD

**Issue by FarozanFarman** [SAPDocuments/Issues#539]
**Tutorials:** https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html
--------------------------
**Issue:** Screenshot Update required.
**Steps to reproduce:**
Step 3: Create ABAP cloud project
2. Select Use Cloud Foundry Environment and click Next >.
Here Screenshot needs to be changed.

**Expected Result:**
![image](https://user-images.githubusercontent.com/71028764/128815486-8a5be8d9-0679-4a4f-9c8c-18d15436f189.png)

**Actual Result:**
![image](https://user-images.githubusercontent.com/71028764/128815527-b35f45a2-8eff-4db0-8471-96a239c0df9a.png)

**Labels:**
Landscape Labels: trail1, trail2
Scenario Label: 
SCPTest-fabap
Priority: Low
Sprint Label: SCPTest-2108A

Thanks and Regards,
Farozan

**Comment by mervey45** [comment]
Hi @FarozanFarman ,

you get the expected result, when you use Eclipse with the ADT plugin. But if you use ADT, then it looks like in your screenshot.

Best regards, 
Merve

**Comment by FarozanFarman** [comment]
Hi Merve,

Yes, last time I used eclipse, there I got the expected screenshot. But as per the tutorial, we should use ADT, hence the screenshot must be adapted, right?
![image](https://user-images.githubusercontent.com/71028764/128850003-8df234cf-2eb7-4573-bf08-431b3e041a10.png)

Regards, 
Farozan

**Comment by mervey45** [comment]
Hi @FarozanFarman ,

thank you for this feedback. I need to update the first tutorial. It is better to use Eclipse with the ADT plugin. But of course ADT also works also fine. 

Best regards,
Merve

**Comment by FarozanFarman** [comment]
Hi @mervey45 ,

Ok, please let me know once updated. Also, can you give me a tentative date by when it will be updated so that I can check from my side too?

Thanks and Regards, 
Farozan
