### ISSUE TITLE
Screenshot has to be changed while adding the workflow

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Issues#54]
Tutorial: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-4-visibility.html
--------------------------
**Step 2: Add a workflow**

Here in the tutorial on pressing '+', four options are displayed but in actual execution, five options are displayed. So the screenshot has to be updated.

**Expected:** 
![image](https://user-images.githubusercontent.com/65999547/104443540-952e8a80-55bc-11eb-87fd-2506907676e4.png)

**Actual:**
![image](https://user-images.githubusercontent.com/65999547/104443499-847e1480-55bc-11eb-804a-5ee5f044ad69.png)

Best Regards,
Priyanka

**Comment by ArchanaShukla** [comment]
Tutorial have been updated with new screenshot.
