### ISSUE TITLE
Req. Product Details - Cloud Integration Activation Failing - EU region

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#541]
Hello,

Tutorial Link: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html
Step 3: Provision the capabilities
Issue: The provisioning of the Cloud Integration capability is failing.

Screenshot:
![image](https://user-images.githubusercontent.com/66831161/128850342-cc505a3e-791d-4ef4-b0aa-8b96b5bcd5b1.png)

Please check the issue.

Thanks,
Shubham

Labels to be added:
Sprint Label: SCPTest-2108A
Scenario Label: SCPTest-cloudin
Landscape Label: EU10
Prio: High-prio

**Comment by Karunaharan** [comment]
Hi @i353590 - there was a known outage with the trial system which is resolved. Kindly proceed with your testing.
