### ISSUE TITLE
Req. Product Details - API portal provisioning issue - AP region

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#542]
Hello,

Tutorial Link: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html
Step 5: Verify the activated capabilities
Issue: After both the capabilities are active and the boosters are executed, we should be able to access them both. But I can't access API Portal. It is running into the error and says there is a temporary problem provisioning your account. (In AP region)

Screenshot: 
![image](https://user-images.githubusercontent.com/66831161/128850923-ba0392de-e019-4089-a0cb-913818e394a6.png)

Please check the issue.

Thanks,
Shubham

Labels to be added:
Sprint Label: SCPTest-2108A
Scenario Label: SCPTest-cloudin
Landscape Label: AP
Prio: High-prio

**Comment by Karunaharan** [comment]
Hi @i353590 - there was a known outage with the trial system which is resolved. Kindly proceed with your testing.

**Comment by i353590** [comment]
Hello @Karunaharan ,

Now the provisioning of the Cloud Integration itself is failing in AP region.
Please re-open the ticket and help with the fix.

Kind Regards,
Shubham

**Comment by lalithmanokar** [comment]
Reopening Still issue persist.

**Comment by Karunaharan** [comment]
The issue is resolved today.

**Comment by i353590** [comment]
The issue was not reproducible.
I was able to execute the scenario E2E.

Thanks,
Shubham
