### ISSUE TITLE
Req. Product Details - Screenshot not loading 

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#543]
Hello,

Tutorial Link: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html
Step 1: Access your Cloud Integration workspace

the attached Screenshot is not loading. Please refer to the screenshot:
![image](https://user-images.githubusercontent.com/66831161/128862521-78d091ee-7478-45a5-939a-99a944db438d.png)
Please check the issue.

Thanks,
Shubham

Labels to be added:
Sprint Label: SCPTest-2108A
Scenario Label: SCPTest-cloudin
Landscape Label: US10,EU10 & AP
Prio: High-prio

**Comment by Karunaharan** [comment]
@MichaelCzcz - could you please help me resolving the issue? I'm not sure what I missed in the .md file?

**Comment by MichaelCzcz** [comment]
@Karunaharan Simply remove the indentation for the image.

**Comment by Karunaharan** [comment]
Thank you @MichaelCzcz 

@i353590 - the issue is fixed now. Will be published very soon.

**Comment by i353590** [comment]
The screenshot is still not loading.
if the change is not pushed yet, by when can we expect the fix.?

thanks,
Shubham

**Comment by Karunaharan** [comment]
Hi, yes the change is not pushed yet. Waiting for other feedback from you/your team, if any.
