### ISSUE TITLE
Req. Product Details - Screenshots Update with new Account explorer feature

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#544]
Hello,

Tutorial Link: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html
Step 1: Enter your trial account
Sub-step: 3, 4 & 5:
Issue: all these screenshots need to be updated from steps 3-5 after the latest UI changes. Also, the statements will also need to be rephrased in some places.

New screenshots:
![image](https://user-images.githubusercontent.com/66831161/128863930-9da2869f-1811-46d2-be31-7848646e4636.png)

![image](https://user-images.githubusercontent.com/66831161/128863968-87e30004-d074-45af-819a-8e4b2a893dec.png)

Thanks,
Shubham

Labels to be added:
Sprint Label: SCPTest-2108A
Scenario Label: SCPTest-cloudin
Landscape Label: US10, EU10 & AP
Prio: Med-prio

**Comment by Karunaharan** [comment]
Hi @i353590 - as discussed, the screenshots of sub steps 3 & 4 are right for a new user of BTP. The step 1 of the tutorial is currently  targeted at such new users. For existing users of BTP (which your screenshots match with), instructions are provided in the tutorial without images.

For sub step 5, I have updated the image as suggested. Will publish the changes soon.

Thanks,
Karuna

**Comment by i353590** [comment]
Hello @Karunaharan 

Thanks for the fix. So the initial screenshots will continue to be as is.
Thanks,
Shubham
