### ISSUE TITLE
Test the Business Rules API from SAP API Business Hub

### ISSUE THREAD

**Issue by jacobahtan** [SAPDocuments/Issues#545]
Tutorials: https://developers.sap.com/tutorials/cp-cf-businessrules09-test-apis.html
--------------------------

payload doesn't tally with the sample code snippet.
company should be ACE_USA, not "2000"

**Comment by VandanaVasudevan** [comment]
Hi @jacobahtan,

When the company is ACE_USA, there is different equipment assigned to the employee. 2000 is just a sample value given to hit the decision table row with the logic for companies other than ACE_USA.  
For better understanding, I will change the company name to a string value in the code snippet. Thanks a lot for your valuable feedback.

Best Regards,
Vandana

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
