### ISSUE TITLE
Build and Deploy Your SAP Fiori App to SAP Business Technology Platform

### ISSUE THREAD

**Issue by shivakumar-p-sap** [SAPDocuments/Issues#546]
Tutorials: https://developers.sap.com/tutorials/appstudio-fioriapps-mta-build-deploy.html
--------------------------
In step 3 the last screenshot can be removed. Its not showing the popup with message "Task 'Deploy MTA Archive(/)' was terminated by signal SIGPIPE". Also it prompts to select ORG and Space after selecting "Deploy MTA Archive".

Regards,
Shivakumar P

**Comment by raz-korn** [comment]
Thanks, @shivakumar-p-sap ,
I updated the tutorial.
The update should be available soon.

Regards - Raz
