### ISSUE TITLE
Add a Web Dynpro ABAP App to Your Launchpad Site

### ISSUE THREAD

**Issue by klickerlebnis** [SAPDocuments/Issues#547]
Tutorials: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-webdynpro-app.html
--------------------------

The final question might be wrong. I thought the answer is Role editor and Group editor and not Role, Group and App. 
Which tools will you use to configure your Web Dynpro app so that users can see it and launch it from your launchpad site?
App editor
Provider Manager
**Role editor
Group editor**

**Comment by LindsayBert** [comment]
Hi - thanks - you are correct and I've fixed it.  The app editor was also checked and I removed it.  

Thanks 
Lindsay

**Comment by LindsayBert** [comment]
The problem is fixed
