### ISSUE TITLE
A step is missing while configuring the status

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Issues#55]
Tutorial: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-4-visibility.html
--------------------------
**Step 4: Configure status**

Here after entering 'Approval Pending' in the Name field of the dialog box. Enter a text to click on OK. 
Although it is mentioned in the screenshot. From a customer perspective, I think it would be good if the text is also included.
![image](https://user-images.githubusercontent.com/65999547/104444154-69f86b00-55bd-11eb-9fd2-e85fedb9a9bc.png)

Best Regards,
Priyanka

**Comment by ArchanaShukla** [comment]
Tutorial have been updated.
