### ISSUE TITLE
Extend the Built-In OData Features with Custom Code

### ISSUE THREAD

**Issue by chatterjeeg** [SAPDocuments/Issues#552]
Tutorials: https://developers.sap.com/tutorials/odata-07-extend-custom-code.html
--------------------------
In the piece of code below Products should be in quote as in 'Products'.

srv.on('TotalStockCount', async (req) => {
        const items = await cds.tx(req).run(SELECT.from(Products))
        return items.reduce((a, item) => a + item.UnitsInStock, 0)
    })

**Comment by qmacro** [comment]
Hi @chatterjeeg I think you may have missed the note next to that usage of `Products` :-)

<img width="629" alt="screenshot 2021-08-16 at 08 07 16" src="https://user-images.githubusercontent.com/73068/129524617-024de822-02b7-46b6-b8ff-f28206b40968.png">
