### ISSUE TITLE
Display Data from the Northwind Service

### ISSUE THREAD

**Issue by klickerlebnis** [SAPDocuments/Issues#555]
Tutorials: https://developers.sap.com/tutorials/sapui5-fiori-cf-display-data.html
--------------------------

In step 7.3 the screenshot should show the detail page
![image](https://user-images.githubusercontent.com/37261568/129560149-3aaf54b9-10e1-4bde-969d-62d5b47b623c.png)

Just my two cents, 
Dominik

**Comment by IObert** [comment]
I fixed this and the new version should be live soon.

Thanks.
