### ISSUE TITLE
Deploy the Fiori App to Cloud Foundry

### ISSUE THREAD

**Issue by klickerlebnis** [SAPDocuments/Issues#556]
Tutorials: https://developers.sap.com/tutorials/sapui5-fiori-cf-deploy.html
--------------------------

In step 3 it might be that the "cf html-5 plugin" has to be installed. In the Web IDE this is already done, but not on our local machines. I have done that installation via the installation instructions on page https://github.com/SAP/cf-html5-apps-repo-cli-plugin 

Maybe a hint and a link would be helpful...

Cheers, 
Dominik

**Comment by IObert** [comment]
Good catch as well. I fixed this and the new version should be live soon.

Thanks.
