### ISSUE TITLE
Build Your First FAQ Chatbot

### ISSUE THREAD

**Issue by Sri129225** [SAPDocuments/Issues#558]
Tutorials: https://developers.sap.com/tutorials/conversational-ai-faq-chatbot-beginner.html
--------------------------

Write here how you think we can improve the tutorial ...

On testing with the csv file given the tutorial, no question had confidence of 37%. But this was the question for "Test and monitor your bot" under this tutorial. Hence the tutorial could not be fully completed. Please help me in resolving this issue.
![ChatBot1](https://user-images.githubusercontent.com/89068823/129687782-54e4c2e4-af1b-48c1-bbc1-7d1cc5aeb727.PNG)
![ChatBot2](https://user-images.githubusercontent.com/89068823/129687882-aa25df99-eaec-41b3-bd75-4640a89148bb.PNG)

Thanks,
Srinivasan

**Comment by thecodester** [comment]
I have updated the question. Sorry for the issues. Let me know if all is OK for you now.
