### ISSUE TITLE
Mission page shows old tutorial titles

### ISSUE THREAD

**Issue by IObert** [SAPDocuments/Issues#559]
I noticed this in the following mission <https://developers.sap.com/mission.sapui5-cf-launchpad.html> (see mentions of "SAP Cloud Platform" and "Cloud Foundry Environment").

Can you please update this?
![Screenshot 2021-08-17 at 10 42 19](https://user-images.githubusercontent.com/1873245/129693736-b486bdc3-d6e7-4913-85c0-53e0e728dec2.png)

**Comment by thecodester** [comment]
Updated
