### ISSUE TITLE
Screenshot has to be changed while starting a new instance

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Issues#56]
Tutorial: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-5-run.html
--------------------------
**Step 4: Execute the workflow sample application**
Screenshot has to be changed while starting a new instance

**Expected:**
![image](https://user-images.githubusercontent.com/65999547/104444876-66191880-55be-11eb-8b48-78e23ad5e94b.png)

**Actual:**
![image](https://user-images.githubusercontent.com/65999547/104444852-5c8fb080-55be-11eb-873a-c205d5d32fb7.png)

Best Regards,
Priyanka

**Comment by ArchanaShukla** [comment]
Tutorial have been updated with new screenshot.
