### ISSUE TITLE
Implement Roles and Authorization Checks In CAP

### ISSUE THREAD

**Issue by AndyGla** [SAPDocuments/Issues#560]
Tutorials: https://developers.sap.com/tutorials/btp-app-cap-roles.html
--------------------------

Dear @iwonahahn Iwona,

thank you for your excellent tutorial!

Just want to submit a minor bug in Step 4:

Within chrome the command to restart the browser needs to be chrome://restart wihtout blank.

Best wishes

Andy

**Comment by iwonahahn** [comment]
Hi @AndyGla,

Sorry for the late reply, I was on vacation. I have to check your suggestionion and will get back to you asap.

Best regards,
Iwona

**Comment by iwonahahn** [comment]
Hi @AndyGla,

The tutorial was updated with this [change](https://github.com/SAPDocuments/Tutorials/pull/6967) and I'm closing this issue here. Thank you again for your feedback.

Best regards,
Iwona
