### ISSUE TITLE
Deploy an SAP Conversational AI Chatbot to Microsoft Teams

### ISSUE THREAD

**Issue by siouxme** [SAPDocuments/Issues#561]
Tutorials: https://developers.sap.com/tutorials/conversational-ai-deploy-teams.html
--------------------------

The Bot Channels Registration is deprecated ...

In Azure: Warning
Web App Bot and Bot Channels Registration will be deprecated but existing resources will continue to work. You should use Azure Bot, instead.

**Comment by thecodester** [comment]
I have updated. Please check and provide any feedback you might have.

Thanks so much for bringing this to my attention.
