### ISSUE TITLE
Tutorial: Add Views and Define Routes to Access Them - Wrong first screenshot

### ISSUE THREAD

**Issue by AlexMFrank** [SAPDocuments/Issues#562]
Tutorials: https://developers.sap.com/tutorials/sapui5-101-add-routing.html
--------------------------

The first screenshot shows the Chrome network tab screenshot from the previous tutorial "Create an Empty SAPUI5 Project" (https://developers.sap.com/tutorials/sapui5-101-create-project.html) instead of the creation of a file called List.view.xml in BAS.

**Comment by cjbernal** [comment]
Hi Alex, 

Thank you for pointing this out. I am trying to get in touch with some colleagues who may be able to help us get this changed out. 

Kind regards,
Conrad

**Comment by cjbernal** [comment]
The tutorial has since be updated (see above) and the changes are now live. Closing this.
