### ISSUE TITLE
Installing SAP HANA, express edition with Docker

### ISSUE THREAD

**Issue by bhardwaj-rahul** [SAPDocuments/Issues#563]
Tutorials: https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html
--------------------------

The folder /data is not read-only with Mac OS Cataline and above. How should we change the config to read not from /data but from some other folder. I received the following error while performing Step 6 and Step 7
(https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html) :

ERROR: mkdir: /data/mydirectory: Read-only file system

**Comment by JCurrie27** [comment]
Hi Rahul - I've CC'd you on a question to our Docker team asking about Mac OS Catalina. 
Closing this issue. Best - John C.
