### ISSUE TITLE
Deploy Your Business Application to Cloud Foundry

### ISSUE THREAD

**Issue by dkclaesk** [SAPDocuments/Issues#564]
Tutorials: https://developers.sap.com/tutorials/appstudio-cap-deploy-app.html
--------------------------

Not able to select plan "hdi-shared", only plan "securestore" is available.

**Comment by Paolaufer** [comment]
Hi,
I am afraid I am unable to reproduce your problem.
I just did the tutorial end to end following the instructions and I get "hdi-shared".
Could you please try again?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
