### ISSUE TITLE
Deploy Your Business Application to Cloud Foundry

### ISSUE THREAD

**Issue by dkclaesk** [SAPDocuments/Issues#565]
Tutorials: https://developers.sap.com/tutorials/appstudio-cap-deploy-app.html
--------------------------

Deploy is failing:

> Executing task: cds deploy --to hana:hanainstance --no-save <

[cds.deploy] - Starting deploy to SAP HANA ...

[cds.deploy] - Creating build tasks
[cds.deploy] - Running build

[cds.deploy] - Using container hanainstance

[cds.deploy] - Running 'cf create-service hana hdi-shared hanainstance' with options {}
Creating service instance hanainstance in org 2bdd66b7trial / space dev as claus.eskildsen@lego.com...
OK

Service hanainstance already exists

[cds.deploy] - Running 'cf create-service-key hanainstance hanainstance-key -c {"permissions":"development"}' with options {}
Creating service key hanainstance-key for service instance hanainstance as claus.eskildsen@lego.com...
OK

[cds.deploy] - Deploying to HANA from /home/user/projects/bookshop/gen/db
[cds.deploy] - Using HDI deployer from /home/user/projects/bookshop/node_modules/@sap/hdi-deploy/library.js
@sap/hdi-deploy, version 4.1.0 (mode default), server version unknown (0.0.0.0), node version 14.16.0, HDI version -1, container API version -1

Deployment started at 2021-08-24 09:49:02
Detection of server version failed; root cause: Connection failed (RTE:[0]  (zeus.hana.prod.us-east-1.whitney.dbaas.ondemand.com:21022))

Detection of container API version failed; root cause: Connection failed (RTE:[0]  (zeus.hana.prod.us-east-1.whitney.dbaas.ondemand.com:21022))
Detection of HDI version failed; root cause: Connection failed (RTE:[0]  (zeus.hana.prod.us-east-1.whitney.dbaas.ondemand.com:21022))

The server does not support live updating of make messages. The messages will be displayed, when the make is done.

No ignore file at /home/user/projects/bookshop/gen/db/.hdiignore.

Collecting files...

Collecting files... ok (0s 4ms)

3 directories collected
26 files collected
0 reusable modules collected
Target service: hanainstance

Session variable APPLICATION is set to "SAP_HDI//".

Could not determine status of last build: invalid schema name: USR_1LH1SJQTMSSJ0O2GY2A9JOR6G#DI: line 1 col 21 (at pos 20)

Processing revoke files...

Processing revoke files... ok (0s 0ms)

Processing grants files...

Processing grants files... ok (0s 0ms)

Preprocessing files...

Preprocessing files... ok (0s 0ms)

Connecting to the container "USR_1LH1SJQTMSSJ0O2GY2A9JOR6G"...

Connecting to the container "USR_1LH1SJQTMSSJ0O2GY2A9JOR6G"... ok (0s 62ms)

Synchronizing files with the container "USR_1LH1SJQTMSSJ0O2GY2A9JOR6G"...
  Deleting files...

Deployment to container USR_1LH1SJQTMSSJ0O2GY2A9JOR6G failed - error: invalid schema name: USR_1LH1SJQTMSSJ0O2GY2A9JOR6G#DI: line 1 col 37 (at pos 36) [Deployment ID: none].

Deployment ended at 2021-08-24 09:49:03

Error: invalid schema name: USR_1LH1SJQTMSSJ0O2GY2A9JOR6G#DI: line 1 col 37 (at pos 36)

(0s 453ms)

[ERROR] [cds.deploy] - HDI deployment failed with exit code 1

Terminal will be reused by tasks.

**Comment by Paolaufer** [comment]
Hi,
I created an app and then deployed it following the instructions and encountered no errors.
I have updated some screenshots as I went along.
Could you please try again? Maybe this will help.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
