### ISSUE TITLE
Get Started with the SAP BTP Command Line Interface (btp CLI)

### ISSUE THREAD

**Issue by mounikat987** [SAPDocuments/Issues#567]
Tutorials: https://developers.sap.com/tutorials/cp-sapcp-getstarted.html
--------------------------

Hi,

I have installed BTP latest version (client v2.8.0) on windows and tried running few steps locally.
After every two or 3 command executions, it's  asking to re-login.
I am facing this issue today repeatedly. Please check on this.

![image](https://user-images.githubusercontent.com/33411431/130948695-ec34d10d-5ded-4383-94a4-a1f9b783e428.png)

Thanks
Mounika

**Comment by annawenger20** [comment]
Hi Mounika, 
thanks for reporting this issue not only here, but also as a bug. As you have probably seen, the issue has been resolved. My apologies on not answering more quickly here! Unfortunately, I was away from the office for a long time and my process of forwarding issues failed. 
Hope you are again enjoying working with the btp CLI. 
Kind regards,
Anna
