### ISSUE TITLE
Get Started with the SAP BTP Command Line Interface (btp CLI)

### ISSUE THREAD

**Issue by ibwis** [SAPDocuments/Issues#568]
Tutorials: https://developers.sap.com/tutorials/cp-sapcp-getstarted.html
--------------------------

There is a spelling mistake in the code: `btp enable **autocompletion** <**SHELL**>`

It should be : `btp enable **autocomplete** <shell>`

Better writing shell in low capitals, the parameter should be entered in low capitals also.

**Comment by annawenger20** [comment]
done. My apologies for the long silence - I was out of office for several weeks and my process for forwarding issues to a substitute failed. 

Promise to better next time & thanks a lot for noticing this issue!
Anna
