### ISSUE TITLE
Prepare SAP Web IDE for Cloud Foundry Development

### ISSUE THREAD

**Issue by IObert** [SAPDocuments/Issues#569]
Tutorials: https://developers.sap.com/tutorials/sapui5-webide-open-webide.html
--------------------------

The tutorial is outdated as it still recommends to use the Web IDE in Trial accounts. Please update the tutorial or add a disclaimer that this can only be used in production accounts.

**Comment by thecodester** [comment]
@Paolaufer @raz-korn Can you decide what to do with this tutorial?

It is only used in this group https://developers.sap.com/group.iot-app-decision-support.html (I will remove tutorial from group)
and this tutorial: https://developers.sap.com/tutorials/cp-cf-fioriapps-create.html (Paola)

FYI: @anzeiger

**Comment by Paolaufer** [comment]
@raz-korn leaving it up for you to decide.

**Comment by anzeiger** [comment]
> @Paolaufer @raz-korn Can you decide what to do with this tutorial?
> 
> It is only used in this group https://developers.sap.com/group.iot-app-decision-support.html (I will remove tutorial from group)
> and this tutorial: https://developers.sap.com/tutorials/cp-cf-fioriapps-create.html (Paola)
> 
> FYI: @anzeiger -- Even though we removed the SAP Web IDE prepare tutorial, doesn't your group/mission require SAP Web IDE (which is only in production)?

**Comment by anzeiger** [comment]
Hi @thecodester, I am no longer part of the IoT team and the decision support tutorial is now maintained by @JitendraSharma01.  As far as I know, the SAP Web IDE is still required for the tutorial group and it requires a license to follow the steps.
