### ISSUE TITLE
Screenshots has to be changed and a step should be included after opening BAS

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Issues#57]
Tutorial: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-3-workflow.html
--------------------------
**Step 2: Import sample application**

**Issue: 1**
Here as soon as we Choose **SAP Business Application Studio**, we get a screen with the privacy statement as below, add a step to accept it.
![image](https://user-images.githubusercontent.com/65999547/104445506-30c0fa80-55bf-11eb-8c72-42bfd5eb57a9.png)

**Issue: 2**
Screenshot has to be changed wherever the Dev space is displayed as now the UI is changed a little, the Restrictions for the trail account is added as below.
![image](https://user-images.githubusercontent.com/65999547/104445695-6d8cf180-55bf-11eb-93ba-2f2b0ef62c12.png)

Best Regards,
Priyanka

**Comment by ArchanaShukla** [comment]
Tutorial have been updated with a new note.
