### ISSUE TITLE
Prepare the RAP-Based Travel Service

### ISSUE THREAD

**Issue by msoberanes1** [SAPDocuments/Issues#572]
Tutorials: https://developers.sap.com/tutorials/fiori-tools-rap-prepare-service.html
--------------------------

When I executed the class /DMO/CL_FE_TRAVEL_GENERATOR, I gen this error below, and the new created  package becomes empty.

Additional messages:
DDLS ZI_FE_STAT_000128: Creation of CDS views is not allowed in the current environment.
DDLS ZI_FE_CARR_000128: Creation of CDS views is not allowed in the current environment.
DDLS ZI_FE_CONN_000128: Creation of CDS views is not allowed in the current environment.
DDLS ZI_FE_FLIG_000128: Creation of CDS views is not allowed in the current environment.
Stack trace:
CX_XCO_RUNTIME_EXCEPTION    constructor [method] Line: 15
CX_XCO_GEN_PUT_EXCEPTION    constructor [method] Line: 1
CX_XCO_GEN_PUT_EXCEPTION    for_ongoing_operation [method] Line: 3
CL_XCO_GEN_O_PUT_ABSTRACT    execute [method] Line: 8

**Comment by anfisc** [comment]
This issue has been fixed a while ago. 
The class /DMO/CL_FE_TRAVEL_GENERATOR now generates view entities rather than classic CDS views.
