### ISSUE TITLE
Build and Deploy a Java Application

### ISSUE THREAD

**Issue by os-neff** [SAPDocuments/Issues#575]
Tutorials: https://developers.sap.com/tutorials/cp-java-reference-app-deploy.html
--------------------------

The Repository is still pointing to Neo. There is an updated repository available for CF environments, but even this cannot easily be run on a the current configuration: There are still dependencies that one would need to sort out manually, instead of just cloning the repository.
It would therefore be great to have a easy-to-work-with repository.

Thanks
Joachim

**Comment by thecodester** [comment]
@YogithaC Can you also update your name in your Git profile, and then republish all 5 tutorials so your full name appears? Thanks.

**Comment by YogithaC** [comment]
Hi Joachim,
Which repo did you take the CF code from? 
Regards,
Yogitha

**Comment by os-neff** [comment]
Hello Yogitha,

the CF repository is: https://github.com/SAP/cloud-cf-espm

Regards
Joachim

**Comment by YogithaC** [comment]
Hi Joachim,

Did you add the ngdbc dependency manually? The developer will add a fix for this in the code.
Just wanted to confirm if there are any missing dependencies. Thank you!

Regards,
Yogitha

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
