### ISSUE TITLE
Build and Deploy Your SAP Fiori App to SAP Cloud Platform

### ISSUE THREAD

**Issue by shivakumar-p-sap** [SAPDocuments/Issues#58]
Tutorial: https://developers.sap.com/tutorials/appstudio-fioriapps-mta-build-deploy.html
--------------------------

Step 4: Access the application on SAP Cloud Platform, Cloud Foundry
             Sub step 4: cf html5-list -di FioriDemo-destination-service -u
     We run the above command to get the details like url but the command is not working. Throwing error as "Too much arguments". Its only happening in AP region. EU and US worked fine. 

![image](https://user-images.githubusercontent.com/65213299/104454634-29ecb480-55cc-11eb-8bae-960f54cdc1f6.png)

Labels :
Landscape Labels: trail3
SCPTest-eboard: Develop an SAP Fiori App Using SAP Business Application Studio
Priority label :‘High-prio’

Best Regards,
Shivakumar P

**Comment by raz-korn** [comment]
Hi @shivakumar-p-sap ,

Where the issue happens (AP trial) - can you run in a BAS terminal the 'cf plugins' command and share the version for the HTML5 plugins?

![image](https://user-images.githubusercontent.com/6040433/104468566-4682ef80-55c0-11eb-8652-7cf488e6c654.png)

Regards - Raz

**Comment by shivakumar-p-sap** [comment]
Hi Raz,
            The version is 1.4.3 in AP region. Please find the below screenshot.
![image](https://user-images.githubusercontent.com/65213299/104712742-ef5c5680-5748-11eb-9a41-9f92d0135d2d.png)

Regards
Shivakumar P

**Comment by raz-korn** [comment]
Hi @shivakumar-p-sap ,
This seems to be the root-cause.
I'm working with Engineering on solving this.
Regards - Raz

**Comment by raz-korn** [comment]
Hi @shivakumar-p-sap ,
I was notified that the issue was solved.
Can you check / test?
Regards - Raz

**Comment by shivakumar-p-sap** [comment]
Hi Raz,
It's working, so closing the issue. Thanks

Regards - Shivakumar P
