### ISSUE TITLE
Use ML to process Documents - Instance creation using Booster fails - EU

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#580]
Hello,

Tutorial Link: https://developers.sap.com/tutorials/cp-aibus-dox-booster-app.html
Step 2: Run booster

Issue: the booster is failing in EU region as creation of Document Info service instance is failing in EU region.
US region it works fine.

![image](https://user-images.githubusercontent.com/66831161/132666938-d026515a-eb8b-4cdf-b78f-f1f7f52c9723.png)

Thanks,
Shubham

Labels to be added:
Sprint label: SCPTest-2109A
Scenario label: SCPTest-docinfo
Landscape Label: SCPTest-trial1
Prio: High-prio

**Comment by Juliana-Morais** [comment]
Hi Shubham,

I've just run the booster with a subaccount in Europe (Frankfurt) and it worked fine. Can you please try again?

Best regards,
Juliana

**Comment by i353590** [comment]
Hello @Juliana-Morais ,

The issue is resolved now. Thanks for the update :)

Thanks,
Shubham
