### ISSUE TITLE
Question and screenshot update for document type - use ML to process documents

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#581]
Hello,

Tutorial link: https://developers.sap.com/tutorials/cp-aibus-dox-ui.html
Step 1.3: In the Select Document screen, drop files directly or click + to upload one or more document files.
& Step 1.4: Select the Document Type. Click Step 2.

Issue: Please update screenshots at both places as we get 4 options under 'Document Type'. Also, new field is added "Schema: which is missing in the screenshot.
 
Due to these changes, the question should also be changed as it has 2 correct answers now.
1- Invoice & Purchase order 
2- Invoice & Payment Advice. but the question is only a one-answer question. So, please update that as well

Screenshot for reference:
![image](https://user-images.githubusercontent.com/66831161/132668165-a3fdf0ca-ac4a-4a58-a006-e49df09cd3d9.png)

Thanks,
Shubham

Labels to be added:
Sprint label: SCPTest-2109A
Scenario label: SCPTest-docinfo
Landscape Label: SCPTest-trial1, SCPTest-trial2
Prio: High-prio

**Comment by Juliana-Morais** [comment]
The tutorial has been updated. https://github.com/SAPDocuments/Tutorials/pull/6976
