### ISSUE TITLE
Create a Reusable Service

### ISSUE THREAD

**Issue by BurningSpy** [SAPDocuments/Issues#584]
Tutorials: https://developers.sap.com/tutorials/cp-cap-java-reusable-service.html
--------------------------

Hi, 
Currently I get the following error, when running mvn spring-boot:run on step 8: 

Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Cannot load driver class: org.sqlite.JDBC

I could not find a fix on google/stackoverflow as most issues there were fixed by changing something in the application.properties, which we don't use.

**Comment by mofterdinger** [comment]
Hi @BurningSpy ,
could you please attach the pom.xml from the srv-module (srv/pom.xml) to this issue ? I assume a missing dependency to the Sqlite DB in your pom.xml that is causing this issue.
Thanks

**Comment by BurningSpy** [comment]
I see, you are probably right. 
These are the current contents of the pom:

<?xml version="1.0" encoding="UTF-8" standalone="no"?><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<artifactId>products-service-parent</artifactId>
		<groupId>com.sap.cap</groupId>
		<version>${revision}</version>
	</parent>

	<artifactId>products-service</artifactId>
	<packaging>jar</packaging>

	<name>products-service</name>

	
	<dependencies>
		
		<dependency>
			<groupId>com.sap.cds</groupId>
			<artifactId>cds-starter-spring-boot</artifactId>
		</dependency>

		
		<dependency>
			<groupId>com.sap.cds</groupId>
			<artifactId>cds-adapter-odata-v4</artifactId>
			<scope>runtime</scope>
		</dependency>

		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>runtime</scope>
		</dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.sap.cds</groupId>
			<artifactId>cds-starter-cloudfoundry</artifactId>
		</dependency>
	</dependencies>

	<build>
		<finalName>${project.artifactId}</finalName>
		<plugins>
			
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>${spring.boot.version}</version>
				<configuration>
					<skip>false</skip>
				</configuration>
				<executions>
					<execution>
						<id>repackage</id>
						<goals>
							<goal>repackage</goal>
						</goals>
						<configuration>
							<classifier>exec</classifier>
						</configuration>
					</execution>
				</executions>
			</plugin>

			
			<plugin>
				<groupId>com.sap.cds</groupId>
				<artifactId>cds-maven-plugin</artifactId>
				<version>${cds.services.version}</version>
				<executions>
					<execution>
						<id>cds.clean</id>
						<goals>
							<goal>clean</goal>
						</goals>
					</execution>

					<execution>
						<id>cds.install-node</id>
						<goals>
							<goal>install-node</goal>
						</goals>
						<configuration>
							<skip>${cdsdk-global}</skip>
							<downloadUrl>${node.url}</downloadUrl>
						</configuration>
					</execution>

					<execution>
						<id>install-cdsdk</id>
						<goals>
							<goal>install-cdsdk</goal>
						</goals>
						<configuration>
							<skip>${cdsdk-global}</skip>
						</configuration>
					</execution>

					<execution>
						<id>cds.build</id>
						<goals>
							<goal>cds</goal>
						</goals>
						<configuration>
							<commands>
								<command>build --for java-cf</command>
								<command>deploy --to sql --dry &gt;
									"${project.basedir}/src/main/resources/schema.sql"</command>
							</commands>
						</configuration>
					</execution>

					<execution>
						<id>cds.generate</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<basePackage>cds.gen</basePackage>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<profiles>
		
		<profile>
			<id>cdsdk-global</id>
			<properties>
				<cdsdk-global>true</cdsdk-global>
			</properties>
		</profile>
	</profiles>
</project>



I'll add the sqlite dependency and check if that fixes it. 
I thought sqlite was supposed to come with the npm install a few steps earlier, so I didn't expect it in the pom though.

**Comment by BurningSpy** [comment]
Okay, 
Adding the newest dependency for sqlite to the pom fixed the issue.
Thanks a lot!

**Comment by mofterdinger** [comment]
Thanks for providing the pom.xml. It looks like the CAP project template uses now H2 database instead of Sqlite.
Sorry for that issue, we have to adapt the tutorial. You can continue with using Sqlite for your tutorial.
Thanks
