### ISSUE TITLE
Create a Basic Flow with a SOAP Endpoint

### ISSUE THREAD

**Issue by liamwalkersap** [SAPDocuments/Issues#585]
Tutorials: https://developers.sap.com/tutorials/cp-integration-create-basic-flow.html
--------------------------

Simply following the tutorial will lead to security issues. There are two steps which are needed. The first is specific to the trial account. It requires using your trial username (a sequence of letters and numbers) as the authorization username in postman and your user password for the password. The second step which is need is to follow this tutorial to set up authentication with gmail. https://blogs.sap.com/2020/01/15/cpi-gmail-smtp-integration/

**Comment by gauthamkrishna-sap** [comment]
Hello,
This tutorial has been deprecated. We will replace it with an updated tutorial in the coming weeks. Please watch out for "Integration Suite tutorials" in the SAP Tutorial Navigator for new updates. 
Thank you.
