### ISSUE TITLE
Add a User Task to Your Workflow and Deploy

### ISSUE THREAD

**Issue by mendesthi** [SAPDocuments/Issues#59]
Tutorial: https://developers.sap.com/tutorials/cp-workflow-3-add-usertask-cf.html
--------------------------

Hi there,
Step 4, deploying MTA Archive, returns the error below:

Error building content deployment configuration for module: "approvals": Controller operation failed: 404 Not Found: Service instance wm_workflow not found. 

Further log:
Operation ID: 8fb3ecbf-55bf-11eb-a396-eeee0a95a55e
Deploying in org "2bffd846trial" and space "dev"
Detected MTA schema version: "3"
No deployed MTA detected - this is initial deployment
Detected new MTA version: "0.0.1"
Error building content deployment configuration for module: "approvals": Controller operation failed: 404 Not Found: Service instance wm_workflow not found. 
Proceeding with automatic retry... (3 of 3 attempts left)
Error building content deployment configuration for module: "approvals": Controller operation failed: 404 Not Found: Service instance wm_workflow not found. 
Proceeding with automatic retry... (2 of 3 attempts left)
Error building content deployment configuration for module: "approvals": Controller operation failed: 404 Not Found: Service instance wm_workflow not found. 
Proceeding with automatic retry... (1 of 3 attempts left)
Error building content deployment configuration for module: "approvals": Controller operation failed: 404 Not Found: Service instance wm_workflow not found. 
Process failed.
Use "cf deploy -i 8fb3ecbf-55bf-11eb-a396-eeee0a95a55e -a abort" to abort the process.
Use "cf deploy -i 8fb3ecbf-55bf-11eb-a396-eeee0a95a55e -a retry" to retry the process.
Use "cf dmol -i 8fb3ecbf-55bf-11eb-a396-eeee0a95a55e" to download the logs of the process.

Terminal will be reused by tasks.

**Comment by Ralphive** [comment]
I've got an error on this same step, but it is a different one.
@mendesthi's environment seem to be lacking the WF services instances.

I tried following the tutorial twice since the begining. 
Let me know if I can jump on this issue or should open a new one

My terminal output is as following:

```
Terminal will be reused by tasks. 

> Executing task: cf deploy "/home/user/projects/cf-onboarding-sample/mta_archives/sample.onboarding.mta_0.0.1.mtar" <

Deploying multi-target app archive /home/user/projects/cf-onboarding-sample/mta_archives/sample.onboarding.mta_0.0.1.mtar in org a20b8e06trial / space dev as ralph.oliveira@sap.com...

Uploading 1 files...
  /home/user/projects/cf-onboarding-sample/mta_archives/sample.onboarding.mta_0.0.1.mtar
OK
Operation ID: 6c3950fc-5650-11eb-9108-eeee0a890e7e
Deploying in org "a20b8e06trial" and space "dev"
Detected MTA schema version: "3"
No deployed MTA detected - this is initial deployment
Detected new MTA version: "0.0.1"
Service key "onboarding-wm_workflow-credentials" for service "wm_workflow" already exists
Uploading content module "onboarding" in target service "wm_workflow"...
Deploying content module "onboarding" in target service "wm_workflow"...
Skipping deletion of services, because the command line option "--delete-services" is not specified.
Process finished.
Use "cf dmol -i 6c3950fc-5650-11eb-9108-eeee0a890e7e" to download the logs of the process.

Terminal will be reused by tasks. 
```

And it shows up a message:
![image](https://user-images.githubusercontent.com/9930965/104577069-f43ddf00-5650-11eb-8766-5c833f2acecb.png)

Thanks

**Comment by mendesthi** [comment]
Thanks, Ralph! That's right, I missed the pre-req. After running the “Step 1: Setup your account using Booster” of the Set Up Workflow Management in Cloud Cockpit tutorial, I could follow the tutorial with no issues. Best, Thiago.
