### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by VanitaDhanagar** [SAPDocuments/Issues#592]
Tutorials: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html
--------------------------

The overall project template is not working as step 4 and further in **"https://developers.sap.com/tutorials/appstudio-fioriapps-mta-build-deploy.html"**    

**Ponit 1 :** 
Step 4.4 : **cf html5-list -di FioriDemo-destination-service -u**   This command doesnot return the project url  ,steps to create project template is not correct . Due to this we cannot continue with next stpes

We are blocked for the validation .
![image](https://user-images.githubusercontent.com/80330660/133257050-7e5c00fc-1646-418b-a4ee-71e624b5c33e.png)

Labels to add:
High-Prio
SCPTest-2109A
SCPTest-fbizapp
SCPTest-trial1
SCPTest-trial2
SCPTest-trial3

Thanks and Regards,
Vanita

**Comment by raz-korn** [comment]
Hi @VanitaDhanagar ,

Thanks for sharing.
A fix was deployed.
Be aware that a major update for this tutorial group is planned to be published next week,

Regards - Raz
