### ISSUE TITLE
Create a Reusable Service

### ISSUE THREAD

**Issue by Rodfior** [SAPDocuments/Issues#596]
Tutorials: https://developers.sap.com/tutorials/cp-cap-java-reusable-service.html
--------------------------

Hi Guys, 

First of all, thanks for the awesome tutorial. 

In item 6 I had to change the profiles variable from default to dev to make it work. 

Best regards, 
Rodrigo.

**Comment by iwonahahn** [comment]
Hi @Rodfior,

Thanks. I will need to talk to the dev colleagues about this. Please give me some time to get back to you. 

Best regards,
Iwona

**Comment by iwonahahn** [comment]
Hi @Rodfior,

After getting back to the dev colleagues we decided to close your issue w/o adapting anything in our tutorial. Please try again and open a new issue if necessary.

Best regards,
Iwona
