### ISSUE TITLE
Configure Object Pages Using SAP Fiori Tools

### ISSUE THREAD

**Issue by vinay31** [SAPDocuments/Issues#597]
Tutorials: https://developers.sap.com/tutorials/fiori-tools-configure-object-pages.html
--------------------------
I am unable to see PageMap and it's empty. 
![image](https://user-images.githubusercontent.com/2324128/133434527-0c11221a-a940-4e9d-9cb0-a2e2ffb277dc.png)

Write here how you think we can improve the tutorial ...

**Comment by cjbernal** [comment]
Hi Vinay,

Sorry to see that you are having this issue. When you preview the app, are you able to navigate to the object page? 

Kind regards,
Conrad

**Comment by vinay31** [comment]
Yes, I am able to navigate.

**Comment by cjbernal** [comment]
Thanks, Vinay. In that case, I will reach out to a colleague on the SAP Fiori tools team who may be able to better assist you. Thank you for your patience.

**Comment by vinay31** [comment]
Thanks, Conrad. I will wait for assistance. As I am unable to proceed further.

**Comment by cfg74** [comment]
Hi Vinay, Conrad forwarded me your case. For deeper analysis we would need to have a look at your project. Can you please delete the "node_modules" folder in your project, zip the project folder with remaining contents, and attach it here? Thanks!

Best regards,
Christoph

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by vinay31** [comment]
> Hi Vinay, Conrad forwarded me your case. For deeper analysis we would need to have a look at your project. Can you please delete the "node_modules" folder in your project, zip the project folder with remaining contents, and attach it here? Thanks!
> 
> Edit: in SAP Business application studio there is a download option form the context menu of the project folder, or from File menu.
> 
[lscreation.zip](https://github.com/SAPDocuments/Issues/files/7259517/lscreation.zip)
here are my files, please have a look
> Best regards, Christoph

**Comment by vinay31** [comment]
Thank you Christoph

**Comment by cfg74** [comment]
Hi @vinay31 please apologize the late response. With the latest version of ux-specification this problem shall be fixed.

Please upgrade to the latest Fiori tools release and open the Application info page for the project (palette command "Fiori: Open Application Info"), there you should find a link under Application status, which gives instructions how to upgrade the node module. After this please execute the command "Reload Window" in VSCode or refresh the browser window with BAS.
