### ISSUE TITLE
Create a Sample Application on Cloud Foundry Using SAP Cloud SDK

### ISSUE THREAD

**Issue by kainattu** [SAPDocuments/Issues#6]
Tutorial: https://developers.sap.com/tutorials/s4sdk-cloud-foundry-sample-application.html
--------------------------

do we have any documentation to connect the same app to hana db? 
I created app and run on Cf smoothly but i need to connect with hana db.  i added sap jdbc driver and cloud connecter. but still i am not able to get DB connection.

**Comment by MichaelCzcz** [comment]
@karstenmelato @MatKuhr Please respond!

**Comment by MatKuhr** [comment]
This question has been discussed here: https://github.com/SAP/cloud-sdk/issues/65
