### ISSUE TITLE
Launchpad Scenario - Screenshot Update: Added setting button

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#60]
Hello,

Scenario URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-new-sapui5.html
Step 1: Click the Content Manager icon in the side panel to open the Content Manager.
Screenshot Update: Setting option is not there in old screenshot.

Please update the screenshot.

New screenshot:

<img width="953" alt="Launchpad_1" src="https://user-images.githubusercontent.com/66831161/104504254-2ecf5980-5608-11eb-916f-9ac901e486f2.PNG">

Labels to be added:
Landscape label: Landscape label: trail1, trail2, trail3
Sprint Label: SCPTest-2101 
Scenario label: SCPTest-psite 
Prio: low-prio

Thanks,
Shubham Agarwal

**Comment by LindsayBert** [comment]
Updated - you can close the ticket

**Comment by MichaelCzcz** [comment]
@LindsayBert You can close your issues in this repository.
