### ISSUE TITLE
Get Started with API Management

### ISSUE THREAD

**Issue by funkela** [SAPDocuments/Issues#600]
Group: https://developers.sap.com/group.cp-apim-code-1.html
![grafik](https://user-images.githubusercontent.com/90826763/133608573-9f5e09a5-11f2-45ec-b9cd-129ca7ecf778.png)

--------------------------

The access for the connected developer system does not work, do I have to configure / request access somewhere in BTP?

**Comment by Karunaharan** [comment]
Hello @MichaelCzcz - I'm not the owner of this tutorial.

**Comment by MichaelCzcz** [comment]
@funkela Please state the name of the tutorial in this group in which you have encountered this issue.

**Comment by funkela** [comment]
@MichaelCzcz "Get Started with API Management" (https://developers.sap.com/group.cp-apim-code-1.html); Second lesson "Create an API Provider System"; Step 7: The result of the connection test is Message 401 instead of 200. Seemingly the credentials for the Trial BTP did not work for me.

**Comment by funkela** [comment]
@MichaelCzcz @kulkarnir : Is there any news? Is the "GATEWAY" user/ pw something different to the user for the sapTrial?

**Comment by MichaelCzcz** [comment]
@kulkarnir It's your tutorial. Do you have any updates?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
