### ISSUE TITLE
Set Up SAP Business Application Studio for CAP Java

### ISSUE THREAD

**Issue by priyankagupta0194** [SAPDocuments/Issues#602]
Tutorials: https://developers.sap.com/tutorials/cp-cap-java-app-studio.html
--------------------------

Step 2: Create application skeleton
Point 4- Initializing application using maven archetype.

Please update the cds-services-archetype version. 1.17.1 is not a valid version.
See Link: https://mvnrepository.com/artifact/com.sap.cds/cds-services-archetype

**Comment by iwonahahn** [comment]
We will have a look and update the tutorial accordingly. Thanks for reporting it.

**Comment by iwonahahn** [comment]
Hi @priyankagupta0194,

We have updated the tutorial using version 1.17.0.

Best regards,
Iwona
