### ISSUE TITLE
Add User Authentication to Your Application (SAP HANA Cloud)

### ISSUE THREAD

**Issue by matbeerkens** [SAPDocuments/Issues#603]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-add-authentication.html
--------------------------

Write here how you think we can improve the tutorial ...
Step 2, point 4, just copy in a piece of the string to make it more clear.
Do we need to add quotes yes or no?

**Comment by jung-thomas** [comment]
No you don't need to add any quotes. Copy the complete array as-is into that spot shown

**Comment by matbeerkens** [comment]
Hi Thomas, if i leave the quotes, i get: 
![image](https://user-images.githubusercontent.com/11061267/133632863-95d06b44-1587-46ce-b7d1-af7a6c2a2784.png)
If i add quotes i get: 
![image](https://user-images.githubusercontent.com/11061267/133632957-4699fb1c-a730-4cc0-b173-dab898e862e0.png)

any thoughts?

**Comment by jung-thomas** [comment]
No you need to move the whole structure that is highlighted in the screenshot to the credentials.  Basically everything returned on the command line from the service-key command goes into that spot. 
![image](https://user-images.githubusercontent.com/12159356/133657762-9ad4251c-aa9a-4031-b617-adffcb6fa59e.png)
