### ISSUE TITLE
Set Up SAP Business Application Studio for CAP Java

### ISSUE THREAD

**Issue by dirkelko** [SAPDocuments/Issues#606]
Tutorials: https://developers.sap.com/tutorials/cp-cap-java-app-studio.html
--------------------------

Step 2: Create application skeleton. 
Point 4. of the instructions, the mvn archetype:generation... doesn't work anymore. It can't find -DarchetypeVersion=1.17.1 
It works with -DarchetypeVersion=1.18.1 (but I don't know, if that's the recommended version)

**Comment by iwonahahn** [comment]
We will have a look and update the tutorial accordingly. Thanks for reporting it.

**Comment by iwonahahn** [comment]
Hi @dirkelko,

We have updated the tutorial using version 1.17.0.

Best regards,
Iwona
