### ISSUE TITLE
Create a Reusable Service

### ISSUE THREAD

**Issue by dirkelko** [SAPDocuments/Issues#607]
Tutorials: https://developers.sap.com/tutorials/cp-cap-java-reusable-service.html
--------------------------
Step 8: Run and test your application
mvn spring-boot:run does not work and results in following error:
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for products-service parent 1.0.0-SNAPSHOT:
[INFO] 
[INFO] products-service parent ............................ SUCCESS [  1.866 s]
[INFO] products-service ................................... FAILURE [ 10.909 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.157 s
[INFO] Finished at: 2021-09-17T08:31:32Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.5.2:run (default-cli) on project products-service: Application finished with exit code: 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :products-service
us

**Comment by iwonahahn** [comment]
Hi @dirkelko,

Sorry for the late reply. Can you please reproduce the issue and provide the full build log by running this command:
`mvn clean install -X > build-output.log`. Please attach the `build-output.log` to this issue for further investigation.  I will need to talk to the dev colleagues about this. Please give me some time to get back to you.

Best regards, 
Iwona

**Comment by dirkelko** [comment]
This seems to happen only with the old version of the tutorial where the project was generated with a different mvn archetype Version. With the current version using version 1.17.0 it works now.
