### ISSUE TITLE
Launchpad: Screenshot Update - new fields- Supported devices

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#61]
Hello,

Scenario URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-new-sapui5.html
Step 2.6: Enter the following values:...
-> New fields are added to select supported devices for the applications which is not there in the old screenshots.
Please update the same.

New Screenshot:
<img width="627" alt="LaunchPad_2" src="https://user-images.githubusercontent.com/66831161/104504534-9b4a5880-5608-11eb-9c35-78b5c188c532.PNG">

Labels to be added:
Landscape label: Landscape label: trail1, trail2, trail3
Sprint Label: SCPTest-2101 
Scenario label: SCPTest-psite 
Prio: low-prio

Thanks,
Shubham Agarwal

**Comment by LindsayBert** [comment]
Updated - you can close this ticket

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

@LindsayBert You have permission to close resolved issues that are assigned to you.
