### ISSUE TITLE
Develop a Fiori App Using the ABAP RESTful Application Programming Model (Managed Scenario)

### ISSUE THREAD

**Issue by welfwalter** [SAPDocuments/Issues#610]
Group: https://developers.sap.com/group.abap-env-expose-cds-travel-model.html
--------------------------

The tutorial is called "Develop a Fiori App Using the ABAP RESTful Application Programming Model (Managed Scenario)" and its description is "Develop a travel booking SAP Fiori application by using the managed approach of the ABAP RESTful Application Programming Model."

But in fact the tutorial ends before the fiori app is really implemented. Only a Fiori preview is shown.
It's ok to end the story at this point (before we leave the ABAP environment) - but then the description should reflect this :)

With regards
 Welf

**Comment by mervey45** [comment]
Hi @welfwalter ,

thank you for your message. We will update the title and description of this group.

Best regards, 
Merve
