### ISSUE TITLE
Create an SAP Cloud Application Programming Model Project for SAP HANA Cloud

### ISSUE THREAD

**Issue by vcanilkumar** [SAPDocuments/Issues#613]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-create-project.html
--------------------------

Write here how you think we can improve the tutorial ...

Created project using command
cds init projectname --add java,hana,mta

I don't see "SAP Hana projects" view in so that I can bind the DB to the service ...any other alternative to bind my DB
![Studio](https://user-images.githubusercontent.com/11570020/134614538-34606da6-b6f5-4228-b4f9-afa011e5a6f5.JPG)
 ?

**Comment by jung-thomas** [comment]
First, this tutorial is for Node.js based CAP yet you created a Java project. So it doesn't seem by the commands you used or the screenshot you shared that this is actually the tutorial you are working on. 

Second, if the HANA view is missing in the Business Application Studio, then most likely your Dev Space is not configured correctly. Please double check the optional tools settings in the Dev Space as described earlier in the tutorial.

**Comment by vcanilkumar** [comment]
Thank you Thomas....Seems some issue with the studio..I have unselected and selected the HANA tools in the config and restarted the workspace and it worked now...also able to generate for java runtime as well....Thanks
