### ISSUE TITLE
Create Behavior and Service in SAP BTP, ABAP Environment

### ISSUE THREAD

**Issue by dungvti** [SAPDocuments/Issues#617]
Tutorials: https://developers.sap.com/tutorials/abap-environment-behavior-definition.html
--------------------------
https://answers.sap.com/questions/13462887/behavior-definition-validation-service-not-availab.html?url_id=text-global-profile-inbox-mod
Could you help me check?

**Comment by mervey45** [comment]
Hi @dungvti , 

is this made in SAP BTP, ABAP Environment? 

Best regards, 
Merve

**Comment by dungvti** [comment]
Thanks 

> Hi @dungvti ,
> 
> is this made in SAP BTP, ABAP Environment?
> 
> Best regards,
> Merve

Sorry for late reply. I've resolved this problem. I'll close this issue.
Best regards.
