### ISSUE TITLE
Kyma : Sub-steps not properly maintained

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#62]
Hello,

Scenario URL: https://developers.sap.com/tutorials/cp-kyma-getting-started.html
Sub-steps are not maintained properly: In step 1, after sub-step 2, we are missing sub-step numbering. 
Somewhere, sub- steps are maintained properly like in step 3, but otherwise its missed.

Please update the tutorial with proper sub-steps for convenient document understanding.

Labels to be added:
Landscape label: Landscape label: trail1, trail2, trail3
Sprint Label: SCPTest-2101
Scenario label: SCPTest-Kyma
Prio: high-prio

Thanks,
Shubham Agarwal

**Comment by KevinMuessig** [comment]
@i353590 sorry for my late reply. I will take a look right a way and will push changes accordingly.

**Comment by KevinMuessig** [comment]
I made the changes needed and they will be reflected in the next update of the tutorial later today.
