### ISSUE TITLE
Create a Slider Custom Control in an MDK App (Using Metadata Approach)

### ISSUE THREAD

**Issue by stesap** [SAPDocuments/Issues#622]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-dev-kit-slider-extension.html
--------------------------

Hi all,

the mentioned tutorial above, doesn't seem to work for me. On an iOS device I get the error "Can't find variable NativeClass"

<img width="720" alt="image" src="https://user-images.githubusercontent.com/57390068/135217118-81cfa43e-4674-4a1a-8e41-95634f375ce3.png">

I guess the error comes from this [code line](https://github.com/SAP-samples/cloud-mdk-tutorial-samples/blob/d2be6b9247a5711d059d3c5b365229c3b4827a1b/6-Create-Extension-Controls-in-Mobile-Development-Kit-Apps/1-Create-a-Slider-Custom-Control-Using-Metadata-Approach/MDK_Slider/Extensions/MySliderModule/controls/MySliderPlugin/ios/MySlider.ts#L15)

I used `Mobile Svcs` app to test it, with version `6.0.1`. 

-Steffen

**Comment by jitendrakansal** [comment]
@stesap i just tested again with Mobile Svcs (6.0.1) on my iOS device (iOS 15), it works as expected.
Can you clone the repo directly and deploy the slider project to test it?
https://github.com/SAP-samples/cloud-mdk-tutorial-samples.git

**Comment by stesap** [comment]
@jitendrakansal I found out that, I still had the `tsconfig.json` file in my project which was removed with the [latest change](https://github.com/SAPDocuments/Tutorials/commit/3e9da9cf8f15f4cd069058b65f3960ed68b99e85#diff-99014191d58c8c252dd7e7e1506c7ca9258629aabbcbcdc61cf657a2e79dd2b5) 

After I removed this file, it's working again. Thanks
