### ISSUE TITLE
Create Business Configuration for Factory Calendar

### ISSUE THREAD

**Issue by GirodFred** [SAPDocuments/Issues#625]
Tutorials: https://developers.sap.com/tutorials/abap-environment-service-binding.html
--------------------------

Hi team,

in the step 4 of the tutorial, where I need to set the log activation for the table, Eclipse does not really appreciate.
-> I have updated Eclipse the 29-sept-2021
-> The error message is : Failed to create the part's  control  
-> My Eclipse screen
<img width="739" alt="Capture d’écran 2021-09-30 à 09 47 26" src="https://user-images.githubusercontent.com/48822355/135409997-0520d957-cfc5-4da3-b03c-ce3f2fe9e060.png">

The project is in the BTP Europe, if you want to try from your side

Best regards
Frederic Girod

**Comment by mervey45** [comment]
Hi @GirodFred , 

do you also added the latest[ ADT]( https://tools.hana.ondemand.com/latest)?

Best regards, 
Merve

**Comment by GirodFred** [comment]
I hope, Eclipse update both at the same time
<img width="533" alt="Capture d’écran 2021-09-30 à 12 57 36" src="https://user-images.githubusercontent.com/48822355/135443216-21c62532-1ff7-40ff-a479-e6a36d268104.png">

**Comment by mervey45** [comment]
Hi @GirodFred ,

I would test it. You can do following: Go to Eclipse > Help > Install New Software and paste follówing: https://tools.hana.ondemand.com/latest/ .
If you have new entries, then install ADT, otherwise you are up to date.

Best regards, 
Merve

**Comment by GirodFred** [comment]
<img width="425" alt="Capture d’écran 2021-09-30 à 13 14 27" src="https://user-images.githubusercontent.com/48822355/135445212-8405bc15-0a53-45f7-9d14-bc4546d0777f.png">
I already have used the "latest" to install it

**Comment by GirodFred** [comment]
I have checked before for another problem :)
And see in a SCN topic, it is better to update all Eclipse before doing the Tutorials 

Fred

**Comment by GirodFred** [comment]
Another little comment, you set 30' time for the Tutorial. No no no :)  more than 30'  maybe 1 hour it will be better :)

**Comment by mervey45** [comment]
Hi @GirodFred ,

thank you for your feedback :) Is your problem solved now?

Best regards, 
Merve

**Comment by GirodFred** [comment]
No, seems to be an Eclipse bug
<img width="484" alt="Capture d’écran 2021-09-30 à 13 44 39" src="https://user-images.githubusercontent.com/48822355/135449306-7ff387ac-82ee-4e2f-95b3-9f68ef2cda00.png">

**Comment by GirodFred** [comment]
I am not locked for this "log" setting. I have finished the tutorial without it.

**Comment by mervey45** [comment]
Hi @GirodFred ,

you can also check all the prerequisites, if your Eclipse have all of them: https://tools.hana.ondemand.com/#abap.

Best regards, 
Merve

**Comment by GirodFred** [comment]
So, the prerequisites
Eclipse plateform Version: 2021-09 (4.21.0)    
WIndows 10 Pro
Java  15.0.2v20210201
SAPGui  7.50  (but: not required to work on SAP BTP ABAP Environnement)
Microsoft Visual C++ 2013 (just installed, reboot, and same result)

**Comment by mervey45** [comment]
Hi @GirodFred, 

then I would recommend to open a ticket. It seems to be a specific problem.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
