### ISSUE TITLE
SAP HANA, XS Advanced - Access an external HTTP service

### ISSUE THREAD

**Issue by ahmedkhan29789** [SAPDocuments/Issues#628]
Tutorials: https://developers.sap.com/tutorials/xsa-xsjs-access-external-service.html
--------------------------

Kindly include scenario of HTTPS external service as in real scenario mainly we use HTTPS services, while trying for HTTPS I am getting this error
![image](https://user-images.githubusercontent.com/22063881/135659154-ec69cdf2-7eee-4f7f-bf54-b29134c9b68a.png)

I have also mentioned the issue in community https://answers.sap.com/questions/13495993/error-500-unable-to-get-local-issuer-certificate-w.html

**Comment by jung-thomas** [comment]
No further development of this tutorial is planned and the current scope of it only includes HTTP. The community is the correct place to ask questions about the scenario using HTTPS.
