### ISSUE TITLE
Kyma - Correct command - remove "shell/bash"

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#63]
Hello,

Scenario URL: https://developers.sap.com/tutorials/cp-kyma-redis-function.html
Step 1.2: Shell/Bash git clone https://github.com/SAP-samples/kyma-runtime-extension-samples

Please mention correct command: remove shell/bash from command

Labels to be added:
Landscape label: Landscape label: trail1, trail2, trail3
Sprint Label: SCPTest-2101
Scenario label: SCPTest-Kyma
Prio: high-prio

Thanks,
Shubham Agarwal

**Comment by jcawley5** [comment]
@thecodester - are the language identifiers no longer supported/working for code blocks?

**Comment by thecodester** [comment]
@jcawley5 The code block is not indented properly -- needs 4 spaces (2 tabs) instead of 3 spaces

**Comment by jcawley5** [comment]
Fixed in qa, will be in prod in next push.
