### ISSUE TITLE
Register for SAP HANA, express edition

### ISSUE THREAD

**Issue by Ngugisenior** [SAPDocuments/Issues#631]
Tutorials: https://developers.sap.com/tutorials/hxe-ua-register.html
--------------------------

the done button is not responding after clicking done

**Comment by JCurrie27** [comment]
Thanks for your feedback. Are you still experiencing the problem? I was not able to reproduce the "Done" button bug in my testing. If you're still encountering problems, could you please post the issue to the HANA Express community Q&A page to take advantage of the community support model? The Q&A page receives much more traffic, and other users may be able to provide answers immediately.

To log your questions on the Q&A page:

1. Go to [https://answers.sap.com/questions/ask.html](https://answers.sap.com/questions/ask.html)
2. Add a Title. Enter your GitHub question in the Fill in the details... form.
3. In Select Primary Tag, search for "express". Select SAP HANA, express edition.
4. Click Submit your Question.
