### ISSUE TITLE
Create an SAP Cloud Application Programming Model Project for SAP HANA Cloud

### ISSUE THREAD

**Issue by GirodFred** [SAPDocuments/Issues#632]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-create-project.html
--------------------------

Hi team, I have an error message when I try to create CAP Project 
The "path" argument must be of type string. Received undefined

Expected 
<img width="828" alt="Capture d’écran 2021-10-04 à 20 47 25" src="https://user-images.githubusercontent.com/48822355/135907254-8ca130f1-1ac4-4433-acf2-9a9dbdb6df5a.png">

Actual 
<img width="803" alt="Capture d’écran 2021-10-04 à 20 47 36" src="https://user-images.githubusercontent.com/48822355/135907288-5af182cb-1e44-444b-a4b2-029444a4b0c5.png">

Best regards
Fred

**Comment by jung-thomas** [comment]
I just ran through the tutorial now and I can not recreate this issue. The wizard works fine.
![image](https://user-images.githubusercontent.com/12159356/135927493-623b0050-4806-497a-819c-b4532a1e0a7a.png)

![image](https://user-images.githubusercontent.com/12159356/135927506-806a8072-9248-4902-8f9c-9e4cea0e3e25.png)

So there does not appear to be any issue with steps of the tutorial or a general issue with the wizard itself. I'd suggest repeating the steps up this point as I can't say what might be going wrong. Perhaps a transitory problem with the wizard itself that is now corrected. There is also an alternative to the graphical wizard already described in the tutorial at this step to use the command line interface instead. You might try following those steps if the problem persists.
