### ISSUE TITLE
Expose Integration Flow Endpoint as API and Test the Flow

### ISSUE THREAD

**Issue by smabdelrahman** [SAPDocuments/Issues#636]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html
--------------------------
 17) says Note: Make sure that you append ?grant_type=client_crendentials to the token URL that you pasted.

the spelling of the variable is incorrect, causing errors: it should be grant_type=client_credentials not grant_type=client_crendentials

After 19) we need to deploy the changes - this is not specified in the tutorial.

**Comment by Karunaharan** [comment]
@smabdelrahman - thanks for catching the minor errors. These are fixed and republished now.
