### ISSUE TITLE
Add the SAP Launchpad Service

### ISSUE THREAD

**Issue by jasonmuzzy** [SAPDocuments/Issues#639]
Tutorials: https://developers.sap.com/tutorials/btp-app-launchpad-service.html
--------------------------

In steps 10 and 12 it is not possible to enter destination cpapp-app-srv.  The generator only shows value "None" and using the arrow keys doesn't show any more options, and it's not possible to enter a value manually.  This destination is properly configured in my mta.yaml.

Additionally, after adding the content to the Launchpad and clicking the Risks app it gives the following error:  "Application could not be started due to technical issues.
File not found"

Please help!

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by jegiraldog** [comment]
Hello, I have the same Issue:
In steps 10 and 12 it is not possible to enter destination cpapp-app-srv. The generator only shows value "None" and using the arrow keys doesn't show any more options, and it's not possible to enter a value manually. 
This destination is properly configured in my mta.yaml.

Thank you for your cooperation

**Comment by smahati** [comment]
@jegiraldog Try to update the extensions and modules if you haven't, also you might need to update the generators which are seprate.

Trigger updates of the generators from VS Code as follows:

* In VS Code, invoke the Command Palette ( View → Command Palette or Shift + Command + P for macOS / Ctrl + Shift + P for Windows) and choose Fiori: Open Application Generator.
* Click on the link "Explore and Install Generators".
* Next to search for Generators input field there is a dropdown called "Search Shortcuts", click on the dropdown and select "SAP Fiori". VS Code should install and updates for generators if available.

Create a new issue if you need further support as this one is closed and you can tage me.

Best regards,
Maha (She/Her)
