### ISSUE TITLE
Kyma - Statement rephrase & add step to click on Create

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#64]
Hello,

Scenario URL: https://developers.sap.com/tutorials/cp-kyma-redis-function.html#c1579029-cff3-43a6-b9ff-116af0477c97

Step 3.6: Choose Add the create a Service Instance of the SAP Commerce Cloud - Events
 rephrase the statement - "the" should be "to" - "Choose Add TO create a service ....."
Also, step to click on "Create" is missing - please add step for the same.

Similarly,
Step 4.4: Choose Add the create a Service Instance of the SAP Commerce Cloud - Commerce Webservices.
-> Replace "the" to "to" & Add a step to click on "Create".

Labels to be added:
Landscape label: Landscape label: trail1, trail2, trail3
Sprint Label: SCPTest-2101
Scenario label: SCPTest-Kyma
Prio: high-prio

Thanks,
Shubham Agarwal

**Comment by jcawley5** [comment]
@thecodester - are the language identifiers for a code block no longer working or supported?

**Comment by jcawley5** [comment]
Thanks for the feedback, fixed in qa and will be pushed in next update.

**Comment by i353590** [comment]
Hi @jcawley5 ,

Thanks for quick update :)

Regards,
Shubham
