### ISSUE TITLE
Implement a Business Add-in (BAdI) To Check a Purchase Requisition

### ISSUE THREAD

**Issue by larshp** [SAPDocuments/Issues#642]
Tutorials: https://developers.sap.com/tutorials/abap-s4hanacloud-procurement-purchasereq-checks.html
--------------------------

under Step 1, looks like an image is missing

![image](https://user-images.githubusercontent.com/5888506/136400019-40a64eda-2ef5-4662-98bd-bf355295971a.png)

I would fix the issue via a pull request but SAP does not accept pull requests

https://github.com/SAPDocuments/Tutorials/blob/master/tutorials/abap-s4hanacloud-procurement-purchasereq-checks/abap-s4hanacloud-procurement-purchasereq-checks.md

**Comment by julieplummer20** [comment]
Hi Lars,
Yikes! 
Thanks for the heads-up.
I'll fix that at once.
Cheers, Julie.
