### ISSUE TITLE
Call an External Endpoint to Retrieve Additional Information

### ISSUE THREAD

**Issue by norikoszilagy** [SAPDocuments/Issues#649]
Tutorials: https://developers.sap.com/tutorials/cp-integration-consume-external-api.html
--------------------------

To create a user credential, we are supposed to provide a client ID, which is not mentioned how to get it or create it.

**Comment by gauthamkrishna-sap** [comment]
Hello,
This tutorial has been deprecated. We will replace it with an updated tutorial in the coming weeks. Please watch out for "Integration Suite tutorials" in the SAP Tutorial Navigator for new updates. 
Thank you.
