### ISSUE TITLE
Kyma - Screenshot Update: One more tab added: Resources

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#65]
Hello,

Scenario URL: https://developers.sap.com/tutorials/cp-kyma-redis-function.html#c1579029-cff3-43a6-b9ff-116af0477c97

Step 6.3: Choose the tab Configuration.
->> screenshot update: one more tab is added: 'Resources'
Please update the tutorial with new screenshot
New screenshot:

<img width="737" alt="Kyma_3" src="https://user-images.githubusercontent.com/66831161/104506893-0184aa80-560c-11eb-8127-029135110d83.PNG">

Labels to be added:
Landscape label: Landscape label: trail1, trail2, trail3
Sprint Label: SCPTest-2101
Scenario label: SCPTest-Kyma
Prio: low-prio

Thanks,
Shubham Agarwal

**Comment by jcawley5** [comment]
Fixed in qa, will be in prod in next push.
