### ISSUE TITLE
Set Up SAP Business Application Studio for Development

### ISSUE THREAD

**Issue by SMG1985** [SAPDocuments/Issues#659]
Tutorials: https://developers.sap.com/tutorials/appstudio-onboarding.html
--------------------------

Write here how you think we can improve the tutorial ...
I have gone through steps 2 end. Question was asked as below should be appropriate to ask after step 3 instead of step2 as in step 3 it has been described.
From which account do you subscribe to SAP Business Application Studio?
Thanks & Regards,
Sweta Gohil.

**Comment by raz-korn** [comment]
THanks @SMG1985.
The update should be visible soon.

Regards - Raz
