### ISSUE TITLE
Kyma - Statement Update: Event triggers

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#66]
Hello,

Scenario URL: https://developers.sap.com/tutorials/cp-kyma-redis-function.html#c1579029-cff3-43a6-b9ff-116af0477c97

6.4: In the Configuration scroll down and choose Event Triggers.
->> Statement should be Choose "Add event triggers" instead of just choose event triggers.
Please update the same.

Labels to be added:
Landscape label: Landscape label: trail1, trail2, trail3
Sprint Label: SCPTest-2101
Scenario label: SCPTest-Kyma
Prio: low-prio

Thanks,
Shubham Agarwal

**Comment by jcawley5** [comment]
Thanks for the feedback, fixed in qa and will be pushed in next update.
