### ISSUE TITLE
Get Started with the SAP BTP Command Line Interface (btp CLI)

### ISSUE THREAD

**Issue by pjcools** [SAPDocuments/Issues#668]
_Tutorials:_ https://developers.sap.com/tutorials/cp-sapcp-getstarted.html
--------------------------

Write here how you think we can improve the tutorial ...

Step: 6 Login to your Global account

I cannot seem to login at all - I always get 

SAP BTP command line interface (client v2.8.0)

CLI server URL [https://cpcli.cf.us10.hana.ondemand.com]>https://cpcli.cf.ap10.hana.ondemand.com
Connecting to CLI server at https://cpcli.cf.ap10.hana.ondemand.com...

Global account subdomain [e712556dtrial-ga]>bournedigitalptyltd-01
User [phil@bournedigital.com.au]>
Password>
You're about to send your credentials to https://cpcli.cf.ap10.hana.ondemand.com for the first time.
Do you trust this server? [no]>yes
Global account 'bournedigitalptyltd-01' not found.

FAILED

Not sure why this is not working. 

Thanks
Phil

**Comment by annawenger20** [comment]
Hi @pjcools , I just noticed that in your case, the problem is not the global accozunt subdomain, but the server url. 
Please change it to https://cpcli.cf.eu10.hana.ondemand.com:

CLI server URL [https://cpcli.cf.us10.hana.ondemand.com]>https://cpcli.cf.eu10.hana.ondemand.com

Kind regards,
Anna
