### ISSUE TITLE
Kyma - Logs not loading: US region

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#67]
Hello,

Scenario URL: https://developers.sap.com/tutorials/cp-kyma-redis-function.html
Step 10.3: Expand the Log view at the button of the function viewer.

LOGS Didn't load even after many refresh of browser.
Specifically in US region

Screenshot:
<img width="956" alt="kyma_5" src="https://user-images.githubusercontent.com/66831161/104510037-95f10c00-5610-11eb-893e-2684858a3753.PNG">

Labels to be added:
Landscape label: Landscape label: trail3
Sprint Label: SCPTest-2101
Scenario label: SCPTest-Kyma
Prio: high-prio

Thanks,
Shubham Agarwal

**Comment by jcawley5** [comment]
The log viewer is not shown until you click the up arrow at the bottom middle of the screen. Can you please recheck?

**Comment by i353590** [comment]
Hello @jcawley5,

yes, I tried that also... Since I have tried the same scenario in other regions as well, it worked fine in other regions.
But anyways, I tried once again, the logs are shown now.  Logs appeared a bit late maybe.

Thanks,
Shubham
