### ISSUE TITLE
Add the SAP Launchpad Service

### ISSUE THREAD

**Issue by ceedee666** [SAPDocuments/Issues#679]
Tutorials: https://developers.sap.com/tutorials/btp-app-launchpad-service.html
--------------------------
In order for step 10 do work I also had to install Yeoman using the following command:
```
npm i -g yo
```
Maybe this info should be added to step 8.

**Comment by slavipande** [comment]
Hi @ceedee666 ,

Thanks for your feedback.

The instruction to install Yeoman is already part of the section [Set Up Local Development Using VS Code](https://developers.sap.com/tutorials/btp-app-set-up-local-development.html#bb1c3630-6d3b-41d2-a177-63208247fd7d) which is a prerequisite for the tutorial [Add the SAP Launchpad Service](https://developers.sap.com/tutorials/btp-app-launchpad-service.html).

Hope this helps.

Best regards,
Svetoslav

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
