### ISSUE TITLE
Kyma - Environment slow - Region specific - Feedback

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#68]
Hello,

Tutorial: https://developers.sap.com/mission.cp-kyma-build-app.html

- Enabling Kyma : Takes a lot of time for the kyma to get enabled for the subaccount.

- https://developers.sap.com/tutorials/cp-kyma-mocks.html -> Step 3.2: Open the mock application in the browser by choosing the HOST value ->> The application took too much time to load in EU region specifically.

- Not enough permissions -->>sometimes, if i refresh the application, it suddenly says not enough permissions even after role collection was created and application was working fine few minutes before. After sometime, the issue gets resolved automatically.

- https://developers.sap.com/tutorials/cp-kyma-redis-function.html : Step 2.1: In the Kyma home workspace, choose Integration > Applications/Systems.  -->> Took too much time in EU and US region while it worked smooth in AP region (same network strength).

- Similarly, Step 3.3: Within the dev namespace, choose Service Management > Catalog. -->> Took too much time to load, worked fine in AP region.

Please have a look once if their is some issue with the system or a temporary issue since it worked fast & smooth in AP region.

Labels to be added:
Landscape label: Landscape label: trail1, trail2, trail3
Sprint Label: SCPTest-2101
Scenario label: SCPTest-Kyma
Prio: low-prio

Thanks,
Shubham Agarwal

**Comment by jcawley5** [comment]
Please report issue on Kyma runtime git.
