### ISSUE TITLE
Configure and Run a Predefined SAP Continuous Integration and Delivery (CI/CD) Pipeline

### ISSUE THREAD

**Issue by SMG1985** [SAPDocuments/Issues#687]
Tutorials: https://developers.sap.com/tutorials/btp-app-ci-cd-btp.html
--------------------------

When I try to follow Step 4 getting following error. Role collection already assigned.
Failed to load repositories.
You do not have required privileges to execute requested action.
Forbidden

**Comment by iwonahahn** [comment]
Hi @SMG1985,

We haven't heard from you in a while, so we are closing the issue. If you still have questions, feel free to open a new issue.

Best regards,
Iwona
