### ISSUE TITLE
Deploy Your Multi-Target Application (MTA)

### ISSUE THREAD

**Issue by I501000** [SAPDocuments/Issues#689]
Tutorials: https://developers.sap.com/tutorials/btp-app-cap-mta-deployment.html![image](https://user-images.githubusercontent.com/74337345/138439579-df040db9-3e9e-4934-addd-6d2debcf6ffe.png)--------------------------

It is a great tutorial write by you in the following linkage !  I following the steps and come to deploy step . But the app cpapp-db-deployer deloy failed .  I can not find the table in database cpapp-db .  I would be very appreciated if you could give some input on this .

![2021-10-22_1](https://user-images.githubusercontent.com/74337345/138440090-edfe3c78-483d-414b-bd4b-2b8fdc459167.jpg)

![2021-10-22_4](https://user-images.githubusercontent.com/74337345/138440190-b08fd233-89b9-453d-a5de-ffcdccd31ffd.jpg)

![2021-10-22_2](https://user-images.githubusercontent.com/74337345/138440225-1bb2bf61-6087-4979-8df0-c2f780f03e43.jpg)
![2021-10-22_3](https://user-images.githubusercontent.com/74337345/138440248-b5e84b9c-0801-4aa7-acbf-42d2c2c3f420.jpg)
`## Generated mta.yaml based on template version 0.4.0
## approuter=
_schema-version: "3.1"
ID: cpapp
version: 1.0.0
description: "A simple CAP project."
parameters:
  enable-parallel-deployments: true

build-parameters:
  before-all:
    - builder: custom
      commands:
        - npm install --production
        - npx -p @sap/cds-dk cds build --production
        - npx rimraf gen/db/src/gen/data

modules:
  # --------------------- SERVER MODULE ------------------------
  - name: cpapp-srv
    # ------------------------------------------------------------
    type: nodejs
    path: gen/srv
    parameters:
      buildpack: nodejs_buildpack
    requires:
      # Resources extracted from CAP configuration
      - name: cpapp-db
      - name: cpapp-uaa
    provides:
      - name: srv-api # required by consumers of CAP services (e.g. approuter)
        properties:
          srv-url: ${default-url}

  # -------------------- SIDECAR MODULE ------------------------
  - name: cpapp-db-deployer
    # ------------------------------------------------------------
    type: hdb
    path: gen/db
    parameters:
      buildpack: nodejs_buildpack
    requires:
      # 'hana' and 'xsuaa' resources extracted from CAP configuration
      - name: cpapp-db
      - name: cpapp-uaa

resources:
  # services extracted from CAP configuration
  # 'service-plan' can be configured via 'cds.requires.<name>.vcap.plan'
  # ------------------------------------------------------------
  - name: cpapp-db
    # ------------------------------------------------------------
    type: com.sap.xs.hdi-container
    parameters:
      service: hana # or 'hanatrial' on trial landscapes
      service-plan: hdi-shared
    properties:
      hdi-service-name: ${service-name}
  # ------------------------------------------------------------
  - name: cpapp-uaa
    # ------------------------------------------------------------
    type: org.cloudfoundry.managed-service
    parameters:
      service: xsuaa
      service-plan: application
      path: ./xs-security.json
      config:
        xsappname: cpapp-${space} #  name + space dependency
        tenant-mode: dedicated
        role-collections:
          - name: "RiskManager-${space}"
            description: Manage Risks
            role-template-references:
              - $XSAPPNAME.RiskManager
          - name: "RiskViewer-${space}"
            description: View Risks
            role-template-references:
              - $XSAPPNAME.RiskViewer
`

**Comment by iwonahahn** [comment]
Hi @I501000,

Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 
If you still have questions, feel free to reopen the issue.

Best regards,
Iwona

**Comment by manasranjanmohanta** [comment]
Hello,
I am also facing the same issue, can anyone help me?

**Comment by smahati** [comment]
Hi @manasranjanmohanta,

If the DB tables are missing it means that the db deployer failed to run correctly or that the database was somehow deleted.

Could you please do the following and share if the issue still persists:

- Check if your HANA Instance is running, as noted after the deploy command in [Step 8](https://developers.sap.com/tutorials/btp-app-cap-mta-deployment.html#60b95fff-2d95-41bd-8e61-f2a417fdbd9d).
- Please retry the deployment and if you get the same error again, get the logs with this command: `cf logs cpapp-db-deployer --recent`.
- Share the logs here so we can investigate further. Please add it  in a new issue so that we can track it.

We will be looking forward to your kind reply.

Best regards,
Mahati
