### ISSUE TITLE
LOD-BPM-PVS - Trial Account Problems

### ISSUE THREAD

**Issue by IsabellaMasselli** [SAPDocuments/Issues#69]
LOD-BPM-PVS Please assist with the following as suggested below:-

Can you please raise a ticket on LOD-BPM-PVS component. This could be a product issue or an issue with your trial account. The dev teams might need your cloud account details to look into it and update your account if needed. 

Details of issue are as follows:-

Tutorial: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-5-run.html

Write here what you need help with ... This is the second time I have logged this issue. It was previously closed (Closed #6104.) as I did not have the time to check whether it had been fixed..

I get all the way passed the successful Importing of the EmployeeOnboardingEvents JSON file but when I try to filter it there is no file to be found so I cannot continue with the tutorial.

Thanks for your support

**Comment by ArchanaShukla** [comment]
@IsabellaMasselli - Have you raised a BCP ticket on LOD-BPM-VIS component?

**Comment by IsabellaMasselli** [comment]
I have raised a LOD-BPM-VIS component issue on this forum, I don't think I have access to BCP??

**Comment by ArchanaShukla** [comment]
@IsabellaMasselli - We checked internally on many other trial accounts and we did not face the issue. Can you check and confirm (a) if the name you are using to search is "onboard" (without quotes and without any leading or trailing spaces) and (b)  click on the Errors tab, to see if there were any issues while importing the events.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
