### ISSUE TITLE
Configure Business Rules, Workflow and Process Visibility

### ISSUE THREAD

**Issue by JFUD66** [SAPDocuments/Issues#696]
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-configure.html
--------------------------

Hello, I´m havin problems trying to set mu SAP Buisiness Rules Service because when I import a Rule as the instructions said, I got an error:
![image](https://user-images.githubusercontent.com/93174375/138804771-e1c55b79-49de-4724-9086-ee2b5dcec966.png)
![Captura2](https://user-images.githubusercontent.com/93174375/138805443-6352a834-b4a7-4001-87e9-9c2360bc9592.JPG)

I got an error -> Invalid gateway
...

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
