### ISSUE TITLE
Create a Basic Flow with a SOAP Endpoint

### ISSUE THREAD

**Issue by davidsmith288** [SAPDocuments/Issues#698]
Tutorials: https://developers.sap.com/tutorials/cp-integration-create-basic-flow.html
--------------------------

In the prerequisites, there is no step 6 in the Integration Suite onboarding Tutorial.  How do we assign the ESBMessaging.send role to the calling user?

**Comment by gauthamkrishna-sap** [comment]
Hello,
This tutorial has been deprecated. We will replace it with an updated tutorial in the coming weeks. Please watch out for "Integration Suite tutorials" in the SAP Tutorial Navigator for new updates. 
Thank you.
