### ISSUE TITLE
Deploy the Fiori App to Cloud Foundry

### ISSUE THREAD

**Issue by timcashmore** [SAPDocuments/Issues#7]
Tutorial: https://developers.sap.com/tutorials/sapui5-fiori-cf-deploy.html
--------------------------

Followed this tutorial exactly.  The newly created app does not appear in the HTML5 application repo when trying to add to the fiori launchpad service in cloud foundry (in SAP Trial account) - when accessing from the Launchpad service.
I have installed the cf-html5-apps-repo-cli-plugin in order to list the apps deployed in the repo and it is listed in there but shown as 'private' - not sure what the implications are, but the other apps that are generated by SAP BAS are shown as public ?  Maybe the yo eaasy-ui5 template generator has changed or something -> the platform option is: 'Fiori Launchpad on Cloud Foundry' which is slightly different to the tutorial.

Below is th eoutput from cf html5-list command at the terminal - one app from BAS (first one which can be seen in the repository) and the second one from the tutorial using yo easy-ui5.

nsApp              1.0.0     7701f9e5-20c7-4894-9482-4a51596d3c32   launchpad-html5-app-host-service   public       Mon, 21 Dec 2020 10:43:52 GMT
tutorialproducts   1.0.0     3bc7c748-9c8a-47ab-a3e9-82b83172e4cf   products_html5_repo_host           private      Mon, 21 Dec 2020 11:28:45 GMT

ANy thoughts would be greatly appreciated (am trying to reconfigure my standalone app to be accessible from the launchpad)

**Comment by IObert** [comment]
This difference comes from the property `sap.cloud` in the `manifest.json`. Other generators might use the `public` flag here while easy UI5 doesn't use it (changing the visibility wouldn't contribute much to the overall tutorial).

In both cases, the launchpad app should be accessible from the launchpad. Can you please try to reproduce the issue?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
