### ISSUE TITLE
Add a User Task to Your Workflow and Deploy - Outdated Screen and Option

### ISSUE THREAD

**Issue by Ralphive** [SAPDocuments/Issues#70]
Tutorial: https://developers.sap.com/tutorials/cp-workflow-3-add-usertask-cf.html
--------------------------

On Step 5.8 there is new option "Start New Instance and Close" that should be prefered. Otherwise user stays with the dialog open. Screenshot below
![image](https://user-images.githubusercontent.com/9930965/104586773-d460e800-565d-11eb-8799-eb201c1c515c.png)

Thank you! 🙂

**Comment by AstridHerbst** [comment]
Hi,
Thanks for your input. The tutorial is now updated at: https://developers.sap.com/tutorials/cp-workflow-3-add-usertask-cf.html#ca52591c-cc90-47bc-b59a-644a9cc7a4b0

Best regards,
Astrid
