### ISSUE TITLE
Not able to run app , unauthorized 403 - cap MTA Exercise 4 , as part of bootcamp for extension suite  

### ISSUE THREAD

**Issue by chavadiyil21** [SAPDocuments/Issues#700]
Fails in kibbana logs for the Application: capapp1-app - Logs

27 Oct 2021, 02:02:36 (GMT+05:30) - [RTR/0]
6xxxxxtrial-dev-capapp1-app.cfapps.us10.hana.ondemand.com - [2021-10-26T20:32:36.026880963Z] "GET /favicon.ico HTTP/1.1" 403 0 9 "https://6xxxxxxtrial-dev-capapp1-app.cfapps.us10.hana.ondemand.com/index.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36" "-" "10.32.1.9:61089" x_forwarded_for:"-" x_forwarded_proto:"https" vcap_request_id:"65d278ca-8b0a-43bc-536b-c5cea9a5d4fb" response_time:0.014379 gorouter_time:0.000071 app_id:"9738b6ba-7f13-422d-a787-b9772834aeec" app_index:"0" instance_id:"383c8c18-63f7-4ae5-6508-a0a0" x_cf_routererror:"-" x_correlationid:"-" tenantid:"-" sap_passport:"-" x_scp_request_id:"8811a64c-115e-4c2d-bc4a-d1a169168397-617865E3-3D09A4" x_cf_app_instance:"-" x_forwarded_host:"-" x_custom_host:"-" x_ssl_client:"-" x_ssl_client_session_id:"-" x_ssl_client_verify:"-" x_ssl_client_subject_dn:"-" x_ssl_client_subject_cn:"-" x_ssl_client_issuer_dn:"-" x_ssl_client_notbefore:"-" x_ssl_client_notafter:"-" x_b3_traceid:"87acade76c8ffdb4" x_b3_spanid:"87acade76c8ffdb4" x_b3_parentspanid:"-" b3:"87acade76c8ffdb4-87acade76c8ffdb4"

![image](https://user-images.githubusercontent.com/92533509/138958478-047a4f93-8dbc-4ab4-a88b-b35f57606c94.png)

![image](https://user-images.githubusercontent.com/92533509/138958546-0e7d3428-a01e-4fd9-a27c-7f61f10855b9.png)

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
