### ISSUE TITLE
Let Customers Ask Chatbot for Shipping Price

### ISSUE THREAD

**Issue by MarvinSzyperski** [SAPDocuments/Issues#701]
Tutorials: https://developers.sap.com/tutorials/cai-bot-shipping-3-price-parcel.html
--------------------------
Step 1 Point 2:
It says, the user should download a .csv file from https://raw.githubusercontent.com/SAPDocuments/Tutorials/master/tutorials/cai-bot-shipping-3-price-parcel/parcel-sizes.csv[]
This .csv and the folder `cai-bot-shipping-3-price-parcel` does not exist anymore.

Same for Tutorial: https://developers.sap.com/tutorials/conversational-ai-faq-chatbot-beginner.html#
Step 2: 
Requires https://github.com/SAPDocuments/Tutorials/raw/master/tutorials/conversational-ai-faq-chatbot-beginner/HowToBuildAChatbot.csv 

And for Tutorial: https://developers.sap.com/tutorials/conversational-ai-faq-chatbot-beginner.html
Step 2:
https://github.com/SAPDocuments/Tutorials/raw/master/tutorials/conversational-ai-faq-chatbot-beginner/HowToBuildAChatbot.csv

**Comment by thecodester** [comment]
@MarvinSzyperski I have updated and fixed -- the second and third files listed seem to be the same. Did I misread? Did you just copy that twice? Let me know and feel free to reopen.
