### ISSUE TITLE
Launchpad Site - Change in steps to add role to a user

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#703]
Hello,

Tutorial Link: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html
Step 2: Add yourself to the Launchpad_Admin role

Since we can't assign roles to a user from Trust configuration now, the 'default identity provider' option will also be disabled, the steps are changed (as we have to add the roles either from Users/Role collections tab now)

Please update the steps and the relevant screenshots with the latest ones.

Screenshot for reference:
![image](https://user-images.githubusercontent.com/66831161/141351888-e9fdc88b-db8d-4d4f-af8b-cec92bfff7e1.png)

Labels to be added:
Sprint Label: SCPTest-2111A
Landscape Labels: SCPTest-trail2, SCPTest-trail3
Scenario Label: SCPTest-psite
prio: high-prio

Thanks,
Shubham

**Comment by LindsayBert** [comment]
Hi - this has already been done and it was published on Wednesday.

Thanks Lindsay

**Comment by i353590** [comment]
Hello @LindsayBert,

I can see the scenario has been updated with the changes. Thanks for the fix.
We can close the issue.

Regards,
Shubham

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
