### ISSUE TITLE
Define and Expose a CDS-Based Travel Data Model

### ISSUE THREAD

**Issue by farozan1996** [SAPDocuments/Issues#72]
Tutorial: https://developers.sap.com/tutorials/abap-environment-data-model.html
--------------------------

In the Step4. Create Service Binding:
Observation: After the 3rd step: Click Finish to use your transport request. 
Step missing: To activate the service binding. 
The "publish" button will only then be enabled which is required for the next step.

Labels :
Landscape Labels: trail1, trail2
SCPTest-fabap : Develop a Fiori App Using ABAP
Label: SCPTest-2101
Priority label : 'Medium'

Thanks and Regards,
Farozan

**Comment by mervey45** [comment]
Hi @MamathaKH ,

this will be updated with following merge: #6422.
@MichaelCzcz can you merge?

Thank you.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
