### ISSUE TITLE
Create an Analytical Dashboard via UI5 Web Components for React

### ISSUE THREAD

**Issue by cuevasDev** [SAPDocuments/Issues#76]
Tutorial: https://developers.sap.com/tutorials/ui5-webcomponents-react-dashboard.html
--------------------------

Write here what you need help with ...
In AnalyticalTable Component, is it not possible to pass filterable property as prop per columns ?, because if you can only pass as props in AnalyticalTable Component, all columns would be filterable, but in case we want only one or two specific columns to be filterable?

**Comment by Lukas742** [comment]
Hi @cuevasDev 

as mentioned [here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable--default-story#column-properties), you can pass `disableFilters` to the corresponding column configuration in the `columns` array. 

I prepared a [codesandbox](https://codesandbox.io/s/fast-water-1ddd9?file=/src/App.js) that demonstrates this behavior.

**Comment by Lukas742** [comment]
I'm going to close this issue. 
If there are any more questions, or something is unclear, please feel free to create another issue here or directly in the [UI5 Web Components for React repo](https://github.com/SAP/ui5-webcomponents-react).
