### ISSUE TITLE
Consume API Services and Call Webhooks from Your Chatbot

### ISSUE THREAD

**Issue by faebulicious** [SAPDocuments/Issues#77]
Tutorial: https://developers.sap.com/tutorials/conversational-ai-webhook-api-call.html
--------------------------

In Step 3 the API Service Configuration has to retrieve Data using GET instead of the default value POST. This is mentioned CORRECT in the text, but not in the Printscreen.

**Comment by thecodester** [comment]
Updated. Thanks for the feedback 👍 

https://github.com/SAPDocuments/Tutorials/commit/db5a19f57d442d8086fa83dfa7599ecff497843f
