### ISSUE TITLE
Create a Business Service with Node.js Using Visual Studio Code

### ISSUE THREAD

**Issue by cuevasDev** [SAPDocuments/Issues#78]
Tutorial: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html
--------------------------

Write here what you need help with ...
It is not an issue, just a recommendation. To explore the SQLite database can be used this extension:
Name: SQLite
Id: alexcvzz.vscode-sqlite
Description: Explore and query SQLite databases.
Version: 0.10.1
Publisher: alexcvzz
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=alexcvzz.vscode-sqlite

**Comment by iwonahahn** [comment]
Hi @cuevasDev,

Thank you for your suggestion. Users have their own preferences for extensions therefore we only recommend extensions that are required to run the tutorial. As this is not an issue, we can close it.

Best regards,
Iwona
