### ISSUE TITLE
Create a Reusable Service

### ISSUE THREAD

**Issue by mts2605** [SAPDocuments/Issues#79]
Tutorial: https://developers.sap.com/tutorials/cp-cap-java-reusable-service.html
--------------------------
Step 5 - npm install --save-dev sqlite3

When trying this i get this error.

Please advice.
_
0 info it worked if it ends with ok
1 verbose cli [ '/opt/nodejs/node-v10.23.0-linux-x64/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   'sqlite3' ]
2 info using npm@6.14.8
3 info using node@v10.23.0
4 verbose npm-session 2174f55bb8240ee7
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 timing stage:rollbackFailedOptional Completed in 1ms
8 timing stage:runTopLevelLifecycles Completed in 18ms
9 verbose stack Error: Failed to parse json
9 verbose stack Unexpected token p in JSON at position 1 while parsing near 'npm install --save-de...'
9 verbose stack     at parseError (/opt/nodejs/node-v10.23.0-linux-x64/lib/node_modules/npm/node_modules/read-package-json/read-json.js:470:11)
9 verbose stack     at parseJson (/opt/nodejs/node-v10.23.0-linux-x64/lib/node_modules/npm/node_modules/read-package-json/read-json.js:105:26)
9 verbose stack     at /opt/nodejs/node-v10.23.0-linux-x64/lib/node_modules/npm/node_modules/read-package-json/read-json.js:52:5
9 verbose stack     at /opt/nodejs/node-v10.23.0-linux-x64/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:123:16
9 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
10 verbose cwd /home/user/projects/products-service
11 verbose Linux 5.4.0-4-cloud-amd64
12 verbose argv "/opt/nodejs/node-v10.23.0-linux-x64/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "sqlite3"
13 verbose node v10.23.0
14 verbose npm  v6.14.8
15 error code EJSONPARSE
16 error file /home/user/projects/products-service/package.json
17 error JSON.parse Failed to parse json
17 error JSON.parse Unexpected token p in JSON at position 1 while parsing near 'npm install --save-de...'
18 error JSON.parse Failed to parse package.json data.
18 error JSON.parse package.json must be actual JSON, not just JavaScript.
19 verbose exit [ 1, true ]

**Comment by iwonahahn** [comment]
Hi @mts2605,

Please try the provided solution [here](https://github.com/SAPDocuments/Tutorials/issues/6240#issuecomment-734740827) and let us know if this works for you.

Best regards,
Iwona

**Comment by mts2605** [comment]
It did, finally I got the sqlite;-)
Thanks.
