### ISSUE TITLE
Define a Simple Data Model and OData Service with CDS

### ISSUE THREAD

**Issue by fjcarrasco** [SAPDocuments/Issues#81]
Hello. In tutorial  https://developers.sap.com/tutorials/odata-05-data-model-service.html  step 11 when create the database, I'm getting this error:

![image](https://user-images.githubusercontent.com/77397326/104916357-3ab57580-5992-11eb-8fc8-294da5260f45.png)

Thanks

**Comment by qmacro** [comment]
Thanks for the notification, @fjcarrasco , I'll look into it.

**Comment by qmacro** [comment]
Hi again @fjcarrasco - given the renaming trigger this week, this tutorial group will be reworked and also moved from Web IDE to App Studio, at the same time. As such, the context of this error will sadly (happily?) disappear. Would you mind therefore if we close this issue? Please expect the new versions for App Studio to appear over the next weeks. Thanks. DJ.

**Comment by fjcarrasco** [comment]
Ok @qmacro thanks for your answer. I'll wait for new versions.
