### ISSUE TITLE
Set Up SAP Cloud Platform Launchpad Service

### ISSUE THREAD

**Issue by jberthe** [SAPDocuments/Issues#82]
Tutorial: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html
--------------------------

Hello, 

I try to activate the service Launchpad, but in the subscription part, there is no Launchpad. 
![image](https://user-images.githubusercontent.com/6067155/104931365-9689f980-59a6-11eb-9a3c-23deb95769de.png)

I think I am on the correct subaccount :
![image](https://user-images.githubusercontent.com/6067155/104931446-b4575e80-59a6-11eb-9754-3e7787d75830.png)

Can you advice ?
Regards,
Joseph

**Comment by LindsayBert** [comment]
Hi - please make sure that you are using the **Launchpad** trial account and that you have assigned yourself to the Launchpad_Admin role.

Thanks
Lindsay

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
