### ISSUE TITLE
Create an SAP HANA Database Project

### ISSUE THREAD

**Issue by renatogandara** [SAPDocuments/Issues#83]
Tutorial: https://developers.sap.com/tutorials/hana-cloud-create-db-project.html
--------------------------

Write here what you need help with ...
during the Step 4: Deploy the database module > https://developers.sap.com/tutorials/hana-cloud-create-db-project.html
I did as the tutorial are indicating but for me i have this message erro when i execute the step 4 
Error: HDI make failed
(1s 847ms)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deploy@ start: `node node_modules/@sap/hdi-deploy/deploy.js "--exit"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deploy@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-01-18T17_31_39_957Z-debug.log

**Comment by jung-thomas** [comment]
Is that the whole log?  I seems like there should be more details in the log as the root of the error.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
