### ISSUE TITLE
Set Up Workflow Management in Cloud Cockpit

### ISSUE THREAD

**Issue by TrinidadMG** [SAPDocuments/Issues#84]
Tutorial: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-1-setup.html
--------------------------

Hi,
I have run the Booster to have all the Workflow configuration required in my SCP Trial account but it fails at the Destinations step. I have tried to run it several times but always fails at the Destinations creation.

BUSINESSRULES_APIHUB and WM_CF_SPACE_PROVIDER Destinations are created.

**There is an error on the creation of the BUSINESS_RULES Destination**. See screen captures.

My trial account is 059820e6trial.

What can I do to fix it? 
Could I create it by hand? 
There is some client secret authentication required for that destination (I checked a colleague Destination).
Please let me know if there is a document that could allow me to create it by hand or you can fix my account problem.

Thanks,
Trinidad.

![Workflow_Dest_Fail_1](https://user-images.githubusercontent.com/18447094/105006864-81a97680-5a37-11eb-987f-97e866319bb1.png)
![Workflow_Dest_Fail_2](https://user-images.githubusercontent.com/18447094/105006867-82420d00-5a37-11eb-8595-0fb2a9c9f2fc.png)

**Comment by TrinidadMG** [comment]
I also created a support incident: https://support.wdf.sap.corp/sap/support/message/2180037363 
Got some details to manually create the BUSINESS_RULES destination.
I have created the destination and I'll check if Workflow works now.

**Comment by ArchanaShukla** [comment]
@TrinidadMG - sometimes trying one more time solves the problem. There are some issues with the destinations on old accounts. To unblock yourself, you can also create the BUSINESS_RULES destination manually with OAuthClientCredential flow using information from business rules service instance. 

@MichaelCzcz - please close the ticket.

**Comment by ArchanaShukla** [comment]
@TrinidadMG - closing the issue. If you face any further then reopen it.

**Comment by TrinidadMG** [comment]
Hi Archana,
Why are you closing the issue? It is not solved yet...
Thanks,
Trinidad.

**Comment by ArchanaShukla** [comment]
@TrinidadMG - you have already raised a BCP ticket on it and you already mentioned "Manually creating the Destination did the trick, my workflow seems to be fully working now." - I also requested to try out the booster again. Can you please let me know what else needs to be solved ?

**Comment by TrinidadMG** [comment]
Really sorry, I answered the wrong github issue... 
You can close this one.

Thanks,
Trinidad.
