### ISSUE TITLE
Get Started with SAP API Management

### ISSUE THREAD

**Issue by I027876** [SAPDocuments/Issues#85]
Group: https://developers.sap.com/group.cp-apim-code-1.html
--------------------------

Thanks for the tutorial group. I am new to SCP and API Management and was able to complete the tutorials in the group. Now i am wondering how can i consume my API proxies, are there plans to add a tutorial to this group, for example how to consume Applications (API Proxy) as a Developer in a sample SAPUI5 project using Business Application Studio tools? I thought there was one at the end of this tutorial group for WebIDE but has been removed?

Many thanks,
Julia

**Comment by Karunaharan** [comment]
Hi Julia,
We don't have a tutorial in place to explain how to consume the API (or API proxies). But we have the detailed product documentation that will help you understand how to consume APIs from a developer's perspective. Sharing some useful links here.

What is API Management - https://help.sap.com/viewer/66d066d903c2473f81ec33acfe2ccdb4/Cloud/en-US/0aef7634df25497896abf18faac8a1ce.html 

Consuming APIs - https://help.sap.com/viewer/66d066d903c2473f81ec33acfe2ccdb4/Cloud/en-US/dd6d58c1586a4a0a8ffca46a1a019d38.html 

I hope this helps.
