### ISSUE TITLE
Develop and Run SAP Fiori Application With SAP Business Application Studio

### ISSUE THREAD

**Issue by I027876** [SAPDocuments/Issues#86]
Tutorial: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html
--------------------------

Is it possible to link a final tutorial to show how the deployed app in SCP ABAP runtime can be consumed by user. The end of the tutorial includes a step to redeploy in Business Application Studio to get the URL (this is working) but how can i access this application in a more user friendly way from SCP? Is it available on some launchpad if i have the new business catalog assigned to my user? I assigned the new business catalog to a business role and then to my user but there is no new tile on the ABAP instance Fiori Dashboard showing this app. How can users subscribe to this app deployed on SCP ABAP?

Many thanks,
Julia

**Comment by mervey45** [comment]
Hi @I027876 ,

in step 9.3 you see the final link with the result (9.6). The assignement is only for your user, since we use a trial system here. The users won't be able to subscribe this app on SCP ABAP since it is a trial system.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
