### ISSUE TITLE
Inspect and Test the API Proxy

### ISSUE THREAD

**Issue by rvodela** [SAPDocuments/Issues#87]
Tutorial: https://developers.sap.com/tutorials/cp-apim-shoppingfresh-inspect-apiproxy.html
--------------------------
If possible can you kindly provide the scripts including preconditions in a text format 
Best regards
Ramesh

**Comment by shilpavij** [comment]
We have decommissioned this tutorial and are in the process of revamping them hence closing this issue as of now.
