### ISSUE TITLE
Inspect and Test the API Proxy

### ISSUE THREAD

**Issue by rvodela** [SAPDocuments/Issues#88]
Tutorial: https://developers.sap.com/tutorials/cp-apim-shoppingfresh-inspect-apiproxy.html
--------------------------

The following blog is much better approach please ignore my earlier issue
https://blogs.sap.com/2016/10/11/sap-api-management-mash-api-proxy/

**Comment by shilpavij** [comment]
We have decommissioned this tutorial and are in the process of revamping them hence closing this issue as of now.
