### ISSUE TITLE
Install the Kubernetes Command Line Tool

### ISSUE THREAD

**Issue by iwonahahn** [SAPDocuments/Issues#89]
Tutorial: https://developers.sap.com/tutorials/cp-kyma-download-cli.html
--------------------------

In step 3 you are saying: "Please note that the `kubeconfig` has an expiration and will have to be re-download once it expires." 

Can you please add a note of how long the downloaded `kubeconfig` can be used?

Thanks a lot and best regards,
Iwona

**Comment by jcawley5** [comment]
Hi Iwona,

Thanks for the feedback. This will be included in the next push to production.
