### ISSUE TITLE
Deploy Commerce Mock Application in the Kyma Runtime

### ISSUE THREAD

**Issue by mounikat987** [SAPDocuments/Issues#90]
Tutorial: https://developers.sap.com/tutorials/cp-kyma-mocks.html
--------------------------

Landscape label: trail1 & trail2 & ap
Priority : High-prio

**Step 2: Apply resources to Kyma runtime**

Apply the APIRule of the mock application to the dev Namespace by choosing the Deploy new resource option, using the Browse option to choose the xf.yaml file, and finally choosing Deploy. The APIRule exposes the resource to the Internet.

You can find the file at at /SAP-samples/xf-application-mocks/commerce-mock/deployment/xf.yaml.

**Actual Result** : 

The file name has to be "kyma.yaml" not "xf.yaml" inside deployment folder.

Please update accordingly.

Thanks
Mounika

**Comment by jcawley5** [comment]
Hi Mounika,

Thank you. This is fixed in QA and will be updating to prod later this week.

**Comment by mounikat987** [comment]
Hi @jcawley5 ,

Could you please prioritize this & update document by EOD today?
since we have this scenario to be executed in d-kom hands-on session that's going to happen tomorrow in India.


Thanks
Mounika

**Comment by jcawley5** [comment]
Added the xf.yaml file back temporarily until the tutorial is updated.
