### ISSUE TITLE
Create a Basic Workflow in SAP Business Application Studio

### ISSUE THREAD

**Issue by mendesthi** [SAPDocuments/Issues#91]
Tutorial: https://developers.sap.com/tutorials/cp-workflow-2-create-module-cf.html
--------------------------
Hi there,

Issue on the step 3 - BAS cannot open the Workflow editor.
I have raised an internal ticket to support, if somebody can look at it: 2180040662

Problem description:
BAS cannot load embedded editor functionality for the Workflow.

It was working good until yesterday, I could edit my workflow using the workflow embedded editor, but started throwing bellow this morning.
 
The error message pops as a "Notification" in BAS:
"The embedded editor functionality failed to load. This could happen due to bad connectivity or loading errors. Please check the browser console logs for more information."

Steps to reproduce the issue(incl. used master data and/or business documents numbers):

Open the web browser;
Browse to https://2bffd846trial.eu10cf.trial.applicationstudio.cloud.sap/index.html#ws-csrd9
Right click file "/home/user/projects/onboarding/approvals/workflows/onboard.workflow"
Click "Open With"
The only option available is "Code Editor", it should allow to edit using the workflow editor.
Additional information to reproduce the issue, e.g. server, browser version, operating system, ...

Thanks,
Thiago.

**Comment by AstridHerbst** [comment]
Hi Thiago,

I have just learned that the issue has been solved and that the workflow editor should work again on Trial SBAS. Please let me know should the error persist. 

Regards, Astrid
