### ISSUE TITLE
Set Up Business Rules for Determining Equipment

### ISSUE THREAD

**Issue by TrinidadMG** [SAPDocuments/Issues#92]
Tutorial: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-businessrules.html
--------------------------

I'm following this tutorial, Step 3: Import business rules.

**After selecting the Equipment Determination Rules, as soon as I press the Import button an error is shown saying "An error has occurred. Contact technical support." What can be done to fix that problem?**
I have tried several times.

The BUSINESSRULES_APIHUB destination seems to be correct. Check Connection returns 200 OK.
**I'm not sure how to check if my account has "Two factor authentication" activated, maybe you can add some explanations in the tutorial?**

I have also created a support incident:
https://support.wdf.sap.corp/sap/support/message/2180040973

<img width="502" alt="Workflow_ImportRules" src="https://user-images.githubusercontent.com/18447094/105198294-d0413880-5b3d-11eb-9615-2ce5d3ef1d90.png">
<img width="260" alt="Workflow_ImportRules_error" src="https://user-images.githubusercontent.com/18447094/105198302-d1726580-5b3d-11eb-8101-d0d466ceb5d5.png">

**Comment by ArchanaShukla** [comment]
@TrinidadMG - Does this issue still persists? Can you refresh your browser and check. Also use your browser Developer Console and send across the error message from the Network tab.

**Comment by TrinidadMG** [comment]
Hi,
Today I have just tried to reproduce the issue but it seems it is not working?
As soon as I press the + button in the Configure Systems screen I get an error, see attachment.
![image](https://user-images.githubusercontent.com/18447094/105714026-1cb0bd80-5f1c-11eb-8166-4e3683be8253.png)

Thanks,
Trinidad.

**Comment by ArchanaShukla** [comment]
@TrinidadMG - Can you try the whole operation in incognito mode with fresh login. Many times the browser cache causes this problem.

**Comment by TrinidadMG** [comment]
Hi Archana,
The error on the Configure Systems screen appears even in an Incognito window after doing log out + login again.
Regards,
Trinidad.

**Comment by ArchanaShukla** [comment]
@TrinidadMG - The screenshot you attached is not of Configure System. Can you please let me know what exactly are you trying to do. Also, send across the Network tab log for the operation that is failing.

**Comment by TrinidadMG** [comment]
Hi Archana,
I'm following the tutorial:
https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-businessrules.html
Step 2: Configure a system
3. Click + to add a system.
The screen capture I sent is the one that opens after clicking +

I have attached the screen capture with F12 details on Network tab as well as the logs from the Network.

Thanks,
Trinidad.
[ScreenshotN.zip](https://github.com/SAPDocuments/Issues/files/5867229/ScreenshotN.zip)

**Comment by ArchanaShukla** [comment]
@TrinidadMG - What screenshot you have attached is of Project page and not of Configure Systems (see carefully the sub-step 3 of Step 2 in the tutorial). It seems you have not created APIHub system and are trying to use the name in project details page.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
