### ISSUE TITLE
Get Started with UI5 Web Components for React

### ISSUE THREAD

**Issue by AlexandreFossati** [SAPDocuments/Issues#94]
Tutorial: https://developers.sap.com/tutorials/ui5-webcomponents-react-introduction.html
--------------------------

Write here what you need help with ...

The command "npx create-react-app my-app --template @ui5/cra-template-webcomponents-react" does not generate the template properly to follow the tutorial instructions.

**Comment by Lukas742** [comment]
Hi @AlexandreFossati 

for me it works as expected. Could you please elaborate on what exactly is missing?

**Comment by AlexandreFossati** [comment]
The YARN command was working perfectly, so I run node -v and noticed that I was using version 10, that was the problem, the command now is working fine, sorry :(
