### ISSUE TITLE
Set Up Process Visibility to Track Employee Onboarding Workflow

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Issues#95]
Tutorial: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-4-visibility.html
--------------------------

Step 1.3

Has the fields/Create button issue been fixed yet? The tutorial seems not to have been updated.

Thank you,
gm

**Comment by ArchanaShukla** [comment]
Hello @greg2git,
There is no issue with the Create button. I am able to create the visibility scenario without issues. There is however some change in the screenshot with introduction of namespace but that is not mandatory. Can you try and create again and ensure that you do not have any special characters in the Name and description.

**Comment by greg2git** [comment]
seems 'broken' when a space or '_' is being used:

![image](https://user-images.githubusercontent.com/24355032/105607743-a458c980-5d6e-11eb-896c-a6c2bfa20a8c.png)

but eventually works with these inputs:

![image](https://user-images.githubusercontent.com/24355032/105608070-c7d04400-5d6f-11eb-8465-2bc5b3617b4c.png)

**Comment by ArchanaShukla** [comment]
@greg2git - Spaces are not allowed in the namespace. Also, namespace is not mandatory. You can enter the namespace if we want to avoid name clashes across different projects. 

@MichaelCzcz - please close the issue.

**Comment by thecodester** [comment]
@ArchanaShukla You should be able to close your own issues now (in this repo). Please confirm.

**Comment by ArchanaShukla** [comment]
@thecodester - Thanks Daniel for letting me know
