### ISSUE TITLE
Create an Account on the Gateway Demo System

### ISSUE THREAD

**Issue by bri-davis** [SAPDocuments/Issues#97]
Tutorial: https://developers.sap.com/tutorials/gateway-demo-signup.html
--------------------------

It appears that the SAP Gateway Server link in Step 1 is down:

<img width="738" alt="issue" src="https://user-images.githubusercontent.com/37200864/105536294-1b825500-5cbe-11eb-99ac-4faf4200bc0b.PNG">

link: https://register.sapdevcenter.com/SUPSignForms/

**Comment by thecodester** [comment]
@jung-thomas Sorry to bother you here but who is responsible for this?

**Comment by thecodester** [comment]
@bri-davis I see on the sign-in page that there is planned maintenance from Jan. 22-24. Please try again tomorrow and let us know if it works. Sorry for the inconvenience.

**Comment by bri-davis** [comment]
@thecodester  I tried again and I was able to successfully sign up. Thank you for the help.
