### ISSUE TITLE
Enable SAP Cloud Platform, Kyma Runtime

### ISSUE THREAD

**Issue by pjcools** [SAPDocuments/Issues#98]
Tutorial: https://developers.sap.com/tutorials/cp-kyma-getting-started.html
--------------------------

Write here what you need help with ...

Step: 1 - I have assigned the entitlements and clicking on Done however it fails so the tutorial is not updating my progress.

Please fix. 

thanks
Phil Cooley

**Comment by thecodester** [comment]
I am checking. Sorry for the problems.

**Comment by thecodester** [comment]
The issue seems fixed.

@pjcools : Can you confirm?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
