### ISSUE TITLE
Download and Prepare App for Cloud Foundry Deployment

### ISSUE THREAD

**Issue by SAPonCloud** [SAPDocuments/Issues#99]
Tutorial: https://developers.sap.com/tutorials/cp-cf-dev-01-prepare-app.html
--------------------------

I am unable to confirm the tutorial steps in any training on developers.sap.com 
Upon clicking 'Done' button, nothing happens disregarding browser or tutorial. I have tried clearing browsing data, cookies and cache, and also tried incognito mode.
Any idea what could be wrong and how this could be solved?

**Comment by thecodester** [comment]
I am working on this. Sorry for the inconvenience.

**Comment by thecodester** [comment]
The issue seems fixed.

@SAPonCloud : Can you confirm?

**Comment by SAPonCloud** [comment]
> The issue seems fixed.
> 
> @SAPonCloud : Can you confirm?

Yes, it's working now. Thank you!
